"""Build source-only MADOran enrichment Batch 14 for Sentno 833..896."""
from __future__ import annotations

import json
import sys
from pathlib import Path

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts import build_madoran_enrichment_batch10 as engine
from scripts.build_madoran_enrichment_scaffold import ROOT

BATCH_ID = "MADORAN-ENRICH-014"
BASE_COMMIT = "799e228"
PROMPT_VERSION = "madoran-source-enrichment-v14"
TARGET_START = 833
TARGET_END = 896
BATCH_OUT = ROOT / "data/master/enrichment/batches/batch14_sentno_0833_0896.tsv"
MANIFEST_OUT = ROOT / "data/master/enrichment/batches/batch14_manifest.json"
QA_OUT = ROOT / "data/master/qa/madoran_enrichment_batch14_generation_qa.json"
BATCH_FIELDS = engine.BATCH_FIELDS
item = engine.item


def r(english, korean, domain, topic, genre="conversation", speech="description", register="colloquial", context="high", flags="source_ambiguity", state="flagged", cefr="B2", score=60):
    return item(english, korean, cefr, score, domain, topic, genre, speech, register, context, flags, state)


RAW = {
    833: r("The stranger points out the listener's phone and villa keys, asks what happened to them, and orders the listener to be quiet after asking whether they threw them away. The coercive context is explicit but the exact action is unclear.", "낯선 사람이 듣는 사람의 전화기와 별장 열쇠를 가리키며 그것들이 어떻게 되었는지 묻고, 버렸느냐고 한 뒤 조용히 하라고 해요. 강압적 맥락은 분명하지만 정확한 행동은 불분명해요.", "crime_safety", "coercive_control_of_phone_and_villa_keys", "conversation", "command", "offensive", "high", "long_source|source_ambiguity"),
    834: r("The speaker says they are speaking rationally and tells the listener to sit and listen carefully. They threaten to kill the listener if they follow or confront them after leaving, then tell a friend to move away; the threat is preserved as source content.", "화자는 이성적으로 말하고 있다며 앉아서 잘 들으라고 해요. 나간 뒤 자신을 따라오거나 맞서면 죽이겠다고 위협하고, 친구에게 물러나라고 해요. 위협은 원문 내용으로 보존해요.", "crime_safety", "threat_after_coercive_encounter", "conversation", "warning", "offensive", "high", "long_source|source_ambiguity", "flagged", "C1", 86),
    835: r("Dalila asks someone to watch her table while she goes to comb her hair at Nariman's place and returns.", "달릴라가 누군가에게 자기 테이블을 봐 달라고 하고 나리만에게 머리를 빗으러 갔다가 돌아오겠다고 해요.", "daily_life", "hair_appointment_and_table_watch", "conversation", "request", "colloquial", "medium", "source_ambiguity"),
    836: r("A woman asks why Dalila is carrying this item to Nariman in the morning and says Nariman could have combed her hair; she adds that the place will open first.", "한 여성이 달릴라가 왜 아침부터 이것을 들고 나리만에게 가느냐고 묻고, 나리만이 머리를 빗어 줄 수도 있었다고 해요. 그곳이 먼저 문을 열 것이라고 덧붙여요.", "daily_life", "morning_hair_arrangement", "conversation", "question", "colloquial", "high", "source_ambiguity"),
    837: r("Before the clients arrive, the speaker says there is still time and warns Dalila to watch out for anyone who might mix something into the speaker's goods.", "손님들이 오기 전에는 아직 시간이 있다며, 달릴라에게 누군가 자기 물건에 무엇인가를 섞지 않도록 조심하라고 해요.", "shopping", "protecting_goods_before_clients_arrive", "conversation", "warning", "colloquial", "high", "source_ambiguity"),
    838: r("A woman says goodbye to her sister and wishes her a good morning. The other woman returns the greeting and asks how she is; she answers that she is fine.", "한 여성이 자매에게 작별 인사를 하고 좋은 아침이 되라고 해요. 다른 여성이 인사를 돌려주며 어떠냐고 묻고, 괜찮다고 답해요.", "daily_life", "sisterly_greeting_and_wellbeing", "conversation", "greeting", "colloquial", "medium", "source_ambiguity"),
    839: r("One person asks what is wrong when the other says nothing is wrong. They tell her to come and wait there while they go handle some matters and return.", "한 사람이 아무 일도 없다는 상대에게 무슨 일이냐고 물어요. 자신이 일을 처리하고 돌아오는 동안 이곳에 와서 기다리라고 해요.", "daily_life", "reassurance_and_brief_errand", "conversation", "request", "colloquial", "high", "source_ambiguity"),
    840: r("An exclamation to God asks the woman to look and warns that one day she may be driven crazy by these services or jobs. The speaker insists that Nariman should handle this time, then says goodbye.", "하느님을 부르며 여성이 이것을 보라고 하고, 언젠가 이런 일이나 서비스 때문에 미칠 수도 있다고 말해요. 이번에는 나리만이 맡아야 한다고 강조한 뒤 작별해요.", "daily_life", "frustration_with_services_and_hair_work", "conversation", "complaint", "colloquial", "high", "idiom_culture|source_ambiguity"),
    841: r("The speaker wishes the listener well and remarks that some girls seem to have good fortune.", "화자는 상대의 앞날을 빌어 주고, 어떤 여자들은 운이 좋은 것 같다고 말해요.", "daily_life", "blessing_and_good_fortune", "conversation", "wish", "neutral", "low", "", "draft", "A2", 22),
    842: r("The speaker asks whether the people being questioned have brought the listener money.", "화자는 상대가 묻고 있는 사람들이 돈을 가져왔는지 물어요.", "finance", "asking_about_money_delivery", "conversation", "question", "colloquial", "medium", "source_ambiguity"),
    843: r("The speaker says there are two more rounds or matters left and that they will go to Hussein.", "화자는 두 번이나 두 가지 일이 더 남았고 후세인에게 가겠다고 말해요. 정확한 단위는 불분명해요.", "daily_life", "remaining_tasks_before_visiting_hussein", "conversation", "information", "colloquial", "medium", "source_ambiguity", "draft", "A2", 24),
    844: r("The speaker asks why they were given a container and says four pallets have not been sold.", "화자는 왜 컨테이너를 받았는지 묻고, 팔리지 않은 팔레트 네 개가 있다고 말해요.", "shopping", "unsold_stock_and_container", "conversation", "question", "colloquial", "high", "source_ambiguity"),
    845: r("They say the goods were sold, but ask the listener to wait because an older woman needed them.", "물건은 팔았지만 한 노년 여성이 필요로 했으니 조금 기다려 달라고 말했다고 해요.", "shopping", "sale_delayed_for_customer_need", "conversation", "information", "colloquial", "medium", "source_ambiguity"),
    846: r("The speaker says they have social insurance or a similar arrangement and tells the listener to see whether Toufik can deal with the people involved because he brought the goods.", "화자는 사회보험이나 그와 비슷한 것이 있다고 말하고, 물건을 가져온 사람이 투피크이니 그가 관련된 사람들과 처리할 수 있는지 보라고 해요.", "work", "delegating_a_goods_arrangement_to_toufik", "conversation", "suggestion", "mixed", "high", "source_ambiguity"),
    847: r("Asked where they were, the speaker says they were working on a purchase. Another voice tells them to get up, stop making excuses, and do something with their life.", "어디 있었느냐는 질문에 화자는 구매 일을 처리하고 있었다고 해요. 다른 목소리는 일어나서 변명하지 말고 인생에서 무언가를 하라고 말해요.", "work", "work_and_reproach_about_inactivity", "conversation", "complaint", "colloquial", "high", "source_ambiguity"),
    848: r("A phone call begins with greetings and questions about what is happening. The speaker will handle matters with a cheap person or deal, asks whether there is good merchandise like yesterday's henna, and says their head is bursting; several references remain unclear.", "전화로 인사를 나누며 무슨 일이냐고 물어요. 화자는 값싼 상대나 거래를 자신이 처리하겠다고 하고, 어제의 헤나처럼 좋은 물건이 있는지 묻다가 머리가 터질 것 같다고 해요. 몇몇 지칭은 불분명해요.", "shopping", "phone_call_about_merchandise_and_deal", "conversation", "information", "mixed", "high", "code_switching|long_source|source_ambiguity", "flagged", "C1", 78),
    849: r("Someone asks what she wants to cook. She answers harira, and the other person complains jokingly that it is harira every day.", "누군가 무엇을 요리하고 싶은지 묻자 하리라라고 답해요. 다른 사람은 매일 하리라냐고 장난스럽게 불평해요.", "food", "harira_every_day_joke", "conversation", "question", "colloquial", "medium", "idiom_culture|source_ambiguity"),
    850: r("Mira asks what Uncle Ali wants from her. He answers that he wants her.", "미라가 알리 아저씨가 자신에게 무엇을 원하는지 묻자, 그는 그녀를 원한다고 답해요.", "family_relationships", "romantic_exchange_with_uncle_ali", "conversation", "disagreement", "colloquial", "high", "source_ambiguity"),
    851: r("The speaker suggests that they should be together, but lawfully, and proposes making a customary marriage contract between them.", "화자는 둘이 함께하되 합법적으로 해야 한다고 말하며, 두 사람 사이에 관습혼 계약을 맺자고 제안해요.", "family_relationships", "proposal_of_customary_marriage", "conversation", "suggestion", "mixed", "high", "source_ambiguity"),
    852: r("The woman asks whether he wants her merely as a temporary or casual partner. She is still young and wants security; she worries about his mother and sister. She tells him to ask his wife whether she accepts, then come formally to propose so they can see what happens.", "여성이 그가 자신을 그저 임시적이거나 가벼운 상대로 원하는지 물어요. 자신은 아직 어리고 안전을 보장받고 싶으며 그의 어머니와 누이에 대해서도 걱정해요. 아내가 받아들일지 물어본 뒤 정식으로 청혼하러 오라고 해요.", "family_relationships", "conditions_for_a_second_marriage", "conversation", "request", "mixed", "high", "long_source|source_ambiguity", "flagged", "C1", 82),
    853: r("The man asks whether she wants him to marry her casually. She says she is still young and wants security, will make his wife comfortable, and wants to live fully; she asks whether a daughter would accept sharing herself with the first wife.", "남성이 그녀를 그렇게 가볍게 맞이하기를 원하는지 묻자, 그녀는 아직 젊고 자신을 보장하고 싶으며 그의 아내도 편하게 해 주겠다고 해요. 자신은 세상에 와서 살고 싶다며, 딸이 첫 아내와 자신을 나누는 일을 받아들이겠느냐고 물어요.", "family_relationships", "security_and_acceptance_in_second_marriage", "conversation", "question", "mixed", "high", "long_source|source_ambiguity", "flagged", "C1", 84),
    854: r("The speaker says the other person is reproaching her because the speaker has no children. The other person apologizes, says they would never think that way, and asks for some empathy.", "화자는 상대가 자신에게 아이가 없다고 비난한다고 말해요. 상대는 그렇게 생각하지 않는다며 사과하고, 자신을 조금 이해해 달라고 해요.", "family_relationships", "reproach_about_childlessness", "conversation", "complaint", "mixed", "high", "idiom_culture|source_ambiguity"),
    855: r("The speaker says the listener understands nothing and explains that her brother has influence, while the listener is not simple either. She asks what happened between the listener's wife and that man, saying nothing will change if the wife accepts and that the woman standing before him also deserves happiness.", "화자는 상대가 아무것도 모른다며, 자신의 오빠는 영향력이 있고 상대도 만만하지 않다고 설명해요. 상대의 아내와 그 남자 사이에 무슨 일이 있었는지 묻고, 아내가 받아들여도 달라질 것은 없으며 앞에 서 있는 여성도 행복할 자격이 있다고 말해요.", "family_relationships", "family_power_and_marital_acceptance", "conversation", "opinion", "mixed", "high", "long_source|source_ambiguity", "flagged", "C1", 84),
    856: r("The speaker tells the listener to sit and recounts that someone imprisoned him for three days in the villa shack, taking the villa keys and a portable phone. The listener asks how three days could have passed and says he was only released after thinking about it.", "화자는 앉으라고 하며 누군가 자신을 별장 창고에 사흘 가두고 별장 열쇠와 휴대전화를 빼앗았다고 말해요. 상대는 어떻게 사흘이나 되었느냐고 묻고, 그가 생각한 뒤에야 자신을 내보냈다고 해요.", "crime_safety", "detention_in_villa_and_taken_keys", "conversation", "information", "mixed", "high", "long_source|source_ambiguity", "flagged", "C1", 84),
    857: r("The speaker says the villa keys were lost, but they had a duplicate hidden away. After being released, they went straight to the villa and found everything in place, though something may have been taken without the listener noticing.", "화자는 별장 열쇠를 잃어버렸지만 숨겨 둔 여분 열쇠가 있었다고 해요. 풀려난 뒤 곧장 별장에 가 보니 모든 것이 제자리에 있었지만, 상대가 알아차리지 못한 채 무엇인가 없어졌을 수도 있다고 말해요.", "crime_safety", "checking_villa_after_key_loss", "conversation", "information", "mixed", "high", "source_ambiguity"),
    858: r("The villa originally had almost nothing in it, only belongings. Si Toufik and his wife regularly travel to America to see their children, while the speaker says his employer never left money at the villa.", "별장에는 원래 거의 아무것도 없고 물건만 있었다고 해요. 시 투피크와 그의 아내는 미국에 사는 자녀들을 보러 자주 여행하고, 화자는 자신의 고용주가 별장에 돈을 남긴 적이 없다고 말해요.", "housing", "villa_contents_and_toufik_family_travel", "conversation", "information", "mixed", "high", "code_switching|source_ambiguity"),
    859: r("The speaker asks why Madame left all her jewelry in the bank and why the listener kept the keys for three days. The listener says they do not know, and is asked whether they remember the man's face.", "화자는 부인이 보석을 모두 은행에 두었는데 왜 열쇠를 맡겼는지, 왜 상대가 사흘 동안 열쇠를 가지고 있었는지 물어요. 상대는 모른다고 하고, 그 남자의 얼굴을 기억하는지 질문받아요.", "crime_safety", "questions_about_keys_and_missing_property", "conversation", "question", "mixed", "high", "source_ambiguity"),
    860: r("The listener says they never saw the man's face because it was covered, but he looked young and like a respectable family man.", "상대는 얼굴이 가려져 있어서 그 남자의 얼굴을 한 번도 보지 못했지만, 젊고 집안이 좋은 사람처럼 보였다고 말해요.", "crime_safety", "description_of_masked_man", "conversation", "description", "colloquial", "medium", "source_ambiguity"),
    861: r("The listener apologizes for not explaining earlier and says the man never approached or struck them. When he came to check on them occasionally, he brought food, loosened their restraints, and let them go to the bathroom.", "상대는 제대로 설명하지 못해 미안하다며, 그 남자가 자신에게 다가오거나 때린 적은 없다고 해요. 가끔 확인하러 올 때 음식을 가져오고 묶인 것을 풀어 주며 화장실에 가게 했다고 말해요.", "crime_safety", "captivity_and_limited_care_by_captor", "conversation", "information", "mixed", "high", "long_source|source_ambiguity", "flagged", "C1", 82),
    862: r("The other person asks whether the listener did not try to escape, call out, or shout.", "상대는 듣는 사람이 도망치거나 사람을 부르거나 소리치려 하지 않았는지 물어요.", "crime_safety", "question_about_escape_attempt", "conversation", "question", "colloquial", "medium", "source_ambiguity"),
    863: r("The listener says this was stated in the first report: they could not shout because the man carried a weapon under his coat, but in fairness he never used it. They called the villa owners, who said they would enter with a first official report or preliminary procedure.", "상대는 첫 번째 진술서에 그렇게 말했다며, 그 남자가 옷 아래 무기를 들고 있어 소리칠 수 없었지만 공정하게 말하면 그것을 사용한 적은 없다고 해요. 별장 주인에게 전화하자 예비 절차나 첫 보고를 들고 들어가겠다고 했다고 말해요.", "administration", "police_report_after_villa_incident", "conversation", "information", "mixed", "high", "code_switching|long_source|source_ambiguity", "flagged", "C1", 88),
    864: r("They decide to go to the villa together to see what this situation is about.", "그들은 이 일이 어떻게 된 것인지 보러 함께 별장에 가기로 해요.", "crime_safety", "going_to_villa_to_investigate", "conversation", "suggestion", "colloquial", "medium", "source_ambiguity"),
    865: r("Hussein asks his friend what to do about the money affair. The other person says they know nothing and calls Houari his brother.", "후세인이 친구에게 돈 문제를 어떻게 해야 하는지 묻자, 상대는 아무것도 모르겠다며 호아리를 형제라고 불러요.", "finance", "uncertainty_about_money_affair", "conversation", "question", "colloquial", "high", "source_ambiguity"),
    866: r("The speaker says Ali will not give up his rights and admits being afraid that Toufik will confront him. They ask what the matter is and tell their friend to look.", "화자는 알리가 자신의 권리를 포기하지 않을 것이며 투피크와 맞설까 봐 무섭다고 말해요. 무슨 일인지 묻고 친구에게 보라고 해요.", "finance", "fear_of_conflict_over_rights", "conversation", "warning", "colloquial", "high", "source_ambiguity"),
    867: r("The speaker insults the listener, calling him a mafioso and a man, while saying that everyone else is cheap or worthless.", "화자는 상대를 마피아나 사내라고 부르며, 다른 사람들은 모두 값싸거나 형편없다고 모욕해요.", "daily_life", "insults_during_money_conflict", "conversation", "complaint", "offensive", "high", "source_ambiguity", "flagged", "C1", 78),
    868: r("Toufik threatens the other person over money, telling him to shut his mouth and saying he will plant something in his head if he continues. Another speaker says the money will reach Toufik, while the threat continues.", "투피크가 돈 문제로 상대를 위협하며 입을 다물라고 하고 계속하면 머리에 무엇인가를 박겠다고 해요. 다른 화자는 돈이 투피크에게 도착할 것이라고 말하지만 위협은 이어져요.", "crime_safety", "threats_during_money_dispute", "conversation", "warning", "offensive", "high", "long_source|source_ambiguity", "flagged", "C1", 88),
    869: r("The speaker says that if the listener has money that does not reach Ali by the appointed time, they will cut off his head. The line is a direct violent threat.", "화자는 상대가 가진 돈이 정해진 때까지 알리에게 도착하지 않으면 목을 자르겠다고 해요. 직접적인 폭력 위협이에요.", "crime_safety", "violent_threat_over_missing_money", "conversation", "warning", "offensive", "high", "long_source|source_ambiguity", "flagged", "C1", 90),
    870: r("A woman greets Aunt Zoulikha and asks her to remember to bring bread from the bakery when she finishes. Zoulikha refuses because the last bread smelled of chicken.", "한 여성이 줄리카 이모에게 인사하고, 빵이 떨어지면 빵집에서 가져오는 것을 잊지 말라고 해요. 줄리카는 지난번 빵에서 닭 냄새가 났다며 거절해요.", "food", "bread_from_bakery_and_food_complaint", "conversation", "request", "colloquial", "medium", "source_ambiguity"),
    871: r("The baker says they wash before finishing work and then bring the bread, while the customer insists that she already said what she wanted. They agree to do it as she wishes.", "빵을 파는 사람은 일을 마치기 전에 씻고 그다음 가져오겠다고 해요. 손님은 이미 원하는 것을 말했다고 하고, 상대는 원하는 대로 하겠다고 해요.", "food", "bakery_hygiene_and_customer_request", "conversation", "information", "colloquial", "medium", "source_ambiguity"),
    872: r("Aunt Zoulikha tells the boy to go and work.", "줄리카 이모가 아이에게 가서 일하라고 말해요.", "work", "telling_a_boy_to_work", "conversation", "command", "colloquial", "low", "", "draft", "A1", 16),
    873: r("A customer asks Aunt Zoulikha to make a special item. She says there is no special one because she has finished the kofta.", "손님이 줄리카 이모에게 특별한 것을 하나 만들어 달라고 해요. 이모는 특별한 것은 없고 코프타를 다 만들었다고 해요.", "food", "special_bakery_order_and_kofta", "conversation", "request", "colloquial", "medium", "source_ambiguity"),
    874: r("A woman asks whether the finished kofta was only for her. The seller says the items belong to their owner and were ordered, and that the owner will come to collect them; she will handle one item herself and tells the customer to give him one.", "한 여성이 완성한 코프타가 자기 것뿐인지 묻어요. 판매자는 물건들이 주인의 것이고 주문받은 것이라 주인이 와서 가져갈 것이라고 해요. 하나는 자신이 처리하겠다며 손님에게 그에게 하나 주라고 해요.", "food", "ordered_food_and_customer_collection", "conversation", "information", "mixed", "high", "code_switching|long_source|source_ambiguity", "flagged", "C1", 78),
    875: r("The speaker says they would not be asking the others if it were not for them; without the speaker, the others would have been eaten by wasps. The insult is exaggerated social banter.", "화자는 자신 때문이 아니라면 상대에게 부탁하지 않았을 것이라고 해요. 자신이 없었다면 상대가 말벌에게 먹혔을 것이라고 과장해 말해요.", "daily_life", "exaggerated_banter_about_help", "conversation", "complaint", "offensive", "high", "idiom_culture|source_ambiguity"),
    876: r("The speaker says they should normally receive a percentage, but tells the boy to work like a man instead of coming there to act tough with women. He is told to shut up and leave.", "화자는 원래 수수료나 비율을 받아야 하지만, 소년에게 여자들 앞에서 허세를 부리러 오지 말고 남자답게 일하라고 해요. 입을 다물고 가라고 해요.", "work", "commission_dispute_and_harassment", "conversation", "command", "offensive", "high", "code_switching|source_ambiguity", "flagged", "C1", 84),
    877: r("The speaker says they will take two good ones and tells Tito that it is fine, while the others tell him not to interfere. The exchange becomes a mutual insult about whose father's fortune is involved.", "화자는 좋은 것 두 개를 가져가겠다고 하고 티토에게 괜찮다고 말해요. 다른 사람들은 그에게 끼어들지 말라고 해요. 누구 아버지의 재산이냐를 두고 서로 모욕해요.", "daily_life", "mutual_insults_over_goods_and_fortune", "conversation", "disagreement", "offensive", "high", "code_switching|source_ambiguity", "flagged", "C1", 82),
    878: r("Someone asks what is wrong. The other says their mad dog has attacked them, then warns that in front of men they will smash the listener's mouth.", "누군가 무슨 일이냐고 묻자, 상대는 미친 개가 자신들을 덮쳤다고 해요. 이어 남자들 앞에서 상대의 입을 부숴 버리겠다고 위협해요.", "crime_safety", "threat_after_aggressive_confrontation", "conversation", "warning", "offensive", "high", "source_ambiguity", "flagged", "C1", 84),
    879: r("The speaker tells the other person to go to the café because they are coming. They swear the matter is not finished, complain about the situation, then tell the other person to go; an apology and payment exchange follows.", "화자는 상대에게 자신이 가고 있으니 카페로 가라고 해요. 일이 끝나지 않았다고 맹세하고 상황을 불평한 뒤 가라고 해요. 이어 사과와 계산에 관한 말이 오가요.", "daily_life", "cafe_argument_and_payment", "conversation", "complaint", "offensive", "high", "source_ambiguity"),
    880: r("A woman asks the other why she came and says it is none of her business. She tells her to return to work after seeing how he spoke to them.", "한 여성이 상대에게 왜 왔고 무슨 상관이냐고 물어요. 그가 자신들에게 어떻게 말했는지 봤으니 일하러 돌아가라고 해요.", "work", "workplace_interference_and_reproach", "conversation", "command", "offensive", "high", "source_ambiguity"),
    881: r("Elias is told that they should sit quietly. The speaker asks what he wants them to say and tells him that anger will solve no problem, so he should calm down.", "엘리아스에게 이제 조용히 앉아 있어야 한다고 말해요. 무엇을 말해 달라는지 묻고, 화낸다고 문제가 해결되지 않으니 마음을 넓히라고 해요.", "family_relationships", "calming_anger_in_family_conflict", "conversation", "suggestion", "colloquial", "high", "source_ambiguity"),
    882: r("The speaker says they are angry with Elias and with themselves because, through their own fault, the other person was deprived of everything.", "화자는 엘리아스에게도 자신에게도 화가 났다고 해요. 자기 탓으로 상대가 모든 것을 빼앗겼기 때문이라고 말해요.", "family_relationships", "guilt_over_family_loss", "conversation", "complaint", "mixed", "high", "source_ambiguity"),
    883: r("The speaker tells the boy that he has those assets and the property, and hopes that tomorrow her son will graduate from university, find work, and compensate her for everything. She says he never made her feel like a father and that she never felt his tenderness, even while living with him.", "화자는 아이에게 그 돈과 재산이 있다고 말하고, 내일 자신의 아들이 대학을 졸업해 일하며 모든 것을 보상해 주기를 바래요. 그 아들은 자신에게 아버지 같은 느낌을 준 적이 없고, 함께 살면서도 그의 다정함을 느껴 본 적이 없다고 해요.", "family_relationships", "paternal_absence_and_child_support", "conversation", "complaint", "mixed", "high", "long_source|source_ambiguity", "flagged", "C1", 86),
    884: r("The child says that mother should not have forced him to sponsor or take responsibility for the child. The speaker answers that his father was happy with her and supported her, as shown by giving her his name, while criticizing the family and asking forgiveness.", "아이는 어머니가 자신을 보증하거나 책임지도록 강요할 필요가 없었다고 말해요. 화자는 그의 아버지가 자신을 기뻐하고 지지했으며, 이름을 준 것이 그 증거라고 답해요. 그러면서 가족을 비판하고 용서를 빌어요.", "family_relationships", "kafala_and_family_name_conflict", "conversation", "disagreement", "mixed", "high", "source_ambiguity", "flagged", "C1", 82),
    885: r("The speaker says Uncle Nasser was treated badly and had his head turned, so they could not even hold his funeral in the house.", "화자는 나세르 삼촌이 부당하게 대우받고 마음을 돌려 버리게 되어, 그의 장례식조차 집에서 치를 수 없었다고 말해요.", "family_relationships", "family_conflict_and_funeral", "conversation", "complaint", "mixed", "high", "source_ambiguity"),
    886: r("The speaker wishes to close and reopen their eyes in a faraway place where no one asks where they came from. They say they want to forget Elias completely, while Elias calls them his child and asks not to be forgotten.", "화자는 눈을 감았다가 다시 뜨면 아무도 어디서 왔는지 묻지 않는 먼 곳에 있기를 바래요. 엘리아스를 완전히 잊고 싶다고 말하자, 엘리아스는 자신을 아이처럼 부르며 잊지 말라고 해요.", "family_relationships", "desire_to_escape_and_be_remembered", "conversation", "complaint", "mixed", "high", "long_source|source_ambiguity", "flagged", "C1", 82),
    887: r("Dalila asks her sister to call because she needs her. She agrees to speak to mother, then asks each woman to contribute three hundred thousand to buy a refrigerator, recalling that they had said making one would be better.", "달릴라가 동생에게 전화해 달라고 해요. 어머니에게 말하겠다고 한 뒤, 냉장고를 사려고 각자 30만씩 내 달라고 해요. 전에 직접 만드는 것이 낫다고 하지 않았느냐고 되묻기도 해요.", "finance", "family_contribution_for_refrigerator", "conversation", "request", "mixed", "high", "source_ambiguity"),
    888: r("The speaker says a man has declared that the item cannot be made and that they need a new one today. They reject the idea of dealing with unsold goods and tell the listener to buy a refrigerator or whatever they want.", "화자는 한 남자가 그것은 만들 수 없다고 했고 오늘 새것이 필요하다고 말해요. 팔리지 않는 물건에 자신이 왜 관여하느냐며 냉장고나 원하는 것을 사라고 해요.", "shopping", "buying_a_refrigerator_instead_of_repairing", "conversation", "command", "colloquial", "high", "source_ambiguity"),
    889: r("Someone says they forgot that the woman is a guest in their home and tells her that, since she lives with them, their belongings must not be wasted; everyone should manage their own affairs.", "누군가 그 여성이 집에 온 손님이라는 사실을 잊었다고 말해요. 함께 살고 있으니 자신의 물건을 낭비해서는 안 되며 각자 알아서 하라고 해요.", "family_relationships", "guest_and_household_boundaries", "conversation", "complaint", "mixed", "high", "source_ambiguity"),
    890: r("The speaker asks why the woman does not put anything in the refrigerator or eat anything cold from it. The woman says it has not cooled for some time and asks for the original or replacement parts.", "화자는 여성이 왜 냉장고에 아무것도 넣지 않고 차가운 것도 먹지 않느냐고 물어요. 여성은 한동안 차가워지지 않았다며 원래 부품이나 교체 부품을 가져와 달라고 해요.", "shopping", "broken_refrigerator_complaint", "conversation", "question", "colloquial", "high", "code_switching|source_ambiguity"),
    891: r("The speaker says the only thing the other woman puts in is money. The other woman refuses to give even a coin and says she does not touch the money she saves.", "화자는 상대 여성이 넣는 것은 돈뿐이라고 해요. 상대는 한 푼도 주지 않겠다며 자신이 모은 돈에는 손대지 않는다고 말해요.", "finance", "argument_over_shared_money", "conversation", "disagreement", "colloquial", "high", "source_ambiguity"),
    892: r("One woman asks why she should contribute from her savings. The other explains that they are not the same: one saves for marriage, while she saves for rent and to open a cosmetics shop so she can improve her situation and escape poverty.", "한 여성이 왜 자신이 모은 돈에서 내야 하느냐고 묻자, 다른 여성은 둘은 같지 않다고 해요. 한 사람은 결혼을 위해 모으고 자신은 집세와 화장품 가게를 열기 위해 모아 지금의 가난에서 벗어나려 한다고 설명해요.", "finance", "different_saving_goals_and_cosmetics_shop", "conversation", "disagreement", "mixed", "high", "source_ambiguity", "flagged", "C1", 82),
    893: r("The speaker tells the woman to raise her standard and asks whether she hears them. They say they are only concerned with the money being put in and complain that rent and everything else have fallen on them.", "화자는 여성에게 수준을 높이라고 하며 듣고 있느냐고 물어요. 자신은 상대가 넣는 돈만 걱정하는데 집세와 모든 일이 자신에게 떨어졌다고 불평해요.", "finance", "rent_burden_and_household_expenses", "conversation", "complaint", "offensive", "high", "source_ambiguity"),
    894: r("The speaker says the woman is from there and that helping is her duty. The woman threatens to cut out the speaker's tongue, orders her to fetch a slipper, then the exchange shifts to greetings and a question about how Ziguomar is doing.", "화자는 여성이 이곳 사람이고 돕는 것이 의무라고 말해요. 여성은 화자의 혀를 잘라 버리겠다고 위협하고 슬리퍼를 가져오라고 명령해요. 이어 인사와 지구마르가 잘 지내는지 묻는 말로 바뀌어요.", "daily_life", "household_argument_and_threat", "conversation", "warning", "offensive", "high", "source_ambiguity", "flagged", "C1", 84),
    895: r("A greeting asks whether Ali and the others are well and notes that they have not been seen for a week. The speaker jokes or complains that they are under house arrest and not enjoying themselves, then tells the other person to be quiet.", "인사를 나누며 알리와 다른 사람들이 잘 지내는지, 일주일 동안 보이지 않았다고 말해요. 화자는 자신들이 가택연금 상태라 즐기지 못한다고 농담하거나 불평한 뒤 조용히 하라고 해요.", "daily_life", "house_arrest_joke_and_greeting", "conversation", "complaint", "mixed", "high", "code_switching|source_ambiguity"),
    896: r("The listener asks why they should be quiet and what the other person wants, joking about coming every morning with a gift. The speaker apologizes for being wrong and says they will go decorate the house and return soon.", "상대는 왜 조용히 해야 하고 무엇을 원하는지 묻으며, 매일 아침 선물이나 보상을 들고 오라는 것이냐고 해요. 화자는 자신이 잘못하고 혼란스러웠다며 사과하고, 집을 꾸민 뒤 곧 오겠다고 말해요.", "daily_life", "apology_after_household_argument", "conversation", "apology", "mixed", "high", "source_ambiguity"),
}


def build():
    engine.BATCH_ID = BATCH_ID
    engine.BASE_COMMIT = BASE_COMMIT
    engine.PROMPT_VERSION = PROMPT_VERSION
    engine.TARGET_START = TARGET_START
    engine.TARGET_END = TARGET_END
    engine.BATCH_OUT = BATCH_OUT
    engine.MANIFEST_OUT = MANIFEST_OUT
    engine.QA_OUT = QA_OUT
    engine.RAW = RAW
    return engine.build()


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    print(json.dumps(build(), ensure_ascii=False, indent=2))
