"""Build source-only MADOran enrichment Batch 18 for Sentno 1089..1152."""
from __future__ import annotations

import json
import sys
from pathlib import Path

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts import build_madoran_enrichment_batch10 as engine
from scripts.build_madoran_enrichment_scaffold import ROOT

BATCH_ID = "MADORAN-ENRICH-018"
BASE_COMMIT = "1e63f19"
PROMPT_VERSION = "madoran-source-enrichment-v18"
TARGET_START = 1089
TARGET_END = 1152
BATCH_OUT = ROOT / "data/master/enrichment/batches/batch18_sentno_1089_1152.tsv"
MANIFEST_OUT = ROOT / "data/master/enrichment/batches/batch18_manifest.json"
QA_OUT = ROOT / "data/master/qa/madoran_enrichment_batch18_generation_qa.json"

def r(english, korean, domain, topic, genre="conversation", speech="description",
      register="colloquial", context="high", flags="source_ambiguity",
      state="flagged", cefr="B2", score=60):
    return engine.item(english, korean, cefr, score, domain, topic, genre, speech, register, context, flags, state)

RAW = {
    1089: r("The speaker tells someone to be quiet, then says they want to get the person out of their mind and want hair to grow on their head; the surface description remains direct.", "화자는 상대에게 조용히 하라고 한 뒤 상대를 머릿속에서 떨쳐 내고 싶으며 머리에 머리카락이 자라기를 바란다고 말해요.", "health", "telling_someone_to_be_quiet_and_describing_hair", speech="command", context="medium", flags="", state="draft", cefr="B1", score=38),
    1090: r("In a long opaque exchange, the speaker says they will explain and understand the listener, mentions being with a ghoul-like or otherwise unclear figure and a charm or talisman, and repeatedly says they will sell or betray people. The Sons of the Day, a costly resolution, living with or near a named place, being brought here, and a final command to be quiet are all retained as separate surfaces.", "긴 불투명 대화에서 화자는 설명하고 상대를 이해시키겠다고 하며, 구울처럼 들리는 인물이나 불분명한 존재와 부적을 언급하고 사람들을 팔거나 배신하겠다는 말을 반복해요. 울라드 나하르, 값비싼 해결, 특정 장소에서 사는 일, 여기로 데려온 일, 마지막의 조용히 하라는 명령을 각각의 표면형으로 보존해요.", "crime_safety", "opaque_accusation_and_sale_of_people", speech="warning", register="offensive", context="high", flags="long_source|source_ambiguity", cefr="C1", score=82),
    1091: r("The speaker says they are bringing the listener a sal3a or commodity and asks whether it belongs to the listener, while using opaque surfaces such as sh7ma and a phrase about the ground. They say they brought a commodity of their life and that the items can speak or move on their own; the praise of the commodity is preserved without fixing the referent.", "화자는 상대에게 sal3a라는 물건이나 상품을 가져왔다고 하며 그것이 상대의 것인지 묻고 sh7ma와 땅에 관한 불투명한 표현을 써요. 자신의 삶의 상품을 가져왔다고 하고 물건들이 스스로 말하거나 움직인다고 하며, 대상을 확정하지 않은 채 상품을 칭찬해요.", "shopping", "comic_description_of_an_opaque_commodity", speech="description", register="colloquial", context="high", flags="long_source|source_ambiguity", cefr="C1", score=78),
    1092: r("The speaker tells the listener to look at the commodity and show it to someone. They identify it as a piece or bead called krawson, then insult the person who brought it and curse them; krawson remains opaque.", "화자는 상대에게 그 상품을 보고 누군가에게 보여 주라고 해요. 그것을 krawson이라고 부르는 조각이나 알갱이로 설명한 뒤 가져온 사람을 모욕하고 저주하며 krawson 표면형을 보존해요.", "shopping", "showing_and_insulting_over_an_opaque_item", speech="command", register="offensive", context="high", flags="source_ambiguity", cefr="B2", score=58),
    1093: r("The speaker exclaims and asks whether the listeners know how to hunt, mentioning lizandian and several other opaque or foreign-derived surfaces. They say none of those things are present and ask what they can do with what was brought; the list is not normalized.", "화자는 감탄하며 상대가 사냥할 줄 아는지 묻고 lizandian과 몇 가지 불투명하거나 외래어처럼 들리는 표면형을 나열해요. 그런 것들은 하나도 없다고 하며 가져온 것으로 무엇을 할 수 있느냐고 묻고 목록을 임의로 정규화하지 않아요.", "sports", "opaque_hunting_list_and_reproach", speech="question", register="colloquial", context="high", flags="long_source|source_ambiguity", cefr="C1", score=74),
    1094: r("The speaker says they will pierce or poke something with the item and bargains over ten doro, then refuses to give it and asks the friend to give eight doro instead.", "화자는 그 물건으로 무언가를 찌르겠다고 하며 10도라를 요구해요. 곧 주지 않겠다고 했다가 친구에게 8도라를 달라고 흥정해요.", "shopping", "bargaining_over_doro_for_an_item", speech="request", register="colloquial", context="medium", flags="", state="draft", cefr="A2", score=32),
    1095: r("The speaker refuses to give the item for nothing, offers six doro or four doro, and distinguishes the money from money for bran and animal feed used to feed the cows.", "화자는 물건을 공짜로 주지 않겠다고 하며 6도라 또는 4도라를 제시하고, 그 돈은 겨와 가축 사료를 사서 소를 먹이는 돈과 다르다고 말해요.", "shopping", "bargaining_and_animal_feed_costs", speech="disagreement", register="colloquial", context="medium", flags="", state="draft", cefr="B1", score=42),
    1096: r("The speaker says they will keep or sleep with something unless it is sold, tells the listener to go, and uses several opaque surfaces about scratching, swelling, or biting; the bodily imagery is retained without choosing one reading.", "화자는 그것이 팔리지 않으면 간직하거나 함께 자겠다고 하며 상대에게 가라고 해요. 긁기나 부어오름, 무는 일처럼 읽힐 수 있는 불투명한 신체 표현들을 하나로 확정하지 않고 보존해요.", "daily_life", "opaque_bodily_reproach_during_a_sale", speech="complaint", register="offensive", context="high", flags="source_ambiguity", cefr="B2", score=62),
    1097: r("The speaker calls the situation or person upside down or overturned, asks God to send them to hell, says dogs will eat them, and says they will be rid of them; this is a curse.", "화자는 상황이나 상대가 뒤집혔다고 말하고 신이 상대를 지옥으로 보내기를 바라며 개들이 먹게 하겠다고 저주하고 자신이 상대에게서 벗어나겠다고 해요.", "crime_safety", "curse_with_dogs_and_hell", speech="warning", register="offensive", context="medium", flags="", state="draft", cefr="B1", score=46),
    1098: r("The speaker says the listeners have not released a person and have stayed all day, accuses them of betraying bread, asks why they are acting that way, and uses an opaque comic image involving a bundle and a pigeon or bathroom item being swallowed.", "화자는 상대가 사람을 풀어 주지 않고 하루 종일 있었다고 하며 빵을 배신한다고 비난해요. 왜 그렇게 하느냐고 묻고 묶음과 비둘기나 욕실 물건을 삼키는 듯한 불투명한 희극 이미지를 써요.", "crime_safety", "opaque_accusation_of_detention", flags="source_ambiguity", cefr="B2", score=64),
    1099: r("The speaker tells someone to sit there and says they want to go lie down because a molar hurts. They say they are fasting or have fasted in an opaque expression and warn the listener not to talk, adding an unclear mouth-related threat or offer.", "화자는 상대에게 거기 앉으라고 하고 어금니가 아파서 누우러 가고 싶다고 해요. 금식이나 머리에 관한 불투명한 표현을 쓰며 말하지 말라고 경고하고 입과 관련된 불분명한 말도 덧붙여요.", "health", "toothache_and_command_to_be_quiet", speech="complaint", register="colloquial", context="high", flags="source_ambiguity", cefr="B1", score=48),
    1100: r("The speaker says they do not understand and asks what the other person understands. They propose sitting and hunting lizandian, say they did not film anything, and call the fatigue useless. They list several opaque or foreign-derived hunting names, then say the others put this on them every day; the long list is preserved.", "화자는 이해하지 못한다고 하며 상대가 무엇을 이해하는지 물어요. 앉아서 lizandian을 사냥하자고 하고 아무것도 촬영하지 않았으며 피로가 쓸모없다고 해요. 여러 불투명하거나 외래어처럼 들리는 사냥 이름을 나열하고, 상대가 매일 자신에게 그것을 떠넘긴다고 말해 긴 목록을 보존해요.", "sports", "opaque_hunting_list_and_fatigue", speech="disagreement", register="colloquial", context="high", flags="long_source|source_ambiguity", cefr="C1", score=80),
    1101: r("The speaker says they will add money or another opaque kind of money, complains that they did not give it to the others, calls the listener a friend, and says the listener did not give them their due.", "화자는 돈이나 불투명한 종류의 돈을 더 주겠다고 하며 상대방에게 그것을 주지 않았다고 불평해요. 상대를 친구라고 부르고 자신의 몫을 주지 않았다고 말해요.", "finance", "complaint_about_unpaid_money", speech="complaint", register="colloquial", context="medium", flags="source_ambiguity", cefr="B1", score=44),
    1102: r("The speaker tells the listener not to repeat this talk, asks them to give a visa or opaque item, says they will not meet them, and says they will meet a ghoula and lizandian instead. They tell the listener to follow and curse the service; the named surfaces remain unchanged.", "화자는 이런 말을 다시 하지 말라고 하며 visa나 불투명한 물건을 달라고 해요. 상대를 만나지 않고 ghoula와 lizandian을 만나겠다고 하며 따라오라고 하고 그 서비스나 일을 저주해요. 명명된 표면형을 그대로 보존해요.", "administration", "refusal_and_request_for_an_opaque_document", speech="refusal", register="offensive", context="high", flags="source_ambiguity", cefr="B2", score=66),
    1103: r("In a long exchange, the speaker repeats an opaque name or address, says others did not bring them, tells them to let the speaker down or take them down, and describes friends from the listener's village as having detained them. The speaker alternates between saying they are there and not there, mentions running away or being taken, says they came yesterday and were housed in kadous, and complains of cold, hunger, and thirst; actor and place references remain uncertain.", "긴 대화에서 화자는 불투명한 이름이나 호칭을 반복하고 상대가 자신을 데려오지 않았다고 하며 내려 달라고 해요. 상대 마을의 친구들이 자신을 붙잡았다고 말하고, 거기에 있다거나 없다고 번갈아 말하며 도망치거나 끌려간 일을 언급해요. 어제 와서 kadous에 머물렀고 추위·배고픔·갈증을 겪었다고 불평하며 행위자와 장소는 불확실하게 남겨요.", "crime_safety", "long_opaque_detention_and_hardship_exchange", speech="complaint", register="offensive", context="high", flags="long_source|source_ambiguity", cefr="C1", score=86),
    1104: r("The speaker says the listener is here and asks why they deserve this treatment. They say they love the listener, while the listener replies that they do not love them; the speaker answers that it is not a problem.", "화자는 상대가 여기 있다고 하며 왜 자신이 이런 일을 겪어야 하느냐고 물어요. 상대를 사랑한다고 말하지만 상대는 사랑하지 않는다고 답하고, 화자는 괜찮다고 대답해요.", "family_relationships", "rejected_affection_and_reassurance", speech="disagreement", register="colloquial", context="medium", flags="", state="draft", cefr="A2", score=30),
    1105: r("The speaker says they tied or arranged an opaque middle or object, asks a brother why they do not understand it, and tells a son to do it with Boujadia as the others did not do it with them; the relationship and object remain uncertain.", "화자는 불투명한 중간 부분이나 물건을 묶었다고 하며 형제에게 왜 이해하지 못하느냐고 묻고, 아들에게 다른 사람들이 자신들과 하지 않은 일을 Boujadia와 하라고 해요. 관계와 대상은 불확실하게 보존해요.", "family_relationships", "opaque_instruction_in_family_exchange", speech="command", register="colloquial", context="high", flags="source_ambiguity", cefr="B2", score=60),
    1106: r("The speaker tells someone to raise their hands and look at them, calls them a troublemaker, asks where their friend is, and says the friend is in the forest hunting. The speaker says they do not know what the friend is doing, says they are not a worker or are a robot for one day, came to stroll for a while, then returns to a series of opaque insults and commands about a cat, seven, and going to the listener.", "화자는 상대에게 손을 들고 자신을 보라고 하며 문제를 일으키는 사람이라고 부르고 친구가 어디 있는지 물어요. 친구가 숲에서 사냥한다고 하며 무엇을 하는지 모르겠다고 하고, 자신은 일꾼이 아니거나 하루 동안 로봇이라고 말해요. 잠시 산책하러 왔다고 한 뒤 고양이·일곱·상대에게 가라는 불투명한 모욕과 명령을 이어 가요.", "crime_safety", "long_opaque_accusation_and_forest_hunt", speech="command", register="offensive", context="high", flags="long_source|source_ambiguity", cefr="C1", score=84),
    1107: r("The speaker addresses a friend, asks them to come back repeatedly, says they are laughing at them, and tells them not to worry so they can understand one another. They ask where the friend saw them worried, mention a hidden head or carbine-like surface and a deadly danger, say they will not remain or find them together, and finish with an opaque name and father reference.", "화자는 친구를 부르며 여러 번 돌아오라고 하고 상대를 비웃는다고 말해요. 걱정하지 말고 서로 이해하자고 하며 상대가 어디에서 자신이 걱정하는 모습을 봤는지 묻고, 숨겨진 머리나 카빈처럼 들리는 표면과 죽을 위험을 언급해요. 함께 남거나 찾지 않겠다고 하며 불투명한 이름과 아버지 언급으로 끝나요.", "crime_safety", "long_opaque_threat_and_reassurance", speech="warning", register="offensive", context="high", flags="long_source|source_ambiguity", cefr="C1", score=82),
    1108: r("The speaker says they were absent or distracted for five minutes and accuses the listeners of killing someone, reminding them that bullets are forbidden there.", "화자는 5분 동안 자리를 비웠거나 한눈을 팔았다고 하며 상대가 누군가를 죽였다고 비난하고, 그곳에서는 총알이 금지되어 있다고 상기시켜요.", "crime_safety", "warning_about_forbidden_bullets", speech="warning", register="colloquial", context="medium", flags="source_ambiguity", cefr="B1", score=48),
    1109: r("The speaker says there was no one who saw the heads or people, then says it is normally possible to see them and mentions seeing them during Ramadan. They conclude that the listeners are completely unaware; the reference remains opaque.", "화자는 머리나 사람들을 본 사람이 없다고 했다가 보통은 볼 수 있고 라마단 달에는 그를 볼 수 있다고 말해요. 상대가 전혀 알아차리지 못한다고 결론 내리며 지칭은 불투명하게 남겨요.", "religion", "opaque_visibility_statement_during_ramadan", speech="description", register="colloquial", context="high", flags="source_ambiguity", cefr="B2", score=58),
    1110: r("The speaker asks who knocked or laid someone down and swears they do not know. They say they were inside lahi and that every three weeks they see someone laid down there, but they did not see the person and remain inside; the location surface is uncertain.", "화자는 누가 누군가를 쓰러뜨리거나 눕혔는지 묻고 자신은 모른다고 맹세해요. lahi 안에 있었다고 하며 3주마다 그곳에서 누군가 쓰러진 것을 본다고 하지만 이번에는 보지 못했고 계속 안에 있다고 해요. 장소 표면은 불확실해요.", "crime_safety", "report_of_people_being_knocked_down", speech="information", register="colloquial", context="high", flags="source_ambiguity", cefr="B2", score=62),
    1111: r("The speaker says the listener does not see anything and says they work and meet people in an opaque way. They ask why there is no two-hour register or commerce register, preserving the administrative surfaces without fixing the activity.", "화자는 상대가 아무것도 보지 못한다고 하며 자신은 일하고 사람들을 만난다고 불투명하게 말해요. 왜 2시간짜리 등록이나 상업 등록이 없느냐고 묻고 활동을 확정하지 않은 채 행정 표면을 보존해요.", "administration", "opaque_work_and_registration_question", speech="question", register="colloquial", context="high", flags="source_ambiguity", cefr="B2", score=64),
    1112: r("The speaker says the listener has not finished lizam or another opaque task and tells them to sit because a forensic doctor is being brought.", "화자는 상대가 lizam이나 다른 불투명한 일을 끝내지 않았다고 하며 앉아 있으라고 해요. 법의학 의사를 데려오겠다고 말해요.", "crime_safety", "waiting_for_a_forensic_doctor", speech="command", register="colloquial", context="medium", flags="source_ambiguity", cefr="B1", score=46),
    1113: r("The speaker says they do not know about the listeners, will change jobs tomorrow, addresses Moulkheir, and tells him to loosen himself or let the speaker go with him. They say they are playing and ask whether they should ask the listener; the actor directions remain uncertain.", "화자는 상대들에 대해 모르겠다고 하며 내일 일을 바꾸겠다고 해요. 물카이르를 부르고 자신을 풀어 주거나 함께 가게 해 달라고 하며, 놀고 있다고 말하고 물어볼지 묻어요. 행위자 방향은 불확실해요.", "work", "opaque_job_change_and_release_request", speech="request", register="colloquial", context="high", flags="source_ambiguity", cefr="B2", score=58),
    1114: r("The speaker says the listener is not jumping and that the speaker came for their sake. They deny that the listener wants to make something disappear for the coupons, then say they wanted to make it disappear for them because the listener came; the opaque term is preserved.", "화자는 상대가 뛰는 것이 아니며 자신이 상대를 위해 왔다고 해요. 상대가 coupons처럼 들리는 것을 없애려는 것이 아니라고 했다가, 상대가 왔기 때문에 자신이 그들을 위해 없애고 싶었다고 말해 불투명한 표현을 보존해요.", "shopping", "opaque_exchange_about_coupons_or_items", speech="disagreement", register="colloquial", context="high", flags="source_ambiguity", cefr="B2", score=60),
    1115: r("The speaker tells the listener not to ask and to release themselves, asks why they are being shameful, and wishes that their heart has goodness. They ask the listener to let them hear a little of an opaque cry or noise.", "화자는 상대에게 묻지 말고 스스로 풀려나라고 하며 왜 부끄럽게 구느냐고 묻고 마음에 선함이 있기를 바라요. 불투명한 울음이나 소리를 조금 들려 달라고 해요.", "family_relationships", "reproach_and_request_to_hear_a_sound", speech="complaint", register="colloquial", context="high", flags="source_ambiguity", cefr="B1", score=48),
    1116: r("The speaker asks a sir what decision was made. The answer is that they decided on war, honor, and manliness, then tells the others to go away and asks where they should go.", "화자는 선생님이나 어른에게 무엇을 결정했는지 묻고, 전쟁·명예·남자다움으로 결정했다고 답해요. 이어 상대에게 떠나라고 하고 자신들은 어디로 가야 하느냐고 물어요.", "crime_safety", "declaring_war_and_demanding_departure", speech="warning", register="mixed", context="medium", flags="", state="draft", cefr="B1", score=48),
    1117: r("The speaker asks where the listener is stuck and says they are by a tree. They tell the listener to go, appeal to the right of what was released between them, suggest using a telephone number, and finally say God will bring it to the listener; several relations remain opaque.", "화자는 상대가 어디에 붙어 있는지 묻고 나무 옆에 있다고 해요. 가라고 하며 서로 풀어 준 일의 권리를 언급하고 전화번호를 쓰자고 했다가 하나님이 그것을 가져다주실 것이라고 말해 관계를 불투명하게 남겨요.", "daily_life", "opaque_departure_and_phone_exchange", speech="command", register="colloquial", context="high", flags="source_ambiguity", cefr="B2", score=58),
    1118: r("The speaker tells the listener to go and not be frightened by their own trouble, asks what they did, and complains that they are still playing with dogs.", "화자는 상대에게 가라고 하며 자신의 소동을 두려워하지 말라고 하고 자신이 무엇을 했는지 물어요. 상대가 아직도 개들과 장난치고 있다고 불평해요.", "crime_safety", "reproach_about_playing_with_dogs", speech="complaint", register="colloquial", context="medium", flags="source_ambiguity", cefr="B1", score=42),
    1119: r("The speaker says they did not feed the dogs and accuses the listener of not giving them food or drink, saying the listener caused the hunt to be lost. They want to ask where the listener was for three days and say they now know they are the listener's child; the kinship and time reference are retained.", "화자는 개들에게 먹이를 주지 않았다고 하며 상대가 개들에게 먹거나 마실 것을 주지 않았다고 비난하고, 그 때문에 사냥을 망쳤다고 해요. 상대가 3일 동안 어디 있었는지 물으려 하며 이제 자신이 상대의 자식이라는 것을 안다고 말해 시간과 친족 관계를 보존해요.", "family_relationships", "accusation_about_dogs_and_three_day_absence", speech="complaint", register="colloquial", context="high", flags="long_source|source_ambiguity", cefr="B2", score=68),
    1120: r("The speaker asks the listener to tell them where they were.", "화자는 상대에게 어디 있었는지 말해 달라고 해요.", "daily_life", "asking_where_someone_was", speech="question", register="neutral", context="low", flags="", state="draft", cefr="A1", score=12),
    1121: r("The speaker says two people took them and tied them, although they do not know who they are. They say they were housed in kadous for three days with no dinner or breakfast and that the listeners made them lacking; the place and final accusation remain opaque.", "화자는 두 사람이 자신을 데려가 묶었지만 그들이 누구인지는 모른다고 해요. kadous에 3일 동안 머물며 저녁과 아침을 먹지 못했고 상대가 자신을 부족하게 만들었다고 말해 장소와 마지막 비난을 불투명하게 보존해요.", "crime_safety", "detention_and_food_deprivation", speech="complaint", register="colloquial", context="high", flags="long_source|source_ambiguity", cefr="B2", score=70),
    1122: r("The speaker says the listener is not Boiya and only appears to be Boiya. A friend tells them not to cry, saying they will understand with the others now.", "화자는 상대가 Boiya가 아니고 그렇게 보일 뿐이라고 해요. 친구는 울지 말라고 하며 이제 상대가 다른 사람들과 함께 이해하게 될 것이라고 말해요.", "family_relationships", "denial_of_identity_and_reassurance", speech="answer", register="colloquial", context="medium", flags="source_ambiguity", cefr="A2", score=30),
    1123: r("The speaker says the listener appears to have brought them only to the listener's place. A woman or chief arrives; the speaker tells someone to be quiet, bring in their daughter, and give her a little fenugreek.", "화자는 상대가 자신을 상대의 집에만 데려온 것처럼 보인다고 해요. 여성이나 우두머리가 도착하고, 화자는 조용히 하며 딸을 안으로 데려와 약간의 호로파를 주라고 해요.", "family_relationships", "bringing_a_daughter_inside_and_giving_fenugreek", speech="command", register="colloquial", context="high", flags="source_ambiguity", cefr="B1", score=52),
    1124: r("The speaker says, thank God, they did not do anything except an opaque activity, then says there is no war and tells the listener to go and play; the final command is repeated.", "화자는 하느님께 감사하며 불투명한 어떤 일 외에는 아무것도 하지 않았다고 해요. 전쟁은 전혀 없다고 하며 상대에게 가서 놀라고 하고 마지막 명령을 반복해요.", "crime_safety", "denying_war_and_telling_someone_to_play", speech="command", register="colloquial", context="medium", flags="source_ambiguity", cefr="B1", score=44),
    1125: r("The speaker says they are talking with the listeners and tells them to go away. They ask someone to stand at the front and mention an opaque jifantes surface and how much someone did yesterday. They repeat zero-like surfaces and address a chief or other unclear person.", "화자는 상대들과 이야기하고 있다며 가라고 해요. 누군가에게 앞에 서라고 하고 불투명한 jifantes 표면과 어제 누군가가 한 일을 언급해요. 0처럼 들리는 표면을 반복하고 우두머리나 불분명한 사람을 불러요.", "daily_life", "opaque_reproach_and_report_of_yesterday", speech="command", register="colloquial", context="high", flags="long_source|source_ambiguity", cefr="C1", score=76),
    1126: r("The speaker says they brought this news and tells the listener to go away, addresses an opaque person named or sounding like Bourton, and asks for jifantes to speak to them. They call someone back, then bargain over 120 doro for a sheikh who was absent that night and another 120 doro for a group, listing large and small opaque items and high or low ones.", "화자는 이 소식을 가져왔다며 상대에게 가라고 하고 Bourton처럼 들리는 불투명한 이름을 부르며 jifantes가 자신에게 말하기를 원해요. 누군가를 다시 부른 뒤 그날 밤 사라진 셰이크를 위한 120도라와 집단을 위한 또 다른 120도라를 흥정하고, 크고 작은 불투명한 물건과 높고 낮은 것을 나열해요.", "finance", "long_bargaining_over_doro_and_opaque_items", speech="request", register="colloquial", context="high", flags="long_source|source_ambiguity", cefr="C1", score=84),
    1127: r("The speaker lists a known group present that night, asks the listener not to forget to go to their friend, then remembers an opaque arm or Yemeni surface. They mention a true vein, a red vein, and a contrast involving shinin and lizabaj; the blessing for health and all named surfaces are retained.", "화자는 그날 밤 있는 알려진 집단을 나열하고 상대에게 친구에게 가는 것을 잊지 말라고 해요. 불투명한 팔이나 예멘 관련 표면을 떠올리고 진짜 혈관과 붉은 혈관, shinin과 lizabaj 사이의 대조를 말하며 건강을 비는 표현과 이름을 보존해요.", "health", "opaque_health_and_group_blessing", speech="wish", register="mixed", context="high", flags="long_source|source_ambiguity", cefr="C1", score=82),
    1128: r("The speaker says they will give the listener a poem and also mentions friends who missed the listener last night. They tell the listener to hear what a poet says, then repeat the opaque refrain 7ay7aya and say the hunters should rise but should not eat them.", "화자는 상대에게 시 한 편을 주겠다고 하며 어젯밤 상대를 그리워한 친구들도 언급해요. 시인이 무슨 말을 하는지 들으라고 하고 불투명한 후렴 7ay7aya를 반복하며 사냥하는 사람들이 일어나되 그것들을 먹지는 말아야 한다고 해요.", "entertainment_music", "poem_and_opaque_hunting_refrain", genre="song_lyric", speech="narration", register="mixed", context="high", flags="long_source|source_ambiguity", cefr="C1", score=78),
    1129: r("The speaker says people who are passionate about hunting will come tomorrow, are awake from an opaque heat or smoke surface, cannot wait, and then adds the repeated opaque zghratat sound.", "화자는 사냥에 열중한 사람들이 내일 올 것이라고 하며 불투명한 열기나 연기 표면에서 깨어 있고 기다릴 수 없다고 해요. 이어 반복되는 불투명한 zghratat 소리를 덧붙여요.", "sports", "hunting_enthusiasm_and_opaque_refrain", genre="song_lyric", speech="description", register="mixed", context="high", flags="source_ambiguity", cefr="B2", score=66),
    1130: r("The speaker wishes that God replace what is lost and strengthen health, calls for joy, asks someone to turn over, asks where a bullet came from, mentions an opaque forest or hiding surface, and tells the listener to go.", "화자는 하느님이 잃은 것을 대신하고 건강을 강하게 해 주기를 바라며 기쁨을 말해요. 누군가에게 뒤집으라고 하고 총알이 어디에서 왔는지 물으며 불투명한 숲이나 숨음의 표면을 언급하고 가라고 해요.", "crime_safety", "health_wish_and_question_about_a_bullet", speech="warning", register="mixed", context="high", flags="source_ambiguity", cefr="B2", score=62),
    1131: r("The speaker says they turned it toward artists and asks who killed this. They say they did not see it and that the listener did not see it either, then say they are in an opaque kozina or similar place and still did not see it.", "화자는 그것을 예술가들에게 돌렸다고 하며 누가 이것을 죽였는지 물어요. 자신도 보지 못했고 상대도 전혀 보지 못했다고 하며 불투명한 kozina 같은 장소에 있지만 보지 못했다고 말해요.", "entertainment_music", "opaque_question_about_artists_and_an_event", speech="question", register="colloquial", context="high", flags="source_ambiguity", cefr="B2", score=60),
    1132: r("The speaker says life is not pleasing, compares it with a door lock, and says they are looking for a leader. They ask the listener to request less than ten miles or doro from madam and ask whether the listener is listening.", "화자는 삶이 즐겁지 않다고 하며 문 자물쇠와 비교하고 지도자나 우두머리를 찾고 있다고 해요. madam에게 10마일이나 도라보다 적은 것을 요구해 달라고 하며 상대가 듣고 있는지 물어요.", "finance", "request_to_madam_and_complaint_about_life", speech="request", register="colloquial", context="high", flags="source_ambiguity", cefr="B2", score=60),
    1133: r("The speaker tells someone to go along with her, says they will explain and make them understand, repeats that life is not pleasing, and tells the listener to tie or finish it and let the speaker go ask for themselves.", "화자는 누군가에게 그녀와 함께 가라고 하며 설명하고 이해시키겠다고 해요. 삶이 즐겁지 않다는 말을 반복하고 상대에게 그것을 묶거나 마무리하라고 한 뒤 자신이 직접 물으러 가게 해 달라고 해요.", "daily_life", "opaque_instruction_about_leaving_and_explaining", speech="command", register="colloquial", context="high", flags="source_ambiguity", cefr="B2", score=58),
    1134: r("The speaker says they are coming and describes a woman or place as empty. They tell someone to listen, say the other person will finish with a man with black hair, and call Khaldar expensive.", "화자는 오고 있다고 하며 여성이나 장소가 비어 있다고 말해요. 들으라고 하고 상대가 검은 머리 남자와 마무리할 것이라고 하며 Khaldar가 비싸다고 해요.", "family_relationships", "opaque_arrival_and_bargaining_reference", speech="information", register="colloquial", context="high", flags="source_ambiguity", cefr="B1", score=50),
    1135: r("The speaker calls Khaldar an agent or source of evil, asks what the listener is doing, and says the listener is among tents all day, in the tents, in the bathroom, and not one of them. They end with repeated commands to swallow it.", "화자는 Khaldar를 악의 근원처럼 부르며 상대가 무엇을 하는지 물어요. 상대가 하루 종일 천막에 있고 천막과 욕실에 있으며 자신들과 같은 편이 아니라고 하고 삼키라는 명령을 반복해요.", "crime_safety", "reproach_about_tents_and_bathroom", speech="complaint", register="offensive", context="high", flags="source_ambiguity", cefr="B2", score=62),
    1136: r("The speaker says well done, says they are here, and tells someone to walk in front. They mention that a whip is still available and that they will give it to the listener in the house.", "화자는 잘했다고 하며 자신이 여기 있다고 말하고 상대에게 앞장서서 걸으라고 해요. 아직 채찍이 있다며 집에서 그것을 주겠다고 해요.", "daily_life", "command_to_walk_ahead_with_a_whip", speech="command", register="offensive", context="medium", flags="", state="draft", cefr="A2", score=34),
    1137: r("The speaker says they brought a few drinks for a madam and thinks she is fasting these days. They say they planned to visit the poor woman because she has no one, but that they are the only person who comes to ask about her; the final reproach is retained.", "화자는 madam에게 마실 것을 조금 가져왔고 그녀가 요즘 금식하는 것 같다고 해요. 그 불쌍한 여성에게 아무도 없어서 찾아가려 했지만 자신만 그녀를 찾아오는 사람이라고 말하며 마지막의 불평을 보존해요.", "health", "visiting_a_woman_who_may_be_fasting", speech="information", register="mixed", context="high", flags="long_source|source_ambiguity", cefr="B2", score=66),
    1138: r("The speaker asks forgiveness from the sheikh of the Sons of the Day tribe and says they wronged him and did not pass his matter correctly. They deny being the flitshat that deceived them, explain that they thought the listener's group had acted against them, and say the group wanted to ignite the fire of fitna between them.", "화자는 울라드 나하르 부족의 셰이크에게 용서를 구하며 자신이 그를 부당하게 대했고 그의 일을 제대로 전달하지 않았다고 해요. 자신을 속인 것이 flitshat은 아니라고 부인하고 상대 집단이 자신들에게 공격적으로 행동했다고 생각했다며 서로 사이에 fitna의 불을 지피려 했다고 말해요.", "crime_safety", "apology_and_accusation_of_inciting_fitna", speech="apology", register="mixed", context="high", flags="long_source|source_ambiguity", cefr="C1", score=78),
    1139: r("The speaker denies that they are igniting a fire of fitna, says they are speaking generally, and describes the group as relatives or good people. They say Boiya and the speakers are paternal cousins; the kinship surface is preserved.", "화자는 자신들이 fitna의 불을 지피는 것이 아니라고 부인하고 일반적으로 말하는 것이라고 해요. 자신들이 친척이거나 좋은 사람들이라고 하며 Boiya와 자신들은 친가 쪽 사촌이라고 말해 친족 표면을 보존해요.", "family_relationships", "denial_and_paternal_cousin_claim", speech="disagreement", register="mixed", context="high", flags="source_ambiguity", cefr="B2", score=64),
    1140: r("The speaker tells someone to swallow it and says that when elders speak, the young should be quiet. They name opaque figures or titles such as Sidi Gous and Sidi Zounfoun, say they will feed meat to the person involved today, call the matter expensive, and tell the listener to follow and leave their brother.", "화자는 그것을 삼키라고 하며 어른들이 말할 때 젊은이는 조용히 해야 한다고 해요. Sidi Gous와 Sidi Zounfoun처럼 불투명한 인물이나 호칭을 부르고 오늘 그 사람에게 고기를 먹이겠다고 하며 일이 비싸다고 말한 뒤 따라오고 형제를 두고 가라고 해요.", "family_relationships", "elder_authority_and_opaque_named_figures", speech="command", register="offensive", context="high", flags="source_ambiguity", cefr="C1", score=74),
    1141: r("The speaker asks whether the kouboui or opaque group is at the end of time, accuses the listeners of kidnapping only women and small girls, and says they found or did nothing.", "화자는 kouboui나 불투명한 집단이 세상의 끝에 있는지 묻고, 상대가 여자와 어린 소녀만 납치한다고 비난하며 아무것도 찾거나 하지 못했다고 말해요.", "crime_safety", "accusation_of_kidnapping_women_and_girls", speech="complaint", register="offensive", context="medium", flags="source_ambiguity", cefr="B2", score=66),
    1142: r("The speaker addresses a brother, tells him to go, says that he kidnapped the speaker but that this is not the same kidnapping, and asks the listener to look at how he is holding on.", "화자는 형제를 부르며 가라고 하고 그가 자신을 납치했지만 이것은 그런 납치가 아니라고 말해요. 그가 어떻게 붙잡고 있는지 보라고 해요.", "crime_safety", "disputed_kidnapping_and_restraint", speech="complaint", register="offensive", context="high", flags="", state="draft", cefr="B1", score=54),
    1143: r("In a long exchange, the speaker asks Hazim to forgive them and asks for something while wanting to know how he and the others acted. They say they cannot hear, ask whether Hazim was alone or with a group, distinguish two people with each side, ask to be allowed, and say they are fine. They call Akasha to go, say God gave someone reason on the day they took the speaker, ask where they were taken, accuse Hazim and a friend of carrying them to a madam, then ask what will be made and threaten to roast or set fire to them; actor and object references remain source-close and partly opaque.", "긴 대화에서 화자는 하짐에게 용서해 달라고 하며 무엇인가를 요구하고 그와 다른 사람들이 어떻게 했는지 알고 싶다고 해요. 들리지 않는다고 하고 하짐이 혼자였는지 집단과 함께였는지 묻고, 양쪽에 두 사람이 있었다고 구분하며 허락해 달라고 해요. 괜찮다고 말한 뒤 Akasha에게 가라고 하고, 자신을 데려간 날 누군가에게 이성이 주어졌다고 하며 어디로 데려갔는지 묻어요. 하짐과 친구가 자신을 madam에게 데려왔다고 비난하고 무엇을 만들 것인지 물으며 굽거나 불을 붙이겠다고 위협해 행위자와 대상의 불확실성을 보존해요.", "crime_safety", "long_accusation_and_threat_against_hazim", speech="warning", register="offensive", context="high", flags="long_source|source_ambiguity", cefr="C1", score=88),
    1144: r("The speaker says they will make stuffed cabbage and that it will be tasty, then asks Hazim to forgive them.", "화자는 속을 채운 양배추 요리를 만들면 맛있을 것이라고 말한 뒤 하짐에게 용서해 달라고 해요.", "food", "stuffed_cabbage_and_apology", speech="apology", register="colloquial", context="medium", flags="", state="draft", cefr="A2", score=28),
    1145: r("The speaker says they are only a woman and asks to be released, insists they did nothing, asks why the listeners want to kill them, and asks Boiya what they did to him.", "화자는 자신이 그저 여자일 뿐이라며 풀어 달라고 하고 아무것도 하지 않았다고 주장해요. 왜 자신을 죽이려 하느냐고 묻고 Boiya에게 자신이 그에게 무엇을 했는지 물어요.", "crime_safety", "plea_for_release_and_denial_of_wrongdoing", speech="request", register="offensive", context="medium", flags="", state="draft", cefr="B1", score=50),
    1146: r("Hazim asks whether the listener knew a spy or informer named jasus who had been making trouble. The reply says they knew him and will leave him suddenly, then uses opaque place or name surfaces and offers a daily amount of grain or seed to a brother who does not come.", "하짐은 문제를 일으키던 jasus라는 스파이나 밀고자를 상대가 아는지 물어요. 상대는 안다고 하며 갑자기 그를 떠나겠다고 하고, 불투명한 장소나 이름을 언급한 뒤 오지 않는 형제에게 매일 곡물이나 씨앗을 주겠다고 해요.", "crime_safety", "question_about_an_informer_and_opaque_payment", speech="question", register="colloquial", context="high", flags="source_ambiguity", cefr="B2", score=68),
    1147: r("The speaker says the donkey eats bran and offers to buy a kofrit or opaque item if they are not a donkey; the animal and object surfaces are retained.", "화자는 당나귀가 겨를 먹는다고 하며 자신이 당나귀가 아니라면 kofrit이나 불투명한 물건을 사 주겠다고 해요. 동물과 물건의 표면형을 보존해요.", "food", "donkey_feed_and_opaque_purchase_joke", genre="joke", speech="other", register="colloquial", context="medium", flags="source_ambiguity", cefr="B1", score=44),
    1148: r("The speaker says good morning and tells the listener not to be frightened; the speaker says it is only them.", "화자는 좋은 아침이라고 인사하며 상대에게 전혀 놀라지 말라고 하고 여기에는 자신만 있다고 말해요.", "daily_life", "morning_reassurance", speech="greeting", register="neutral", context="low", flags="", state="draft", cefr="A1", score=10),
    1149: r("Abdelkader asks Hawari how he is doing.", "압델카데르가 하와리에게 어떻게 지내는지 물어요.", "daily_life", "asking_how_someone_is", speech="question", register="neutral", context="low", flags="", state="draft", cefr="A1", score=8),
    1150: r("Hawari replies that he is fine, says praise be to God, and asks Abdelkader how he is.", "하와리가 잘 지낸다고 답하고 하느님을 찬양하며 압델카데르에게 어떻게 지내는지 물어요.", "daily_life", "answering_a_greeting", speech="answer", register="neutral", context="low", flags="", state="draft", cefr="A1", score=10),
    1151: r("Abdelkader replies that he is fine.", "압델카데르가 잘 지낸다고 답해요.", "daily_life", "brief_wellbeing_reply", speech="answer", register="neutral", context="low", flags="", state="draft", cefr="A1", score=6),
    1152: r("Hawari asks whether there is anything new.", "하와리가 새로운 일이 있는지 물어요.", "daily_life", "asking_for_news", speech="question", register="neutral", context="low", flags="", state="draft", cefr="A1", score=8),
}

def build():
    engine.BATCH_ID = BATCH_ID
    engine.BASE_COMMIT = BASE_COMMIT
    engine.PROMPT_VERSION = PROMPT_VERSION
    engine.TARGET_START = TARGET_START
    engine.TARGET_END = TARGET_END
    engine.BATCH_OUT = BATCH_OUT
    engine.MANIFEST_OUT = MANIFEST_OUT
    engine.QA_OUT = QA_OUT
    engine.RAW = RAW
    return engine.build()

if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    print(json.dumps(build(), ensure_ascii=False, indent=2))
