"""Build source-only MADOran enrichment Batch 13 for Sentno 769..832."""
from __future__ import annotations

import json
import sys
from pathlib import Path

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts import build_madoran_enrichment_batch10 as engine
from scripts.build_madoran_enrichment_scaffold import ROOT

BATCH_ID = "MADORAN-ENRICH-013"
BASE_COMMIT = "7f948a5"
PROMPT_VERSION = "madoran-source-enrichment-v13"
TARGET_START = 769
TARGET_END = 832
BATCH_OUT = ROOT / "data/master/enrichment/batches/batch13_sentno_0769_0832.tsv"
MANIFEST_OUT = ROOT / "data/master/enrichment/batches/batch13_manifest.json"
QA_OUT = ROOT / "data/master/qa/madoran_enrichment_batch13_generation_qa.json"
BATCH_FIELDS = engine.BATCH_FIELDS
item = engine.item


def r(english, korean, domain, topic, genre="conversation", speech="description", register="colloquial", context="high", flags="source_ambiguity", state="flagged", cefr="B2", score=60):
    return item(english, korean, cefr, score, domain, topic, genre, speech, register, context, flags, state)


RAW = {
    769: r("The speaker says that they go swimming and stay up late, but afterward they insult or mock the addressee; the social context is unclear.", "화자는 사람들이 수영을 하고 밤늦게까지 놀지만 그 뒤 상대를 헐뜯거나 놀린다고 말해요. 사회적 맥락은 불분명해요.", "daily_life", "swimming_late_night_and_mockery", "conversation", "complaint"),
    770: r("A lament about Oran says that its haouch or old homes were demolished and its future was wasted; an Oran woman and crowded household images are praised and criticized in dense colloquial language.", "오랑에 대한 탄식은 옛 주거지나 집들이 허물어지고 미래가 망가졌다고 말해요. 오랑 여인과 붐비는 집안의 모습이 조밀한 구어체로 칭찬과 비판을 받아요.", "history", "oran_demolished_homes_and_woman", "proverb", "opinion", "mixed", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "C1", 78),
    771: r("Marzak is challenged about bringing the speaker there and starting this discussion. The speaker says the villa or house is being sold and objects to selling their home.", "마르자크가 화자를 여기 데려와 이런 말을 하게 한 이유를 따져요. 화자는 별장이나 집을 팔려 한다며 자기들의 집을 파는 데 반대해요.", "housing", "dispute_over_selling_family_home", "conversation", "complaint", "mixed", "high", "long_source|source_ambiguity"),
    772: r("The speaker asks them to stop humiliating the family because people can hear them, and says the speaker knows what happened this month; the relation to outsiders is unclear.", "화자는 사람들이 듣고 있으니 가족을 망신시키는 일을 그만하라고 해요. 이번 달에 무슨 일이 있었는지는 화자가 알고 있다며 외부 사람들과의 관계는 불분명하게 남겨요.", "family_relationships", "family_argument_about_public_shame", "conversation", "warning", "mixed", "high", "source_ambiguity"),
    773: r("The speakers say they lost their father and their business or company, and now someone wants to sell their home, leaving them without a house or anything else.", "화자들은 아버지와 사업이나 회사를 잃었고, 이제 누군가 집까지 팔려 해 집도 아무것도 없이 남게 된다고 말해요.", "housing", "loss_of_business_and_home", "conversation", "complaint", "mixed", "high", "long_source|source_ambiguity"),
    774: r("One person asks for another solution, while the other says selling the house is not their problem and tells them to get the idea of selling it out of their head.", "한 사람은 다른 해결책을 달라고 하고, 다른 사람은 집을 파는 일은 자신의 문제가 아니니 그 생각을 머리에서 지우라고 해요.", "housing", "rejecting_a_home_sale_solution", "conversation", "request", "colloquial", "high", "source_ambiguity"),
    775: r("Zino is asked to slow down and listen. The speaker argues that the very large villa is too expensive to maintain and that even renovating it is unaffordable.", "지노에게 천천히 자신을 이해하게 해 달라고 해요. 아주 큰 별장은 유지비가 너무 많이 들고 수리조차 감당할 수 없다고 주장해요.", "housing", "villa_maintenance_costs", "conversation", "complaint", "colloquial", "high", "source_ambiguity"),
    776: r("The speaker proposes selling the villa, buying a smaller home for the two of them, and using the remaining money for a small project so they can get back on their feet.", "화자는 별장을 팔고 둘이 살 작은 집을 사며, 남은 돈으로 작은 사업을 해 다시 자립하자고 제안해요.", "housing", "selling_villa_and_restarting", "conversation", "suggestion", "mixed", "high", "source_ambiguity"),
    777: r("The speaker accepts that selling may be a solution but questions a price of two billion. They say the beautiful house in a good location could be listed on Ouedkniss and bring ten, normally.", "화자는 매도가 해결책일 수는 있지만 20억 가격을 묻고, 좋은 곳의 아름다운 집을 우드키니스에 올리면 보통 100억은 받을 수 있다고 말해요.", "housing", "villa_price_and_ouedkniss_listing", "conversation", "information", "mixed", "high", "code_switching|source_ambiguity"),
    778: r("The speaker says there has been no sale despite five months of searching through a real-estate agency. They found a buyer but the buyer was not suitable and had to be replaced.", "화자는 5개월 동안 부동산 중개업소를 찾아다녔지만 팔리지 않았다고 해요. 구매자를 찾았지만 적합하지 않아 바꿔야 했다고 말해요.", "housing", "failed_real_estate_sale", "conversation", "complaint", "mixed", "high", "code_switching|long_source|source_ambiguity"),
    779: r("A greeting begins a real-estate conversation. A visitor asks whether they may sit and talk for a while, while the other person says they are speaking with a brother and welcomes them.", "인사로 부동산 대화가 시작돼요. 방문객은 잠시 앉아 이야기해도 되는지 묻고, 상대는 형제와 이야기 중이라며 환영해요.", "housing", "real_estate_greeting_and_waiting", "conversation", "greeting", "mixed", "medium", "code_switching|source_ambiguity"),
    780: r("The agent presents the villa and says it is in a calm neighborhood with everything nearby. The visitor is welcomed and asks whether they can go inside to look.", "중개인은 별장을 보여 주며 조용한 동네에 있고 필요한 것이 모두 가까이 있다고 말해요. 방문객은 환영받고 안으로 들어가 볼 수 있는지 물어요.", "housing", "villa_viewing_in_quiet_neighborhood", "conversation", "information", "mixed", "medium", "source_ambiguity"),
    781: r("They agree to enter through the door. The villa is described as costing three billion, and the other person says they can inspect it first and discuss the price later; it is said to be impossible to find another at that price.", "그들은 문으로 들어가 보기로 해요. 별장 가격은 30억이라고 소개되고, 먼저 살펴본 뒤 나중에 이야기하자고 해요. 그 가격에 이런 집을 찾기는 어렵다고 말해요.", "housing", "villa_inspection_and_price", "conversation", "information", "mixed", "high", "code_switching|source_ambiguity"),
    782: r("Mr. Elias apologizes for calling at a bad time but asks the listener to tell the mother to come to the office tomorrow, God willing, about an important matter.", "엘리아스 씨는 때가 좋지 않아 미안하다고 하면서도, 중요한 일 때문에 하느님의 뜻이라면 내일 어머니가 사무실로 오시라고 전해 달라고 해요.", "family_relationships", "request_for_mothers_office_appointment", "conversation", "request", "mixed", "high", "source_ambiguity"),
    783: r("The listener says it is no problem, thanks him, wishes him courage, and says goodbye with a blessing.", "상대는 괜찮다고 하며 감사와 격려를 전하고 축복과 함께 작별해요.", "daily_life", "thanks_and_encouragement", "conversation", "thanks", "mixed", "low", "code_switching"),
    784: r("The speaker says they are negotiating by phone. They understand the other person and will speak after the others arrive to prepare the needed amount; they worry someone else may offer more, then end the call when the others enter.", "화자는 전화로 협상 중이라고 말해요. 다른 사람들이 도착하면 필요한 금액을 준비하도록 이야기하겠다고 하며, 누군가 더 많이 제안할까 걱정하다가 사람들이 들어오자 전화를 끊어요.", "housing", "phone_negotiation_before_villa_sale", "conversation", "information", "mixed", "high", "code_switching|long_source|source_ambiguity"),
    785: r("A short follow-up says they will talk later.", "나중에 이야기하겠다는 짧은 후속 말이에요.", "daily_life", "follow_up_later", "other", "information", "neutral", "low", "", "draft", "A1", 15),
    786: r("A delayed greeting apologizes for worrying the group. The speaker says they were embarrassed to speak, had a plane to catch at midday, and apologizes for making everyone wait.", "늦은 인사가 이어지고 화자는 일행을 걱정시켜 미안하다고 해요. 말하기가 부끄러웠고 정오 비행기를 타야 했다며 기다리게 한 것을 사과해요.", "daily_life", "delayed_greeting_and_apology", "conversation", "apology", "mixed", "high", "code_switching|long_source|source_ambiguity"),
    787: r("Someone asks what is happening and tells another person to go speak with him.", "무슨 일이냐고 묻고 다른 사람에게 그와 이야기하러 가 보라고 해요.", "daily_life", "asking_about_a_disturbance", "conversation", "request", "colloquial", "medium", "source_ambiguity"),
    788: r("Salim is asked what he will drink. Mr. Jamal says he will be direct: he does not accept the current offer and asks whether they have made their decision, since they had agreed to meet and finish the purchase today.", "살림에게 무엇을 마실지 묻고, 자말 씨는 직접 말하겠다며 현재 제안을 받아들일 수 없다고 해요. 오늘 만나 매매를 끝내기로 했는데 결정을 내렸는지 물어요.", "housing", "villa_purchase_negotiation", "conversation", "complaint", "mixed", "high", "code_switching|long_source|source_ambiguity"),
    789: r("A short reply says that the speaker did not make any decision.", "화자는 아무 결정도 내리지 않았다고 짧게 답해요.", "housing", "no_decision_in_negotiation", "other", "information", "neutral", "low", "", "draft", "A1", 15),
    790: r("The speaker says they know how buying and selling works and that the younger brother seems to think the other person took advantage of his situation. They ask whether a decision has been made.", "화자는 매매가 어떻게 돌아가는지 안다며, 어린 남동생은 상대가 자신의 상황을 이용했다고 생각하는 것 같다고 말해요. 결정했는지 물어요.", "housing", "accusation_in_property_negotiation", "conversation", "complaint", "mixed", "high", "code_switching|source_ambiguity"),
    791: r("They ask Salim to speak directly. The parties say they had finished the discussion yesterday and agreed to complete it today, while acknowledging the family's difficult circumstances.", "살림에게 직접 이야기하라고 해요. 당사자들은 어제 협의를 마치고 오늘 끝내기로 했다고 하면서 가족의 어려운 사정도 이해한다고 말해요.", "housing", "resuming_property_deal_after_agreement", "conversation", "information", "mixed", "high", "code_switching|long_source|source_ambiguity"),
    792: r("The buyer raises the offer by five hundred million and says they will not discuss it further.", "구매자는 제안을 5억 올리고 더는 논의하지 않겠다고 말해요.", "housing", "raising_villa_offer", "conversation", "refusal", "mixed", "medium", "source_ambiguity"),
    793: r("They ask whether this is the final offer. One side proposes three hundred sixty million or four billion, then returns to the first offer of three billion six hundred and says ‘bon courage’; the negotiation is closed.", "이것이 최종 제안인지 묻고 36억이나 40억을 제시하다가 처음 제안인 36억으로 돌아가며 ‘bon courage’라고 해요. 협상은 끝나요.", "housing", "final_villa_price_negotiation", "conversation", "disagreement", "mixed", "high", "code_switching|source_ambiguity"),
    794: r("The speaker says their house would bring ten billion if sold tomorrow, complains that there is no sale and asks whether they are being driven mad, then says they will rely on God and congratulates the buyer if desired.", "화자는 자기 집을 내일 팔면 100억을 받을 수 있다고 말해요. 팔리지 않아 미치게 하느냐고 불평한 뒤 하느님께 맡기고, 원하면 축하한다고 말해요.", "housing", "house_value_and_accepting_a_sale", "conversation", "complaint", "mixed", "high", "source_ambiguity"),
    795: r("The speaker refuses to congratulate anyone until signing the act. They mention a billion ready to be paid in euros and discuss the villa's fittings and refrigerators.", "화자는 계약서에 서명할 때까지 축하하지 않겠다고 해요. 유로로 지급할 10억이 준비되어 있다고 하며 별장의 비품과 냉장고를 이야기해요.", "housing", "signing_and_euro_payment_for_villa", "conversation", "refusal", "mixed", "high", "code_switching|source_ambiguity"),
    796: r("They confirm the refrigerators and ask about the kitchen. The speaker invites the other person to come to the villa in case anything is needed or unknown.", "냉장고를 가져왔다고 확인하고 주방에 무엇이 있는지 물어요. 필요한 것이나 모르는 것이 있을 수 있으니 별장에 함께 가자고 해요.", "housing", "villa_fixtures_and_kitchen_visit", "conversation", "request", "mixed", "high", "code_switching|source_ambiguity"),
    797: r("The speaker has no time because of a plane, but says they have the phone number and can be contacted whenever needed, even at night.", "화자는 비행기 때문에 시간이 없지만 전화번호가 있으니 필요할 때 언제든, 밤에도 연락하라고 해요.", "daily_life", "phone_availability_before_travel", "conversation", "suggestion", "mixed", "medium", "code_switching|source_ambiguity"),
    798: r("They ask where the money is. It is with the notary to sign, and the speaker says the money can be collected and they can leave immediately if desired, relying on God.", "돈이 어디 있는지 묻자 공증인에게 서명하러 가 있다고 해요. 원하면 돈을 받고 바로 떠날 수 있다며 하느님께 맡기자고 해요.", "housing", "notary_and_receiving_sale_money", "conversation", "information", "mixed", "high", "code_switching|source_ambiguity"),
    799: r("Salima is offered more coffee. She asks for an honest opinion about the decor and villa, and the response is a hesitant or approving remark.", "살리마에게 커피를 더 권해요. 그녀는 장식과 별장에 대한 솔직한 의견을 묻고, 상대는 망설이거나 긍정하는 듯한 말을 해요.", "housing", "coffee_and_villa_decor_opinion", "conversation", "question", "mixed", "medium", "source_ambiguity"),
    800: r("The speaker says they asked Khaled's company for better decor and that the listener's brother would not refuse. Khaled has not risen yet because he entered at dawn and is very tired.", "화자는 칼레드의 회사에 더 좋은 장식을 부탁했고 상대의 오빠가 거절하지 않을 거라고 말해요. 칼레드는 새벽에 들어와 매우 피곤해서 아직 일어나지 않았어요.", "housing", "home_decor_and_tired_family_member", "conversation", "information", "mixed", "high", "code_switching|source_ambiguity"),
    801: r("Sabiha is greeted and invited to go see the aunt. Affectionate exclamations praise the speaker's beauty and daughter, and the speaker says they missed her.", "사비하를 부르며 이모를 보러 가자고 해요. 화자의 아름다움과 딸을 다정하게 외치며 딸이 그리웠다고 말해요.", "family_relationships", "greeting_and_missing_a_daughter", "conversation", "greeting", "mixed", "medium", "source_ambiguity"),
    802: r("They ask how the other person is and warn that seeing the aunt now will make them miss her. The visitor says they did not know she was leaving today, while the other says she is loved and missed.", "상대가 어떻게 지내는지 묻고 지금 이모를 보면 더 그리워질 거라고 해요. 방문객은 오늘 떠나는 줄 몰랐다고 하고, 상대는 모두가 그녀를 사랑하고 그리워한다고 말해요.", "family_relationships", "family_visit_and_missing_someone", "conversation", "question", "mixed", "high", "source_ambiguity"),
    803: r("The speaker reassures Salima that the house is her brother's house and she may stay there whenever she wants; they suggest leaving to study when the others pass by.", "화자는 살리마에게 그 집은 오빠의 집이니 언제든 머물러도 된다고 안심시켜요. 다른 사람들이 지나가면 공부하러 가자고 해요.", "family_relationships", "reassurance_about_staying_at_family_home", "conversation", "suggestion", "mixed", "high", "source_ambiguity"),
    804: r("The speaker says the visitor has changed since arriving there and has forgotten that they grew up together; what was studied is said to be deeply remembered in a coarse comparison.", "화자는 방문객이 이곳에 온 뒤 변했고 함께 자랐다는 사실을 잊은 것 같다고 해요. 배운 것은 깊이 기억한다고 거친 비교로 말해요.", "family_relationships", "family_memory_and_changed_relationship", "conversation", "complaint", "mixed", "high", "idiom_culture|source_ambiguity"),
    805: r("The speaker asks Salima to clear her heart and forget good years and difficult days. The speaker wants to forget the husband because he kept both spouses from leaving the situation.", "화자는 살리마에게 마음을 풀고 좋았던 세월과 힘들었던 날을 잊으라고 해요. 남편이 두 사람 모두 그 상황에서 벗어나지 못하게 해서 그를 잊고 싶다고 말해요.", "family_relationships", "marital_conflict_and_forgetting_pain", "conversation", "suggestion", "mixed", "high", "long_source|source_ambiguity"),
    806: r("Someone says that no one in Oran could handle his affairs, but only Ali could; there are a hundred or two hundred people who could handle them.", "누군가 오랑에서는 그의 일을 처리할 사람이 없고 알리만 할 수 있다고 말해요. 그런 일을 할 수 있는 사람이 백 명이나 이백 명은 있다고도 해요.", "family_relationships", "who_can_handle_affairs_in_oran", "conversation", "opinion", "mixed", "high", "source_ambiguity"),
    807: r("The speaker questions what it means to handle affairs and asks why the family came here and left the others there, hoping the days will improve instead of turning against them.", "화자는 일을 처리한다는 것이 무슨 뜻인지 묻고, 가족이 왜 이곳에 와 다른 사람들을 그곳에 두었는지 물어요. 세월이 나아지기를 바라며 자신들에게 불리해지지 않기를 바래요.", "family_relationships", "family_migration_and_better_days", "conversation", "question", "mixed", "high", "source_ambiguity"),
    808: r("The speaker asks whether Salima is in her right mind and reminds her that she knows why Khaled fled Oran; she should not imagine that Youssef and his group are shouting at her.", "화자는 살리마가 제정신인지 묻고, 칼레드가 왜 오랑을 떠났는지 그녀도 잘 안다고 해요. 유수프와 그 일행이 소리친다고 생각하지 말라고 해요.", "family_relationships", "why_khaled_left_oran", "conversation", "question", "mixed", "high", "source_ambiguity"),
    809: r("Salima asks whether the speaker is not afraid for her brother. The speaker answers that she fears for him even more and wants to be with him.", "살리마는 화자가 오빠를 걱정하지 않느냐고 묻고, 화자는 자신이 더 걱정하며 오빠와 함께 있고 싶다고 답해요.", "family_relationships", "sisterly_concern_for_brother", "conversation", "question", "mixed", "medium", "source_ambiguity"),
    810: r("The speaker says Salima will be better than his mother and sister, but asks whether she wants Khaled to leave his wife and children in Oran. Khaled cannot live far from them; the family came for the children to attend a private school and be raised well.", "화자는 살리마가 자신의 어머니와 누이보다 나을 거라고 말하지만, 칼레드가 아내와 아이들을 오랑에 두고 오기를 바라는지 물어요. 칼레드는 가족과 멀리 살 수 없고, 가족은 아이들이 사립학교에 다니며 잘 자라게 하려고 왔다고 해요.", "family_relationships", "family_migration_for_childrens_schooling", "conversation", "question", "mixed", "high", "long_source|source_ambiguity"),
    811: r("The speaker asks why the others would come and says there is no difference between here and there. A woman complains that she is being mocked for not giving birth, while she says wanting something for herself is God's matter.", "화자는 다른 사람들이 왜 오겠느냐며 여기나 저기나 다를 것이 없다고 해요. 한 여성이 아이를 낳지 못한다고 조롱받는다고 불평하고, 자신을 위해 원하는 것은 하느님의 뜻이라고 말해요.", "family_relationships", "childlessness_and_family_reproach", "conversation", "complaint", "mixed", "high", "idiom_culture|source_ambiguity"),
    812: r("The speaker says that anyone who tells the truth is mocked, curses the situation, and asks them to leave this subject and return to another discussion.", "화자는 진실을 말하는 사람은 조롱받는다고 하며 상황을 욕하고, 이 주제를 그만두고 다른 이야기로 돌아가자고 해요.", "family_relationships", "truth_and_family_reproach", "conversation", "complaint", "mixed", "medium", "idiom_culture|source_ambiguity"),
    813: r("One person asks the other to wake him. She says she cannot because he is upset, but urges them to take her to Oran because the driver is coming and she does not want to leave without seeing her brother.", "한 사람은 그를 깨워 달라고 해요. 상대는 그가 화가 나서 깨울 수 없다고 하지만, 운전기사가 곧 오니 오랑으로 데려가 달라고 하며 오빠를 보지 않고 떠나고 싶지 않다고 해요.", "family_relationships", "waking_an_upset_brother_before_departure", "conversation", "request", "mixed", "high", "long_source|source_ambiguity"),
    814: r("Salima is told that her brother's house is also her house. She may go upstairs to wake him or go wake him in the salon.", "살리마에게 오빠의 집은 곧 당신의 집이라고 말해요. 위로 올라가 그를 깨우거나 거실에서 깨우라고 해요.", "family_relationships", "permission_to_wake_brother_at_home", "conversation", "suggestion", "mixed", "medium", "source_ambiguity"),
    815: r("The speaker will call a driver to return him to Oran and asks Salima to stay until next week; she seems to complain that the speaker is shouting at her.", "화자는 운전기사에게 그를 오랑으로 데려다 달라고 하고 살리마에게 다음 주까지 머물러 달라고 해요. 살리마는 화자가 자신에게 소리친다고 불평하는 듯해요.", "family_relationships", "arranging_return_to_oran", "conversation", "request", "mixed", "high", "source_ambiguity"),
    816: r("Goodbyes are exchanged with a guest. The visitor is thanked and welcomed to stay well, while the speaker asks whether the other person can see a friend and apologizes.", "손님과 작별 인사를 나눠요. 잘 지내라고 인사하고, 친구가 보이는지 묻고 미안하다고 해요.", "daily_life", "goodbye_to_a_guest", "conversation", "greeting", "mixed", "medium", "code_switching|source_ambiguity"),
    817: r("The speaker says to leave the friend and apologizes.", "화자는 친구를 두고 가자고 하며 미안하다고 해요.", "daily_life", "leaving_a_friend", "other", "request", "neutral", "low", "code_switching", "flagged", "A1", 18),
    818: r("A morning greeting confirms that the teacher is there and that the visitor has an appointment. They are invited to sit and negotiate for a while.", "아침 인사 뒤 선생님이 여기 있는지 확인하고 방문객에게 약속이 있는지 물어요. 앉아서 잠시 협의하자고 해요.", "administration", "appointment_with_an_official", "conversation", "information", "mixed", "medium", "source_ambiguity"),
    819: r("The visitor says the official was once the speaker's student. An appointment and a purpose are mentioned, but the phrase about a subject is partly unclear; the speaker asks whether everything is well.", "방문객은 그 관리자가 예전에 자신의 학생이었다고 말해요. 약속과 용건이 언급되지만 주제에 관한 표현은 일부 불분명하고, 상대는 괜찮은 일인지 물어요.", "administration", "former_student_and_official_appointment", "conversation", "question", "mixed", "high", "code_switching|source_ambiguity"),
    820: r("The speaker says that before his death the deceased sold his properties. The official says he has no information and asks what happened.", "화자는 고인이 죽기 전에 자신의 재산을 팔았다고 말해요. 관리자는 그 일에 대해 아는 것이 없다고 하며 무슨 일이냐고 물어요.", "administration", "deceased_persons_property_sale", "conversation", "information", "mixed", "high", "code_switching|source_ambiguity"),
    821: r("The speaker explains that all of the deceased's properties were sold legally and that everything is registered to Karim and his brother Nasser.", "화자는 고인의 재산을 모두 합법적으로 팔았고 모든 것이 카림과 그의 형제 나세르 명의로 등록되어 있다고 설명해요.", "administration", "legal_registration_of_inherited_property", "conversation", "information", "mixed", "high", "source_ambiguity"),
    822: r("The official asks about the deceased's son and says he summoned the listener to explain the matter first, before the family tells her and shocks her. She is told to prepare herself.", "관리자는 고인의 아들을 묻고, 가족이 먼저 말해 그녀를 놀라게 하기 전에 자신이 먼저 설명하려고 불렀다고 해요. 마음의 준비를 하라고 말해요.", "administration", "summons_about_property_and_family_news", "conversation", "warning", "mixed", "high", "code_switching|long_source|source_ambiguity"),
    823: r("A short question asks what will happen to the villa where they live.", "현재 살고 있는 별장은 어떻게 되는지 묻는 짧은 질문이에요.", "administration", "question_about_current_villa", "other", "question", "neutral", "low", "", "draft", "A1", 18),
    824: r("The official says the villa was also sold and asks where the woman and her son will go.", "관리자는 별장도 팔렸다고 말하고, 여성이 아들과 함께 어디로 갈지 묻는 듯해요.", "administration", "sale_of_current_villa_and_displacement", "conversation", "question", "mixed", "high", "source_ambiguity"),
    825: r("The speaker says that if she is professionally registered or established, he will add a clause to the villa contract protecting her while she is alive so the heirs cannot take it.", "화자는 그녀가 직업적으로 자립해 있다면 별장 계약서에 그녀가 살아 있는 동안 보호받는 조항을 넣어 상속인들이 가져가지 못하게 하겠다고 해요.", "administration", "contractual_life_interest_in_villa", "conversation", "suggestion", "mixed", "high", "code_switching|source_ambiguity"),
    826: r("The speaker apologizes for the difficult news and says they did not know how to bring it up, while wishing the woman a long life.", "화자는 어려운 소식을 어떻게 전해야 할지 몰랐다며 미안해하고, 그녀가 오래 살기를 바래요.", "administration", "delivering_difficult_property_news", "conversation", "apology", "mixed", "medium", "source_ambiguity"),
    827: r("After her death, the villa would automatically return to Nasser's children, who are the two people waiting for it. The speaker laments that the house will be taken and that they will pressure her when she dies.", "그녀가 죽은 뒤에는 별장이 자동으로 나세르의 자녀들에게 돌아가고, 그 둘이 이곳에서 기다리고 있다고 해요. 집을 빼앗기고 죽을 때까지 압박받게 될까 한탄해요.", "administration", "life_interest_and_heirs_after_death", "conversation", "warning", "mixed", "high", "long_source|source_ambiguity"),
    828: r("The speaker apologizes for what happened and asks what fault the poor woman had.", "화자는 일어난 일에 미안해하며 그 불쌍한 여성이 무슨 잘못을 했느냐고 물어요.", "administration", "sympathy_after_property_loss", "conversation", "apology", "mixed", "medium", "code_switching|source_ambiguity"),
    829: r("The speaker explains that the deceased had sponsored or guaranteed Mr. Elias, but a guarantee does not give the beneficiary inheritance rights, even if he is a full sibling.", "화자는 고인이 엘리아스 씨를 보증하거나 후견했지만, 보증은 수혜자에게 상속권을 주지 않으며 친형제라 해도 마찬가지라고 설명해요.", "administration", "guarantee_without_inheritance_rights", "conversation", "information", "mixed", "high", "code_switching|long_source|source_ambiguity"),
    830: r("The official tells the listener to take a five-minute walk and return, apologizing that the day has been long and asking her not to shout.", "관리자는 5분간 산책하고 돌아오라고 해요. 오늘 오래 붙잡아 미안하다며 소리치지 말라고 해요.", "administration", "pause_during_difficult_legal_meeting", "conversation", "request", "mixed", "medium", "code_switching|source_ambiguity"),
    831: r("A threatening stranger asks who brought the listener there and tells him not to try to understand. He displays his hands and says he is poor but does not approach poor people; the situation is intimidating and unclear.", "위협적인 낯선 사람이 누가 그를 이곳에 데려왔는지 묻고 이해하려 하지 말라고 해요. 손을 보이며 자신은 가난하지만 가난한 사람들에게 다가가지 않는다고 말해 상황을 위협적으로 만들어요.", "daily_life", "threatening_unknown_encounter", "conversation", "question", "offensive", "high", "long_source|source_ambiguity", "flagged", "C1", 80),
    832: r("The stranger warns the listener not to make him do something he does not want to do. He says he will solve the matter but threatens consequences if the listener calls out or makes noise, then asks for the phone and villa keys.", "낯선 사람은 자신이 원하지 않는 일을 하게 만들지 말라고 경고해요. 문제를 해결해 주겠지만 소리를 지르거나 소란을 피우면 결과가 있을 것이라고 위협하고, 전화기와 별장 열쇠를 요구해요.", "daily_life", "threat_to_take_phone_and_keys", "conversation", "warning", "offensive", "high", "long_source|source_ambiguity", "flagged", "C1", 82),
}


def build():
    engine.BATCH_ID = BATCH_ID
    engine.BASE_COMMIT = BASE_COMMIT
    engine.PROMPT_VERSION = PROMPT_VERSION
    engine.TARGET_START = TARGET_START
    engine.TARGET_END = TARGET_END
    engine.BATCH_OUT = BATCH_OUT
    engine.MANIFEST_OUT = MANIFEST_OUT
    engine.QA_OUT = QA_OUT
    engine.RAW = RAW
    return engine.build()


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    print(json.dumps(build(), ensure_ascii=False, indent=2))
