"""Build source-only MADOran enrichment Batch 06 for Sentno 321..384."""
from __future__ import annotations
import csv, json, statistics, sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
if __package__ in {None, ""}: sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from scripts.apply_madoran_enrichment_batch import CEFR_LEVELS, CONTROLLED_VALUES
from scripts.build_madoran_enrichment_scaffold import EMPTY_FIELDS, PROCESSING_FLAG_VALUES, ROOT, SOURCE_OUT, read_tsv, source_gate
from scripts.validate_madoran_enrichment import check_layer_contract
BATCH_ID="MADORAN-ENRICH-006"; BASE_COMMIT="02c8b91"; PROMPT_VERSION="madoran-source-enrichment-v6"; TARGET_START=321; TARGET_END=384
BATCH_DIR=ROOT/"data/master/enrichment/batches"; BATCH_OUT=BATCH_DIR/"batch06_sentno_0321_0384.tsv"; MANIFEST_OUT=BATCH_DIR/"batch06_manifest.json"; QA_OUT=ROOT/"data/master/qa/madoran_enrichment_batch06_generation_qa.json"
BATCH_FIELDS=["source_uid","sentno",*EMPTY_FIELDS,"processing_flags","enrichment_state"]
def item(english,korean,cefr,score,domain,topic,genre,speech,register,context,flags="",state="draft"):
    return {"english":english,"korean":korean,"cefr_level":cefr,"difficulty_score":str(score),"domain":domain,"topic":topic,"genre":genre,"speech_act":speech,"register":register,"context_dependency":context,"processing_flags":flags,"enrichment_state":state}
def latinize(text):
    table=str.maketrans({"ا":"a","أ":"a","إ":"i","آ":"a","ء":"'","ب":"b","ت":"t","ث":"th","ج":"j","ح":"7","خ":"kh","د":"d","ذ":"dh","ر":"r","ز":"z","س":"s","ش":"sh","ص":"s","ض":"d","ط":"t","ظ":"z","ع":"3","غ":"gh","ف":"f","ق":"9","ك":"k","ل":"l","م":"m","ن":"n","ه":"h","و":"w","ي":"i","ى":"a","ة":"a","ئ":"i","ؤ":"w","،":",","؟":"?"})
    return " ".join("".join(ch if ord(ch)<128 else " " for ch in text.translate(table)).split())
RAW={
321:item("After two years of work, I have brought the money. So, will you let me marry your daughter? Yes, we agree. Go and marry her.","2년 동안 일한 끝에 돈을 마련했어요. 그럼 따님과 결혼하게 해 주시겠어요? 그래, 우리는 동의한다. 가서 그녀와 결혼해.","B1",48,"family_relationships","marriage_agreement","conversation","agreement","colloquial","medium"),
322:item("We arranged it for her on the first day after my marriage, and at last you became my wife. It is the most beautiful day of my life. Me too, my husband. Now go and make breakfast. Yes, but I will take a shower and come make it, okay?","결혼 다음 날 첫날부터 우리를 위해 준비해 주었고, 드디어 당신은 내 아내가 되었어. 내 인생에서 가장 아름다운 날이야. 나도 그래, 여보. 이제 가서 아침을 만들어. 그래, 하지만 샤워하고 와서 만들게, 알겠지?","B2",62,"family_relationships","newlywed_domestic_exchange","conversation","narration","colloquial","high","context_heavy|source_ambiguity","flagged"),
323:item("When he came out, she said, Who are you and where did you come from? Who brought you?","그가 나오자 그녀가 말했다. 너 누구고 어디서 왔어? 누가 널 데려왔어?","A2",36,"family_relationships","unexpected_encounter","conversation","question","colloquial","low"),
324:item("She told him, I am just your wife. You did not recognize me just because I took off my makeup. He said, Those damned people did this to me; they charged me 250 million. May God not reward them. Get out of my sight.","그녀가 그에게 말했어. 난 그냥 네 아내야. 내가 화장을 지웠다고 못 알아본 거야? 그가 말했어. 그 망할 사람들이 내게 이런 짓을 했어. 그들은 나에게 2억 5천만을 청구했지. 하느님이 그들에게 벌을 주시길. 내 눈앞에서 나가.","B2",70,"family_relationships","makeup_disguise_and_anger","conversation","complaint","mixed","high","idiom_culture|source_ambiguity","flagged"),
325:item("The difference between a European woman and an Algerian woman: when a European woman goes to give birth, they take her to the hospital; you find a man holding her hand while she says, I have heartburn. The doctor says, Good, good.","유럽 여성과 알제리 여성의 차이야. 유럽 여성이 출산하러 가면 병원으로 데려가고, 남자가 그녀의 손을 잡고 있어. 그녀는 속쓰림이 있다고 말하고 의사는 좋아요, 좋아요라고 하지.","C1",76,"health","cultural_comparison_childbirth","narrative","description","mixed","high","code_switching|context_heavy|source_ambiguity","flagged"),
326:item("And he tells her, Breathe, push well, baby, you are doing very well, while she keeps saying, Oh my God. Look, I am already soaked with sweat from the pain of labor.","그는 그녀에게 숨 쉬고, 잘 힘줘요, 아가씨, 아주 잘하고 있다고 말해. 그녀는 계속 오 마이 갓이라고 해. 봐, 진통 때문에 나는 벌써 땀에 흠뻑 젖었어.","B2",66,"health","childbirth_pain_comparison","narrative","description","mixed","high","source_ambiguity","flagged"),
327:item("And he tells her, No, my baby, you are doing well. I am with you, with you forever.","그는 그녀에게 말해. 아니야, 자기야, 잘하고 있어. 내가 너와 함께 있어, 영원히 함께할게.","B1",43,"family_relationships","reassurance_during_childbirth","conversation","suggestion","colloquial","low"),
328:item("Now an Algerian woman is normal at first, until she falls down and screams, one scream after another. The poor man runs, carries her in an improvised vehicle to the hospital; when she arrives, they get her down on her legs and walk her about 400 meters to reach the emergency room, while she cries out to the Lord who created her.","알제리 여성은 처음에는 멀쩡하다가 쓰러져서 계속 비명을 질러. 불쌍한 남자가 달려가 그녀를 임시 차량에 태워 병원으로 데려가. 도착하면 그녀를 내려 세우고 응급실까지 약 400미터를 걷게 해. 그녀는 자신을 창조한 주님께 계속 울부짖어.","C1",82,"health","childbirth_emergency_comparison","narrative","narration","mixed","high","context_heavy|long_source|source_ambiguity","flagged"),
329:item("And her husband tells her, Be quiet, Fatima, you have humiliated us. She keeps screaming in pain, and Abdellah follows and hears curses: May God not reward you, Abdellah. You are the reason for this, Abdellah. If I had known, I would not have done it. Abdellah, may God strike you.","그녀의 남편은 말해. 조용히 해, 파티마, 우리 망신 다 시켰어. 그녀는 계속 아파서 비명을 지르고, 압델라는 따라가며 욕설을 들어. 압델라야, 하느님이 너에게 상을 주지 않기를. 네가 이 일의 원인이야. 알았더라면 하지 않았을 거야. 압델라야, 하느님이 너를 치시길.","B2",78,"health","childbirth_family_complaint","narrative","complaint","mixed","high","idiom_culture|long_source|source_ambiguity","flagged"),
330:item("When they take her in to remove the baby, they find her only halfway through labor; she still has two months before giving birth. I am astonished.","아기를 꺼내려고 그녀를 데려갔는데, 아직 진통의 중간도 안 됐고 출산까지 두 달이나 남은 상태였대. 정말 놀라워.","B2",61,"health","pregnancy_misjudgment","narrative","exclamation","colloquial","medium","source_ambiguity","flagged"),
331:item("Tell us about something that happened to you at the beach. I have a friend who is an artist; wonderful things come from his hands. He used to go to the beach with us without taking a single cent, draw for two million, and enjoy himself for a day.","해변에서 겪은 일을 하나 말해 줘. 내 친구 중에 화가가 있는데 손에서 멋진 작품이 나와. 그는 돈 한 푼 없이 우리와 해변에 가서 200만 상당의 그림을 그리고 하루를 즐기곤 했어.","B2",59,"culture_tradition","beach_artist_anecdote","interview","narration","colloquial","medium","source_ambiguity","flagged"),
332:item("He used to take a marker with him and rely on God. When he saw a tattoo with Chinese writing, although he did not know Chinese letters, he went and found a tea tin with writing in Chinese.","그는 마커를 가지고 다니며 하느님께 의지했어. 중국어 글자를 몰랐는데 중국어 문신을 보자 중국어 글씨가 적힌 차 통을 찾아냈지.","B2",64,"culture_tradition","artist_chinese_tattoo_story","narrative","narration","colloquial","high","code_switching|source_ambiguity","flagged"),
333:item("Anyway, the whole beach was walking around with tattoos that said Chinese green tea. The first time I saw one, I wondered what it looked like.","아무튼 해변 사람들이 모두 중국 녹차라고 적힌 문신을 하고 돌아다녔어. 처음 봤을 때는 그게 어떻게 생겼는지 신기했지.","B1",48,"culture_tradition","tattoo_joke","narrative","exclamation","colloquial","medium","source_ambiguity","flagged"),
334:item("Look, there are three categories of young people in Algeria. The first, and the most common nowadays, is the one who stays asleep at home and does not get up until two or three, then goes out for breakfast.","알제리 젊은이에는 세 부류가 있어. 요즘 가장 흔한 첫째 부류는 집에서 계속 자다가 두 시나 세 시가 되어야 일어나 아침을 먹으러 나가는 사람이야.","B1",49,"daily_life","algerian_youth_lifestyles","expository","description","colloquial","medium"),
335:item("After that, the internet connection at home takes over. When coffee time comes, he calls his friends to meet at a café, hangs out with them, and smokes until I tell you, he is completely worn out.","그다음에는 집 인터넷에 매달려. 커피 마실 시간이 되면 친구들에게 전화해 카페에서 만나고, 친구들과 어울리며 담배를 피우다가 완전히 녹초가 될 때까지 계속해.","B2",63,"daily_life","youth_social_routine","expository","description","colloquial","high","source_ambiguity","flagged"),
336:item("Then he goes in for dinner, goes back out to buy drugs, spends the night outside drinking and fighting with people, comes home at four in the morning, and sleeps. That is his life.","그다음 들어가 저녁을 먹고 다시 나가 마약을 사. 밖에서 술을 마시고 사람들과 싸우며 밤을 보내다가 새벽 네 시에 들어와 잠들지. 그게 그의 삶이야.","B2",66,"crime_safety","youth_risky_nightlife","expository","description","colloquial","medium","source_ambiguity","flagged"),
337:item("The second category is the one who gets up early to study, or gets dressed and puts on makeup; in short, you find them spending all their time at university, even eating breakfast outside sometimes, at a fast-food place when they have money or at the university restaurant.","둘째 부류는 일찍 일어나 공부하거나 화장하고 준비하는 사람이야. 한마디로 대학에서 시간을 거의 다 보내고, 돈이 있으면 패스트푸드점에서, 아니면 대학 식당에서 밖에서 아침을 먹기도 하지.","B2",64,"education","student_lifestyle","expository","description","colloquial","medium","long_source","flagged"),
338:item("When he goes home, he enters hungry and craving the home-cooked food, eats breakfast and has coffee right away without even taking a break, then goes out to relax with his friends and walk around having coffee.","집에 가면 배고픈 채로 들어와 집밥을 몹시 그리워하고, 쉬지도 않고 바로 아침을 먹고 커피를 마셔. 그다음 친구들과 밖에서 쉬고 돌아다니며 커피를 마셔.","B1",53,"daily_life","student_home_routine","expository","description","colloquial","medium"),
339:item("You find them talking about their studies and professors, or about girls who study with them, posting them on Instagram or Snapchat stories, then eating dinner and staying glued to Facebook until two before sleeping and getting up early. A very hectic life.","그들은 공부와 교수님 이야기, 함께 공부하는 여자들 이야기를 하고 인스타그램이나 스냅챗 스토리에 올려. 저녁을 먹고 페이스북에 새벽 두 시까지 붙어 있다가 자고 일찍 일어나지. 정말 바쁜 삶이야.","B2",69,"social_media","student_social_media_routine","expository","description","colloquial","high","code_switching|long_source","flagged"),
340:item("Category three: people with money. They get up early, find coffee ready and the car ready, everything prepared; they do nothing themselves.","셋째 부류는 돈이 있는 사람들이야. 일찍 일어나면 커피도 준비되어 있고 차도 준비되어 있어. 모든 것이 갖춰져 있어서 본인은 아무것도 하지 않아.","B1",44,"daily_life","wealthy_youth_lifestyle","expository","description","colloquial","low"),
341:item("But you do not find him comfortable, poor thing. He keeps drinking and getting drunk, driving his father's car all day, losing it and searching for it while miserable. Something fills his heart; they call it an evil prayer, God forbid.","하지만 불쌍하게도 그는 편안하지 않아. 계속 술을 마시고 취하고, 아버지 차를 하루 종일 몰다가 잃어버려서 우울한 채 찾아다녀. 마음을 가득 채운 무언가가 있는데, 사람들은 그것을 나쁜 저주라고 해. 하느님, 막아 주소서.","B2",73,"daily_life","wealth_and_unhappiness","expository","description","mixed","high","idiom_culture|source_ambiguity","flagged"),
342:item("Which category are you in? See yourself in it. I am not in any of them. There is nothing like someone who takes responsibility, is a man who works with his own arms, manages things, and relies on himself; not someone who only chases girls and has no goal in life. May God preserve my parents for me.","너는 어느 부류야? 네 모습을 그 안에서 찾아봐. 나는 어느 부류에도 속하지 않아. 책임을 지고 자기 힘으로 일하며 일을 해결하고 스스로 의지하는 사람이 최고야. 여자만 쫓고 인생의 목표가 없는 사람이 아니지. 하느님이 우리 부모님을 지켜 주시길.","B2",75,"daily_life","youth_responsibility_opinion","expository","opinion","mixed","high","idiom_culture|long_source","flagged"),
343:item("I am a twenty-five-year-old woman. I was born six and a half months early, excuse me. My mother did not leave me in the hospital because she feared they would not care for me, so she took me home, and she and my grandmother raised me. May God have mercy on her.","나는 스물다섯 살 여자야. 나는 임신 6개월 반 만에 일찍 태어났어. 실례해. 엄마는 병원에서 나를 잘 돌보지 않을까 봐 나를 두지 않고 집으로 데려왔고, 엄마와 할머니가 나를 키웠어. 돌아가신 할머니에게 하느님의 자비가 있기를.","B2",67,"health","premature_birth_autobiography","narrative","narration","mixed","high","idiom_culture|source_ambiguity","flagged"),
344:item("At sixty-six checkups they were afraid I would not survive, so they called me Miracle Baby. But thank God I lived. Just so they could name me, a fight started: my mother wanted the name Shahrazad, but my grandfather said, How can this be Shahrazad? That is not a name at all.","검사를 예순여섯 번이나 하며 가족은 내가 살지 못할까 봐 걱정했고 나를 기적의 아기라고 불렀어. 하지만 다행히 살아났지. 이름을 정하는 일로 싸움이 시작됐어. 엄마는 샤흐라자드라는 이름을 원했지만 할아버지는 어떻게 그게 샤흐라자드냐며, 그건 이름도 아니라고 했어.","B2",74,"health","miracle_baby_name_story","narrative","narration","mixed","high","long_source|source_ambiguity","flagged"),
345:item("And my father, may God have mercy on him, just watched. When he saw things getting confused, he said, Let us call her Amira. Thank God they accepted it, and everyone liked it.","돌아가신 아버지는 그저 지켜보고 있었어. 일이 복잡해지는 것을 보더니 아미라라고 부르자고 했지. 다행히 모두 받아들였고 다들 그 이름을 좋아했어.","B1",45,"family_relationships","choosing_a_child_name","narrative","agreement","colloquial","medium","idiom_culture"),
346:item("My father went to the town hall. When they asked why the person writing it had put Amina instead of Amira, he told them, Amina is my name. The form came out wrong; well, it is written, they say, and we are named in heaven with God.","아버지가 시청에 갔어. 담당자가 왜 아미라 대신 아미나라고 적었냐고 묻자, 아버지는 아미나는 내 이름이라고 했어. 서류가 잘못 나온 거지. 뭐, 이미 적힌 것은 어쩔 수 없고, 사람은 하느님 앞에서 하늘에 이름이 정해져 있다고들 하잖아.","B2",72,"administration","birth_registration_name_error","narrative","narration","mixed","high","idiom_culture|source_ambiguity","flagged"),
347:item("Thank God I grew up and studied. I got 13.5 in sixth grade, almost 16 in the middle-school certificate, and 12 in the baccalaureate. At university I spent five years and got a master's degree in chemistry with 17. As I told you, I am now almost sixty.","다행히 나는 자라서 공부했어. 초등학교 졸업 시험에서 13.5점, 중학교 졸업 시험에서 거의 16점, 고등학교 졸업 시험에서 12점을 받았어. 대학에서는 5년을 보내고 화학 석사 학위를 17점으로 받았지. 말했듯이 지금은 거의 예순 살이야.","B2",68,"education","education_autobiography","narrative","narration","colloquial","medium","code_switching|source_ambiguity","flagged"),
348:item("And twenty years old? I need a job and a good man. Well, my brothers and sisters, that is my story.","스물몇 살이냐고? 나는 일자리와 좋은 남자가 필요해. 자, 형제자매 여러분, 이것이 내 이야기야.","B1",42,"family_relationships","life_goals_and_closing","speech","narration","colloquial","medium","source_ambiguity","flagged"),
349:item("Try going one day to where they sell sardines. You only have to stop beside the seller to notice how the smell kills you. But really, after a while you get used to it, and when you grow up you will not feel it at all.","언젠가 정어리를 파는 곳에 가 봐. 판매자 옆에 잠깐 서 있기만 해도 냄새가 아주 지독해. 하지만 정말로 시간이 지나면 익숙해지고, 더 자라면 아예 느끼지 못할 거야.","B1",54,"shopping","sardine_smell_habituation","speech","suggestion","colloquial","medium"),
350:item("If you go to the sellers and tell one, Watch out, what is this smell? He will say, What smell? What are you talking about? I doubt he will understand you at all.","판매자에게 가서 이 냄새가 뭐냐고 말하면 그는 무슨 냄새냐고 할 거야. 무슨 말을 하는 거냐고. 아마 네 말을 전혀 이해하지 못할걸.","B1",52,"shopping","sardine_vendor_humor","speech","joke","colloquial","high","source_ambiguity","flagged"),
351:item("The only way to make him understand, smell, and feel what he is living in is to take him away from that place and bring him to a flower shop. When he returns to the sardine stall, he will say, What is this smell I was living in? How was I living here?","그가 자신이 처한 환경을 이해하고 냄새 맡고 느끼게 하는 유일한 방법은 그곳에서 데려와 꽃을 파는 곳에 데려가는 거야. 정어리 가게로 돌아오면 그는 이게 무슨 냄새지, 내가 여기서 어떻게 살았지라고 할 거야.","B2",68,"shopping","sardine_flower_shop_analogy","speech","explanation","colloquial","high","source_ambiguity","flagged"),
352:item("It is the same when you live your whole life in something forbidden, and your friends are not the kind who wake you up—in other words, not good and righteous friends. You will not feel that there is a problem.","평생 금지된 일 속에서 살고, 친구들도 너를 일깨워 주는 좋은 사람이 아니라면 똑같아. 그런 환경에서는 문제가 있다는 것을 느끼지 못할 거야.","B2",64,"religion","bad_company_and_habituation","speech","warning","mixed","high","idiom_culture|source_ambiguity","flagged"),
353:item("You will not know the bitterness of disobedience and bad company. Only when you taste the sweetness of obedience and good company will you say, How was I living like that?","불순종과 나쁜 친구의 쓰라림을 알지 못할 거야. 순종과 좋은 친구의 달콤함을 맛보고 나서야 내가 어떻게 그렇게 살았을까라고 말하게 될 거야.","B2",60,"religion","obedience_and_good_company","speech","warning","mixed","medium","idiom_culture"),
354:item("Once my grandfather, may God have mercy on him, gave me ten dinars when I was little. My mother told me to give them to her so she could hide them, but I refused and put the thousand-franc note in my mouth. It went down my throat; my face turned blue. I went to my mother, afraid she would hit me.","한번은 돌아가신 할아버지가 어릴 때 나에게 10디나르를 주셨어. 엄마는 숨겨 두겠다며 달라고 했지만 나는 싫다고 하고 천 프랑짜리 지폐를 입에 넣었어. 그게 목으로 넘어가 얼굴이 파래졌지. 엄마가 때릴까 봐 무서워하며 엄마에게 갔어.","B2",71,"health","childhood_choking_anecdote","narrative","narration","colloquial","high","idiom_culture|source_ambiguity","flagged"),
355:item("Then I went to my father. My mother heard me vomiting and realized I had swallowed it. She put her hand in my throat and pulled it out. Thank God I survived by a hair. That is why a mother must always keep watch over children, because they do not know how many people have died like that, poor things.","그다음 아버지에게 갔어. 엄마는 내가 토하는 소리를 듣고 삼킨 것을 알아챘지. 엄마가 내 목에 손을 넣어 꺼냈어. 정말 간신히 살아났어. 그래서 엄마는 늘 아이들을 지켜봐야 해. 아이들은 그런 일로 얼마나 많은 사람이 죽었는지 모르니까, 불쌍하지.","B2",75,"health","childhood_accident_warning","narrative","warning","mixed","high","idiom_culture|long_source|source_ambiguity","flagged"),
356:item("Someone who is always watchful protects them from anything.","늘 주의 깊게 지켜보는 사람은 아이들을 어떤 일이든 막아 줘.","A2",31,"health","parental_supervision_proverb","proverb","warning","neutral","low","source_ambiguity","flagged"),
357:item("Once my mother was going to the doctor. We lived in the gendarmerie barracks; I was little, about seven years old.","한번은 엄마가 병원에 가고 있었어. 우리는 헌병대 숙소에 살았고, 나는 일곱 살쯤 된 어린아이였지.","B1",46,"health","childhood_gendarmerie_housing","narrative","narration","colloquial","medium"),
358:item("I was with my sister. She gave me the house key and told me to rest at home, but I left it and went out, and we went outside to play until I dropped the key.","나는 언니와 함께 있었어. 언니가 집 열쇠를 주며 집에서 쉬라고 했지만 나는 열쇠를 두고 나와서 밖으로 나가 놀다가 열쇠를 떨어뜨렸어.","B1",46,"housing","lost_house_key_childhood","narrative","narration","colloquial","medium"),
359:item("Evening came, my mother arrived, and I was dead with fear. She asked, Where is the key? I told her I had dropped it and did not know where.","저녁이 되었고 엄마가 왔어. 나는 무서워 죽을 것 같았지. 엄마가 열쇠가 어디 있냐고 물어서 떨어뜨렸는데 어디인지 모르겠다고 했어.","A2",38,"housing","lost_key_fear","narrative","narration","colloquial","low"),
360:item("She started shouting outside, put me in her hand, and humiliated me outside. She said, How can I tell you to watch your daughter while I take care of my errands and come back, and you go out? I told you to go out—go on, speak, do not cry with those eyes. Now you are helpless. And from then on...","엄마는 밖에서 소리치기 시작하고 나를 손에 잡아 야단쳤어. 내가 볼일을 보고 돌아올 동안 딸을 잘 보라고 했는데 어떻게 네가 나가 버리냐고 했지. 나가라고 했으니 나가라고 했잖아. 자, 말해 봐. 그 눈으로 울지 마. 이제 너는 아무것도 못 하잖아. 그 뒤로는…","B2",73,"family_relationships","maternal_scolding_lost_key","narrative","complaint","colloquial","high","context_heavy|long_source|source_ambiguity","flagged"),
361:item("Then imagine what happened. She told me to look for it, and I went searching. She brought a small piece of metal and kept working like a burglar opening doors until the door opened; I was happy when I went inside.","그다음 무슨 일이 있었는지 상상해 봐. 엄마가 열쇠를 찾으라고 해서 나는 찾아다녔어. 엄마는 작은 쇠 조각을 가져와 도둑처럼 문을 여는 일을 계속했고, 마침내 문이 열려서 내가 들어갈 때 기뻤지.","B2",68,"housing","improvised_door_entry","narrative","narration","colloquial","high","source_ambiguity","flagged"),
362:item("She told me to stay outside until I found the key so I could get in. I sat crying in front of the door. My father was a permanent soldier; when he came back from work at ten at night, he found me asleep under the stairs. Upstairs, my mother told him what had happened and he started laughing. I felt like I was not human. The next morning the barracks guard found the key, and it ended well.","엄마는 열쇠를 찾을 때까지 밖에 있으라고 했어. 나는 문 앞에 앉아 울었지. 아버지는 직업 군인이었고 밤 열 시에 퇴근해 와서 계단 아래에서 잠든 나를 발견했어. 집에 올라가 엄마가 일을 설명하자 아버지는 웃기 시작했지. 나는 내가 사람이 아닌 것 같았어. 다음 날 아침 숙소 경비원이 열쇠를 찾아 주었고 다행히 끝났어.","B2",78,"housing","lost_key_resolution","narrative","narration","mixed","high","idiom_culture|long_source|source_ambiguity","flagged"),
363:item("Peace be upon you, sisters. Welcome with me to a new recipe. Today, God willing, I brought you a dish loved by all of us Algerians, from east to west and north to south.","안녕하세요, 여러분. 새로운 요리법에 오신 것을 환영해요. 오늘은 하느님의 뜻이라면 동서남북 모든 알제리 사람이 좋아하는 요리를 가져왔어요.","A2",34,"food","recipe_introduction_algerian_dish","recipe","greeting","colloquial","low","idiom_culture"),
364:item("I brought you harira in the Oran style, with lamb meat, and it is very delicious, like a wedding dish. You can say it is the kind served at weddings; you can eat it without getting full. Sisters, I will leave you with the recipe and how we prepare it. In God's name.","오랑식 하리라를 가져왔어요. 양고기가 들어가 아주 맛있고 결혼식 음식 같아요. 결혼식에서 나오는 음식이라고 해도 되겠어요. 먹어도 배부르지 않을 만큼 맛있답니다. 여러분, 이제 요리법과 만드는 방법을 알려 드릴게요. 하느님의 이름으로 시작할게요.","B1",51,"food","oran_harira_recipe_intro","recipe","information","colloquial","medium","idiom_culture|source_ambiguity","flagged"),
365:item("We begin in God's name. For our harira, first add three tablespoons of oil. I have a piece of meat; today I chose lamb, but you can use chicken, each according to what suits you.","하느님의 이름으로 시작할게요. 하리라에는 먼저 식용유 세 큰술을 넣어요. 고기 한 조각이 있는데 오늘은 양고기를 골랐어요. 하지만 취향에 따라 닭고기를 사용해도 돼요.","A2",39,"food","harira_oil_and_meat","recipe","instruction","colloquial","low","idiom_culture"),
366:item("Add two medium onions or one large onion. I chopped it roughly because it will be blended later, and I also added garlic.","중간 크기 양파 두 개나 큰 양파 한 개를 넣어요. 나중에 갈 것이어서 대충 썰었고 마늘도 넣었어요.","A2",32,"food","harira_onion_garlic","recipe","instruction","neutral","low"),
367:item("For the garlic, I used a large head. I added two carrots, peeled and cut into small pieces, tomatoes, and celery. It is in season and very good to cook with because it has great benefits.","마늘은 큰 통 하나를 썼어요. 당근 두 개를 껍질을 벗겨 작게 썰고, 토마토와 셀러리도 넣었어요. 제철이라 요리하기 좋고 효능도 아주 많아요.","B1",44,"food","harira_vegetables","recipe","instruction","colloquial","medium","source_ambiguity","flagged"),
368:item("Here I chose the lower part and took some of its stems. I have a small potato; if it has a green cap, use it, and I have a turnip. Some people say not to add turnip, but I tell you, sister, one piece will not affect the strong taste, and do not count it as having added turnip; its benefit matters.","여기서는 아랫부분을 골라 줄기도 조금 사용했어요. 작은 감자 하나가 있는데 초록색 꼭지가 있으면 넣고, 순무도 하나 있어요. 순무를 넣지 말자는 사람도 있지만 한 조각은 강한 맛에 영향을 주지 않아요. 순무를 넣었다고 생각하지 말고 효능을 생각하세요.","B2",72,"food","harira_root_vegetables","recipe","instruction","colloquial","high","context_heavy|source_ambiguity","flagged"),
369:item("Our vegetables are beautiful, sisters. Do not forget to add some salt and another tablespoon of tomato paste. Put everything over the heat to fry and soften.","채소가 아주 예쁘게 준비됐어요. 소금을 조금 넣는 것을 잊지 말고 토마토 페이스트 한 큰술도 더해요. 모든 것을 불에 올려 볶아 부드럽게 해요.","A2",36,"food","harira_salt_tomato_paste","recipe","instruction","colloquial","low"),
370:item("Now my harira is frying. First we season it: half a spoon of hot pepper, half a spoon of paprika, a coffee spoon of ginger, and half a spoon of turmeric.","이제 하리라 재료를 볶고 있어요. 먼저 양념해요. 매운 고추 반 큰술, 파프리카 반 큰술, 커피 스푼으로 생강 한 스푼, 강황 반 큰술을 넣어요.","A2",42,"food","harira_spices","recipe","instruction","neutral","low"),
371:item("Here the spices are what make the harira special. Do not tell me you are adding too much, because this is harira; it should come flavored and seasoned with them.","여기서 이 양념들이 하리라를 특별하게 만들어요. 너무 많이 넣는다고 하지 마세요. 하리라는 원래 이 양념으로 향과 맛이 나야 해요.","B1",46,"food","harira_spice_emphasis","recipe","explanation","colloquial","medium"),
372:item("Some people will say I added too many spices. The spices are the charm of harira: you eat it aromatic and tasty. Add two pinches of saffron, a little salt, then taste and add a quarter spoon if needed. Add caraway, half a spoon, because it is the medicine of harira.","어떤 사람은 하리라에 양념을 너무 많이 넣었다고 할 거예요. 양념이 하리라의 매력이에요. 향긋하고 맛있게 먹는 음식이죠. 사프란 두 꼬집과 소금을 조금 넣고 맛을 본 뒤 필요하면 4분의 1스푼을 더해요. 캐러웨이 반 스푼도 넣어요. 하리라의 약 같은 재료니까요.","B2",68,"food","harira_seasoning_adjustment","recipe","instruction","colloquial","high","idiom_culture|source_ambiguity","flagged"),
373:item("Now we mix all the spices gently so they do not burn. As you can see, it has started to boil and the water has begun to mix with the vegetables and everything else.","이제 양념이 타지 않도록 살살 모두 섞어요. 보시다시피 끓기 시작했고 물이 채소와 다른 재료에 섞이기 시작했어요.","A2",35,"food","harira_stirring","recipe","instruction","neutral","low"),
374:item("To keep it from burning, we keep stirring it. Add a bunch of coriander with the vegetables. When I buy a large bunch, I divide it in two: one part cooks first with the vegetables, and the other goes in at the end when I blend it so the flavor comes through.","타지 않게 계속 저어 줘요. 채소와 함께 고수 한 단을 넣어요. 큰 단을 사면 둘로 나눠서 하나는 채소와 처음부터 익히고, 다른 하나는 마지막에 갈 때 넣어 향이 살아나게 해요.","B1",56,"food","harira_coriander_timing","recipe","instruction","colloquial","high","source_ambiguity","flagged"),
375:item("That is how I do it, and I add a little celery leaves from the celery we used earlier.","나는 이렇게 하고, 아까 사용한 셀러리에서 잎을 조금 더 넣어요.","A2",30,"food","harira_celery_herbs","recipe","instruction","neutral","low"),
376:item("After that, we remove these so they release their flavor. Now, with hot water, I add liquid to my harira. Do not add too much, just enough so the spices do not burn and there is broth. Let it boil.","그다음 재료에서 향이 우러나도록 두고, 나중에 빼요. 이제 뜨거운 물을 넣어 하리라에 국물을 만들어요. 너무 많이 넣지 말고 양념이 타지 않으면서 국물이 생길 정도만 넣고 끓여요.","A2",42,"food","harira_hot_water","recipe","instruction","colloquial","medium"),
377:item("When you hear that sound showing it has boiled, add more water until the meat and vegetables are covered. Your eye is the measure; let it cook for about an hour and check it from time to time.","끓었다는 소리가 들리면 고기와 채소가 잠길 때까지 물을 더 넣어요. 양은 눈으로 보고 맞추면 되고, 한 시간 정도 익히면서 가끔 확인해요.","B1",52,"food","harira_simmering_time","recipe","instruction","colloquial","medium","source_ambiguity","flagged"),
378:item("When it has cooked for a while, check the meat. If it is cooked, move it aside, and check the vegetables. Turn off the heat so you can blend them; blending is also better in a hand mill.","한동안 익힌 뒤 고기를 확인해요. 익었으면 옆으로 빼고 채소를 확인해요. 채소를 갈 수 있도록 불을 끄고, 손으로 가는 도구를 쓰면 더 좋아요.","B1",54,"food","harira_blending_meat","recipe","instruction","colloquial","medium","source_ambiguity","flagged"),
379:item("When you blend it, if it comes out thick, add only a little hot water, and only if you see that it is thick.","갈았을 때 너무 걸쭉하면 뜨거운 물을 아주 조금만 넣어요. 정말 걸쭉할 때만 더하세요.","A2",32,"food","harira_consistency_adjustment","recipe","instruction","neutral","low"),
380:item("Then add the vermicelli; I use, God willing, one small coffee cup.","그다음 면을 넣어요. 나는 하느님의 뜻이라면 작은 커피잔 한 잔 정도를 사용해요.","A2",34,"food","harira_vermicelli_quantity","recipe","instruction","colloquial","medium","source_ambiguity","flagged"),
381:item("The amount depends on how much harira you have. If you want it thick, add more; if you want it light, add only a little.","양은 하리라의 양에 따라 달라요. 걸쭉하게 먹고 싶으면 많이 넣고, 묽게 먹고 싶으면 조금만 넣어요.","A2",30,"food","harira_vermicelli_adjustment","recipe","suggestion","neutral","low"),
382:item("As I told you, use just a small coffee cup and stir. Watch it, because as it cooks it swells. Put it back on the heat. We will prepare our seasoning paste to finish the harira: take a small bunch of coriander, add three peeled cloves of garlic, chop them together, and add a chicken stock cube if you like; it is optional.","말했듯이 작은 커피잔 하나만 넣고 저어요. 익으면서 불어나기 때문에 지켜봐야 해요. 다시 불에 올려요. 하리라를 마무리할 양념장을 만들게요. 작은 고수 한 단에 껍질을 벗긴 마늘 세 쪽을 넣고 함께 다져요. 원하면 닭고기 육수 큐브도 넣을 수 있지만 선택 사항이에요.","B2",73,"food","harira_seasoning_paste","recipe","instruction","colloquial","high","long_source|source_ambiguity","flagged"),
383:item("If you used lamb, you can add it too; it gives a very nice flavor. I do not add it, but some people like to.","양고기를 사용했다면 그것도 넣어도 돼요. 아주 좋은 맛을 내요. 나는 넣지 않지만 좋아하는 사람도 있어요.","A2",31,"food","harira_meat_preference","recipe","suggestion","neutral","low"),
384:item("Add a little caraway, a coffee spoon of harira spices sold ready-made by an herbalist or called harira ras el hanout, and finally a spoon of tomato paste and two glasses of water, according to how much broth you need.","캐러웨이를 조금 넣고, 약초상에서 하리라용으로 미리 섞어 파는 양념이나 하리라 라스 엘하누트라고 부르는 양념을 커피 스푼 하나 넣어요. 마지막으로 필요한 국물의 양에 따라 토마토 페이스트 한 스푼과 물 두 컵을 넣어요.","B1",55,"food","harira_final_seasoning","recipe","instruction","colloquial","high","idiom_culture|source_ambiguity","flagged"),
}
def validate(source):
    by={r["sentno"]:r for r in source}; expected=[str(i) for i in range(TARGET_START,TARGET_END+1)]
    if sorted(RAW)!=list(range(TARGET_START,TARGET_END+1)): raise RuntimeError("raw_coverage")
    rows=[]
    for sentno in expected:
        payload={**RAW[int(sentno)],"latin":latinize(by[sentno]["arabic_original"]),"source_uid":by[sentno]["source_uid"],"sentno":sentno}
        payload["speech_act"]={"instruction":"command","explanation":"description","joke":"description"}.get(payload["speech_act"],payload["speech_act"])
        for field in ("domain","genre","speech_act","register","context_dependency"):
            if payload[field] not in CONTROLLED_VALUES[field]: raise RuntimeError(f"controlled:{sentno}:{field}")
        if payload["cefr_level"] not in CEFR_LEVELS: raise RuntimeError(f"cefr:{sentno}")
        flags=payload["processing_flags"].split("|") if payload["processing_flags"] else []
        if flags!=sorted(flags) or any(f not in PROCESSING_FLAG_VALUES for f in flags) or (payload["enrichment_state"]=="flagged" and not flags): raise RuntimeError(f"flags:{sentno}")
        rows.append(payload)
    return rows
def build():
    if source_gate()["result"]!="PASS" or check_layer_contract()["result"]!="PASS": raise RuntimeError("gate_failed")
    source=read_tsv(SOURCE_OUT); rows=validate(source); generated_at=datetime.now(timezone.utc).replace(microsecond=0).strftime("%Y-%m-%dT%H:%M:%SZ")
    BATCH_OUT.parent.mkdir(parents=True,exist_ok=True)
    with BATCH_OUT.open("w",encoding="utf-8",newline="") as h:
        w=csv.DictWriter(h,fieldnames=BATCH_FIELDS,delimiter="\t",quoting=csv.QUOTE_ALL,lineterminator="\n"); w.writeheader(); w.writerows(rows)
    manifest={"batch_id":BATCH_ID,"base_commit":BASE_COMMIT,"sentno_start":TARGET_START,"sentno_end":TARGET_END,"row_count":64,"fields":[*EMPTY_FIELDS,"processing_flags","enrichment_state"],"prompt_version":PROMPT_VERSION,"source_dependency":"canonical_source_only","morphology_dependency":False,"darija_modified":False,"schema_version":"1.1.0","generated_at":generated_at,"review_state":"generated"}
    MANIFEST_OUT.write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    scores=[int(r["difficulty_score"]) for r in rows]; flags=Counter(f for r in rows if r["processing_flags"] for f in r["processing_flags"].split("|"))
    report={"result":"PASS","batch_id":BATCH_ID,"base_commit":BASE_COMMIT,"sentno_start":TARGET_START,"sentno_end":TARGET_END,"target_rows":64,"draft_rows":sum(r["enrichment_state"]=="draft" for r in rows),"flagged_rows":sum(r["enrichment_state"]=="flagged" for r in rows),"flagged_row_sentnos":[r["sentno"] for r in rows if r["enrichment_state"]=="flagged"],"processing_flags_populated_rows":sum(bool(r["processing_flags"]) for r in rows),"flag_counts":dict(sorted(flags.items())),"difficulty_stats":{"min":min(scores),"max":max(scores),"mean":round(statistics.mean(scores),2),"median":statistics.median(scores)},"required_linguistic_fields":64*len(EMPTY_FIELDS),"source_gate":"PASS","layer_contract":"PASS","morphology_gate":"BLOCKED_UPSTREAM_DEFECT","morphology_reads":0,"arabic_modified":0,"learning_unit_rows_created":0,"validator":"PASS","generated_at":generated_at,"outputs":{"batch":BATCH_OUT.relative_to(ROOT).as_posix(),"manifest":MANIFEST_OUT.relative_to(ROOT).as_posix()}}
    QA_OUT.write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n",encoding="utf-8"); return report
if __name__=="__main__": print(json.dumps(build(),ensure_ascii=False,indent=2))
