"""Build source-only MADOran enrichment Batch 07 for Sentno 385..448."""
from __future__ import annotations

import csv, json, statistics, sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.apply_madoran_enrichment_batch import CEFR_LEVELS, CONTROLLED_VALUES
from scripts.build_madoran_enrichment_scaffold import EMPTY_FIELDS, PROCESSING_FLAG_VALUES, ROOT, SOURCE_OUT, read_tsv, source_gate
from scripts.validate_madoran_enrichment import check_layer_contract

BATCH_ID="MADORAN-ENRICH-007"; BASE_COMMIT="2c57e69"; PROMPT_VERSION="madoran-source-enrichment-v7"; TARGET_START=385; TARGET_END=448
BATCH_DIR=ROOT/"data/master/enrichment/batches"; BATCH_OUT=BATCH_DIR/"batch07_sentno_0385_0448.tsv"; MANIFEST_OUT=BATCH_DIR/"batch07_manifest.json"; QA_OUT=ROOT/"data/master/qa/madoran_enrichment_batch07_generation_qa.json"
BATCH_FIELDS=["source_uid","sentno",*EMPTY_FIELDS,"processing_flags","enrichment_state"]

def item(english,korean,cefr,score,domain,topic,genre,speech,register,context,flags="",state="draft"):
    return {"english":english,"korean":korean,"cefr_level":cefr,"difficulty_score":str(score),"domain":domain,"topic":topic,"genre":genre,"speech_act":speech,"register":register,"context_dependency":context,"processing_flags":flags,"enrichment_state":state}

def latinize(text):
    table=str.maketrans({"ا":"a","أ":"a","إ":"i","آ":"a","ء":"'","ب":"b","ت":"t","ث":"th","ج":"j","ح":"7","خ":"kh","د":"d","ذ":"dh","ر":"r","ز":"z","س":"s","ش":"sh","ص":"s","ض":"d","ط":"t","ظ":"z","ع":"3","غ":"gh","ف":"f","ق":"9","ك":"k","ل":"l","م":"m","ن":"n","ه":"h","و":"w","ي":"i","ى":"a","ة":"a","ئ":"i","ؤ":"w","،":",","؟":"?"})
    return " ".join("".join(ch if ord(ch)<128 else " " for ch in text.translate(table)).split())

RAW={
385:item("We mix everything in a blender and blend it all. The harira on low heat starts to boil; we add our cooked meat, bring the seasoning paste, mix the paste well, and pour it into the harira.","모든 것을 믹서에 넣고 잘 갈아요. 약한 불에 올린 하리라가 끓기 시작하면 익힌 고기를 넣고 양념장을 가져와 잘 섞은 뒤 하리라에 부어요.","B2",60,"food","harira_blending_and_seasoning","recipe","command","colloquial","high","long_source|source_ambiguity","flagged"),
386:item("Mix everything, then let the tchicha cook like that for about fifteen minutes and turn off the heat. It comes out thick and delicious; the exact adjective is colloquial.","모든 것을 섞은 다음 치샤를 그렇게 15분 정도 익히고 불을 꺼요. 걸쭉하고 맛있게 되는데, 정확한 표현은 구어체라 불분명해요.","B1",45,"food","harira_tchicha_final_cooking","recipe","command","colloquial","medium","source_ambiguity","flagged"),
387:item("This is how we make it rich and let it take time, but it comes out excellent. In Ramadan we serve it with bourek filled with kefta or chicken, salad, sometimes fried peppers or chakchouka, sometimes a gratin, and sometimes a sweet-olive tajine: a lavish Ramadan table, with blessings descending.","우리는 이렇게 재료를 풍성하게 넣고 시간을 들여 만들지만 정말 훌륭하게 나와요. 라마단에는 케프타나 닭고기를 넣은 부레크, 샐러드, 때로는 튀긴 고추나 샥슈카, 때로는 그라탱, 또 때로는 달콤한 올리브 타진과 함께 내요. 풍성한 라마단 식탁이고 축복이 내려와요.","B2",65,"food","ramadan_harira_table","expository","description","colloquial","high","idiom_culture|long_source|source_ambiguity","flagged"),
388:item("To make carrot chermoula, clean the carrots and cut them into rounds. Salt them, then blend garlic, coriander, and parsley together.","당근 셰르물라를 만들려면 당근을 씻어 동그랗게 썰어요. 소금에 절이고 마늘, 고수, 파슬리를 함께 갈아요.","A2",34,"food","carrot_chermoula_preparation","recipe","command","colloquial","low"),
389:item("Take a pot, put water in it, pour the carrots with their ingredients into the couscoussier, and let them steam.","냄비에 물을 넣고 재료를 버무린 당근을 쿠스쿠시에 넣어 쪄요.","A2",32,"food","carrot_steaming","recipe","command","neutral","low"),
390:item("When they have steamed, take the pot and a frying pan, add a little oil, pour the carrots into it, and add cumin and caraway. Take a cinnamon stick, leave it for about ten minutes, then turn off the heat, cover it, and enjoy your meal.","당근이 쪄지면 냄비와 프라이팬을 준비해 기름을 조금 두르고 당근을 넣어요. 쿠민과 캐러웨이를 넣고 계피 스틱도 넣어 약 10분 두었다가 불을 끄고 덮어요. 맛있게 드세요.","B1",48,"food","carrot_chermoula_seasoning","recipe","command","colloquial","medium","source_ambiguity","flagged"),
391:item("Wafa, I wanted to ask you about the squid with rice that you made. I want the sauce or seasoning you put in it and how you made it; I felt like making it too.","와파, 네가 만든 밥을 넣은 오징어에 대해 물어보고 싶었어. 거기에 넣은 소스나 양념을 어떻게 만들었는지 알고 싶어. 나도 만들어 보고 싶었거든.","B1",55,"food","stuffed_squid_recipe_request","interview","request","colloquial","high","source_ambiguity","flagged"),
392:item("Yes, look: prepare one kilogram of squid, clean it completely inside and outside, and set it aside.","그래, 봐. 오징어 1킬로그램을 준비해서 안팎을 깨끗이 손질한 뒤 옆에 두어요.","A2",30,"food","squid_cleaning","recipe","command","colloquial","low"),
393:item("Cook a bowl of rice with a little salt, drain it, and add some parsley, coriander, hot pepper, cumin, red pepper, and a pinch of saffron. Add three peeled garlic cloves and mix everything together.","밥 한 그릇을 소금을 조금 넣어 지은 뒤 물기를 빼요. 파슬리, 고수, 매운 고추, 쿠민, 붉은 고추, 사프란 한 꼬집과 껍질을 벗긴 마늘 세 쪽을 넣고 모두 섞어요.","B1",55,"food","stuffed_squid_rice_filling","recipe","command","colloquial","medium"),
394:item("Fill each squid with the rice stuffing and close it with a toothpick.","오징어 하나하나에 밥소를 채우고 이쑤시개로 닫아요.","A2",38,"food","stuffed_squid_filling","recipe","command","neutral","low"),
395:item("While you are sealing them so the stuffing does not come out, take a pressure cooker. Grate one onion and five garlic cloves, sauté them in two tablespoons of oil, add three grated tomatoes, and fry everything.","밥소가 나오지 않도록 오징어를 닫는 동안 압력솥을 준비해요. 양파 한 개와 마늘 다섯 쪽을 갈아 기름 두 큰술에 볶고, 간 토마토 세 개를 넣어 모두 볶아요.","B1",50,"food","stuffed_squid_sauce_base","recipe","command","colloquial","high","long_source"),
396:item("Add a pinch of salt, not too much because the rice is already salted, then a pinch of hot pepper, a pinch of turmeric, half a cinnamon stick, and a bay leaf.","소금을 한 꼬집 넣되 밥에 이미 소금이 들어갔으니 너무 많이 넣지 않아요. 매운 고추와 강황을 한 꼬집씩, 계피 반 스틱과 월계수 잎도 넣어요.","B1",47,"food","stuffed_squid_sauce_spices","recipe","command","neutral","low"),
397:item("Add a coffee spoon of tomato paste and two glasses of water, and let the sauce cook well.","토마토 페이스트를 커피 스푼 하나 넣고 물 두 컵을 부어 소스를 잘 익혀요.","A2",34,"food","stuffed_squid_sauce","recipe","command","neutral","low"),
398:item("Do not let the sauce dry out too much; it needs about ten minutes. Put all the squid in the pressure cooker with the sauce and close it over them.","소스가 너무 마르지 않게 해요. 10분 정도면 돼요. 오징어를 모두 소스와 함께 압력솥에 넣고 뚜껑을 닫아요.","B1",50,"food","stuffed_squid_pressure_cooking","recipe","command","colloquial","medium"),
399:item("Leave it for ten minutes to a quarter of an hour, then turn it off. It is very delicious and filling; when I made it at home, everyone enjoyed it. Try it and let me know. Thank you, goodbye.","10분에서 15분 정도 두었다가 불을 꺼요. 정말 맛있고 든든해요. 집에서 만들어 보니 모두가 맛있게 먹었어요. 만들어 보고 알려 주세요. 고마워요, 안녕히 계세요.","B1",48,"food","stuffed_squid_recipe_closing","recipe","thanks","colloquial","medium","source_ambiguity","flagged"),
400:item("One weekend Friday was very hot, so we decided to go to the beach and spend the whole day there. We prepared sandwiches with fries and omelet, juice and cold water, made tea, and brought cake, flatbread, and cookies before setting off.","어느 주말 금요일에 날씨가 아주 더워서 바다에 가 하루 종일 보내기로 했어요. 감자튀김과 오믈렛을 넣은 샌드위치, 주스와 찬물을 준비하고 차와 케이크, 플랫브레드와 과자를 챙겨 길을 나섰어요.","B1",54,"travel","beach_day_trip_preparation","narrative","narration","colloquial","high","long_source|source_ambiguity","flagged"),
401:item("We left in the morning to have enough time. On the way, we saw a black vehicle and many others stopped near a place or sign whose name is unclear. We slowed down and found a crash: a car had collided with a crushed truck, people were injured, and there was blood. God forbid.","시간을 넉넉히 쓰려고 아침에 출발했어요. 가는 길에 이름이 불분명한 장소나 표지 근처에서 검은 차량과 많은 차가 멈춰 있는 것을 봤어요. 속도를 줄이니 차와 찌그러진 트럭이 충돌한 사고가 있었고, 사람들이 다치고 피도 보였어요. 하느님, 그런 일이 없기를.","C1",78,"travel","road_accident_on_beach_trip","narrative","narration","mixed","high","long_source|source_ambiguity","flagged"),
402:item("When we asked, they told us that the cars had been speeding and a truck was trying to enter or overtake a car when they collided. The firefighters came, carried the poor people, and moved the car and truck aside to clear the road so we could pass.","물어보니 차들이 과속했고 트럭이 차 앞으로 들어가거나 추월하려다가 서로 부딪혔다고 했어요. 소방대원들이 와서 불쌍한 사람들을 옮기고 차와 트럭을 옆으로 치워 길을 열어 우리가 지나가게 했어요.","B2",65,"travel","road_accident_response","narrative","narration","mixed","high","long_source|source_ambiguity","flagged"),
403:item("When we reached the beach, it was a little damaged or rough, but the water was excellent. We parked in a park where the first charge was only 50 dinars.","바다에 도착했을 때 주변은 조금 망가졌거나 거칠었지만 물은 정말 좋았어요. 주차장에 차를 세웠는데 처음에는 50디나르밖에 받지 않았어요.","B1",45,"travel","beach_arrival_and_parking","narrative","narration","colloquial","medium","source_ambiguity","flagged"),
404:item("Later they raised the price and made it 400 dinars. Even if it was only a park, people had maintained it or it looked like a track with nothing there; in any case, we said it was fine as long as someone watched it. The remaining wording is unclear.","나중에는 요금을 올려 400디나르로 받았어요. 그냥 주차장일 뿐이거나 아무것도 없는 길처럼 보여도 사람들이 관리하고 있었고, 누군가 지켜보기만 하면 괜찮다고 했어요. 나머지 표현은 불분명해요.","B2",60,"travel","beach_parking_fee","narrative","opinion","colloquial","high","source_ambiguity","flagged"),
405:item("We rented a parasol and chairs and rested. We did not go into the water immediately; we faced the sea, ate, and extended our meal so it could settle.","파라솔과 의자를 빌려 쉬었어요. 바로 물에 들어가지는 않고 바다를 마주 보며 먹고, 음식이 소화되도록 조금 더 쉬었어요.","A2",36,"travel","beach_rest_and_meal","narrative","narration","colloquial","low"),
406:item("When we went into the water, we saw someone struggling and saying, Save me. I told my brother, Look, he is drowning; please go and see him.","물에 들어가니 누군가 허우적거리며 살려 달라고 하는 게 보였어요. 나는 형제에게 저기 사람이 물에 빠지고 있으니 제발 가서 보라고 했어요.","B1",52,"health","beach_drowning_rescue","narrative","warning","colloquial","high","source_ambiguity","flagged"),
407:item("My brother went to him because the man had fallen into the water. He kept turning around in place and pulling at the water until my brother saved him and brought him out. Civil protection arrived and gave him artificial respiration to bring him back because he had lost consciousness; they removed the water he had swallowed until he came back to life, dressed him, and took him away.","형제는 그 사람에게 갔어요. 그 남자가 물에 빠져 제자리에서 계속 허우적거리며 물을 잡아당기고 있었고, 형제가 그를 구해 밖으로 데리고 나왔어요. 의식을 잃었기 때문에 민방위 구조대가 와서 인공호흡을 해 살렸고, 삼킨 물을 빼내며 정신을 되찾게 한 뒤 옷을 입혀 데려갔어요.","C1",82,"health","beach_drowning_emergency_response","narrative","narration","mixed","high","long_source|source_ambiguity","flagged"),
408:item("He had mistakenly thought he was a swimmer. The sea was dangerous and the warning sign or flag was red, but fortunately we saw him, my brother saved him, and everything ended well. We returned to our day at the beach.","그 사람은 자신이 수영을 잘한다고 잘못 생각했던 것 같아요. 바다는 위험했고 경고 표지나 깃발은 빨간색이었지만, 다행히 우리가 그를 봤고 형제가 구해서 일이 잘 끝났어요. 우리는 다시 해변에서 하루를 보냈어요.","B1",56,"health","beach_rescue_reflection","narrative","narration","mixed","high","source_ambiguity","flagged"),
409:item("After that we got hungry, went out, drank tea, and ate flatbread and cake. We played cards, then played dominoes; people relaxed, gathered, and chatted, while some played in the sand. It was a beautiful, rich day, and we came back tired.","그 뒤 배가 고파져 밖으로 나가 차와 플랫브레드, 케이크를 먹었어요. 카드놀이를 하고 도미노도 했고, 사람들은 쉬고 모여서 이야기를 나누며 일부는 모래에서 놀았어요. 즐겁고 풍성한 하루였고 우리는 지쳐서 돌아왔어요.","B1",50,"entertainment_music","beach_day_games_and_food","narrative","narration","colloquial","medium","source_ambiguity","flagged"),
410:item("At night there was music, fun, and clapping again. We made a scene all along the road. Kholoud wanted a small ice cream, so we stopped and finished it because we were full.","밤에도 음악과 흥겨운 분위기, 박수가 이어졌어요. 우리는 길을 따라 신나게 떠들었어요. 클룻이 작은 아이스크림을 원해서 멈춰 먹고, 배가 불러서 그것으로 마무리했어요.","B1",55,"entertainment_music","beach_trip_evening_fun","narrative","narration","colloquial","high","source_ambiguity","flagged"),
411:item("We cooled down with that ice cream. I wanted a lemon Eskimo, and then we continued the journey. We reached home tired, showered, and went to sleep.","그 아이스크림을 먹으며 더위를 식혔어요. 나는 레몬 에스키모를 원했고, 다시 길을 계속 갔어요. 집에 도착하니 지쳐서 샤워하고 잠들었어요.","A2",35,"travel","beach_trip_return","narrative","narration","colloquial","medium","source_ambiguity","flagged"),
412:item("When a man wants to spend the night and intends a lawful marriage, he goes to ask for the woman from her family or guardian. He takes relatives with him, brings a cake and a bouquet of flowers, and a ring; some also bring chocolate and sweets.","남자가 결혼을 하고 정식으로 혼인할 뜻이 있으면 여자의 가족이나 보호자에게 청혼하러 가요. 친척들을 데리고 케이크와 꽃다발, 반지를 가져가고, 어떤 사람은 초콜릿과 과자도 가져가요.","B2",67,"family_relationships","marriage_proposal_custom","expository","description","colloquial","high","idiom_culture|source_ambiguity","flagged"),
413:item("If they like each other, they continue with it and agree on conditions such as money and household goods. Then they choose the day for the Fatiha ceremony.","서로 마음에 들면 결혼을 계속 진행하고 돈과 살림살이 같은 조건을 합의해요. 그런 다음 파티하를 올릴 날을 정해요.","B1",52,"family_relationships","marriage_terms_and_fatiha","expository","agreement","colloquial","medium","idiom_culture"),
414:item("On the day before the Fatiha, the groom brings a ram, vegetables, fruit, and everything needed for cooking. The bride receives a tray with a traditional dress such as a karakou, Constantine dress, Oran blouza, Mansouria, or caftan, according to each family's means, with shoes and a bag, plus a djellaba and a burnous; almost everyone gives a burnous.","파티하 전날 신랑 쪽에서는 요리에 필요한 숫양, 채소, 과일을 모두 가져와요. 신부에게는 집안 형편에 따라 카라쿠, 콘스탄틴 전통 의상, 오랑 블루자, 만수리아, 카프탄 같은 옷을 담은 쟁반을 주고, 신발과 가방, 젤라바와 부르누스도 함께 마련해요. 거의 모두 부르누스를 해요.","B2",72,"family_relationships","algerian_fatiha_gifts","expository","description","mixed","high","idiom_culture|long_source|source_ambiguity","flagged"),
415:item("They also give undergarments such as camisoles, panties, and pajamas, a belt, and another tray filled with makeup, perfume, shampoo, and soap.","또 속옷과 캐미솔, 팬티, 잠옷, 허리띠를 주고, 화장품과 향수, 샴푸와 비누로 채운 또 하나의 쟁반도 마련해요.","B2",69,"family_relationships","bride_gift_trays","expository","description","mixed","medium","idiom_culture|source_ambiguity","flagged"),
416:item("They add a loaf of sugar, two glasses, candles, henna, milk, cotton, a platter of dates, and trays of cake. When the Fatiha day comes, all the prepared things are taken to the hall.","설탕 한 덩이, 유리잔 두 개, 양초, 헤나, 우유, 솜, 대추야자 접시와 케이크 쟁반도 더해요. 파티하 날이 오면 준비한 물건을 모두 행사장으로 가져가요.","B1",59,"family_relationships","fatiha_ceremony_supplies","expository","description","colloquial","medium","idiom_culture"),
417:item("She brings invited women who are neighbors, friends, or family. The groom's father brings the men he invited to attend the Fatiha, with an imam and witnesses. The bride also has her own invited guests.","신부 쪽에서는 이웃과 친구, 가족처럼 초대한 여자들을 데려와요. 신랑의 아버지는 초대한 남자들을 데려오고, 파티하를 위해 이맘과 증인들도 함께해요. 신부 쪽에도 초대한 사람들이 있어요.","B2",68,"family_relationships","fatiha_guests_and_witnesses","expository","description","mixed","high","idiom_culture|source_ambiguity","flagged"),
418:item("We begin with the Fatiha, people ululate, the men eat and drink, then the women sit and are served food too. When we finish, the celebration and dancing start with a DJ. Every so often we see the bride arrive in another outfit with her husband beside her, and people ululate and celebrate until evening.","파티하로 시작하고 사람들이 자그라트를 하며, 남자들은 먹고 마셔요. 그다음 여자들도 앉아 음식을 대접받아요. 다 끝나면 DJ 음악에 맞춰 축하와 춤이 시작돼요. 때때로 신부가 남편을 곁에 두고 다른 옷으로 나타나고, 사람들은 저녁까지 자그라트를 하며 즐겨요.","B2",63,"family_relationships","fatiha_celebration","narrative","narration","mixed","high","idiom_culture|long_source","flagged"),
419:item("After that they distribute assorted cakes, coffee, and tea, the evening continues, and people dance.","그 뒤에는 여러 종류의 케이크와 커피, 차를 나누고 저녁이 이어지며 사람들이 춤을 춰요.","B1",49,"family_relationships","wedding_refreshments_and_dance","narrative","narration","colloquial","medium"),
420:item("Afterward the groom sets the date of his wedding, because in our tradition the Fatiha is for the engagement and then comes the wedding.","그다음 신랑이 결혼 날짜를 정해요. 우리 전통에서는 파티하가 약혼을 위한 절차이고 그 뒤에 결혼식이 오기 때문이에요.","B1",48,"family_relationships","fatiha_before_wedding","expository","description","colloquial","medium","idiom_culture"),
421:item("As people say, a wedding is one night whose preparation takes a year. Another saying is that in summer there are cakes and rain. And a wedding is easy: slaughter a kid and call her to come; but it is only ten days after the groom. The exact sayings are preserved as heard and remain partly unclear.","사람들이 말하듯 결혼식은 하룻밤이지만 준비에는 1년이 걸려요. 또 여름에는 케이크와 비가 함께 온다는 식의 말도 있어요. 결혼식은 쉽다며 염소 새끼를 잡고 그녀를 부르라는 말도 있지만, 신랑 뒤로 열흘뿐이라는 부분은 정확히 불분명해요. 속담 표현은 들은 그대로 보존했어요.","B2",60,"family_relationships","wedding_proverbs","proverb","description","colloquial","high","idiom_culture|source_ambiguity","flagged"),
422:item("Once I was traveling, and when I returned from the trip I found that the daughter of our neighbor, whom I loved, had been married off by her father against her will. She had avoided me because she was afraid of her father. I went into our house, saw that something was not normal, asked Malika, and grabbed an unclear object before running to her father.","한번은 여행을 갔다가 돌아왔는데, 내가 사랑하던 이웃집 딸을 아버지가 억지로 시집보냈다는 걸 알게 됐어요. 그녀는 아버지가 무서워 나를 피하고 있었어요. 우리 집에 들어가 이상한 일이 있다는 것을 보고 말리카에게 물은 뒤, 정확히 무엇인지 불분명한 물건을 집어 들고 그녀의 아버지에게 달려갔어요.","C1",82,"crime_safety","forced_marriage_rescue_story","narrative","narration","mixed","high","idiom_culture|long_source|source_ambiguity","flagged"),
423:item("He told me, I have given her away, and only you remain; do not take her. The exact wording and implication are unclear.","그는 나에게 그녀를 이미 시집보냈고 이제 남은 사람은 너뿐이니 그녀를 데려가지 말라고 했어요. 정확한 말과 의도는 불분명해요.","B2",75,"crime_safety","forced_marriage_confrontation","conversation","refusal","mixed","high","source_ambiguity","flagged"),
424:item("She came out of the living room crying and told me, Nazir, save me. Her nose was bleeding and her body was blue from the beatings. I grabbed her father, struck him, took her to our house, and told her to stay here with us. I went back, put earphones in her ears, and told her to listen to music so she would not hear the beating.","그녀가 거실에서 울며 나와 나지르, 나를 구해 달라고 했어요. 코에서는 피가 나고 몸은 맞아서 멍들어 있었어요. 나는 그녀의 아버지를 붙잡아 때리고 그녀를 우리 집으로 데려와 여기 우리와 있으라고 했어요. 나는 다시 돌아가 그녀의 귀에 이어폰을 꽂고 폭행 소리를 듣지 않도록 음악을 들으라고 했어요.","C1",88,"crime_safety","domestic_violence_rescue","narrative","narration","mixed","high","long_source|source_ambiguity","flagged"),
425:item("I locked the door on them and went out. I found her fiancé and his friends rushing into the neighborhood. I picked up an unclear object and stepped between them; I knocked down about twelve people, though one stabbed me in the back. I gathered courage, confronted them, and told them not to do it that way, but to come and do something decent. I beat them and they all ran away.","나는 그들을 안에 가두고 밖으로 나왔어요. 그녀의 약혼자와 친구들이 동네로 몰려오는 것을 봤어요. 불분명한 물건을 들고 그들 사이에 들어가 열두 명가량을 쓰러뜨렸지만 한 명이 내 등을 찔렀어요. 용기를 내서 맞서며 그렇게 하지 말고 와서 제대로 해결하자고 했어요. 내가 그들을 때리자 모두 도망갔어요.","C1",86,"crime_safety","rescue_confrontation","narrative","narration","mixed","high","long_source|source_ambiguity","flagged"),
426:item("Her fiancé told me, You are a real man; you are the one who deserves her. I am all tea and strong, but your love is great and you deserve her; may God complete your happiness. It was like an Indian film. If anyone knows an Indian director, bring him here; there is already a film, and God's people will laugh.","그녀의 약혼자는 나에게 네가 진짜 남자이고 그녀를 받을 자격이 있는 사람이라고 했어요. 나는 차와 힘이 전부인 사람이라는 식의 불분명한 말 뒤에, 네 사랑이 크고 그녀를 받을 자격이 있으니 하느님이 행복을 완성해 주길 바란다고 했어요. 인도 영화 같았어요. 인도 감독을 아는 사람이 있으면 데려오라고, 이미 영화가 있으니 사람들이 웃을 거라고 했어요.","B2",72,"humor","rescue_story_humorous_closing","narrative","description","colloquial","high","source_ambiguity","flagged"),
427:item("I was sitting with a group and they brought up politics. When Algerians started talking about Kabyles and about a flag, saying that we do not recognize the flag representing the Zwawa, the argument began.","나는 사람들과 앉아 있었는데 정치 이야기가 나왔어요. 알제리 사람들이 카빌인과 어느 깃발에 대해 이야기하며 즈와와를 대표하는 그 깃발을 인정하지 않는다고 하자 논쟁이 시작됐어요.","B2",65,"politics_public_affairs","algerian_identity_flag_debate","conversation","disagreement","mixed","high","source_ambiguity","flagged"),
428:item("There is no Kabyle and Arab division; we are all Algerians and come from one land. A Kabyle woman stood up and said, Stop being racist and ignorant. You have slept for twenty years and are pleased with this humiliation. When they began speaking, they left poverty, misery, and a low level in every field—education, health, tourism, and trade. Everything is ruined, and now they have come to talk about a flag and who knows what.","카빌인과 아랍인의 구분은 없고 우리는 모두 알제리 사람이며 한 땅에서 왔어요. 카빌 여성이 일어나 인종차별주의자와 무지한 사람이 되지 말라고 했어요. 20년 동안 잠들어 있으면서 이런 굴욕을 좋아한다고요. 그들이 말하기 시작하자 교육, 보건, 관광, 무역 등 모든 분야에 가난과 비참함, 낮은 수준만 남겼어요. 모든 것이 망가졌는데 이제 깃발인지 뭔지에 대해 이야기하러 왔다고 했어요.","C1",88,"politics_public_affairs","identity_debate_and_social_crisis","speech","complaint","mixed","high","long_source|source_ambiguity","flagged"),
429:item("An ignorant person does not speak about the simplest matters; he is supposed to educate himself and distinguish between a flag, a banner, and an identity. Then he can speak and discuss. I want to ask you: when you raise the Palestinian flag, is it beside Algeria's?","무지한 사람은 가장 기본적인 일도 말하지 못해요. 스스로 공부해서 깃발과 현수막, 정체성을 구분해야 해요. 그래야 말하고 토론할 수 있어요. 당신에게 묻고 싶어요. 팔레스타인 깃발을 들 때 그것은 알제리 깃발과 함께 있는 건가요?","B2",70,"politics_public_affairs","flags_and_identity_argument","speech","question","mixed","high","source_ambiguity","flagged"),
430:item("Ignorance is what has made us backward and among the last people. Even if they brought a brilliant person to govern Algeria, we would remain backward like this.","무지가 우리를 뒤처지고 가장 낙후된 사람들처럼 만들었어요. 알제리를 다스릴 똑똑한 사람을 데려온다 해도 우리는 이렇게 뒤처진 채일 거예요.","B2",68,"politics_public_affairs","ignorance_and_governance","speech","opinion","colloquial","medium"),
431:item("You find a doctor or knowledgeable person saying that the Palestinian flag is one thing and the Amazigh identity flag is another; no, they are an inseparable part of Algeria.","어떤 의사나 식견 있는 사람은 팔레스타인 깃발은 하나의 문제이고 아마지그 정체성의 깃발은 또 다른 문제라고 말해요. 하지만 그들은 알제리에서 떼어 놓을 수 없는 일부예요.","B2",60,"politics_public_affairs","palestinian_and_amazigh_identity","speech","opinion","mixed","medium","source_ambiguity","flagged"),
432:item("I told her that I saw no difference between Kabyle, Arab, or Sahrawi: we are all one block, all written as Algerians on our documents. These are only empty-headed people who seek to create division.","나는 그녀에게 카빌인, 아랍인, 사하라 사람 사이에 차이가 없고 우리는 모두 하나이며 서류에는 모두 알제리 사람으로 적힌다고 했어요. 분열을 만들려는 사람들은 그저 생각이 빈 사람들이에요.","B2",70,"politics_public_affairs","algerian_unity_argument","speech","opinion","mixed","high","source_ambiguity","flagged"),
433:item("This is only regionalism and racism; we are all brothers. I spoke, and she said, Yes, you are right. They should first achieve the demands raised by the people, then they get distracted by matters beyond their understanding—ignorant people who understand nothing.","이건 지역주의와 인종차별일 뿐이고 우리는 모두 형제예요. 내가 말하자 그녀는 네 말이 맞다고 했어요. 먼저 사람들이 제기한 요구를 해결해야 하는데, 그다음에는 이해하지도 못하는 일에 빠져드는 무지한 사람들이라고 했어요.","B2",72,"politics_public_affairs","regionalism_and_public_demands","speech","disagreement","mixed","high","long_source|source_ambiguity","flagged"),
434:item("People in the old days said: a rolled mat carried on a pig's back—one person eats and the other watches. It means that people have started eating what is forbidden, while few people watch and find nothing to eat.","옛사람들이 말했어요. 돼지 등에 말아 올린 돗자리처럼 한 사람은 먹고 다른 사람은 지켜본다는 뜻이에요. 사람들이 금지된 것을 먹기 시작했는데, 지켜보는 소수는 먹을 것을 찾지 못한다는 말이에요.","B2",65,"culture_tradition","proverb_about_inequality","proverb","description","colloquial","high","idiom_culture|source_ambiguity","flagged"),
435:item("Oh Oran, yes, Oran.","오, 오랑, 그래 오랑.","A1",20,"culture_tradition","oran_poetic_lament","song_lyric","exclamation","colloquial","low"),
436:item("You used to be a water channel with water in you, between the mountains where the horsemen drank from you.","너는 물이 흐르는 수로였고, 산들 사이에서 기사들이 네 물을 마셨지.","B1",55,"culture_tradition","oran_poetic_lament","song_lyric","narration","colloquial","medium","source_ambiguity","flagged"),
437:item("You became a pond with reeds, and rats are living in you. The exact plant word is preserved as heard.","너는 갈대가 있는 웅덩이가 되었고 그 안에는 쥐들이 살고 있어. 식물 이름은 들은 그대로 보존해.","B2",64,"culture_tradition","oran_poetic_lament","song_lyric","description","colloquial","high","source_ambiguity","flagged"),
438:item("Live on, Barak, in the land of animals. The name or expression Barak is preserved as heard and its reference is unclear.","동물의 땅에서 살아가라, 바라크. 바라크라는 이름이나 표현은 들은 그대로 보존하며 무엇을 가리키는지는 불분명해.","B1",45,"culture_tradition","oran_poetic_lament","song_lyric","wish","colloquial","high","source_ambiguity","flagged"),
439:item("A gandoura, a turban, and a bed covering; I carry it around to households and memorize sixty hizb with a prayer and a candle. Someone like me who cannot read holds on as he goes around with his children and neighbors and brings them a saying or lesson. Several expressions are unclear.","간두라와 터번, 침구를 갖추고 집집마다 돌아다니며 기도와 촛불로 60히즈브를 외운다는 말이야. 나처럼 글을 읽지 못하는 사람은 아이들과 이웃을 데리고 다니며 그들에게 말이나 교훈을 전한다는 뜻인데, 몇몇 표현은 불분명해.","C1",80,"religion","religious_and_moral_saying","speech","description","mixed","high","idiom_culture|long_source|source_ambiguity","flagged"),
440:item("Listen: clean your face and do not worry about what you meet. If you miss beauty, make it up with a smile; if you miss clothing, make it up with cleanliness; if you miss knowledge, make it up with wit; and if you miss money, make it up with contentment.","들어 봐. 얼굴을 깨끗이 하고 무엇을 만나든 걱정하지 마. 아름다움이 부족하면 미소로 보완하고, 옷이 부족하면 청결로 보완하고, 지식이 부족하면 재치로 보완하고, 돈이 부족하면 만족으로 보완해.","A2",35,"culture_tradition","proverb_about_personal_qualities","proverb","suggestion","colloquial","low"),
441:item("That one paid a million and went to sleep, while I paid billions. These girls did not increase, those boys did not leave, and my unclear amount or obligation was not paid. The line is a rhyming colloquial expression and remains partly unclear.","저 사람은 백만을 내고 잠들었고 나는 수십억을 냈다는 식의 말이야. 이 여자들은 늘지 않았고 저 남자들은 가지 않았으며, 내가 지불하지 못한 불분명한 금액이나 의무가 있다는 내용이 이어져. 운율이 있는 구어 표현이라 일부는 불분명해.","B2",61,"finance","rhyming_money_saying","joke","description","colloquial","high","source_ambiguity","flagged"),
442:item("Ramadan is near and money is tight for me. The Eid ram has arrived, but I have no sacrifice. Everything has become difficult because there is no contentment. A purebred son does not come stained, and an oleander tree does not produce apples.","라마단이 다가오는데 내 형편은 빠듯해. 명절 양이 왔지만 희생 제물을 마련할 수가 없어. 만족이 없으니 모든 것이 힘들어졌다는 말이야. 순종적인 아들이 얼룩진 채 오지 않고 협죽도 나무가 사과를 맺지 않는다는 속담도 이어져.","B2",64,"finance","ramadan_financial_proverbs","proverb","complaint","colloquial","high","idiom_culture|source_ambiguity","flagged"),
443:item("Act crazy and you will get your fill of flatbreads.","미친 사람처럼 행동하면 빵을 배불리 얻어먹는다는 말이야.","A2",25,"culture_tradition","proverb_about_cleverness","proverb","description","colloquial","low"),
444:item("Not everything that glitters is gold, and not every green thing is grass.","반짝이는 것이 모두 금은 아니고, 초록색이라고 모두 풀이 아니야.","A2",28,"culture_tradition","proverb_about_appearances","proverb","description","neutral","low"),
445:item("The ant grew up and started looking in the garbage, excuse me.","개미가 자라서 쓰레기통을 뒤지기 시작했다는 말이야. 실례해.","A2",30,"culture_tradition","proverb_about_decline","proverb","description","colloquial","medium","idiom_culture"),
446:item("The river carries him, and he says, How beautiful the coolness is.","강물이 그를 떠내려가게 하는데도 그는 시원함이 참 좋다고 말해.","A2",30,"culture_tradition","proverb_about_denial","proverb","description","neutral","low"),
447:item("Coffee and a cigarette are better than a sultan in his house.","커피와 담배가 자기 집에 있는 술탄보다 낫다는 말이야.","A2",30,"culture_tradition","proverb_about_simple_pleasures","proverb","opinion","colloquial","low"),
448:item("However large the eye becomes, the eyebrow is always above it.","눈이 아무리 커져도 눈썹은 언제나 그 위에 있다는 말이야.","A2",24,"culture_tradition","proverb_about_hierarchy","proverb","description","neutral","low"),
}

def validate(source):
    by={r["sentno"]:r for r in source}; expected=[str(i) for i in range(TARGET_START,TARGET_END+1)]
    if sorted(RAW)!=list(range(TARGET_START,TARGET_END+1)): raise RuntimeError("raw_coverage")
    rows=[]
    for sentno in expected:
        payload={**RAW[int(sentno)],"latin":latinize(by[sentno]["arabic_original"]),"source_uid":by[sentno]["source_uid"],"sentno":sentno}
        for field in ("domain","genre","speech_act","register","context_dependency"):
            if payload[field] not in CONTROLLED_VALUES[field]: raise RuntimeError(f"controlled:{sentno}:{field}")
        if payload["cefr_level"] not in CEFR_LEVELS: raise RuntimeError(f"cefr:{sentno}")
        flags=payload["processing_flags"].split("|") if payload["processing_flags"] else []
        if flags!=sorted(flags) or any(flag not in PROCESSING_FLAG_VALUES for flag in flags): raise RuntimeError(f"flags:{sentno}")
        if payload["enrichment_state"]=="flagged" and not flags: raise RuntimeError(f"flagged_without_reason:{sentno}")
        rows.append(payload)
    return rows

def build():
    if source_gate()["result"]!="PASS" or check_layer_contract()["result"]!="PASS": raise RuntimeError("gate_failed")
    rows=validate(read_tsv(SOURCE_OUT)); generated_at=datetime.now(timezone.utc).replace(microsecond=0).strftime("%Y-%m-%dT%H:%M:%SZ")
    BATCH_OUT.parent.mkdir(parents=True,exist_ok=True)
    with BATCH_OUT.open("w",encoding="utf-8",newline="") as h:
        w=csv.DictWriter(h,fieldnames=BATCH_FIELDS,delimiter="\t",quoting=csv.QUOTE_ALL,lineterminator="\n"); w.writeheader(); w.writerows(rows)
    manifest={"batch_id":BATCH_ID,"base_commit":BASE_COMMIT,"sentno_start":TARGET_START,"sentno_end":TARGET_END,"row_count":64,"fields":[*EMPTY_FIELDS,"processing_flags","enrichment_state"],"prompt_version":PROMPT_VERSION,"source_dependency":"canonical_source_only","morphology_dependency":False,"darija_modified":False,"schema_version":"1.1.0","generated_at":generated_at,"review_state":"generated"}
    MANIFEST_OUT.write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    scores=[int(r["difficulty_score"]) for r in rows]; flags=Counter(f for r in rows if r["processing_flags"] for f in r["processing_flags"].split("|"))
    report={"result":"PASS","batch_id":BATCH_ID,"base_commit":BASE_COMMIT,"sentno_start":TARGET_START,"sentno_end":TARGET_END,"target_rows":64,"draft_rows":sum(r["enrichment_state"]=="draft" for r in rows),"flagged_rows":sum(r["enrichment_state"]=="flagged" for r in rows),"flagged_row_sentnos":[r["sentno"] for r in rows if r["enrichment_state"]=="flagged"],"processing_flags_populated_rows":sum(bool(r["processing_flags"]) for r in rows),"flag_counts":dict(sorted(flags.items())),"difficulty_stats":{"min":min(scores),"max":max(scores),"mean":round(statistics.mean(scores),2),"median":statistics.median(scores)},"required_linguistic_fields":64*len(EMPTY_FIELDS),"source_gate":"PASS","layer_contract":"PASS","morphology_gate":"BLOCKED_UPSTREAM_DEFECT","morphology_reads":0,"arabic_modified":0,"learning_unit_rows_created":0,"validator":"PASS","generated_at":generated_at,"outputs":{"batch":BATCH_OUT.relative_to(ROOT).as_posix(),"manifest":MANIFEST_OUT.relative_to(ROOT).as_posix()}}
    QA_OUT.write_text(json.dumps(report,ensure_ascii=False,indent=2)+"\n",encoding="utf-8"); return report

if __name__=="__main__": print(json.dumps(build(),ensure_ascii=False,indent=2))
