"""Build source-only MADOran enrichment Batch 20 for Sentno 1217..1280."""
from __future__ import annotations

import json
import sys
from pathlib import Path

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts import build_madoran_enrichment_batch10 as engine
from scripts.build_madoran_enrichment_scaffold import ROOT

BATCH_ID = "MADORAN-ENRICH-020"
BASE_COMMIT = "debf929"
PROMPT_VERSION = "madoran-source-enrichment-v20"
TARGET_START = 1217
TARGET_END = 1280
BATCH_OUT = ROOT / "data/master/enrichment/batches/batch20_sentno_1217_1280.tsv"
MANIFEST_OUT = ROOT / "data/master/enrichment/batches/batch20_manifest.json"
QA_OUT = ROOT / "data/master/qa/madoran_enrichment_batch20_generation_qa.json"


def r(english, korean, domain, topic, genre="conversation", speech="description",
      register="colloquial", context="high", flags="source_ambiguity",
      state="flagged", cefr="B2", score=60):
    normalized_flags = "|".join(sorted(filter(None, flags.split("|"))))
    return engine.item(english, korean, cefr, score, domain, topic, genre, speech, register, context, normalized_flags, state)


RAW = {
    1217: r("The speaker praises Oran as a premier city with Ottoman architecture and mentions the well-known Wahrani figure or building called Bastos, then says that Oran is alive and should be described freely.", "화자는 오랑을 오스만 건축이 있는 뛰어난 도시로 칭찬하고 잘 알려진 와흐라니 인물이나 건축물인 바스토스를 언급한 뒤, 오랑은 살아 있는 도시이므로 자유롭게 이야기해야 한다고 말해요.", "history", "praising_oran_and_ottoman_architecture", genre="expository", speech="opinion", register="mixed", context="high", flags="idiom_culture|source_ambiguity|long_source", cefr="C1", score=84),
    1218: r("The speaker rejects a commonly heard story about the siege of Oran as nonsense and says the story did not happen as it is being told.", "화자는 오랑 포위에 관한 흔히 들리는 이야기를 허튼소리라고 일축하며, 그 이야기가 전해지는 방식대로 일어난 것이 아니라고 말해요.", "history", "rejecting_a_false_siege_story", speech="disagreement", register="colloquial", context="medium", flags="idiom_culture|source_ambiguity", cefr="B1", score=48),
    1219: r("The speaker says the story should not be told as an absolute account and claims that the Spanish were surrounded by Arabs at Santa Cruz, ran out of food, and found chickpeas instead.", "화자는 그 이야기를 절대적인 사실처럼 말해서는 안 된다고 하며, 스페인인들이 산타크루스에서 아랍인들에게 포위되어 먹을 것이 떨어지고 병아리콩을 찾았다고 주장해요.", "history", "correcting_the_santa_cruz_siege_story", genre="expository", speech="narration", register="mixed", context="high", flags="idiom_culture|source_ambiguity", cefr="B2", score=72),
    1220: r("The speaker argues that the Spanish were not besieged in Oran: they entered and colonized it and remained for three centuries. The speaker questions how Oran could have been liberated if a powerful Ottoman fleet was present and the Spanish were supposedly under siege.", "화자는 스페인인들이 오랑에서 포위된 것이 아니라 들어와 식민화했고 3세기 동안 머물렀다고 주장해요. 강력한 오스만 함대가 있었고 스페인인들이 포위되어 있었다면 어떻게 오랑을 해방하지 못했겠느냐고 반문해요.", "history", "challenging_the_three_century_siege_claim", genre="expository", speech="opinion", register="mixed", context="high", flags="idiom_culture|long_source|source_ambiguity", cefr="C1", score=94),
    1221: r("The speaker says the history being told is not the same as what really happened and accuses many people of lying and inventing accounts.", "화자는 전해지는 역사가 실제 일어난 일과 같지 않으며 많은 사람이 거짓말을 하고 이야기를 지어낸다고 비판해요.", "history", "criticizing_invented_history", speech="opinion", register="colloquial", context="medium", flags="idiom_culture|source_ambiguity", cefr="B1", score=48),
    1222: r("The speaker presents Oran as a great, beautiful civilization and city rather than a small village, welcomes everyone who lives there or arrives there, and says they will describe what happened without inventing or denying facts.", "화자는 오랑을 작은 마을이 아니라 크고 아름다운 문명과 도시로 소개하고, 그곳에 사는 사람과 찾아온 사람을 모두 환영해요. 없는 말을 만들거나 사실을 부정하지 않고 일어난 일을 말하겠다고 해요.", "culture_tradition", "welcoming_oran_residents_and_visitors", genre="speech", speech="narration", register="mixed", context="high", flags="idiom_culture|long_source|source_ambiguity", cefr="C1", score=90),
    1223: r("The speaker says that next time they will tell the listeners about a French expression that will make them laugh intensely.", "화자는 다음에 듣는 사람들을 크게 웃게 할 프랑스어 표현에 대해 이야기하겠다고 해요.", "humor", "announcing_a_funny_french_expression", genre="joke", speech="narration", register="colloquial", context="medium", flags="code_switching|idiom_culture|source_ambiguity", cefr="B1", score=42),
    1224: r("The speaker tells someone not to be cheeky because the speaker is not their equal, then warns that cheekiness can lead to trouble or loss.", "화자는 상대에게 자신을 만만하게 보거나 건방지게 굴지 말라고 하며, 건방짐은 손해나 곤란으로 이어질 수 있다고 경고해요.", "humor", "warning_against_cheekiness", speech="warning", register="colloquial", context="high", flags="idiom_culture|source_ambiguity", cefr="B1", score=52),
    1225: r("The speaker reassures someone not to worry about Mohamed Degourdi and says to leave him alone so that he can manage himself.", "화자는 무함마드 디구르디를 걱정하지 말고 혼자 두면 스스로 해결할 것이라고 말해요.", "daily_life", "reassuring_about_mohamed_degourdi", speech="answer", register="colloquial", context="medium", flags="source_ambiguity", state="draft", cefr="A2", score=26),
    1226: r("A corrupted, title-like line appears to announce a compilation of funny videos; the remaining characters are not recoverable as a stable sentence.", "손상된 제목 형태의 줄로, 웃긴 동영상 모음으로 보이지만 남은 문자를 안정적인 문장으로 복원할 수 없어요.", "social_media", "corrupted_funny_video_compilation_title", genre="social_media", speech="other", register="mixed", context="high", flags="source_ambiguity|source_corruption", cefr="A1", score=30),
    1227: r("The speaker jokes that betrayal is their bad luck: other people have the mafia, while the speaker ended up with this person, whom they call frightening.", "화자는 다른 사람들은 마피아에게 배신당하는데 자신은 이 사람을 만난 것이 운이 나빴다고 농담하며, 상대가 무섭다고 말해요.", "humor", "joking_about_betrayal_and_the_mafia", genre="joke", speech="opinion", register="colloquial", context="high", flags="idiom_culture|source_ambiguity", cefr="B1", score=58),
    1228: r("The speaker asks Abdine to bring or get some work, then asks what he wants to do with it; the object of the request is opaque in the isolated exchange.", "화자는 아브딘에게 어떤 일을 가져오거나 해 오라고 한 뒤, 그걸로 무엇을 하려는지 묻지만 고립된 대화에서는 대상이 불투명해요.", "work", "opaque_request_about_work", speech="question", register="colloquial", context="high", flags="source_ambiguity", cefr="A2", score=34),
    1229: r("The speaker tells people not to shout, asks why they were betrayed, and says the reason was to demand money from the listener.", "화자는 사람들에게 소리치지 말라고 하며, 왜 자신을 배신했는지 묻고 상대에게 돈을 요구하려고 그랬다는 답을 말해요.", "crime_safety", "accusing_someone_of_betrayal_for_money", speech="question", register="colloquial", context="high", flags="source_ambiguity", cefr="B2", score=68),
    1230: r("The speaker calls the listener a brother and tells him to cut the matter short, warning that if the speaker calls their father, the father will cause a great deal of trouble that the listener will not be able to withstand.", "화자는 상대를 형제라고 부르며 일을 끝내라고 하고, 아버지에게 전화하면 상대가 감당하지 못할 큰일을 벌일 것이라고 경고해요.", "family_relationships", "threatening_to_call_father", speech="warning", register="colloquial", context="high", flags="idiom_culture|source_ambiguity", cefr="B2", score=64),
    1231: r("The speaker teases their sister Chahinaz for being good at nothing, neither cooking nor cleaning, and recalls her mocking the speaker after finding them cleaning the house with a face-cleaning tissue. The speaker adds that they eat a lot and only bother their mother, with the final joke partly opaque.", "화자는 여동생 샤히나즈가 요리도 청소도 못하고 아무것도 잘하는 게 없다고 놀려요. 얼굴 닦는 티슈로 집을 청소하던 자신을 보고 샤히나즈가 놀렸던 일을 떠올리며, 자신은 많이 먹고 어머니만 건드린다고 농담해요.", "family_relationships", "teasing_a_sister_about_housework", genre="joke", speech="narration", register="colloquial", context="high", flags="idiom_culture|long_source|source_ambiguity", cefr="C1", score=86),
    1232: r("The speaker asks whether the others are having breakfast and jokes that someone thinks she is in a restaurant, accusing them of bothering God's people during breakfast.", "화자는 일행이 아침을 먹고 있는지 묻고, 누군가 자신을 식당에 있는 줄 아느냐고 농담하며 아침 식사 시간에 사람들을 괴롭힌다고 말해요.", "food", "teasing_about_breakfast", genre="joke", speech="question", register="colloquial", context="high", flags="idiom_culture|source_ambiguity", cefr="B1", score=48),
    1233: r("The speaker asks for bread with tomatoes, says they would die there without it, mentions a television series starting at two and taking a nap while watching it, then asks for a phone to connect for a while.", "화자는 토마토를 곁들인 빵을 조금 달라고 하며 그것이 없으면 여기서 죽겠다고 과장해요. 두 시에 시작하는 드라마를 보며 낮잠을 자겠다고 하고, 잠깐 연결할 수 있게 휴대전화를 빌려 달라고 해요.", "food", "asking_for_food_and_phone_access", genre="conversation", speech="request", register="colloquial", context="high", flags="code_switching|idiom_culture|long_source|source_ambiguity", cefr="C1", score=78),
    1234: r("The speaker concludes that the listener has tricked them by asking for a phone to connect.", "화자는 상대가 휴대전화를 빌려 연결하게 해 달라고 한 자신을 속였다고 말해요.", "humor", "joking_about_being_tricked_for_a_phone", genre="joke", speech="opinion", register="colloquial", context="medium", flags="source_ambiguity", cefr="A2", score=30),
    1235: r("The speaker asks what they are entitled to do, complains that the others brought them there to kill them with humiliation, asks whether the place is their home or the others' home, and says the listener wants to drive them crazy.", "화자는 자신이 무엇을 할 권리가 있는지 묻고, 일행이 자신을 창피하게 만들어 죽이려고 데려왔다고 불평해요. 여기가 자기 집인지 상대 집인지 되묻고, 자신을 미치게 하려는 것이냐고 말해요.", "family_relationships", "complaining_about_being_embarrassed", genre="joke", speech="complaint", register="colloquial", context="high", flags="idiom_culture|source_ambiguity", cefr="B2", score=64),
    1236: r("The speaker asks the listener not to betray their friend and to accompany them for a little while, promising not to forget the favor.", "화자는 상대에게 자신의 친구를 배신하지 말고 잠시 동행해 달라고 부탁하며 그 은혜를 잊지 않겠다고 해요.", "family_relationships", "asking_for_companionship", speech="request", register="colloquial", context="medium", flags="source_ambiguity", state="draft", cefr="A2", score=28),
    1237: r("The speaker asks where a woman is going every day while going out dressed up, tells her to come look at the speaker, says the speaker is not a mirror, and jokes that she should put on a mirror so people will not say she has none at home.", "화자는 여성이 매일 치장하고 어디로 나가는지 묻고 자신에게 와서 보라고 해요. 자신은 거울이 아니라고 하며, 집에 거울이 없다는 말을 듣지 않으려면 거울을 하나 두라고 농담해요.", "family_relationships", "teasing_someone_about_mirrors_and_appearance", genre="joke", speech="warning", register="colloquial", context="high", flags="idiom_culture|source_ambiguity", cefr="B2", score=68),
    1238: r("The speaker says Aicha has arrived and is teasing them, says a brother has gone to the army and someone is wearing tight clothes, asks whose trousers they are, and continues humorous comments about cheeks, Pikachu, marriage, and men of the last age.", "화자는 아이샤가 와서 자신을 놀린다고 하고, 형제가 군대에 갔으며 누군가 꽉 끼는 옷을 입었다고 말해요. 그 바지가 누구 것인지 묻고 볼과 피카츄, 결혼, 요즘 남자들에 관한 과장된 농담을 이어 가요.", "family_relationships", "teasing_family_members_about_clothes", genre="joke", speech="exclamation", register="colloquial", context="high", flags="idiom_culture|source_ambiguity|long_source", cefr="C1", score=86),
    1239: r("The speaker complains about a smell and asks what it is, then jokes that the other person has only two hairs and is combing those hairs for the speaker.", "화자는 냄새가 난다고 불평하며 무슨 냄새냐고 묻고, 상대에게 머리카락이 두 가닥뿐인데 그것을 자신에게 빗어 주고 있다고 농담해요.", "family_relationships", "teasing_about_smell_and_hair", genre="joke", speech="complaint", register="colloquial", context="high", flags="idiom_culture|source_ambiguity", cefr="B1", score=54),
    1240: r("The speaker greets someone and asks how she is, says they are coming and will not stay long, comments on a seemingly kind girl who may have been cursed, criticizes the colors she mixed as a rainbow, and jokes that the speaker's face is all she needs to find a man.", "화자는 인사를 건네고 상대가 잘 지내는지 물으며 오래 머물지 않겠다고 해요. 착해 보이지만 불운한 일을 당한 듯한 여성을 언급하고, 섞어 입은 색이 무지개 같다며 놀리고, 남자를 찾으려면 자신의 얼굴만 보면 된다고 농담해요.", "family_relationships", "teasing_about_colors_and_appearance", genre="joke", speech="description", register="colloquial", context="high", flags="idiom_culture|long_source|source_ambiguity", cefr="C1", score=82),
    1241: r("The speaker invokes a religious phrase, says the listener has driven them crazy, and mocks the makeup on the listener's face as if all the household coffee and turmeric had been used up.", "화자는 종교적 감탄 표현을 하고 상대가 자신을 미치게 했다고 말해요. 상대 얼굴의 화장을 집에 있는 커피와 강황을 다 쓴 것처럼 놀려요.", "family_relationships", "teasing_heavy_face_makeup", genre="joke", speech="exclamation", register="colloquial", context="high", flags="idiom_culture|source_ambiguity", cefr="B1", score=54),
    1242: r("The speaker jokes that the listener may one day be thrown out of the house, calls her exhausting, and mocks her for putting honey on an already bad-looking face while asking whether people would really pay for that face.", "화자는 언젠가 상대가 집에서 쫓겨날 수 있다고 농담하고, 상대가 사람을 지치게 한다고 말해요. 이미 보기 싫은 얼굴에 꿀을 바른다며 놀리고 누가 그런 얼굴에 돈을 내겠느냐고 과장해요.", "family_relationships", "teasing_someone_about_makeup_and_household_life", genre="joke", speech="warning", register="colloquial", context="high", flags="idiom_culture|source_ambiguity", cefr="B2", score=68),
    1243: r("The speaker tells the listener not to be ashamed, says they have been silent since morning, and complains that the listener makes noise while eating and does not know how to eat quietly.", "화자는 상대에게 부끄러운 줄 알라고 하며 아침부터 참고 있었다고 말해요. 상대가 먹을 때 소리를 내고 조용히 먹을 줄 모른다고 불평해요.", "food", "complaining_about_noisy_eating", genre="joke", speech="complaint", register="colloquial", context="medium", flags="idiom_culture|source_ambiguity", cefr="B1", score=48),
    1244: r("The speaker complains that the soup is too salty and lacks chickpeas, then describes an older woman asking her son to bring a woman who will fill the refrigerator and cook what he wants. The speaker suggests getting nachos from Kadri and sharing them.", "화자는 국물이 너무 짜고 병아리콩도 없다고 불평해요. 이어 한 노인이 아들에게 냉장고를 채우고 원하는 음식을 해 줄 여자를 데려오라고 하는 장면을 말하고, 카드리에게서 나초를 사 와 함께 먹자고 제안해요.", "food", "complaining_about_soup_and_suggesting_nachos", genre="joke", speech="suggestion", register="colloquial", context="high", flags="idiom_culture|long_source|source_ambiguity", cefr="C1", score=82),
    1245: r("The speaker asks why the others are not eating the savory pastries made by Oum Walid.", "화자는 일행이 움 왈리드가 만든 짭짤한 페이스트리를 왜 먹지 않느냐고 물어요.", "food", "asking_about_savory_pastries", speech="question", register="colloquial", context="medium", flags="source_ambiguity", state="draft", cefr="A2", score=24),
    1246: r("A woman says they are full, asks the others to bring the pastries so she can eat them alone, jokes that the others are not worthy of pastries, and tells them to sell the ones underneath.", "한 여성이 모두 배불렀다고 하며 페이스트리를 가져오면 자신이 혼자 먹겠다고 해요. 일행은 페이스트리를 받을 자격이 없다고 농담하고 아래에 있는 것은 팔라고 말해요.", "food", "joking_about_sharing_pastries", genre="joke", speech="answer", register="colloquial", context="high", flags="idiom_culture|source_ambiguity", cefr="B1", score=54),
    1247: r("The speaker says they would be hungry enough to dip bread with the others if they were not dieting, complains that the others made them hungry, and jokes about being gathered at a small table where everyone talks only about games.", "화자는 다이어트 중이 아니라면 일행과 빵을 찍어 먹고 싶을 만큼 배가 고프다고 해요. 일행 때문에 배가 고파졌다고 불평하고, 작은 식탁에 모여 모두 경기 이야기만 한다고 농담해요.", "food", "joking_about_dieting_and_talking_sports", genre="joke", speech="complaint", register="colloquial", context="high", flags="idiom_culture|long_source|source_ambiguity", cefr="B2", score=70),
    1248: r("The speaker says they want something new and different, using an opaque colloquial form for the desired item or activity.", "화자는 어떤 새롭고 다른 것을 원한다고 말하지만, 원하는 대상이나 활동을 가리키는 구어체 표현은 불투명해요.", "daily_life", "requesting_something_new", speech="wish", register="colloquial", context="high", flags="source_ambiguity", cefr="A2", score=24),
    1249: r("The speaker says that after meeting Mohamed, he told them to ask their sister to answer him, and asks whether the two have reconciled yet.", "화자는 무함마드를 만났더니 그가 자신의 누이에게 연락을 받아 달라고 전해 달라고 했다고 말하며, 두 사람이 화해했는지 아직 묻고 있어요.", "family_relationships", "asking_whether_siblings_reconciled", speech="question", register="colloquial", context="medium", flags="source_ambiguity", cefr="A2", score=32),
    1250: r("The speaker says that if women were to come to ask for a marriage proposal, or to propose marriage, something would happen; the sentence is incomplete and context-dependent.", "화자는 여자들이 청혼하러 오면 어떻게 될 것이라고 말하지만, 문장이 완결되지 않아 앞뒤 맥락에 의존해요.", "family_relationships", "incomplete_marriage_proposal_remark", speech="other", register="colloquial", context="high", flags="source_ambiguity|source_corruption", cefr="A2", score=30),
    1251: r("A visitor says the family has been blessed with a visit, thanks an aunt, and says they know why they came; another speaker says that Anis told them about it.", "방문객은 집안에 복이 찾아왔다고 말하며 이모에게 고맙다고 해요. 왜 왔는지 알고 있다고 하고, 다른 화자는 아니스가 그 이야기를 해 주었다고 말해요.", "family_relationships", "family_visit_and_marriage_context", speech="greeting", register="colloquial", context="high", flags="idiom_culture|source_ambiguity", cefr="B1", score=46),
    1252: r("A woman says she had not planned to marry until finishing her studies, but marriage is written for her and she does not want to let it go. An older woman says the prospective groom has prepared much of the household and only the equipment remains.", "한 여성은 공부를 마칠 때까지 결혼할 생각이 없었지만 운명으로 정해진 결혼을 놓치고 싶지 않다고 해요. 나이 든 여성은 예비 신랑이 집안 준비를 많이 끝냈고 이제 살림살이만 남았다고 말해요.", "family_relationships", "discussing_a_marriage_arrangement", genre="conversation", speech="narration", register="colloquial", context="high", flags="idiom_culture|long_source|source_ambiguity", cefr="C1", score=86),
    1253: r("A woman says her daughter told her the prospective groom is good, blesses him, and asks where their peacock is so they can bring him to see it; she is teased about talking and spinning yarn.", "한 여성은 딸이 예비 신랑이 괜찮다고 말했다며 축복하고, 자신들의 공작이 어디 있는지 물어 데려와 보여 달라고 해요. 말이 많고 이야기를 지어낸다고 놀림받아요.", "family_relationships", "welcoming_a_prospective_groom", speech="information", register="colloquial", context="high", flags="idiom_culture|source_ambiguity", cefr="B1", score=54),
    1254: r("The speaker asks someone to call him to visit, wonders whether he is shy, greets him, and compliments him as handsome while joking that the woman knows how to choose an extraordinary man.", "화자는 그에게 와서 자신들을 만나 보라고 부르라고 하며 그가 수줍어하는지 묻고 인사해요. 그가 잘생겼다고 칭찬하며 여성이 특별한 남자를 고를 줄 안다고 농담해요.", "family_relationships", "greeting_and_complimenting_a_prospective_groom", speech="greeting", register="colloquial", context="high", flags="idiom_culture|source_ambiguity", cefr="B1", score=60),
    1255: r("The speaker says there is only a little time or only a small amount, then tells someone to go to her room after they have been seen. They say that the guest is enjoying the gathering and should not be disturbed.", "화자는 시간이나 양이 얼마 남지 않았다고 말한 뒤, 누군가에게 사람들이 보았으니 방으로 가라고 해요. 손님이 모임을 즐기고 있으니 방해하지 말라고 말해요.", "family_relationships", "managing_a_family_gathering", speech="command", register="colloquial", context="high", flags="source_ambiguity", cefr="B1", score=48),
    1256: r("The speaker says that what matters in the end is that the boy is willing or suitable.", "화자는 결국 중요한 것은 그 남자가 괜찮고 받아들일 만하다는 점이라고 말해요.", "family_relationships", "approving_a_marriage_candidate", speech="opinion", register="colloquial", context="medium", flags="source_ambiguity", state="draft", cefr="A2", score=22),
    1257: r("The speaker says they came merely to place a hand on the young man's shoulder and hopes that God will write a good future for them. They will bring him a ring as a token, ask whether he is happy, and ask others to care for him.", "화자는 젊은 남자에게 손을 얹어 인사를 나누러 왔고 하나님이 두 사람의 앞날을 좋게 써 주기를 바란다고 해요. 약속의 표시로 반지를 가져오겠다고 하고, 그가 기쁜지 묻고 잘 돌봐 달라고 부탁해요.", "family_relationships", "formalizing_a_marriage_arrangement", speech="wish", register="colloquial", context="high", flags="idiom_culture|source_ambiguity", cefr="B2", score=68),
    1258: r("The speaker suggests that the members of their household or family should play a match together.", "화자는 집안 사람이나 가족끼리 함께 경기를 하자고 제안해요.", "sports", "suggesting_a_family_match", speech="suggestion", register="colloquial", context="low", flags="", state="draft", cefr="A1", score=12),
    1259: r("The speaker jokes that the opposing team will not beat everyone, only the wife, then says there are five people on their team. They tell the others that they must score in this goal and joke about whether the listener is their father or they are the listener's father.", "화자는 상대 팀이 모두를 이기는 것이 아니라 아내만 이길 것이라고 농담해요. 자기 팀은 다섯 명이라고 하며 이 골에 득점해야 한다고 말하고, 상대가 자신의 아버지인지 자신이 상대의 아버지인지 농담해요.", "sports", "joking_about_a_family_soccer_team", genre="joke", speech="warning", register="colloquial", context="high", flags="idiom_culture|source_ambiguity", cefr="B2", score=70),
    1260: r("The speaker asks someone to teach them, says they know what they are talking about, and predicts that when the others see their team score, they will say the players do not know how to play.", "화자는 누군가에게 자신을 가르쳐 달라고 하면서 자신이 무슨 말을 하는지 알고 있다고 해요. 자기 팀이 득점하는 것을 보면 사람들이 선수들이 경기할 줄 모른다고 말할 것이라고 해요.", "sports", "defending_a_team_before_a_match", speech="opinion", register="colloquial", context="medium", flags="source_ambiguity", cefr="B1", score=54),
    1261: r("The speaker disagrees, then jokes that it is fortunate the listener was not put in Belmadi's place because the situation would not have worked out.", "화자는 그렇지 않다고 반박한 뒤, 상대가 벨마디의 자리에 놓이지 않은 것이 다행이라고 농담해요. 그렇게 했다면 일이 잘되지 않았을 것이라는 뜻이에요.", "sports", "joking_about_a_coach_role", genre="joke", speech="disagreement", register="colloquial", context="high", flags="idiom_culture|source_ambiguity", cefr="B1", score=48),
    1262: r("The speaker accuses someone of wanting their team to lose so that the speaker's sisters can win, then recalls that this person had invited the speaker to play a match with them.", "화자는 상대가 자신들의 팀을 지게 하고 자기 자매들이 이기게 하려 한다고 비난해요. 그러면서 상대가 예전에 자신에게 함께 경기하자고 했던 일을 떠올려요.", "sports", "accusing_a_relative_of_favoritism", speech="complaint", register="colloquial", context="medium", flags="source_ambiguity", cefr="B1", score=58),
    1263: r("The speaker says their aunt will bring her son Miloud, who wears size 47, and that if he plays the speaker will leave because they are afraid he will hit them.", "화자는 이모가 47 사이즈를 신는 아들 밀루드를 데려올 것이라며, 그가 경기에 나오면 자신을 때릴까 봐 나가겠다고 해요.", "sports", "fearing_a_large_player", genre="joke", speech="warning", register="colloquial", context="medium", flags="idiom_culture|source_ambiguity", cefr="B1", score=54),
    1264: r("The speaker jokingly calls someone a worm and says a blessing or wish invoking God will bring them.", "화자는 누군가를 벌레라고 장난스럽게 부르며 신의 뜻으로 그 사람이 오기를 바란다고 말해요.", "sports", "teasing_a_match_participant", genre="joke", speech="exclamation", register="colloquial", context="high", flags="idiom_culture|source_ambiguity", cefr="A2", score=34),
    1265: r("The speaker says their father made them the goalkeeper, so their cousins are afraid of them. They threaten or tease the cousins, say they will place their children in the corner, and mention a ball that could hit them.", "화자는 아버지가 자신을 골키퍼로 세워 사촌들이 자신을 무서워한다고 말해요. 사촌들을 겁주고 아이들을 구석에 세우겠다고 하며 공이 그들을 맞힐 수 있다고 농담해요.", "sports", "playing_goalkeeper_against_relatives", genre="joke", speech="warning", register="colloquial", context="high", flags="idiom_culture|source_ambiguity", cefr="B2", score=66),
    1266: r("One speaker asks whether the other will play goalkeeper in a traditional robe and says she will play in shorts because she does not want her husband to divorce her. Their father asks the players to divide socks among themselves, and the speaker jokes about making a mess before suggesting fruit yogurt and telling the other to run.", "한 화자는 상대가 전통 의상을 입고 골키퍼를 할 것이냐고 묻고, 자신은 남편이 이혼할까 봐 반바지를 입고 경기하겠다고 해요. 아버지가 경기에서 양말을 나눠 가지라고 하자 엉망으로 만들겠다고 농담하고, 과일 요거트를 제안하며 뛰라고 해요.", "sports", "joking_about_clothes_and_family_soccer", genre="joke", speech="suggestion", register="colloquial", context="high", flags="idiom_culture|long_source|source_ambiguity", cefr="C1", score=86),
    1267: r("The speaker invokes God, says the listener frightened them and must be crazy, asks for a little snuff, and tells them to move away. The other speaker asks for a kiss and is told to go to their mother for one.", "화자는 종교적 감탄 표현을 하며 상대가 자신을 놀라게 했고 미쳤다고 말해요. 코담배를 조금 달라고 하고 가까이 오지 말라고 한 뒤, 상대가 입맞춤을 요구하자 어머니에게 가서 받으라고 해요.", "health", "teasing_about_craziness_and_snuff", genre="joke", speech="exclamation", register="colloquial", context="high", flags="idiom_culture|source_ambiguity", cefr="B1", score=58),
    1268: r("The speaker says their luck is only in the madhouse and asks whether they are at a house for crazy people or mistaken.", "화자는 자신의 운이 정신병원에서만 좋다고 농담하며, 자신이 미친 사람들의 집에 있는지 아니면 잘못 온 것인지 묻어요.", "health", "joking_about_being_in_a_madhouse", genre="joke", speech="question", register="colloquial", context="high", flags="idiom_culture|source_ambiguity", cefr="B1", score=48),
    1269: r("A speaker says a woman is at the psychiatric hospital and asks Madame Djemaa to gather everyone and explain why she is there.", "화자는 한 여성이 정신병원에 있다며 마담 즈므아에게 모두를 모아 왜 그곳에 있는지 설명해 달라고 해요.", "health", "asking_about_a_psychiatric_hospital_visit", speech="request", register="colloquial", context="medium", flags="code_switching|source_ambiguity", cefr="B1", score=54),
    1270: r("The speaker recounts walking peacefully when a beggar approached, demanded money without greeting, and received ten thousand. The beggar then mocked the speaker by saying she was asking the speaker for ten thousand, so the speaker chased her and jokes that if she is ill, the speaker is even more so.", "화자는 평화롭게 걷다가 한 구걸하는 여성이 인사도 없이 돈을 요구해 만을 주었다고 말해요. 그 여성이 오히려 자신에게 만을 요구했다고 비꼬자 쫓아갔고, 여성이 아픈 사람이라면 자신은 더 심하다고 농담해요.", "health", "comic_anecdote_about_a_beggar", genre="narrative", speech="narration", register="colloquial", context="high", flags="idiom_culture|long_source|source_ambiguity", cefr="C1", score=82),
    1271: r("The speaker insults the doctor, says people would pay to look at his face, and recounts that two people brought the speaker along with the woman inside. The speaker insists they are not insane but merely lightly unwell and not a resident of the madhouse.", "화자는 의사의 얼굴을 보려고 사람들이 돈을 낼 것이라고 놀리고, 두 사람이 먼저 가서 자신과 그 여성을 함께 데려갔다고 말해요. 자신은 미친 것이 아니라 조금 가벼운 증상일 뿐이며 정신병원 사람은 아니라고 주장해요.", "health", "denying_insanity_in_a_hospital_story", genre="joke", speech="disagreement", register="colloquial", context="high", flags="idiom_culture|long_source|source_ambiguity", cefr="C1", score=78),
    1272: r("The speaker says that because the woman spoke calmly with the doctor, she must be mentally sound, then says they arrived at the facility and accuses her of lying. The speaker asks what she sees and threatens to do the same thing to her.", "화자는 그 여성이 의사와 차분하게 이야기했으니 정신이 온전하다고 말해요. 시설에 도착한 뒤 여성이 거짓말쟁이라고 하고, 자신을 어떻게 보느냐고 물으며 똑같이 해 주겠다고 위협해요.", "health", "arguing_about_mental_health_at_a_hospital", genre="joke", speech="warning", register="colloquial", context="high", flags="idiom_culture|source_ambiguity", cefr="B2", score=72),
    1273: r("The speaker tells Madame to calm down and says she will stay with them for a few days.", "화자는 마담에게 조금 진정하라고 하며 며칠 동안 자신들과 함께 지내게 될 것이라고 말해요.", "health", "reassuring_someone_in_a_hospital", speech="warning", register="colloquial", context="medium", flags="source_ambiguity", state="draft", cefr="A2", score=26),
    1274: r("The speaker invokes God and complains that people eat very well there. They say they have been kept alone during the break, have not left home or gone to the beach that year, and fear being placed with a violent patient who might slap them.", "화자는 종교적 감탄 표현을 하며 그곳에서는 사람들이 아주 잘 먹는다고 말해요. 휴식 시간에도 혼자 있게 되었고 올해 집 밖이나 해변에 가지 못했으며, 자신을 때릴 수 있는 폭력적인 환자와 함께 두지 말라고 걱정해요.", "health", "complaining_about_hospital_isolation", genre="joke", speech="complaint", register="colloquial", context="high", flags="idiom_culture|long_source|source_ambiguity", cefr="C1", score=82),
    1275: r("The speaker refers to the respectable family going to the beach or swimming.", "화자는 점잖은 가족이 바다에 수영하러 가는 상황을 말해요.", "travel", "family_beach_outing", speech="description", register="colloquial", context="medium", flags="source_ambiguity", state="draft", cefr="A1", score=16),
    1276: r("The speaker asks whether a woman will swim. She says she will not swim, but will prepare peanut cones and take them around at the beach; she jokes that she is not a person but a tree stump and cannot swim.", "화자는 여성이 수영할 것인지 묻고, 여성은 수영하지 않고 땅콩 콘을 준비해 해변을 돌아다니겠다고 해요. 자신은 사람이 아니라 나무 그루터기라서 수영하지 못한다고 농담해요.", "travel", "joking_about_not_swimming_at_the_beach", genre="joke", speech="refusal", register="colloquial", context="high", flags="idiom_culture|source_ambiguity", cefr="B1", score=58),
    1277: r("The speaker comments that the woman is talking with them while keeping her eyes open, implying that she can see or is paying attention.", "화자는 그 여성이 눈을 뜬 채 자신과 이야기하고 있다고 말하며, 보고 있거나 정신을 차리고 있다는 뜻을 암시해요.", "travel", "commenting_on_a_companion_at_the_beach", speech="description", register="colloquial", context="high", flags="source_ambiguity", cefr="A2", score=28),
    1278: r("The speaker says it is time to leave and asks how the woman will swim, offering to twist or float in Bourabah and cry in a way that will help her; the local place or expression is retained without forcing a reading.", "화자는 이제 떠나자고 하며 여성이 어떻게 수영할지 묻고, 부라바에서 몸을 비틀거나 떠 있으면서 울어 도와주겠다고 해요. 지역명이나 표현은 한 가지 의미로 확정하지 않고 보존해요.", "travel", "comic_offer_to_help_with_swimming", genre="joke", speech="suggestion", register="colloquial", context="high", flags="idiom_culture|source_ambiguity", cefr="B2", score=64),
    1279: r("The speaker asks the others to look and listen, says they will remove their veil and gather a judge from Fez who cannot get them up, then tells the others to go to their own beach. They ask not to be given money or cigarettes for a nap and request a 2021 rai recording by Mamidou to enjoy on the road.", "화자는 일행에게 보라고 하며 자신이 머리 스카프를 벗고 자신을 일으킬 수 없는 페스의 판사를 모아 오겠다고 농담해요. 일행은 자기들 해변으로 가라고 하고, 낮잠을 잘 돈이나 담배는 주지 말라고 해요. 길에서 즐기게 마미두의 2021년 라이 음악을 틀어 달라고 해요.", "entertainment_music", "requesting_rai_music_for_a_beach_trip", genre="joke", speech="request", register="colloquial", context="high", flags="code_switching|idiom_culture|long_source|source_ambiguity", cefr="C1", score=86),
    1280: r("The speaker says they have reached the destination and asks for Mamidou to be played in the car, then asks how the listener knows Mamidou, calling him their father in a teasing exchange.", "화자는 목적지에 도착했다고 하며 차에서 마미두의 음악을 틀어 달라고 해요. 이어 상대가 마미두를 어떻게 아느냐고 묻고 그를 자기 아버지라고 부르며 장난스럽게 대화해요.", "entertainment_music", "playing_rai_music_in_a_car", speech="question", register="colloquial", context="high", flags="code_switching|source_ambiguity", cefr="B1", score=54),
}


def build():
    engine.BATCH_ID = BATCH_ID
    engine.BASE_COMMIT = BASE_COMMIT
    engine.PROMPT_VERSION = PROMPT_VERSION
    engine.TARGET_START = TARGET_START
    engine.TARGET_END = TARGET_END
    engine.BATCH_OUT = BATCH_OUT
    engine.MANIFEST_OUT = MANIFEST_OUT
    engine.QA_OUT = QA_OUT
    engine.RAW = RAW
    return engine.build()


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    print(json.dumps(build(), ensure_ascii=False, indent=2))
