"""Build source-only MADOran enrichment Batch 12 for Sentno 705..768."""
from __future__ import annotations

import json
import sys
from pathlib import Path

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts import build_madoran_enrichment_batch10 as engine
from scripts.build_madoran_enrichment_scaffold import ROOT

BATCH_ID = "MADORAN-ENRICH-012"
BASE_COMMIT = "15e0795"
PROMPT_VERSION = "madoran-source-enrichment-v12"
TARGET_START = 705
TARGET_END = 768
BATCH_OUT = ROOT / "data/master/enrichment/batches/batch12_sentno_0705_0768.tsv"
MANIFEST_OUT = ROOT / "data/master/enrichment/batches/batch12_manifest.json"
QA_OUT = ROOT / "data/master/qa/madoran_enrichment_batch12_generation_qa.json"
BATCH_FIELDS = engine.BATCH_FIELDS
item = engine.item


def r(english, korean, domain, topic, genre="conversation", speech="description", register="colloquial", context="high", flags="source_ambiguity", state="flagged", cefr="B2", score=60):
    return item(english, korean, cefr, score, domain, topic, genre, speech, register, context, flags, state)


RAW = {
    705: r("The speakers discuss a problem and try to find a way to deal with it; the pronouns, the reference to a single blow, and who is relieving whom are unclear.", "화자들은 한 가지 문제를 해결할 방법을 찾으려 하지만, 한 번의 타격을 포함한 표현과 누가 누구의 부담을 덜어 주는지는 불분명해요.", "daily_life", "unclear_problem_solving_exchange", "conversation", "opinion"),
    706: r("The speaker asks what the other person is waiting for, calls the situation good news, offers coffee, and asks the person to come along; a final appointment or place reference is unclear.", "화자는 상대에게 무엇을 기다리느냐고 묻고 좋은 소식이라고 하며 커피를 대접하겠다고 함께 가자고 해요. 마지막 약속이나 장소 언급은 불분명해요.", "daily_life", "invitation_and_unclear_appointment", "conversation", "request"),
    707: r("A greeting exchange addresses Hamed and Ibrahim; Marrakech is mentioned in a colloquial, partly unclear comment about what is good or available.", "인사 대화에서 하메드와 이브라힘이 언급돼요. 마라케시와 무엇이 좋거나 가능한지에 대한 구어적이고 일부 불분명한 말이 나와요.", "daily_life", "greeting_and_marrakech_comment", "conversation", "greeting", "mixed", "high", "code_switching|source_ambiguity"),
    708: r("The speaker says that the listener knows the speaker's problem and offers to explain a problem at home so they can talk about it.", "화자는 상대가 자신의 문제를 알고 있다며 집에서의 문제를 설명하고 함께 이야기하겠다고 해요.", "family_relationships", "discussing_a_problem_at_home", "conversation", "request"),
    709: r("Brahim is addressed about a problem. The speaker says an introduction to Si Houari was forgotten, then offers a courteous introduction; exact names and wording remain partly uncertain.", "브라힘에게 문제에 관해 말을 건네고, 시 후아리를 소개하는 것을 잊었다고 한 뒤 정중하게 소개해요. 정확한 이름과 표현은 일부 불분명해요.", "daily_life", "introducing_si_houari_during_a_problem", "conversation", "greeting", "mixed", "high", "source_ambiguity"),
    710: r("A speaker says that a man is tired or ill from work, then describes meeting him by chance on the road and talking about a matter. The place and actors are unclear.", "화자는 한 남자가 일 때문에 지쳤거나 아프다고 말한 뒤, 길에서 우연히 만나 어떤 일에 관해 이야기했다고 해요. 장소와 행위자는 불분명해요.", "work", "chance_meeting_and_work_problem", "narrative", "narration", "mixed", "high", "long_source|source_ambiguity"),
    711: r("The exchange asks about a housing matter and contains repeated, partly unclear words for talk, killing, and a large ‘ghbina’ or loss. It is not resolved as a literal account of violence.", "주거 문제를 묻는 대화에 말하기와 ‘죽이다’, 큰 ‘غبينة’ 또는 손실을 가리키는 반복적이고 불분명한 표현이 나와요. 문자 그대로의 폭력 사건으로 확정하지 않아요.", "housing", "unclear_housing_loss_wordplay", "conversation", "question", "slang", "high", "idiom_culture|source_ambiguity"),
    712: r("The speaker continues along the road and says that the matter has become a big problem; the repeated expression involving ‘killing’ is colloquial and its literal actor and target are unclear.", "화자는 길을 계속 가며 일이 큰 문제가 되었다고 말해요. ‘죽이다’가 들어간 반복 표현은 구어적이고 실제 행위자와 대상은 불분명해요.", "housing", "continuing_an_unclear_big_problem", "conversation", "complaint", "slang", "high", "idiom_culture|source_ambiguity"),
    713: r("Brahim is asked to come to the house for coffee. The speakers say they are coming together so he can explain what his problem is.", "브라힘에게 집으로 와서 커피를 마시자고 해요. 화자들은 그가 자신의 문제가 무엇인지 설명할 수 있도록 함께 가겠다고 말해요.", "daily_life", "inviting_brahim_to_discuss_a_problem", "conversation", "request"),
    714: r("Si Houari says he is troubled by a housing matter: there is housing and rent, but his completed income or payment does not allow him to rent. Brahim says he wants to do good for people.", "시 후아리는 주거 문제로 어려움을 겪고 있다고 말해요. 집과 임대료가 언급되지만 자신의 수입이나 지불 능력으로는 빌릴 수 없어요. 브라힘은 사람들에게 선행을 하고 싶다고 말해요.", "housing", "housing_difficulty_and_helping_others", "conversation", "complaint", "mixed", "high", "long_source|source_ambiguity"),
    715: r("Brahim says he has helped people before and wants to help Si Houari. Si Houari asks where he can live; Brahim says that from tomorrow, God willing, he can live with him and his wife.", "브라힘은 전에 사람들을 도왔고 시 후아리에게도 선행을 하고 싶다고 말해요. 시 후아리는 어디에서 살 수 있는지 묻고, 브라힘은 하느님의 뜻이라면 내일부터 자신과 아내와 함께 살 수 있다고 해요.", "housing", "offering_housing_to_si_houari", "conversation", "suggestion", "mixed", "high", "idiom_culture|source_ambiguity"),
    716: r("The speakers thank Si Houari and Hamed and say they will complete the arrangement at the house tomorrow, God willing.", "화자들은 시 후아리와 하메드에게 감사하고 하느님의 뜻이라면 내일 집에서 그 일을 마무리하겠다고 해요.", "daily_life", "thanks_and_follow_up_at_home", "conversation", "thanks", "mixed", "medium", "idiom_culture|source_ambiguity"),
    717: r("The speakers exchange blessings and say that when good comes it comes for real. Hamed's good deed is remembered, and he is said to be with the speaker.", "화자들은 서로 축복을 빌며 좋은 일이 오면 진짜로 온다고 말해요. 하메드의 선행을 잊지 않는다고 하고, 그가 화자와 함께 있다고 해요.", "daily_life", "blessing_and_remembering_a_good_deed", "conversation", "wish", "mixed", "high", "idiom_culture|source_ambiguity"),
    718: r("A short proverb-like prompt asks what people in the past used to say; the source provides no stable further proposition.", "옛날 사람들이 무엇이라고 말했는지를 묻는 짧은 속담식 도입이에요. 원문만으로 더 구체적인 명제는 확정되지 않아요.", "culture_tradition", "introductory_proverb_prompt", "proverb", "question", "neutral", "high", "", "draft", "A2", 24),
    719: r("The line gives a religious formula for beginning with Bismillah and finishing with Alhamdulillah.", "이 구절은 시작할 때 ‘비스밀라’, 끝낼 때 ‘알함둘릴라’라고 하는 종교적 표현을 말해요.", "religion", "bismillah_and_alhamdulillah_formula", "proverb", "information", "mixed", "medium", "code_switching|source_ambiguity", "draft", "A2", 28),
    720: r("A long admonition gives bodily and social advice about sweating, drinking water, sitting among people, and eating children’s food; the exact idioms and sequence are unclear.", "땀을 흘리는 상태, 물 마시기, 사람들 사이에서의 자세, 아이들 음식을 먹는 일에 관한 신체·사회적 충고가 이어져요. 정확한 관용 표현과 순서는 불분명해요.", "daily_life", "unclear_manners_and_body_advice", "proverb", "warning", "slang", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "C1", 76),
    721: r("The line gives advice about not drinking while standing and about presenting oneself. What is missed through beauty, manner, politics, or money is said to be surpassed by a smile, good conduct, or contentment; some wording is unclear.", "서서 마시지 말고 자신을 단정히 하라는 충고가 나와요. 아름다움·태도·정치·돈으로 얻지 못한 것을 미소와 좋은 태도, 만족으로 넘어선다는 뜻처럼 들리지만 일부 표현은 불분명해요.", "culture_tradition", "proverb_about_manners_and_contentment", "proverb", "opinion", "mixed", "high", "idiom_culture|long_source|source_ambiguity"),
    722: r("A proverb-like passage uses a seven-year-old boy, a mare, an apple, flour, dog wool, a burnous, a large head, and a stomach as comparisons; the exact moral and several referents are unclear.", "속담식 구절에서 일곱 살 소년, 암말, 사과, 밀가루, 개털, 브누스, 큰 머리와 배를 비교 대상으로 사용해요. 정확한 교훈과 여러 지시 대상은 불분명해요.", "culture_tradition", "proverb_with_animal_and_food_comparisons", "proverb", "description", "slang", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "C1", 82),
    723: r("The proverb says that the beauty of a market is its seating, the beauty of a bed is its children, and when speech is not right, its beauty is silence.", "속담은 시장의 아름다움은 자리에 있고, 침대의 아름다움은 아이들에게 있으며, 말이 옳지 않을 때 말의 아름다움은 침묵이라고 해요.", "culture_tradition", "proverb_about_places_family_and_silence", "proverb", "opinion", "neutral", "medium", "idiom_culture|source_ambiguity"),
    724: r("A proverb-like line compares the beauty or quality of fruit, women, and men; the exact words are colloquial and the intended comparison is partly unclear.", "속담식 구절이 과일과 여성, 남성의 아름다움이나 좋은 점을 비교해요. 정확한 단어와 비교의 의도는 일부 불분명해요.", "culture_tradition", "proverb_about_fruit_women_and_men", "proverb", "opinion", "slang", "high", "idiom_culture|source_ambiguity"),
    725: r("If you are unattractive, hide your flaws; if you are beautiful, hide yourself from the evil eye. The line is a proverb about appearance and protection from envy.", "매력이 없으면 결점을 숨기고, 아름다우면 악한 눈으로부터 자신을 숨기라는 말이에요. 외모와 시기를 막는 일을 다루는 속담이에요.", "culture_tradition", "proverb_about_beauty_and_evil_eye", "proverb", "warning", "mixed", "high", "idiom_culture|source_ambiguity"),
    726: r("A chain of proverbial comparisons says that when teeth fall, beauty goes; when eyes go, the world goes; when dignity or men go, honor or the parents go. The exact mapping is partly unclear.", "속담식 비교가 이어져요. 이가 빠지면 아름다움이 가고, 눈이 사라지면 세상이 가며, 존엄이나 남자가 사라지면 명예나 부모가 사라진다는 식이지만 정확한 대응은 일부 불분명해요.", "culture_tradition", "proverb_about_loss_and_dignity", "proverb", "opinion", "mixed", "high", "idiom_culture|source_ambiguity"),
    727: r("The line introduces a saying attributed to people of old; its short wording depends on the surrounding proverbs.", "옛날 사람들이 하던 말이라고 소개하는 짧은 구절이에요. 정확한 뜻은 주변 속담에 의존해요.", "culture_tradition", "old_saying_introduction", "proverb", "information", "neutral", "high", "idiom_culture|source_ambiguity"),
    728: r("A harsh proverb says that a person who cannot slaughter his sheep, control his wife, or perform his prayers has a death better than his life. The gendered social judgments are preserved as source content, not endorsed advice.", "양을 잡지 못하고 아내를 통제하지 못하며 기도도 하지 않는 사람은 삶보다 죽음이 낫다는 거친 속담이에요. 성별에 관한 사회적 판단은 원문 내용으로만 보존하며 조언으로 지지하지 않아요.", "culture_tradition", "harsh_proverb_about_social_roles", "proverb", "warning", "offensive", "high", "idiom_culture|source_ambiguity", "flagged", "C1", 84),
    729: r("Another harsh proverb says that a person who does not know slaughter or a skewer, and marries into another family's daughter, brings disgrace; several food and marriage terms are idiomatic.", "또 다른 거친 속담은 도살이나 꼬치 요리를 모르면서 다른 집 딸과 결혼하면 망신이라는 식으로 말해요. 음식과 결혼 관련 표현은 관용적이고 일부 불분명해요.", "culture_tradition", "harsh_proverb_about_skill_and_marriage", "proverb", "warning", "offensive", "high", "idiom_culture|source_ambiguity"),
    730: r("A related saying connects not knowing how to work, a ‘bouzlouf’ or head dish, and marriage to another family's son with loss; the exact idiomatic terms are unclear.", "이어지는 속담은 일을 할 줄 모르는 것, ‘부즐루프’ 또는 머리 요리, 다른 집 아들과의 결혼을 손실과 연결해요. 정확한 관용어는 불분명해요.", "culture_tradition", "unclear_proverb_about_work_and_marriage", "proverb", "warning", "slang", "high", "idiom_culture|source_ambiguity"),
    731: r("The speaker introduces seven types of Algerian students at university.", "화자는 알제리 대학생의 일곱 가지 유형을 소개해요.", "education", "seven_types_of_algerian_university_students", "expository", "information", "neutral", "low", "source_ambiguity", "flagged", "A2", 28),
    732: r("The first type plays guitar and sits with girls, singing for them; his hair is not combed, and the group around him is described with an unclear social label.", "첫 번째 유형은 기타를 치며 여자들과 앉아 노래해요. 머리는 빗지 않았고, 그 주변 무리는 불분명한 사회적 표현으로 묘사돼요.", "education", "university_student_type_guitar_and_social_group", "expository", "description", "slang", "high", "source_ambiguity"),
    733: r("The second type wants to show off and displays his father's car; he uses grooming products and the line includes an unclear comparison involving girls and shaving or styling.", "두 번째 유형은 과시하려고 아버지의 차를 보여 줘요. 몸단장 제품을 사용하고 여자와 면도나 스타일링을 둘러싼 불분명한 비교가 나와요.", "education", "university_student_type_showing_off", "expository", "description", "slang", "high", "source_ambiguity"),
    734: r("The third category appears in groups of three, controlling a corner and playing cards or dominoes; girls in the same setting tell tragic stories about their lives.", "세 번째 유형은 세 명씩 모여 한쪽을 차지하고 카드나 도미노를 해요. 같은 공간의 여자들은 자기 삶의 비극적인 이야기를 해요.", "education", "university_student_type_games_and_stories", "expository", "description", "colloquial", "high", "source_ambiguity"),
    735: r("The fourth category is always alone: eating alone, studying alone, going alone, and remaining by itself.", "네 번째 유형은 늘 혼자예요. 혼자 먹고, 혼자 공부하고, 혼자 다니며 계속 혼자 있어요.", "education", "university_student_type_alone", "expository", "description", "neutral", "medium", "source_ambiguity"),
    736: r("The fifth group consists of couples who stay together from morning through the afternoon and evening and do not leave each other.", "다섯 번째 무리는 연인들로, 아침부터 오후와 저녁까지 함께 있고 서로 떨어지지 않아요.", "education", "university_student_type_couples", "expository", "description", "colloquial", "medium", "source_ambiguity"),
    737: r("Another type consists of two friends who walk around the university and know it closely; they move separately from one another and do not mix much with other people, though the final labels are unclear.", "또 다른 유형은 대학을 돌아다니며 구석구석 아는 두 친구예요. 서로 따로 움직이고 다른 사람들과 많이 섞이지 않지만 마지막 표현은 불분명해요.", "education", "university_student_type_two_friends", "expository", "description", "colloquial", "high", "source_ambiguity"),
    738: r("The last group sits in threes or fours, watches people coming and going, and spreads talk about who is among them; the social judgment is colloquial.", "마지막 무리는 셋이나 넷씩 앉아 오가는 사람을 지켜보고 누가 그들 사이에 있는지 이야기를 퍼뜨려요. 사회적 평가는 구어적으로 제시돼요.", "education", "university_student_type_observing_and_gossiping", "expository", "description", "slang", "high", "source_ambiguity"),
    739: r("The speaker describes a repeated scenario when a woman meets someone: if she likes him she laughs and shortens the interaction, while other reactions are expressed with unclear slang.", "화자는 여자가 누군가를 만날 때 반복되는 상황을 설명해요. 마음에 들면 웃고 대화를 줄이며, 다른 반응은 불분명한 속어로 표현돼요.", "family_relationships", "unclear_romantic_meeting_scenario", "conversation", "opinion", "slang", "high", "idiom_culture|source_ambiguity"),
    740: r("The speaker imagines becoming a couple and calling the other person repeatedly; the phone calls, crying, and the final romantic expression are partly unclear.", "화자는 연인이 되어 계속 전화를 하는 상황을 상상해요. 전화와 울음, 마지막 로맨틱한 표현은 일부 불분명해요.", "family_relationships", "unclear_phone_romance_scenario", "conversation", "opinion", "colloquial", "high", "source_ambiguity"),
    741: r("The speaker dislikes talking on the phone all night and dislikes being called every minute; when the other person says ‘my love,’ the exchange shifts into unclear romantic or teasing language.", "화자는 밤새 전화로 이야기하는 것을 싫어하고 매분 전화가 오는 것도 싫어해요. 상대가 ‘내 사랑’이라고 말하면 대화가 불분명한 연애 또는 장난 표현으로 바뀌어요.", "family_relationships", "phone_contact_and_romantic_teasing", "conversation", "complaint", "colloquial", "high", "source_ambiguity"),
    742: r("A comparison involving a German shepherd or German item is used for an inner feeling; the speaker mentions a facial mark from 2015 and looking for problems until stopping the person. The metaphor is unresolved.", "독일 셰퍼드나 독일 물건과 관련된 비교로 내면의 감정을 표현해요. 2015년의 얼굴 자국과 그 사람을 멈출 때까지 문제를 찾는다는 말이 나오지만, 비유는 해소되지 않아요.", "family_relationships", "unclear_romantic_metaphor_and_conflict", "conversation", "opinion", "slang", "high", "idiom_culture|source_ambiguity"),
    743: r("The speaker has begun to worry and wonders whether people will be engaged or married in four or five years and whether the speaker is normal; the ending is an unclear admonition.", "화자는 걱정하기 시작했고 4~5년 뒤 사람들이 약혼하거나 결혼할지, 자신이 정상인지 궁금해해요. 마지막 충고는 불분명해요.", "family_relationships", "uncertainty_about_future_marriage", "conversation", "question", "colloquial", "high", "source_ambiguity"),
    744: r("A short phrase names Algerian romance without explaining it further.", "알제리식 로맨스를 가리키는 짧은 구절이며 더 자세한 명제는 원문에 없어요.", "family_relationships", "algerian_romance_label", "other", "description", "neutral", "low", "", "draft", "A1", 18),
    745: r("A short phrase refers to a couple; the source does not specify their situation.", "한 커플을 가리키는 짧은 구절이며 그들의 상황은 원문에 구체적으로 나오지 않아요.", "family_relationships", "couple_label", "other", "description", "neutral", "low", "source_ambiguity", "flagged", "A1", 18),
    746: r("The speaker asks why the other person does not hold the speaker's hand when they walk outside.", "화자는 왜 밖을 걸을 때 상대가 자신의 손을 잡지 않느냐고 물어요.", "family_relationships", "asking_to_hold_hands_in_public", "conversation", "question", "colloquial", "medium", "source_ambiguity"),
    747: r("The speaker fears that someone who knows the couple will see them and cause trouble. If the speaker proposes, the other person will hold the speaker's hand, and no one will ask them about it.", "화자는 두 사람을 아는 누군가가 둘을 보고 문제를 일으킬까 봐 걱정해요. 화자가 청혼하면 상대가 손을 잡을 것이고 아무도 둘에게 묻지 않을 거라고 말해요.", "family_relationships", "fear_of_being_seen_before_proposal", "conversation", "opinion", "colloquial", "high", "source_ambiguity"),
    748: r("When someone comes to propose, the speaker says to ask what the woman wants and what she is looking for; after marriage, he will hold her hand as she wishes.", "누군가 청혼하러 오면 여성이 무엇을 원하고 무엇을 찾는지 물어보라고 해요. 결혼한 뒤에는 그녀가 원하는 대로 손을 잡아 주겠다고 해요.", "family_relationships", "proposal_questions_and_holding_hands", "conversation", "suggestion", "colloquial", "high", "source_ambiguity"),
    749: r("When they marry, ask whether they have a home and furniture; the answer says, thank God, they have them and can do what they want there.", "결혼할 때 집과 가구가 있는지 물어보면, 하느님께 감사하게도 그것들이 있고 그 안에서 원하는 일을 할 수 있다고 답해요.", "family_relationships", "home_and_furniture_after_marriage", "conversation", "information", "colloquial", "medium", "idiom_culture|source_ambiguity"),
    750: r("The speaker asks why, now that they are married, the other person still does not hold the speaker's hand.", "화자는 이제 결혼했는데도 왜 상대가 여전히 자신의 손을 잡지 않느냐고 물어요.", "family_relationships", "holding_hands_after_marriage", "conversation", "question", "colloquial", "medium", "source_ambiguity"),
    751: r("The line plays with whom the speaker should hold—possibly the other person, her daughter, or an unclear matter. The pronouns and object are unresolved.", "화자가 누구의 손을 잡아야 하는지, 상대인지 그 딸인지 또는 다른 일인지 장난스럽게 말해요. 대명사와 대상은 불분명해요.", "family_relationships", "unclear_holding_hands_wordplay", "joke", "question", "slang", "high", "source_ambiguity"),
    752: r("A marriage-age exchange mentions twenty-five years and asks what kind of man is wanted for a daughter; the answer says people grow old and become worn out. The exact age relation is unclear.", "결혼 나이와 관련해 25년이 언급되고 딸에게 어떤 남자를 원하는지 물어요. 사람은 나이가 들고 쇠약해진다는 답이 나오지만 정확한 나이 관계는 불분명해요.", "family_relationships", "marriage_age_and_choosing_a_man", "conversation", "question", "colloquial", "high", "source_ambiguity"),
    753: r("A parallel exchange mentions fifty years of marriage and asks why the speaker is still not being held by the hand; the woman is described as pitiful, but the exact framing is unclear.", "이어지는 대화에서 결혼 50년이 언급되고 왜 아직 손을 잡아 주지 않느냐고 물어요. 여성이 안쓰럽게 묘사되지만 정확한 구도는 불분명해요.", "family_relationships", "long_marriage_and_affectionate_teasing", "conversation", "complaint", "colloquial", "high", "source_ambiguity"),
    754: r("The speaker says he wants to hold her hand, leave his grenade, die, and have her inherit him; the imagery is hyperbolic romantic or comic speech, not a verified violent plan. The later reference to love in Algeria is unclear.", "화자는 그녀의 손을 잡고 자신의 수류탄을 두고 죽어 그녀가 자신을 상속받게 하고 싶다고 말해요. 과장된 로맨틱 또는 코미디성 표현이며 실제 폭력 계획으로 확정하지 않아요. 뒤의 알제리 사랑 언급은 불분명해요.", "family_relationships", "hyperbolic_romantic_grenade_metaphor", "joke", "opinion", "vulgar", "high", "idiom_culture|source_ambiguity"),
    755: r("The speaker tells a story about a brother: he woke normally, his mother came in the evening, and he said he wanted to marry and asked her to propose to him; she answered ‘okay.’", "화자는 한 형제의 이야기를 해요. 그는 평소처럼 일어났고 저녁에 어머니가 왔으며, 결혼하고 싶으니 자신에게 청혼해 달라고 말했고 어머니는 ‘알겠어’라고 답했어요.", "family_relationships", "brother_and_mothers_marriage_discussion", "narrative", "narration", "colloquial", "high", "source_ambiguity"),
    756: r("The brother says he wants the mother to propose to a female friend. The mother asks how a woman who normally comes to the house can come with him to look for marriage; the exact family roles are partly unclear.", "그 형제는 어머니가 자신의 여자 친구에게 청혼해 주길 원한다고 말해요. 어머니는 평소 집에 오는 여성이 어떻게 그와 함께 결혼 상대를 찾으러 올 수 있느냐고 묻지만, 정확한 가족 역할은 일부 불분명해요.", "family_relationships", "mother_questioning_a_marriage_proposal", "conversation", "question", "colloquial", "high", "source_ambiguity"),
    757: r("The mother agrees, then the brother asks to be left alone and proposes bringing a woman who already has a lover. He fears that she would cry for her lover and deceive him, and says he would rather take the beloved woman he knows and raised; the actors and joke framing are unclear.", "어머니가 동의한 뒤 형제는 자신을 내버려 두라고 하며 이미 애인이 있는 여자를 데려오자는 말을 해요. 그녀가 애인을 그리워해 울고 자신을 속일까 봐 걱정하며, 자신이 알고 키운 사랑하는 여자를 데려가고 싶다고 말해요. 행위자와 농담의 구도는 불분명해요.", "family_relationships", "unclear_marriage_proposal_and_existing_lover", "conversation", "opinion", "colloquial", "high", "long_source|source_ambiguity"),
    758: r("The speaker says that today's topic is a brother and that some women are not deserving or remain in the street; another man jumps from one woman's sister to another. The insults and relationships are unclear and are preserved as colloquial banter.", "오늘의 주제는 한 형제이며, 어떤 여자들은 자격이 없고 늘 거리에 있다는 거친 말이 나와요. 또 다른 남자가 한 여자의 자매에서 다른 여자로 옮겨 간다는 말도 나와요. 욕설과 관계는 불분명한 구어적 말싸움으로 보존해요.", "family_relationships", "unclear_banter_about_women_and_relationships", "joke", "opinion", "offensive", "high", "idiom_culture|source_ambiguity"),
    759: r("The speaker wants only the woman he has seen before and comments on manhood, asking God to bring a lawful or respectable boy; the exact social and romantic targets are unclear.", "화자는 자신이 전에 본 그 여자만을 원하고 남자다움에 대해 말해요. 하느님이 올바르거나 좋은 남자를 보내 주시길 빈다고 하지만 정확한 사회적·연애 대상은 불분명해요.", "family_relationships", "unclear_manhood_and_marriage_wish", "conversation", "wish", "colloquial", "high", "idiom_culture|source_ambiguity"),
    760: r("An Oran woman is described as gentle and sensitive, keeping her house clean, planting flowers, and preparing hrira, bourek, and ma‘qouda.", "오랑 여자는 다정하고 섬세하며 집을 늘 깨끗하게 하고 꽃을 심고 하리라, 부레크, 마‘쿠다를 준비한다고 묘사돼요.", "food", "oran_woman_and_home_cooking", "conversation", "description", "colloquial", "high", "idiom_culture|source_ambiguity"),
    761: r("The description continues with tajine of olives and other dishes, a kitchen apron, a forehead scarf, and an unclear expression that says she captures the speaker's heart.", "올리브 타진과 다른 음식, 주방 앞치마, 이마에 두르는 천이 이어지고 그녀가 화자의 마음을 사로잡는다는 불분명한 표현이 나와요.", "food", "oran_woman_cooking_and_affection", "conversation", "description", "colloquial", "high", "idiom_culture|source_ambiguity"),
    762: r("She makes an almond drink for tea, adds food with raisins, and prepares soup or broth at breakfast; the speaker says this is how a proper man is treated, though some dishes are unclear.", "그녀는 차와 함께 마실 아몬드 음료를 만들고 건포도를 넣은 음식을 더하며 아침에 수프나 국물을 준비해요. 몇몇 음식은 불분명하지만 이런 대접이 남자를 만족시킨다고 말해요.", "food", "home_cooking_and_hospitality", "conversation", "description", "colloquial", "high", "idiom_culture|source_ambiguity"),
    763: r("The speaker calls her his heart and praises her work, bread, pastries, and hot griddle; every finger is said to make a different dish, in an affectionate exaggeration.", "화자는 그녀를 자신의 마음이라고 부르며 빵과 과자, 뜨거운 철판 요리를 칭찬해요. 손가락마다 다른 음식을 만든다는 애정 어린 과장이 나와요.", "food", "affectionate_praise_of_home_cooking", "joke", "opinion", "colloquial", "high", "idiom_culture|source_ambiguity"),
    764: r("When Eid arrives, she fills the speaker with sweets including baklava, griwech, makrout, msemen, tournos, and other pastries; the final praise of an Oran woman is partly unclear.", "이드가 오면 그녀는 바클라바, 그리우시, 마크루드, 므세멘, 투르누와 다른 과자로 화자를 배부르게 해요. 오랑 여자를 칭찬하는 마지막 표현은 일부 불분명해요.", "food", "eid_sweets_and_oran_woman", "conversation", "description", "colloquial", "high", "idiom_culture|source_ambiguity"),
    765: r("A short exclamation asks what is wrong with Oran; the emotional force is preserved without resolving the exact implied complaint.", "오랑에 무슨 일이냐고 묻는 짧은 감탄·질문이에요. 정확히 무엇을 불평하는지는 확정하지 않아요.", "history", "emotional_question_about_oran", "conversation", "question", "colloquial", "medium", "source_ambiguity", "flagged", "A2", 24),
    766: r("The speaker says that Oran's children grew up in the outskirts, moved through the neighborhoods, and came to live in apartments.", "화자는 오랑의 아이들이 외곽에서 자라 동네로 옮겨 다니다가 아파트에 살게 되었다고 말해요.", "history", "oran_children_and_moving_to_apartments", "narrative", "narration", "colloquial", "medium", "source_ambiguity"),
    767: r("Oran is addressed as changing over time; its children built a new neighborhood and named it El Aqid, though the exact historical reference is not fully resolved.", "오랑은 시간이 지나며 변한 곳으로 불리고, 그곳의 아이들이 새 동네를 지어 엘 아키드라고 이름 붙였다고 해요. 정확한 역사적 지칭은 완전히 확정되지 않아요.", "history", "oran_neighborhood_history_el_aqid", "narrative", "information", "mixed", "high", "source_ambiguity"),
    768: r("People who came from far away were housed, while Oran's children lived in iron shacks. The line exclaims about Oran, mentions a visitor taking a picture with a lion, and welcomes the guest in winter and summer; several images are unclear.", "먼 곳에서 온 사람들이 집을 얻고 오랑의 아이들은 철제 판잣집에 살았다고 해요. 오랑을 외치며 방문객이 사자와 사진을 찍는 장면과 겨울·여름에 손님을 환영하는 말이 나오지만 여러 이미지는 불분명해요.", "history", "oran_housing_history_and_guest_welcome", "narrative", "information", "mixed", "high", "long_source|source_ambiguity"),
}


def build():
    engine.BATCH_ID = BATCH_ID
    engine.BASE_COMMIT = BASE_COMMIT
    engine.PROMPT_VERSION = PROMPT_VERSION
    engine.TARGET_START = TARGET_START
    engine.TARGET_END = TARGET_END
    engine.BATCH_OUT = BATCH_OUT
    engine.MANIFEST_OUT = MANIFEST_OUT
    engine.QA_OUT = QA_OUT
    engine.RAW = RAW
    return engine.build()


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    print(json.dumps(build(), ensure_ascii=False, indent=2))
