"""Build source-only MADOran enrichment Batch 21 for Sentno 1281..1344."""
from __future__ import annotations

import json
import sys
from pathlib import Path

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts import build_madoran_enrichment_batch10 as engine
from scripts.build_madoran_enrichment_scaffold import ROOT

BATCH_ID = "MADORAN-ENRICH-021"
BASE_COMMIT = "09efe99"
PROMPT_VERSION = "madoran-source-enrichment-v21"
TARGET_START = 1281
TARGET_END = 1344
BATCH_OUT = ROOT / "data/master/enrichment/batches/batch21_sentno_1281_1344.tsv"
MANIFEST_OUT = ROOT / "data/master/enrichment/batches/batch21_manifest.json"
QA_OUT = ROOT / "data/master/qa/madoran_enrichment_batch21_generation_qa.json"


def r(english, korean, domain, topic, genre="conversation", speech="description",
      register="colloquial", context="high", flags="source_ambiguity",
      state="flagged", cefr="B2", score=60):
    normalized_flags = "|".join(sorted(filter(None, flags.split("|"))))
    return engine.item(english, korean, cefr, score, domain, topic, genre, speech, register, context, normalized_flags, state)


RAW = {
    1281: r("The speaker says people are ordering restaurant food and eating before going to the sea, while the speaker is cleaning potatoes and peppers and has found a watermelon. The speaker complains about this life.", "화자는 사람들이 식당 음식을 시켜 바다에 가기 전에 먹는 동안 자신은 감자와 피망을 손질하고 수박까지 찾았다고 말하며 이런 삶을 불평해요.", "food", "complaining_about_preparing_food_before_the_sea", "conversation", "complaint", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "C1", 82),
    1282: r("The speaker asks how they could not go to the sea, says they are going anyway, and tells the listener to hit their head against the wall; some names and turns are opaque.", "화자는 어떻게 바다에 가지 않을 수 있겠느냐고 하며 자신은 갈 거라고 말하고, 상대에게 머리를 벽에 부딪히라고 해요. 일부 이름과 turn은 불투명해요.", "travel", "arguing_about_going_to_the_sea", "conversation", "complaint", "colloquial", "high", "idiom_culture|source_ambiguity", "flagged", "B2", 70),
    1283: r("The speaker refers to the woman who is still arguing with the taxis; the exact scene is kept source-close.", "화자는 아직도 택시들과 다투고 있는 여성을 말해요. 정확한 장면은 원문에 가깝게 보존해요.", "travel", "arguing_with_taxis", "conversation", "description", "colloquial", "high", "source_ambiguity", "flagged", "A2", 30),
    1284: r("The speaker says that if the listener had helped them, they would have gone farther, and mentions playing the opaque game or activity ‘hwayza’.", "화자는 상대가 도와줬다면 더 멀리 갔을 거라고 말하고, 불투명한 놀이 또는 활동인 ‘hwayza’를 언급해요.", "travel", "joking_about_help_and_an_opaque_game", "joke", "description", "colloquial", "high", "idiom_culture|source_ambiguity", "flagged", "B1", 48),
    1285: r("The speaker says finishing it would be better, asks where the sister is going, hears that she is going home, and says they do not know the family’s house; the opening surface is opaque.", "화자는 그것을 끝내는 편이 낫다고 말하고 누이가 어디로 가는지 물어요. 누이가 집에 간다고 하자 그 집을 모른다고 말하며, 초두 표면은 불투명하게 보존해요.", "daily_life", "asking_where_a_sister_is_going", "conversation", "question", "colloquial", "high", "source_ambiguity", "flagged", "B1", 48),
    1286: r("The speaker tells the brother not to eat the speaker and says that the husband is acting against or jealous of the speaker; the comic wording is source-close.", "화자는 형제에게 자신을 먹지 말라고 하며 남편이 자신에게 화를 내거나 질투한다고 말해요. 코믹한 표현은 원문에 가깝게 보존해요.", "family_relationships", "joking_about_a_husbands_reaction", "joke", "complaint", "colloquial", "high", "idiom_culture|source_ambiguity", "flagged", "B1", 50),
    1287: r("The speaker asks to be left at Dar Dou and teases the listener for not knowing Dar Dou, saying that this shows the listener is not from the area.", "화자는 다르 두에 내려 달라고 하며 상대가 다르 두를 모른다고 놀리고, 그것을 보니 상대가 이 지역 출신이 아니라고 말해요.", "travel", "asking_to_be_dropped_at_a_place", "conversation", "request", "colloquial", "high", "idiom_culture|source_ambiguity", "flagged", "B1", 52),
    1288: r("The speaker says ‘Astaghfirullah’, asks why the listener is dragging them around, tells them to take a main road, and complains that people have no safety. A second exchange asks where the sister is going, rejects the idea that a woman came along, mentions illness, and ends with an opaque instruction about a ‘baft’.", "화자는 ‘아스타그피룰라’라고 말하고 왜 자신을 끌고 다니느냐고 물으며 큰길로 가라고 해요. 사람들이 안전하지 않다고 불평한 뒤, 누이가 어디로 가는지 묻고 여성이 함께 오지 않았다고 하며 아픈 상황을 말하고 불투명한 ‘baft’ 지시로 끝나요.", "travel", "arguing_about_a_chaotic_journey", "conversation", "complaint", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "C1", 84),
    1289: r("The speaker says the matter is over the sister’s head, asks to be left there, gives thanks, invokes protection, and jokes that the others have learned to bargain over money before taking it to the countryside; several surfaces are opaque.", "화자는 일이 누이의 머리 위에 있다고 말하고 그곳에 내려 달라고 해요. 감사와 보호를 말한 뒤 사람들이 돈을 흥정하는 법을 배웠다고 농담하고 그것을 시골로 가져간다고 해요. 여러 표면은 불투명해요.", "daily_life", "joking_about_money_and_leaving_somewhere", "joke", "narration", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "C1", 82),
    1290: r("The line refers to entering prison with a friend; it is an incomplete, context-dependent remark.", "친구와 함께 감옥에 들어가는 상황을 말하는 불완전하고 맥락 의존적인 발화예요.", "crime_safety", "entering_prison_with_a_friend", "conversation", "description", "colloquial", "high", "source_ambiguity|source_corruption", "flagged", "A2", 30),
    1291: r("The speaker tells the others to be quiet, says they are hungry and asks for mbses in a bag, then complains about the person addressed and recalls bringing Bousbaa to measure it with them in the river. The food and personal-name surfaces are kept conservatively.", "화자는 일행에게 조용히 하라고 하고 배가 고프다며 봉지에 담은 ‘mbses’를 달라고 해요. 상대를 불평하고 부스바를 데려와 강에서 함께 재 보라고 했던 일을 떠올리며 음식과 이름 표면을 보수적으로 보존해요.", "food", "asking_for_food_and_recalling_a_river_scene", "joke", "complaint", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "C1", 86),
    1292: r("The speaker tells the other person to shut their mouth, says they would not be here without being sent to Jijel, and separates responsibility for killing someone from the help given to measure him in the river.", "화자는 상대에게 입을 다물라고 하며 지젤로 보내지지 않았다면 여기 없었을 거라고 말해요. 누군가를 죽인 책임과 강에서 그를 재도록 도운 일을 구분해 말해요.", "crime_safety", "arguing_about_responsibility_and_a_river", "conversation", "disagreement", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "C1", 84),
    1293: r("The speaker wants to enter alone but asks the other person to accompany and entertain them. They fear being killed in prison or by their brother when he gets out; the names and slang remain source-close.", "화자는 혼자 들어가고 싶지만 상대에게 동행해 잠시 즐겁게 해 달라고 해요. 감옥에서 죽거나 형제가 출소한 날 자신을 죽일까 봐 두려워하며 이름과 속어는 원문에 가깝게 남겨요.", "crime_safety", "fearing_prison_and_a_brothers_reaction", "conversation", "request", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "C1", 86),
    1294: r("The speaker says the listeners exhausted them in two minutes, calls to the sister, and asks her to stitch or close the speaker’s mouth so the speaker will not fight with the friend; the surface is partly opaque.", "화자는 일행이 2분 만에 자신을 지치게 했다고 하고 누이를 부르며, 친구와 다투지 않도록 자신의 입을 꿰매거나 닫아 달라고 해요. 일부 표면은 불투명해요.", "family_relationships", "joking_about_talking_and_fighting", "joke", "complaint", "colloquial", "high", "idiom_culture|source_ambiguity", "flagged", "B2", 68),
    1295: r("The speaker asks whether the listener knows where she is, tells someone to fly away from a named person, and says that whoever wants blood should come. The line then praises a named woman and her hair; names and slang are retained.", "화자는 상대가 자신이 어디에 있는지 아느냐고 묻고 누군가에게 특정 인물에게서 날아가라고 해요. 피를 원하는 사람은 오라고 한 뒤 이름이 있는 여성을 칭찬하고 머리카락을 언급하며 이름과 속어를 보존해요.", "family_relationships", "teasing_about_a_named_woman", "joke", "exclamation", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "C1", 82),
    1296: r("The speaker describes the woman who works at the town hall when she enters her home; it is a short incomplete comparison.", "화자가 시청에서 일하는 여성이 집에 들어갈 때를 묘사하는 짧고 불완전한 비교예요.", "work", "describing_a_worker_at_home", "conversation", "description", "colloquial", "high", "source_ambiguity", "flagged", "A2", 28),
    1297: r("The speaker warns the mother not to fall and calls someone a donkey, says their head is about to burst, and threatens to knock one of them out later; the comic threats are retained without literal escalation.", "화자는 엄마에게 넘어지지 말라고 하고 누군가를 당나귀라고 부르며 머리가 터질 것 같다고 해요. 나중에 일행 중 한 명을 쓰러뜨리겠다고 농담해요.", "family_relationships", "comic_threats_in_a_family_scene", "joke", "warning", "colloquial", "high", "idiom_culture|source_ambiguity", "flagged", "B2", 64),
    1298: r("The speaker asks their mother whether they can go with Aymen to the stadium, says they are drinking coffee with a service chief, and answers that the companion is their father.", "화자는 엄마에게 아이만과 경기장에 가도 되는지 묻고 서비스 책임자와 커피를 마신다고 해요. 누구와 함께냐는 질문에는 아버지와 함께라고 답해요.", "sports", "asking_to_go_to_a_stadium", "conversation", "question", "colloquial", "medium", "code_switching|source_ambiguity", "flagged", "B1", 52),
    1299: r("The speaker says the listener has been sulky all year and that Aymen’s mother was right to say the listener had not laughed for a long time; the exact time expression is opaque.", "화자는 상대가 일 년 내내 시무룩했다고 하고, 아이만의 어머니가 상대가 오랫동안 웃지 않았다고 한 말이 맞았다고 해요. 정확한 시간 표현은 불투명해요.", "family_relationships", "teasing_someone_for_not_laughing", "joke", "complaint", "colloquial", "high", "idiom_culture|source_ambiguity", "flagged", "B1", 54),
    1300: r("The speaker tells someone to go watch the husband who came today to propose marriage, then jokes that the woman has come to watch the speaker instead.", "화자는 오늘 청혼하러 온 남편을 지켜보러 가라고 하고, 그 여성이 오히려 자신을 지켜보러 왔다고 농담해요.", "family_relationships", "teasing_about_watching_a_marriage_proposal", "joke", "command", "colloquial", "high", "idiom_culture|source_ambiguity", "flagged", "B1", 50),
    1301: r("The speaker asks for sympathy, tells the other person not to talk more, and says they will show the woman what happened; the threat remains source-close.", "화자는 자신을 불쌍히 여겨 달라고 하고 더 말하지 말라고 하며 그 여성에게 무슨 일이 있었는지 보여 주겠다고 해요. 위협의 표면은 원문에 가깝게 보존해요.", "family_relationships", "threatening_to_show_what_happened", "conversation", "warning", "colloquial", "high", "source_ambiguity", "flagged", "B1", 48),
    1302: r("The speaker says they did not make dinner because the pressure cooker is not working and they are on leave. They tell the listener to go to their neighbor Sabah, ask how the neighbor’s morning was, and have her make dinner for tomorrow.", "화자는 압력솥이 작동하지 않고 자신이 휴가라서 저녁을 만들지 않았다고 해요. 상대에게 이웃 사바에게 가서 아침이 어땠는지 묻고 내일 먹을 저녁을 만들어 달라고 하라고 해요.", "food", "discussing_dinner_and_a_broken_pressure_cooker", "conversation", "request", "colloquial", "high", "code_switching|long_source|source_ambiguity", "flagged", "C1", 80),
    1303: r("The speaker mentions types of girls in ‘lafak’, including the one who comes to find a husband in order to marry; the place or surface name is kept source-close.", "화자는 ‘lafak’에 있는 여자들의 유형을 말하며, 결혼할 남편을 찾으러 오는 여성을 언급해요. 장소나 표면 이름은 원문에 가깝게 보존해요.", "family_relationships", "describing_women_seeking_marriage", "conversation", "description", "colloquial", "high", "source_ambiguity", "flagged", "B1", 52),
    1304: r("The speaker greets the brother and asks where the registrations are done, receiving an opaque place-name answer; the greeting exchange is preserved.", "화자는 형제에게 인사하고 등록을 어디에서 하는지 묻으며 불투명한 장소 이름의 답을 들어요. 인사 turn을 보존해요.", "administration", "asking_where_registrations_are_done", "conversation", "question", "colloquial", "medium", "code_switching|source_ambiguity", "flagged", "A2", 30),
    1305: r("The speaker asks where the men gather, says the goods are strong but not cheap, and repeats the question about where they gather; the market vocabulary is source-close.", "화자는 남자들이 어디에 모이는지 묻고 물건이 튼튼하지만 싸지는 않다고 말한 뒤 어디에 모이는지 다시 물어요. 시장 어휘는 원문에 가깝게 보존해요.", "work", "asking_where_people_gather_to_trade", "conversation", "question", "colloquial", "high", "source_ambiguity", "flagged", "B1", 52),
    1306: r("The speaker says they should go in the evening to Mustafa’s place to eat breakfast, then notes that it is only eight; the title-like opening is retained.", "화자는 저녁에 무스타파에게 가서 아침을 먹자고 하며 아직 8시밖에 되지 않았다고 말해요. 제목처럼 보이는 초두 표면도 보존해요.", "food", "planning_a_meal_at_mustafas_place", "conversation", "suggestion", "colloquial", "high", "idiom_culture|source_ambiguity", "flagged", "B1", 48),
    1307: r("The speaker says they are hungry and cannot concentrate because their stomach is empty, then asks what there is to swallow; the blessing remains source-close.", "화자는 배가 고프고 배가 비어서 집중할 수 없다고 하며 무엇을 삼킬 수 있는지 물어요. 보호를 비는 표현은 원문에 가깝게 보존해요.", "food", "asking_for_food_when_hungry", "conversation", "complaint", "colloquial", "medium", "idiom_culture|source_ambiguity", "flagged", "B1", 46),
    1308: r("The speaker says a woman has been arguing with her partner for a year, demands to be released, says he spoke to the speaker and that it is not the speaker’s business, and fears being hit. The repeated request to release her is retained.", "화자는 한 여성이 1년 동안 연인과 다투고 있다고 하며 자신을 놓아 달라고 반복해요. 그 남자가 자신에게 말을 걸었지만 자신의 일이 아니라고 하고 맞을까 봐 걱정해요.", "family_relationships", "arguing_about_a_relationship", "conversation", "complaint", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "C1", 82),
    1309: r("The speaker describes someone who studies only the first course and leaves, calls that person a teacher, insults them with an opaque ‘dog mouth’ expression, and asks whether they can go to the sanitary place.", "화자는 첫 수업만 공부하고 나가는 사람을 선생이라고 부르며 불투명한 ‘개 입’ 표현으로 놀리고 위생 시설에 가도 되는지 물어요.", "education", "teasing_someone_about_studying", "joke", "question", "colloquial", "high", "idiom_culture|source_ambiguity", "flagged", "B2", 64),
    1310: r("The speaker mentions someone who studies only the long course, asks Fouzia what she is doing today, hears that they are making beans, and asks what she is pretending to be for them.", "화자는 긴 과정만 공부하는 사람을 언급하고 푸지아에게 오늘 무엇을 하는지 물어요. 콩을 만들고 있다는 답을 듣고 무엇인 척하는지 다시 물어요.", "education", "teasing_about_studies_and_cooking", "conversation", "question", "colloquial", "high", "source_ambiguity", "flagged", "B1", 52),
    1311: r("The speaker says that if the girls were in the place of the ones who lie, they would tell the truth, and says they bought this one too; the comparison is opaque.", "화자는 여자들이 거짓말하는 사람들의 자리에 있다면 진실을 말할 것이라고 하고 이것도 샀다고 말해요. 비교의 대상은 불투명해요.", "family_relationships", "joking_about_women_and_truth", "joke", "opinion", "colloquial", "high", "idiom_culture|source_ambiguity", "flagged", "B1", 50),
    1312: r("The speaker asks how much an item cost, hears ‘a million’, insults it, and says they will neither buy nor wear nor deserve it, adding that they are not human. They want to make a friend with a good-wish invitation; the insults are comic exaggeration.", "화자는 물건을 얼마에 샀는지 묻고 백만이라고 듣자 그것을 모욕해요. 사지도 입지도 가질 자격도 없고 자신들은 인간이 아니라고 과장하며, 좋은 말로 친구를 만들고 싶다고 해요.", "shopping", "joking_about_an_expensive_item", "joke", "complaint", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "C1", 84),
    1313: r("The speaker addresses the father, compares Tinessa with a woman they used to go out with, tells someone to stop eating themselves, recalls being called to return, and says they do not work as a porter; the final Ibiza surface is retained.", "화자는 아버지에게 말하며 티네사를 예전에 함께 다니던 여성과 비교해요. 상대에게 자신을 갉아먹지 말라고 하고 다시 돌아오라고 계속 불렸던 일을 떠올리며 자신은 짐꾼으로 일하지 않는다고 해요. 마지막 ‘이비자’ 표면을 보존해요.", "family_relationships", "teasing_about_a_past_relationship", "joke", "narration", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "C1", 86),
    1314: r("The speaker says they came with lineage and asks for the lineage to be brought with a rose bouquet. They joke that people who come to propose at ten in the morning will make the speaker run, and remind the listener to wear a shirt when coming to propose.", "화자는 혈통과 신분을 갖추고 왔다고 하며 장미 꽃다발과 함께 그 혈통을 가져오라고 해요. 오전 10시에 청혼하러 오는 사람들을 보면 도망가겠다고 농담하고 청혼하러 올 때 셔츠를 입으라고 상기시켜요.", "family_relationships", "joking_about_marriage_proposals", "joke", "command", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "C1", 82),
    1315: r("The speaker asks whether the listener knows him, answers yes, and says they have been involved with him for five years, calling him a face of misery; the idiom is preserved as a joke.", "화자는 상대가 그 남자를 아느냐고 묻고 안다고 답하며 5년 동안 그와 얽혀 있었다고 해요. 그를 불행의 얼굴이라고 부르는 표현은 농담으로 보존해요.", "family_relationships", "joking_about_a_long_relationship", "joke", "answer", "colloquial", "high", "idiom_culture|source_ambiguity", "flagged", "B1", 54),
    1316: r("The speaker says the woman already looks yellow or pale and refuses to live with her, saying they will make a home of their own and tell her directly.", "화자는 그 여성이 이미 누렇게 보인다고 하며 함께 살지 않겠다고 해요. 자신의 집을 따로 만들고 그 말을 직접 하겠다고 해요.", "family_relationships", "refusing_to_live_with_someone", "conversation", "opinion", "colloquial", "medium", "source_ambiguity", "flagged", "B1", 50),
    1317: r("The speaker compares the friend to a bathroom kiosk, asks why the sister is photographing them, calls someone a frog, and says the listener should look at their own face in a mirror before the speaker photographs them instead.", "화자는 친구를 목욕탕의 작은 시설에 비유하고 누이가 왜 자신을 찍는지 물어요. 누군가를 개구리라고 부르며 거울로 자기 얼굴을 보라고 하고, 보지 않았다면 자신이 그 사람을 찍겠다고 농담해요.", "family_relationships", "teasing_about_photographs_and_a_mirror", "joke", "warning", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "C1", 84),
    1318: r("The speaker asks why the sister is afraid and says the brother’s wife put her in a group for divorced female teachers at the bath; the social-media group surface is preserved.", "화자는 누이가 왜 두려워하는지 묻고 형제의 아내가 그녀를 목욕탕의 이혼한 여성 교사들 그룹에 넣었다고 말해요. 그룹 표면을 보존해요.", "family_relationships", "joking_about_a_group_of_divorced_teachers", "joke", "question", "colloquial", "high", "code_switching|idiom_culture|source_ambiguity", "flagged", "B2", 66),
    1319: r("The speaker asks what the other person is saying, invites everyone to bathe them, and says anyone who is unhappy can go shower at home.", "화자는 상대가 무슨 말을 하는지 묻고 모두에게 자신을 씻겨 달라고 해요. 마음에 들지 않는 사람은 집에서 샤워하러 가라고 해요.", "family_relationships", "joking_about_bathing", "joke", "command", "colloquial", "medium", "idiom_culture|source_ambiguity", "flagged", "B1", 48),
    1320: r("The speaker says the other person’s back has been exposed for an hour and that the speaker has been scratching them, charging by the square metre. They joke that another bathroom kiosk charges five thousand and threaten to fly at her with a towel.", "화자는 상대의 등이 한 시간 동안 드러나 있었고 자신이 긁어 주었다며 제곱미터 단위로 돈을 받겠다고 해요. 다른 목욕탕 시설은 5천만 받는다고 농담하고 수건을 들고 달려들겠다고 해요.", "family_relationships", "joking_about_bathing_and_charging_money", "joke", "warning", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "C1", 84),
    1321: r("The speaker asks for five thousand, threatens to feed the other person the worms they pulled out, and says the other person has brought a very small boy whose huge teeth could satisfy a camel; the body imagery is comic exaggeration.", "화자는 5천을 요구하고 자신이 꺼낸 벌레를 상대에게 먹이겠다고 농담해요. 상대가 아주 작은 소년을 데려왔지만 그 소년의 큰 이빨은 낙타도 만족시킬 수 있다고 과장해요.", "family_relationships", "comic_exaggeration_about_a_small_child", "joke", "warning", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "C1", 82),
    1322: r("The speaker says that if the person only knocks here, they should bring her inside because all the women from the bath will run away; the line is a comic threat.", "화자는 여기서 노크만 하면 그 여성을 안으로 데려오라고 해요. 목욕탕의 모든 여성들이 도망갈 거라고 농담해요.", "family_relationships", "joking_about_people_running_away", "joke", "command", "colloquial", "high", "idiom_culture|source_ambiguity", "flagged", "B1", 48),
    1323: r("The speaker greets the friend with an opaque comparison, says people are leaving for France at five in the morning and someone will run away, asks how Zahra is, recalls being chased by a barking dog, and jokes about carrying date bunches and uprooting palms for the road; the long sequence remains source-close.", "화자는 친구에게 불투명한 비교로 인사하고 사람들이 새벽 5시에 프랑스로 떠나 누군가 도망갈 거라고 해요. 자흐라의 안부를 묻고 짖는 개에게 쫓긴 일을 떠올리며 대추야자 송이를 들고 도로의 야자나무를 뽑아 가는 농담을 해요. 긴 sequence를 보존해요.", "travel", "joking_about_travel_to_france", "joke", "narration", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "C1", 90),
    1324: r("The speaker comments on a woman’s appearance with a gold and crooked-back comparison, calls Karim, says it is six in the morning, and jokes about lowering Karim from the window while mentioning a rented cup and thinking about the listener; names and surfaces are opaque.", "화자는 여성을 금과 굽은 등에 비유하며 외모를 말하고 카림을 불러요. 오전 6시라고 하며 카림을 창문에서 내려 주겠다고 농담하고 빌린 컵과 상대를 생각한다는 표현을 말해요. 이름과 표면은 불투명해요.", "family_relationships", "joking_about_appearance_and_karim", "joke", "description", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "C1", 82),
    1325: r("The speaker says they are in the sky and have not managed with the others, asks what the object is, and says the plane will not fall. They recall a National Geographic report and say even the pilot is confused, then tell the others to close the doors, leave, and not forget a certificate; the long exchange is source-close.", "화자는 하늘에 있으며 일행과 잘 맞지 않았다고 하고 그것이 무엇인지 물어요. 비행기가 떨어지지 않을 거라고 하며 내셔널 지오그래픽 리포트를 떠올리고 조종사도 혼란스러워한다고 해요. 문을 닫고 나가며 증명서를 잊지 말라고 해요.", "travel", "comic_airplane_and_report_exchange", "joke", "narration", "colloquial", "high", "code_switching|long_source|source_ambiguity", "flagged", "C1", 88),
    1326: r("The speaker describes the great Algerian family watching the match and jokes about someone who thinks they are still in 2010.", "화자는 위대한 알제리 가족이 경기를 보는 모습을 말하고 누군가가 아직도 2010년에 있다고 생각한다고 농담해요.", "sports", "joking_about_watching_a_match", "joke", "description", "colloquial", "medium", "idiom_culture|source_ambiguity", "flagged", "B1", 48),
    1327: r("The speaker asks where Ziani is; the named footballer reference is kept without adding context.", "화자는 지아니가 어디 있는지 물어요. 축구 선수 이름이라는 표면은 추가 맥락 없이 보존해요.", "sports", "asking_where_ziani_is", "conversation", "question", "colloquial", "medium", "source_ambiguity", "flagged", "A1", 22),
    1328: r("The speaker says the listener thinks they are in 2010, but Ziani is no longer there and cannot be brought to play even one match; the speaker says they miss him.", "화자는 상대가 아직 2010년에 있다고 생각하지만 지아니는 더 이상 없고 한 경기만 뛰게 데려올 수도 없다고 말해요. 그가 그립다고 해요.", "sports", "missing_a_former_football_player", "conversation", "complaint", "colloquial", "medium", "idiom_culture|source_ambiguity", "flagged", "B1", 52),
    1329: r("The speaker jokes about goat legs, says to make him a tifo like this, and says that if the speaker were the one scoring, they would have scored seven; the football joke is source-close.", "화자는 염소 다리라고 놀리며 그를 이런 식으로 응원 깃발로 만들라고 해요. 자신이 득점한 사람이라면 7골을 넣었을 거라고 농담해요.", "sports", "joking_about_a_football_score", "joke", "opinion", "colloquial", "high", "idiom_culture|source_ambiguity", "flagged", "B1", 54),
    1330: r("The speaker describes the woman who is coming to apply kohl, jokes about how one man became handsome, and mentions his tattoo; the appearance wording is kept source-close.", "화자는 아이라이너를 하러 오는 여성을 말하고 한 남자가 얼마나 잘생겼는지 농담하며 문신을 언급해요. 외모 표현은 원문에 가깝게 보존해요.", "family_relationships", "joking_about_makeup_and_a_tattoo", "joke", "description", "colloquial", "medium", "idiom_culture|source_ambiguity", "flagged", "B1", 48),
    1331: r("The speaker tells a viewer to go, asks why they are being treated that way, jokes as if the people were playing the Africa World Cup, and tells someone to shut their mouth because their words are useless; the name surface is retained.", "화자는 시청자에게 가라고 하며 왜 자신에게 그렇게 하느냐고 물어요. 사람들이 아프리카 월드컵을 하는 것처럼 농담하고 말이 소용없으니 입을 다물라고 해요.", "sports", "joking_about_a_football_tournament", "joke", "warning", "colloquial", "high", "code_switching|idiom_culture|source_ambiguity", "flagged", "B2", 64),
    1332: r("The speaker says the others are making money while the listeners keep arguing about them, then tells someone to get up and clean potatoes because she is gathered with brats; the household complaint is source-close.", "화자는 다른 사람들은 돈을 버는데 일행은 그들에 대해 계속 다툰다고 말해요. 이어 누군가에게 일어나 감자를 손질하라고 하며 그 여성이 장난꾸러기들과 모여 있다고 해요.", "food", "complaining_about_cleaning_potatoes", "conversation", "command", "colloquial", "high", "idiom_culture|source_ambiguity", "flagged", "B2", 66),
    1333: r("The speaker describes ‘the source of tenderness’ going shopping with her daughter, says it takes a year to make the daughter a bride, and jokes that the speaker will put on shoes and leave rather than argue. They say they keep watch until dinner and ask whether the mother should take one item or the other; the long family exchange is preserved.", "화자는 ‘다정함의 샘’이 딸과 쇼핑하러 가는 장면을 말하고 딸을 신부로 만들려면 1년이 걸린다고 해요. 자신은 신발을 신고 나가서 다투지 않겠다고 농담하며 저녁까지 지켜본다고 해요. 엄마에게 이것을 가져갈지 저것을 가져갈지 물어요.", "family_relationships", "shopping_with_a_daughter_for_marriage", "joke", "narration", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "C1", 86),
    1334: r("The speaker says she is coming wanting silk and mentions the one who cuts it; the short line is incomplete and the action is source-ambiguous.", "화자는 비단을 원하며 오고 있고 그것을 자르는 사람을 언급해요. 짧은 문장이라 행동은 불투명하고 불완전해요.", "shopping", "incomplete_remark_about_silk", "conversation", "description", "colloquial", "high", "source_ambiguity|source_corruption", "flagged", "A2", 28),
    1335: r("The speaker says that if they tell the listener to take this one, they should take it, but calls the listener hard-headed. They say they like this one and ask why the other modest one is not chosen, joking that the listener wants to undress her at university and asking whether this is how the speaker raised them.", "화자는 자신이 이것을 가지라고 하면 가지라고 하며 상대가 고집이 세다고 말해요. 자신은 이것이 마음에 든다고 하고 왜 단정한 다른 것을 고르지 않느냐고 물으며, 상대가 대학에서 여성을 벗겨 보이려는 것처럼 농담하고 이렇게 키웠느냐고 해요.", "shopping", "arguing_about_choosing_clothes", "conversation", "warning", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "C1", 82),
    1336: r("The speaker says ‘praise be’ and thought the listener had become angry. The mother will take this item; the price is fifty thousand, while the neighbor’s is two hundred thousand without exchange. The speaker asks the son to be kind because the woman has only fifty thousand, and the mother answers that she has it and tells the speaker to be quiet.", "화자는 ‘찬양받으시길’이라고 하며 상대가 화난 줄 알았다고 해요. 엄마가 이것을 가져가고 가격은 5만이며 이웃의 것은 교환 없이 20만이라고 말해요. 여성이 5만밖에 없으니 아들에게 잘해 달라고 하고, 엄마는 자신에게 돈이 있다며 조용히 하라고 해요.", "shopping", "bargaining_over_the_price_of_clothes", "conversation", "narration", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "C1", 88),
    1337: r("The speakers decide to trust God and mention fifty thousand, wish success, reject the mother’s response, and say ‘here is my face’; if the speaker wins, the other person should leave before them, called a traitor. The exchange is comic and source-close.", "화자들은 신을 믿자고 하며 5만을 언급하고 성공을 빌어요. 엄마의 말을 거부하고 ‘여기 내 얼굴이 있어’라고 하며 자신이 이기면 상대가 자신보다 먼저 나가라고 하고 배신자라고 부르는 코미디 turn이에요.", "shopping", "joking_about_money_and_winning", "joke", "warning", "colloquial", "high", "idiom_culture|source_ambiguity", "flagged", "B2", 72),
    1338: r("The speaker says that if they go out with the listener again, they will not be named or recognized after the morning, because the listener turns around whatever they like and dislike; the speaker admits having a fault and deserving it.", "화자는 상대와 다시 외출하면 아침부터 자신의 이름을 말할 수 없을 것이라고 해요. 상대가 좋아하는 것과 싫어하는 것을 마음대로 돌린다고 하며 자신에게 잘못이 있고 그럴 만하다고 인정해요.", "family_relationships", "complaining_about_a_difficult_outing", "conversation", "complaint", "colloquial", "high", "idiom_culture|source_ambiguity", "flagged", "B2", 68),
    1339: r("The speaker says the family house is used for invitations, asks for two plates of harira, complains about what the others have been doing since morning, and tells the woman to wear a veil and cover herself before men.", "화자는 집에서 초대 모임을 한다고 하며 하리라 두 접시를 가져오라고 해요. 일행이 아침부터 무엇을 했는지 불평하고 여성에게 남자들 앞에서 머리 스카프를 쓰고 몸을 가리라고 해요.", "food", "preparing_harira_for_a_family_gathering", "conversation", "command", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "B2", 72),
    1340: r("The speaker asks about safety, says a woman is acting against them, calls the listener merely the neighbor’s son, and tells him to stop eating himself, bring harira inside, and eat.", "화자는 안전에 대해 묻고 한 여성이 자신에게 달려든다고 말해요. 상대를 그저 이웃의 아들이라고 부르며 자신을 갉아먹지 말고 하리라를 들여와 먹으라고 해요.", "food", "joking_about_harira_and_a_neighbor", "joke", "command", "colloquial", "high", "idiom_culture|source_ambiguity", "flagged", "B1", 58),
    1341: r("The speaker asks the son where the water room is and says there is something there with water for washing. The reply says there is only a little water, and the speaker thanks the son.", "화자는 아들에게 물이 있는 방이 어디인지 묻고 씻을 물이 있는지 말해요. 대답은 물이 조금뿐이라고 하고 화자는 아들에게 고맙다고 해요.", "daily_life", "asking_about_water_for_washing", "conversation", "question", "colloquial", "medium", "source_ambiguity", "flagged", "A2", 30),
    1342: r("The speaker says they are going to the bathroom, asks for a towel for their feet so they can dry them and perform ablution, and asks for the key to the room where the cat is hidden because they want to pray quietly.", "화자는 용변을 보러 가며 발을 닦고 세정 의식을 할 수 있도록 발 수건을 달라고 해요. 고양이를 숨겨 둔 방의 열쇠를 달라고 하며 조용히 기도하고 싶다고 해요.", "daily_life", "preparing_for_ablution_and_prayer", "conversation", "request", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "B2", 68),
    1343: r("The speaker points out an old woman who is a bad person, says she pulls her mouth and fills it with water every fifteen minutes, and jokes that next time they will run over and bury her mouth in the dirt, referring to a plan seen in MBS2.", "화자는 저기 있는 노년 여성이 못된 사람이라고 말하고 15분마다 입을 당겨 물로 부풀린다고 해요. 다음에는 달려가 그 여성의 입을 흙에 묻겠다고 농담하며 MBS2에서 본 계획을 언급해요.", "health", "comic_description_of_an_old_womans_behavior", "joke", "warning", "colloquial", "high", "code_switching|idiom_culture|long_source|source_ambiguity", "flagged", "C1", 82),
    1344: r("The mother and father arrive to take the listener somewhere and say they will drive them before going to the stadium. The speaker tells the person to come now because the group has just opened, says the husband will not object, asks why the listener is dragging them along, and decides to stay overnight after being given a bed; the turns are kept source-close.", "엄마와 아빠가 상대를 데리러 와서 경기장에 가기 전에 데려다주겠다고 해요. 화자는 일행이 이제 막 열렸으니 지금 오라고 하고 남편은 아무 말도 하지 않을 거라고 해요. 왜 자신을 끌고 가느냐고 묻고 잠자리를 마련해 주면 그곳에서 하룻밤 묵겠다고 해요.", "family_relationships", "joking_about_being_taken_to_the_stadium", "conversation", "narration", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged", "C1", 84),
}


def build():
    engine.BATCH_ID = BATCH_ID
    engine.BASE_COMMIT = BASE_COMMIT
    engine.PROMPT_VERSION = PROMPT_VERSION
    engine.TARGET_START = TARGET_START
    engine.TARGET_END = TARGET_END
    engine.BATCH_OUT = BATCH_OUT
    engine.MANIFEST_OUT = MANIFEST_OUT
    engine.QA_OUT = QA_OUT
    engine.RAW = RAW
    return engine.build()


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    print(json.dumps(build(), ensure_ascii=False, indent=2))
