"""Build source-only MADOran enrichment Batch 16 for Sentno 961..1024."""
from __future__ import annotations

import json
import sys
from pathlib import Path

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts import build_madoran_enrichment_batch10 as engine
from scripts.build_madoran_enrichment_scaffold import ROOT

BATCH_ID = "MADORAN-ENRICH-016"
BASE_COMMIT = "d2d3d7d"
PROMPT_VERSION = "madoran-source-enrichment-v16"
TARGET_START = 961
TARGET_END = 1024
BATCH_OUT = ROOT / "data/master/enrichment/batches/batch16_sentno_0961_1024.tsv"
MANIFEST_OUT = ROOT / "data/master/enrichment/batches/batch16_manifest.json"
QA_OUT = ROOT / "data/master/qa/madoran_enrichment_batch16_generation_qa.json"
BATCH_FIELDS = engine.BATCH_FIELDS
item = engine.item


def r(english, korean, domain, topic, genre="conversation", speech="description", register="colloquial", context="high", flags="source_ambiguity", state="flagged", cefr="B2", score=60):
    return item(english, korean, cefr, score, domain, topic, genre, speech, register, context, flags, state)


RAW = {
    961: r("‘There is no god but God; Muhammad is the Messenger of God.’ The line includes a blessing and prayer for him.", "‘신 외에는 신이 없고 무함마드는 신의 사도다.’라는 말에 그를 위한 축복과 기도가 이어져요.", "religion", "religious_declaration_and_blessing", "speech", "wish", "neutral", "low", "", "draft", "A1", 12),
    962: r("A long, partly unclear exchange lists food or household tasks, including cleaning, washing clothes, and gathering firewood, and asks what the other person was doing. Several words and the addressee are uncertain.", "길고 일부 불분명한 대화에서 음식이나 집안일과 관련된 말, 청소·빨래·장작 모으기 같은 일이 나와요. 마지막에는 상대가 무엇을 하고 있었는지 묻지만 여러 단어와 청자가 불확실해요.", "daily_life", "unclear_household_tasks", "conversation", "question", "colloquial", "high", "long_source|source_ambiguity"),
    963: r("One speaker tells the other to stop nagging all day and all year, saying that she is always with her daughter. The address terms and some wording remain uncertain.", "한 화자가 상대에게 하루 종일, 일 년 내내 잔소리하는 것을 그만하라고 하며 늘 딸과만 함께 있다고 말해요. 호칭과 일부 표현은 불확실하게 남겨요.", "family_relationships", "reproach_about_constant_nagging", "conversation", "complaint", "offensive", "high", "source_ambiguity"),
    964: r("The speaker says, ‘You see, Dad.’", "화자가 ‘보세요, 아빠’라고 말해요.", "family_relationships", "addressing_father", "conversation", "information", "colloquial", "low", "source_ambiguity"),
    965: r("The speaker addresses a daughter, says they are raising her and that she is still young, then asks for a little peace and rest. They jokingly ask whether the other person wants to turn her into an ogre that will eat them.", "화자는 딸에게 말을 걸며 자신이 딸을 키우고 있고 아직 어리다고 해요. 잠시 조용히 쉬게 해 달라고 하면서, 상대가 딸을 자신을 잡아먹는 괴물로 만들고 싶은 거냐고 농담처럼 물어요.", "family_relationships", "parental_reproach_and_ogre_joke", "conversation", "complaint", "colloquial", "high", "idiom_culture|source_ambiguity"),
    966: r("The other speaker rejects the ogre idea and lists several household or food-preparation tasks, including cutting meat, making عصبان, washing tripe or skins, and cleaning something. The rest contains opaque descriptions of grooming and another woman who is at least working.", "상대는 괴물 이야기를 받아들이지 않고 고기를 손질하고 عصبان을 만들며 내장이나 가죽을 씻고 무언가를 닦았다는 식으로 여러 집안일이나 음식 준비를 나열해요. 뒤에는 몸단장과 다른 여성이 적어도 일하고 있다는 불투명한 표현이 이어져요.", "daily_life", "unclear_household_work_and_reproach", "conversation", "disagreement", "colloquial", "high", "long_source|source_ambiguity"),
    967: r("The speaker asks, ‘You want to eat me?’", "화자가 ‘나를 먹고 싶은 거야?’라고 물어요.", "family_relationships", "playful_or_threatening_eat_me_expression", "conversation", "question", "colloquial", "high", "idiom_culture|source_ambiguity"),
    968: r("Guests arrive and the speaker asks what is happening. A long comic exchange mentions not working on Friday, being driven crazy, looking for a jacket, payment, moving back, following the speaker, and someone wanting to eat the earth. Several turns and expressions are unclear.", "손님들이 오자 화자가 무슨 일이냐고 물어요. 금요일에는 일하지 않는다는 말, 미치겠다는 말, 재킷을 찾는 말, 계산과 물러서기, 따라오라는 말, 땅을 먹고 싶다는 말이 이어지는 긴 희극적 대화예요. 여러 화행과 표현은 불분명해요.", "daily_life", "comic_guest_arrival_and_household_exchange", "conversation", "complaint", "colloquial", "high", "code_switching|long_source|source_ambiguity"),
    969: r("The tribal sheikh has arrived.", "부족의 셰이크가 도착했어요.", "family_relationships", "arrival_of_tribal_sheikh", "narrative", "information", "neutral", "low", "", "draft", "A1", 14),
    970: r("They welcome the visitors, exchange blessings, and say they have brought honey, an unclear item or word, and jam. Someone tells another person to be quiet and then addresses Dad.", "일행을 환영하고 축복의 말을 주고받으며 꿀과 불분명한 물건이나 표현, 잼을 가져왔다고 해요. 누군가에게 조용히 하라고 한 뒤 아빠를 불러요.", "family_relationships", "welcoming_visitors_with_food", "conversation", "greeting", "colloquial", "medium", "code_switching|source_ambiguity"),
    971: r("The visitors ask for the hand of the family’s daughter for their son, clarifying that they want the complete marriage arrangement, not only her hand. Another speaker tells the father to be quiet, and he says he is quiet.", "방문객들이 자기 아들을 위해 그 집 딸의 손을 달라고 청혼하며, 단지 손만이 아니라 완전한 혼인 관계를 원한다고 덧붙여요. 다른 화자가 아버지에게 조용히 하라고 하고 아버지는 조용히 있겠다고 해요.", "family_relationships", "formal_marriage_proposal", "conversation", "request", "mixed", "high", "source_ambiguity"),
    972: r("The speaker asks who saw the other group’s service, worksite, director general, or secretary general, then asks whom it is for and answers: for their son Bisha. The institutional terms are partly opaque.", "화자는 상대 집단의 업무나 현장, 총국장이나 총서기를 누가 보았는지 묻고, 누구를 위한 것이냐고 한 뒤 자기 아들 비샤를 위한 것이라고 답해요. 기관 관련 표현은 일부 불투명해요.", "family_relationships", "opaque_status_question_about_suitor", "conversation", "question", "mixed", "high", "long_source|source_ambiguity"),
    973: r("Addressing the tribal sheikh, the speaker says they are men and refers to an unclear matter involving not giving something to the other group and a ‘half man.’ They say they came for a difficult or ‘blind-eye’ matter, have no authority to decide, and should consult the mother. The visitors are invited to sit while the speaker consults her and returns.", "화자는 부족 셰이크에게 자신들은 남자들이라고 하며 상대에게 무언가를 주지 않은 일과 ‘반쪽 남자’가 관련된 불분명한 말을 해요. 어려운 문제로 찾아왔지만 자신에게 결정 권한이 없으니 어머니와 상의해야 한다고 하고, 방문객들에게 앉아 있으라며 어머니와 의논하고 돌아오겠다고 해요.", "family_relationships", "sheikh_consults_mother_about_marriage", "conversation", "suggestion", "mixed", "high", "long_source|source_ambiguity"),
    974: r("The speaker invokes God and wishes for good news and good fortune, then welcomes the visitors and exchanges a blessing.", "화자가 신을 부르며 좋은 소식과 좋은 일이 있기를 바란다고 하고 방문객을 환영하며 축복을 주고받아요.", "religion", "blessing_for_good_news", "speech", "wish", "neutral", "low", "", "draft", "A1", 16),
    975: r("The speaker tells Dad that nothing is wrong and says they will take her today, now. The identity of the woman and the intended action remain context-dependent.", "화자는 아빠에게 아무 일도 없다며 오늘, 지금 그녀를 데려가겠다고 해요. 그 여성과 행동의 구체적 의미는 문맥에 의존해요.", "family_relationships", "immediate_marriage_decision", "conversation", "information", "colloquial", "high", "source_ambiguity"),
    976: r("A speaker asks what is happening and answers that, God willing, everything is good and there is nothing but good.", "화자가 무슨 일이냐고 묻고, 신의 뜻이라면 모두 잘될 것이며 좋은 일뿐이라고 답해요.", "daily_life", "reassurance_that_all_is_well", "conversation", "agreement", "neutral", "low", "source_ambiguity"),
    977: r("A speaker tells a woman to listen and says they are speaking to her. They complain that she has spent all morning working on food and threatens to hit her with a shoe if she does not finish. They order her to fetch a brik from Akasha’s wife, tell Dad to light the lamp, and mention several unclear household instructions.", "화자가 한 여성에게 들으라며 자신이 그 여성에게 말하고 있다고 해요. 여성이 아침 내내 음식만 만지고 아직 끝내지 않았다며 신발로 머리를 치겠다고 위협하고, 아카샤의 아내에게서 브리크를 가져오라고 재촉해요. 아빠에게 램프를 켜라고 하는 등 집안 지시가 이어지지만 일부는 불분명해요.", "food", "household_command_and_brik_request", "conversation", "command", "offensive", "high", "code_switching|long_source|source_ambiguity"),
    978: r("The speaker repeats the instruction to go and get a brik from Akasha’s wife, clarifying the source after asking whether it is from Akasha himself. The reply says Akasha’s wife is cooking, followed by an agreement.", "화자는 아카샤의 아내에게서 브리크를 가져오라는 지시를 반복하고, 아카샤 본인에게서 가져오는 것인지 확인해요. 아카샤의 아내가 요리 중이라는 답이 나오고 서로 동의해요.", "food", "clarifying_where_to_get_brik", "conversation", "request", "colloquial", "medium", "source_ambiguity"),
    979: r("The speaker asks the woman whether she knows why the visitors came, then says they came to ask for the girl’s hand in marriage.", "화자는 여성에게 방문객들이 왜 왔는지 아느냐고 묻고, 그들이 딸에게 청혼하러 왔다고 말해요.", "family_relationships", "revealing_marriage_proposal", "conversation", "information", "colloquial", "medium", "source_ambiguity"),
    980: r("A speaker welcomes them but asks whom the proposal is for.", "화자가 그들을 환영하면서 누구를 위한 청혼인지 물어요.", "family_relationships", "asking_which_daughter_or_suitor", "conversation", "question", "colloquial", "medium", "source_ambiguity"),
    981: r("They answer that it is for Bisha, their son. After asking who Bisha is, someone identifies him as ‘that one’ and uses an opaque phrase about a bathhouse. Greetings follow, along with a question about where the father was; he says he was hunting and caught a fox. Several expressions are uncertain.", "비샤라는 그들의 아들을 위한 것이라고 답해요. 비샤가 누구냐고 묻자 ‘저 사람’이라고 가리키고 목욕탕과 관련된 불투명한 표현을 써요. 이어 인사를 나누고 아빠가 어디 있었는지 묻자 사냥을 했고 여우를 잡았다고 답해요. 여러 표현은 불확실해요.", "family_relationships", "identifying_suitor_and_hunting_story", "conversation", "information", "colloquial", "high", "code_switching|source_ambiguity"),
    982: r("The other speaker mocks the claim of catching a fox and says that the person should be hunting lions, tigers, and another unclear animal instead. They refer to a fox caught in the river and insult the other person and their condition.", "상대는 여우를 잡았다는 말을 비웃으며 사자와 호랑이, 또 다른 불분명한 동물을 잡아야 한다고 해요. 강에서 여우를 잡았다는 말을 다시 언급하고 상대와 그 처지를 모욕해요.", "daily_life", "mocking_a_hunting_claim", "conversation", "complaint", "offensive", "high", "source_ambiguity"),
    983: r("The speaker says the important thing is to tell them what happened, but they did not tell them because they wanted to consult the woman. They firmly refuse to give their daughter away. The exchange then reveals that a group from the Sons of the Day tribe came for their son Bisha, who studied with the speaker; one voice says to give her to him.", "화자는 중요한 것은 무슨 말을 했는지 알려 주는 것이라고 하지만, 여성과 상의하려고 상대에게 말하지 않았다고 해요. 자신의 딸을 절대 주지 않겠다고 단호하게 거절해요. 이어 ‘울라드 나하르’ 부족 사람들이 아들 비샤를 위해 왔고 그가 화자와 함께 공부했다는 사실이 드러나며, 한 목소리는 딸을 그에게 주라고 해요.", "family_relationships", "family_refusal_of_suitor_and_consultation", "conversation", "refusal", "offensive", "high", "long_source|source_ambiguity"),
    984: r("The speaker describes the proposed marriage with a chain of exaggerated or opaque comparisons, including marrying a sister, a gladiator, a roundabout, and a water-related object. They tell the listener to say they will not give the daughter. Another voice says Bisha deserves her because his people are good, while the father says he is tired of her and will let the person who takes her have her.", "화자는 자매와 결혼한다거나 검투사·회전목마·물과 관련된 물건을 말하는 식으로 과장되고 불투명한 비교를 이어가요. 딸을 주지 않겠다고 말하라고 하고, 다른 목소리는 비샤와 그 집안이 좋은 사람들이라 딸을 받을 만하다고 해요. 아버지는 딸에게 지쳤다며 데려가는 사람에게 주겠다고 말해요.", "family_relationships", "comic_argument_about_suitor", "conversation", "disagreement", "offensive", "high", "long_source|source_ambiguity"),
    985: r("The speaker tells someone to leave before they deal with them, orders them to go out, and says to tell the suitor no. The insults and exact threat are partly opaque.", "화자가 누군가에게 자신이 상대를 처리하기 전에 나가라고 하고, 밖으로 나가서 청혼자에게 안 된다고 말하라고 해요. 욕설과 정확한 위협의 내용은 일부 불투명해요.", "family_relationships", "ordering_refusal_to_suitor", "conversation", "command", "offensive", "high", "source_ambiguity"),
    986: r("The speaker says they do not have the face to tell him no, but another voice tells them to say no. The exchange includes an insult and says that the man keeps asking for the daughter while the speaker remains unwilling to give her to him; some wording is unclear.", "화자는 그에게 안 된다고 말할 면목이 없다고 하지만, 다른 목소리는 안 된다고 말하라고 해요. 모욕적인 표현과 그 남자가 계속 딸을 요구한다는 말이 나오며, 화자는 딸을 주지 않겠다고 해요. 일부 표현은 불분명해요.", "family_relationships", "refusing_repeated_marriage_request", "conversation", "refusal", "offensive", "high", "source_ambiguity"),
    987: r("The speaker argues that they are the father and have authority to decide, repeatedly saying they will not give their daughter. They complain that others want to make them angry and ask them not to question their livelihood or fortune.", "화자는 자신이 아버지이고 결정권이 있다며 딸을 주지 않겠다고 반복해요. 다른 사람들이 자신을 화나게 하려 한다고 불평하고 자신의 생계나 재산을 캐묻지 말라고 해요.", "family_relationships", "father_asserts_authority_over_marriage", "conversation", "refusal", "offensive", "high", "source_ambiguity"),
    988: r("The speaker mentions a Mercedes and an unclear phrase about an almond or a closed item, then asks for everything to be brought so there will be a large hall for the whole family. Dad agrees.", "화자는 메르세데스와 아몬드나 닫힌 물건을 가리키는 불분명한 말을 한 뒤, 가족 모두를 맞이할 큰 홀이 되도록 그것들을 가져오라고 해요. 아빠가 동의해요.", "family_relationships", "preparing_large_family_reception", "conversation", "request", "colloquial", "high", "source_ambiguity"),
    989: r("The speaker says that when the boy grows up they will name him Saïd.", "화자는 그 아이가 자라면 이름을 사이드라고 짓겠다고 말해요.", "family_relationships", "choosing_a_childs_name", "conversation", "suggestion", "colloquial", "medium", "source_ambiguity"),
    990: r("The speaker tells Dad that the child was already born and named, saying he does not know this. They express happiness and tell someone to respect their father, not smoke or do something in front of him, and ask for something unclear.", "화자는 아빠에게 아이가 이미 태어났고 이름도 지었다며 아빠는 그 사실을 모른다고 해요. 기쁘다고 말한 뒤 누군가에게 아버지를 존중하고 아버지 앞에서 담배를 피우거나 어떤 행동을 하지 말라고 하며 불분명한 것을 요청해요.", "family_relationships", "child_naming_and_respect_for_father", "conversation", "command", "colloquial", "high", "source_ambiguity"),
    991: r("Addressing Mr. Hazim, the speaker asks what they should tell the group and says they handled a woman in a certain way. The exact reference is unclear, followed by reassurance that everything is fine.", "화자는 하짐 씨에게 무엇이라고 말해야 할지 묻고 어떤 여성을 특정한 방식으로 대했다고 해요. 정확한 지칭은 불분명하며, 이어 모두 괜찮다는 말이 나와요.", "family_relationships", "unclear_account_about_a_woman", "conversation", "information", "colloquial", "high", "source_ambiguity"),
    992: r("The speaker blesses the listener and jokes that they are full of feathers or look like Dandoua. The comparison is opaque.", "화자는 상대를 축복하며 깃털로 가득하거나 단두아처럼 보인다고 농담해요. 그 비교의 의미는 불투명해요.", "daily_life", "opaque_comparison_and_blessing", "conversation", "other", "colloquial", "high", "source_ambiguity"),
    993: r("The speaker tells someone to respect themselves because they are speaking with the tribal sheikh.", "화자가 부족의 셰이크와 이야기하고 있으니 자기 자신을 존중하라고 말해요.", "family_relationships", "reprimand_before_tribal_sheikh", "conversation", "warning", "colloquial", "medium", "source_ambiguity"),
    994: r("The speaker tells Bisha to return to his place and asks Dad to speak with him. They repeat the instruction to return to his place.", "화자는 비샤에게 자기 자리로 돌아가라고 하고 아빠에게 그와 이야기하라고 해요. 자기 자리로 돌아가라는 말이 반복돼요.", "family_relationships", "directing_suitor_to_return", "conversation", "command", "colloquial", "medium", "source_ambiguity"),
    995: r("The speaker says the news they have to give is that the girl is still too young, according to her mother’s words.", "화자는 전해야 할 소식은 어머니의 말에 따르면 그 여자가 아직 너무 어리다는 것이라고 해요.", "family_relationships", "family_objection_based_on_age", "conversation", "information", "mixed", "medium", "source_ambiguity"),
    996: r("The speaker says the girl is still studying, has a licence in law, wants to become a lawyer, and hopes to finish her studies, go to France, and marry there because there is no future here. The French-derived educational and legal terms are preserved as code-switching.", "화자는 그 여성이 아직 공부 중이고 법학 학위가 있으며 변호사가 되고 싶어 한다고 해요. 공부를 마치면 프랑스에 가서 그곳에서 결혼하고 싶어 한다며 여기에는 더 이상 미래가 없다고 말해요. 교육·법률 관련 프랑스어계 표현은 코드 스위칭으로 보존해요.", "education", "young_woman_studying_law_and_planning_france", "conversation", "information", "mixed", "high", "code_switching|long_source|source_ambiguity"),
    997: r("The speaker says that even they will follow their daughter as soon as she leaves.", "화자는 자신도 딸이 떠나기만 하면 따라가겠다고 말해요.", "family_relationships", "parent_following_daughter_abroad", "conversation", "information", "colloquial", "medium", "source_ambiguity"),
    998: r("The speaker asks what this talk is and says ‘désolé’. The French apology is preserved as code-switching.", "화자가 이런 말이 무슨 말이냐고 묻고 ‘désolé’라고 해요. 프랑스어 사과 표현은 코드 스위칭으로 보존해요.", "family_relationships", "opaque_objection_and_french_apology", "conversation", "complaint", "mixed", "medium", "code_switching|source_ambiguity"),
    999: r("The speaker asks, ‘What is this?’ and repeats ‘désolé’.", "화자가 ‘이게 뭐야?’라고 묻고 ‘désolé’를 반복해요.", "family_relationships", "repeated_french_apology", "conversation", "question", "mixed", "medium", "code_switching|source_ambiguity"),
    1000: r("The speaker concludes that they will not give their daughter and says, ‘I will take her, and God is great.’ The exact intended action remains context-dependent.", "화자는 결국 딸을 주지 않겠다고 하며 ‘내가 그녀를 데려가겠다, 신은 위대하다’고 말해요. 구체적인 행동의 의미는 문맥에 의존해요.", "family_relationships", "final_refusal_of_marriage_arrangement", "conversation", "refusal", "mixed", "high", "source_ambiguity"),
    1001: r("The speaker asks where the other person has brought them and says there was no way or no connection to reach her. The reference is opaque.", "화자는 상대가 자신을 어디까지 데려왔느냐고 묻고, 그녀에게 닿을 방법이나 연결이 전혀 없었다고 말해요. 지칭은 불투명해요.", "family_relationships", "opaque_objection_to_marriage_route", "conversation", "complaint", "mixed", "high", "source_ambiguity"),
    1002: r("The speaker says that their tribe has never been compatible with the other person’s tribe.", "화자는 자신들의 부족은 상대 부족과 한 번도 어울린 적이 없다고 말해요.", "family_relationships", "tribal_incompatibility_in_marriage", "conversation", "refusal", "mixed", "medium", "source_ambiguity"),
    1003: r("The speaker accuses the other person of being jealous and wanting to take the daughter.", "화자는 상대가 자신을 질투하며 딸을 데려가려 한다고 비난해요.", "family_relationships", "accusation_of_jealousy_in_marriage", "conversation", "complaint", "offensive", "medium", "source_ambiguity"),
    1004: r("The speaker welcomes the visitors, adding that they are doing so instead of throwing them out.", "화자는 방문객을 환영하면서 쫓아내지 않고 이렇게 맞아 주는 것이라고 말해요.", "family_relationships", "hostile_welcome_to_visitors", "conversation", "complaint", "offensive", "medium", "source_ambiguity"),
    1005: r("The speaker asks where the other person has brought them and says they wanted to make the relationship halal or legitimate. The exact situation is unclear.", "화자는 상대가 자신을 어디까지 데려왔느냐고 묻고, 관계를 정당하거나 합법적인 방식으로 만들고 싶었다고 말해요. 정확한 상황은 불분명해요.", "family_relationships", "unclear_legitimate_marriage_intent", "conversation", "information", "mixed", "high", "source_ambiguity"),
    1006: r("Someone asks what is wrong with the maternal cousin; the answer calls her bald.", "누군가 외사촌에게 무슨 문제가 있느냐고 묻자, 상대는 그가 대머리라고 답해요.", "family_relationships", "insult_about_maternal_cousin", "conversation", "complaint", "offensive", "medium", "source_ambiguity"),
    1007: r("Someone refers to the paternal cousin and says he has mange or a skin disease.", "누군가 친사촌을 가리키며 옴이나 피부병이 있다고 말해요.", "family_relationships", "insult_about_paternal_cousin", "conversation", "complaint", "offensive", "medium", "source_ambiguity"),
    1008: r("The speaker emphatically says that the other person will not take her.", "화자가 상대가 그녀를 데려갈 수 없다고 단호하게 말해요.", "family_relationships", "emphatic_refusal_to_give_daughter", "conversation", "refusal", "offensive", "medium", "source_ambiguity"),
    1009: r("The speaker uses an opaque name or phrase and says that she has been placed there so that he will come and take her, then contrasts this with an unclear phrase about what is for the speaker.", "화자는 불투명한 이름이나 표현을 사용하며, 그가 와서 그녀를 데려가도록 그녀가 그곳에 놓여 있다고 말한 뒤 자신을 위한 것이라는 불분명한 표현을 덧붙여요.", "family_relationships", "opaque_arrangement_for_taking_daughter", "conversation", "description", "mixed", "high", "source_ambiguity"),
    1010: r("The speaker insults the other person by asking whether they think the speaker is dead and calling them a fool.", "화자가 상대에게 자신이 죽었다고 생각하느냐고 묻고 바보라고 부르며 모욕해요.", "daily_life", "insult_during_family_argument", "conversation", "complaint", "offensive", "medium", "source_ambiguity"),
    1011: r("The speaker says, ‘Look, we have settled it.’", "화자가 ‘봐, 우리가 이 일을 결정했어’라고 말해요.", "family_relationships", "asserting_decision_in_dispute", "conversation", "information", "colloquial", "medium", "source_ambiguity"),
    1012: r("A long abusive exchange calls someone a traitor and tells them to turn around and fall on an opaque ‘bean owner’ or seller. It says not to be ashamed, lists cows, chickens, sheep, straw, donkeys, and dogs, and asks where everyone is going. The turns and several expressions are uncertain.", "긴 모욕적 대화에서 누군가를 배신자라고 부르고 불투명한 ‘콩 주인’이나 판매자에게 가 보라고 해요. 부끄러워하지 말라고 하며 소·닭·양·짚·당나귀·개를 나열하고 모두 어디로 가는지 물어요. 화행과 여러 표현은 불확실해요.", "daily_life", "abusive_animal_and_goods_listing", "conversation", "complaint", "offensive", "high", "long_source|source_ambiguity"),
    1013: r("The speaker says not to be ashamed and accuses the others of even kidnapping women in villages and reselling them.", "화자는 부끄러워하지 말라고 하며 상대가 마을에서 여성들까지 납치해 다시 판다고 비난해요.", "crime_safety", "accusation_of_kidnapping_and_resale", "conversation", "complaint", "offensive", "high", "source_ambiguity"),
    1014: r("The speaker asks what the problem is, mentions ‘100’ and an opaque noun that may refer to money, and asks what they should do with it.", "화자는 무슨 문제인지 묻고 ‘100’과 돈일 수도 있는 불투명한 명사를 언급하며 그것으로 무엇을 해야 하느냐고 물어요.", "finance", "unclear_use_of_amount", "conversation", "question", "mixed", "high", "source_ambiguity"),
    1015: r("The speaker says they are thinking of using it for an unclear farm or property, asks why they do not make yogurt, and compares it with an unclear reference to the listener’s mother’s yogurt.", "화자는 그것을 불분명한 농장이나 재산에 쓰려고 생각한다고 하며, 왜 요구르트를 만들지 않느냐고 묻고 상대 어머니의 요구르트와 비교하는 불투명한 말을 해요.", "food", "opaque_money_and_yogurt_exchange", "conversation", "suggestion", "mixed", "high", "source_ambiguity"),
    1016: r("The speaker mentions yogurt or a yogurt-related item in an opaque phrase.", "화자가 요구르트나 요구르트와 관련된 물건을 불투명한 표현으로 언급해요.", "food", "opaque_yogurt_reference", "conversation", "description", "colloquial", "high", "source_ambiguity"),
    1017: r("The speaker addresses a friend, says they will take the other one, and asks how much money or value they should make from an unclear amount. The monetary wording is uncertain.", "화자는 친구를 부르며 다른 것을 잡겠다고 하고, 불분명한 금액이나 가치로 얼마를 만들 수 있는지 물어요. 돈과 관련된 표현은 불확실해요.", "finance", "unclear_amount_and_value_exchange", "conversation", "question", "colloquial", "high", "source_ambiguity"),
    1018: r("The speaker asks what the other person will do with an opaque item or expression pronounced ‘zaʿbaṭa’.", "화자는 상대가 ‘자브타’처럼 들리는 불투명한 물건이나 표현으로 무엇을 할지 물어요.", "daily_life", "opaque_item_use_question", "conversation", "question", "colloquial", "high", "source_ambiguity"),
    1019: r("The speaker says they were away for a minute and jokes that one day the other person was given a donkey and today something else, perhaps a ‘kabous’. The comparison is opaque.", "화자는 잠깐 자리를 비웠다며 어느 날에는 상대에게 당나귀를 주더니 오늘은 ‘카부스’처럼 들리는 다른 것을 줬다고 농담해요. 비교의 의미는 불투명해요.", "daily_life", "opaque_joke_about_gifts", "conversation", "other", "colloquial", "high", "source_ambiguity"),
    1020: r("The speaker says the other person does not resemble their grandfather at all and tells them to hold on.", "화자는 상대가 할아버지를 전혀 닮지 않았다고 하며 잡으라고 말해요.", "family_relationships", "teasing_about_family_resemblance", "conversation", "complaint", "colloquial", "medium", "source_ambiguity"),
    1021: r("The speaker asks what is happening and what is wrong with her, then reassures that, God willing, all is well.", "화자는 무슨 일이냐고, 그녀에게 무슨 문제가 있느냐고 묻고 신의 뜻이라면 잘될 것이라고 안심해요.", "family_relationships", "asking_about_womans_condition", "conversation", "question", "colloquial", "medium", "source_ambiguity"),
    1022: r("The speaker says Bisha wants to measure himself against an opaque expression that may be a rank or comparison. They say they knew he wanted to compete because of her and tell the others to follow.", "화자는 비샤가 지위나 비교를 뜻할 수도 있는 불투명한 표현을 기준으로 자신을 재 보려 한다고 해요. 그가 그녀 때문에 경쟁하려 한다는 것을 알고 있었다며 따라오라고 말해요.", "family_relationships", "suitor_competing_for_daughter", "conversation", "warning", "mixed", "high", "source_ambiguity"),
    1023: r("The speaker asks the others not to mention the person they love, not to keep nagging, and not to add more. They say they will leave because they cannot take it anymore, then admit that they love her very much.", "화자는 자신이 사랑하는 사람에 대해 말하지 말고, 계속 괴롭히지도 말며, 더 보태지도 말라고 해요. 더는 견딜 수 없어 떠나겠다고 하다가 그녀를 매우 사랑한다고 인정해요.", "family_relationships", "distress_about_loved_woman_and_marriage", "conversation", "complaint", "mixed", "high", "long_source|source_ambiguity"),
    1024: r("The speaker points out that the other person is there: ‘Here, look! You are here.’", "화자가 상대가 여기 있다는 것을 가리키며 ‘자, 봐! 너 여기 있네’라고 말해요.", "daily_life", "pointing_out_someones_presence", "conversation", "information", "colloquial", "medium", "source_ambiguity"),
}


def build():
    engine.BATCH_ID = BATCH_ID
    engine.BASE_COMMIT = BASE_COMMIT
    engine.PROMPT_VERSION = PROMPT_VERSION
    engine.TARGET_START = TARGET_START
    engine.TARGET_END = TARGET_END
    engine.BATCH_OUT = BATCH_OUT
    engine.MANIFEST_OUT = MANIFEST_OUT
    engine.QA_OUT = QA_OUT
    engine.RAW = RAW
    return engine.build()


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    print(json.dumps(build(), ensure_ascii=False, indent=2))
