"""Build source-only MADOran enrichment Batch 11 for Sentno 641..704."""
from __future__ import annotations

import sys
from pathlib import Path

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts import build_madoran_enrichment_batch10 as engine

BATCH_ID = "MADORAN-ENRICH-011"
BASE_COMMIT = "5b221a9"
PROMPT_VERSION = "madoran-source-enrichment-v11"
TARGET_START = 641
TARGET_END = 704
BATCH_OUT = engine.ROOT / "data/master/enrichment/batches/batch11_sentno_0641_0704.tsv"
MANIFEST_OUT = engine.ROOT / "data/master/enrichment/batches/batch11_manifest.json"
QA_OUT = engine.ROOT / "data/master/qa/madoran_enrichment_batch11_generation_qa.json"
BATCH_FIELDS = engine.BATCH_FIELDS
item = engine.item

RAW = {
    641: item("They brought peas and potatoes. I cannot believe it; now we will go shopping and bring only what we need to start cooking and prepare food for poor people.", "완두콩과 감자를 가져왔어요. 믿을 수가 없네요. 이제 요리를 시작하고 가난한 사람들을 위해 음식을 준비하는 데 필요한 것만 사러 갈 거예요.", "B2", 58, "food", "shopping_for_food_for_poor_people", "conversation", "narration", "colloquial", "high", "long_source|source_ambiguity", "flagged"),
    642: item("This association already specializes in humanitarian activities: visiting patients who donate blood, Ramadan iftar meals, buying Eid clothes for people who do not celebrate so they can be helped, providing a sacrificial ram for Eid al-Adha, and school-entry supplies for children starting school in September.", "이 협회는 이미 헌혈하는 환자 방문, 라마단 이프타르 식사, 명절을 지키지 못하는 사람들을 위한 명절 옷 구입과 지원, 큰 명절의 희생양, 9월에 학교에 들어가는 아이들을 위한 학용품 등 인도주의 활동을 전문으로 해요.", "C1", 82, "culture_tradition", "humanitarian_aid_and_religious_occasions", "expository", "description", "mixed", "high", "idiom_culture|long_source|source_ambiguity", "flagged"),
    643: item("Its activity is extensive, and God willing its reward is great. We will cook everything here, then take it out like an excursion and arrange tables outdoors; the exact place-setting wording is partly unclear, though the place is described as very beautiful.", "활동 규모가 크고 하느님의 뜻이라면 보상도 클 거예요. 여기서 모든 것을 요리한 다음 소풍처럼 밖으로 가져가 탁자를 차릴 거예요. 정확한 상차림 표현은 일부 불분명하지만 장소가 아주 아름답다고 말해요.", "C1", 76, "culture_tradition", "charity_meal_preparation_and_outdoor_tables", "narrative", "description", "mixed", "high", "idiom_culture|long_source|source_ambiguity", "flagged"),
    644: item("Welcome to a new episode of the program ‘Very Frank.’ Today we are in Oran Province, talking about how expensive house rent is for young people who are going to marry, and asking for their opinions.", "‘아주 솔직하게’의 새 회차에 오신 것을 환영해요. 오늘은 오랑 주에서 결혼하려는 젊은이들에게 집세가 얼마나 비싼지 이야기하고 그들의 의견을 물어볼 거예요.", "B1", 42, "social_media", "interview_about_oran_rent_and_marriage", "interview", "greeting", "neutral", "low", "", "draft"),
    645: item("It is very, very expensive. You cannot rent—it is impossible—and you cannot get married in Oran. You work morning and evening and still cannot make it.", "정말, 정말 비싸요. 집을 빌릴 수가 없어요. 불가능하고 오랑에서 결혼할 수도 없어요. 아침부터 저녁까지 일해도 감당할 수가 없어요.", "B1", 46, "housing", "rent_cost_and_marriage_pressure", "conversation", "complaint", "colloquial", "medium", "source_ambiguity", "flagged"),
    646: item("Anyone who tells you, ‘I rent and live well in Oran and have five children,’ is lying. ‘By December, God willing, I will get married’—God willing, may God protect you. How is the rent?", "‘나는 오랑에서 세를 살며 잘 지내고 아이가 다섯 명 있어’라고 말하는 사람은 거짓말하는 거예요. ‘12월쯤 하느님의 뜻이라면 결혼할 거예요.’ 하느님의 뜻이라면, 하느님이 지켜 주시길 바라요. 집세는 어때요?", "C1", 68, "housing", "skepticism_about_rent_and_marriage_claims", "conversation", "question", "colloquial", "high", "idiom_culture|source_ambiguity", "flagged"),
    647: item("Honestly, you cannot rent, my friend. You cannot rent and live with your family or support your wife; renting is impossible. If you want something cheaper, go far away from Oran and leave the city altogether.", "솔직히 친구야, 집을 빌릴 수가 없어요. 세를 살면서 가족과 살거나 아내를 부양할 수도 없어요. 임대는 불가능해요. 더 싼 곳을 원하면 오랑에서 아주 멀리 가서 도시를 완전히 떠나야 해요.", "B2", 64, "housing", "unaffordable_rent_and_family_support", "conversation", "opinion", "colloquial", "high", "source_ambiguity", "flagged"),
    648: item("A studio apartment here is rented for two million. I am close to my wedding, but I cannot rent—do not misunderstand me. I am going to live with my family.", "여기 원룸은 200만에 빌려요. 나는 결혼식이 얼마 남지 않았지만 집을 빌릴 수가 없어요. 나를 오해하지 마세요. 가족과 함께 살 거예요.", "B1", 48, "housing", "living_with_family_before_marriage", "conversation", "information", "colloquial", "medium", "source_ambiguity", "flagged"),
    649: item("If you rent, what will you have left to eat? Look, the next rent here in Oran is three million.", "집세를 내면 무엇을 먹고 살겠어요? 보세요. 여기 오랑의 다음 집세는 300만이에요.", "A2", 30, "housing", "rent_leaves_little_for_living", "conversation", "question", "colloquial", "medium", "source_ambiguity", "flagged"),
    650: item("Even a basic salary is around one million eight hundred thousand; where could someone rent, and where could someone get married? The exact salary term is partly unclear.", "기본급만 해도 약 180만인데, 어디서 집을 빌리고 어디서 결혼하겠어요? 정확한 급여 표현은 일부 불분명해요.", "B2", 58, "housing", "salary_compared_with_rent_and_marriage", "conversation", "complaint", "colloquial", "high", "code_switching|source_ambiguity", "flagged"),
    651: item("So, if you say you will marry and rent, do not marry, brother, unless you already have your own house. Do not rent just to make a deal and wear yourself out; you will not enjoy your marriage at all.", "그러니까 결혼하고 세를 살겠다고 말하려면, 자기 집이 없는 한 결혼하지 말아요, 형제여. 이익을 보려고 세를 얻었다가 자신을 지치게 하지 마세요. 결혼 생활을 전혀 즐기지 못할 거예요.", "C1", 74, "housing", "owning_a_home_before_marriage", "speech", "warning", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged"),
    652: item("A rental in Oran costs about one million per month, and you have to pay a year in advance or the landlord will not accept you. Is it an F3 or something? Yes, an F3 can be nice in a place like ours, around Maramar; you may find something reasonably good.", "오랑의 임대료는 한 달에 약 100만이고, 1년 치를 미리 내야 집주인이 받아 줘요. F3인가요? 네, 마라마르처럼 우리 동네 같은 곳의 F3는 괜찮을 수 있고, 비교적 좋은 집을 찾을 수도 있어요.", "C1", 80, "housing", "oran_apartment_rent_and_advance_payment", "conversation", "information", "mixed", "high", "code_switching|long_source|source_ambiguity", "flagged"),
    653: item("Can you rent for 45 and get married? Ha—45 and get married? The exact French exchange is unclear. Rent in Oran is four to five million for an F3; someone I asked here said an F4 costs six million eight hundred thousand per month.", "45만으로 집을 빌리고 결혼할 수 있어요? 하하, 45만으로 결혼한다고요? 정확한 프랑스어 대화는 불분명해요. 오랑에서는 F3가 400만에서 500만이고, 여기서 물어본 사람은 F4가 한 달에 680만이라고 했어요.", "C1", 82, "housing", "apartment_prices_and_marriage_feasibility", "conversation", "question", "mixed", "high", "code_switching|source_ambiguity", "flagged"),
    654: item("Someone with a low salary may pay three million in rent and still be unable to rent the place at all.", "급여가 적은 사람은 집세로 300만을 내고도 그 집을 전혀 빌릴 수 없을 수 있어요.", "B1", 44, "housing", "low_salary_and_rent_mismatch", "conversation", "description", "colloquial", "medium", "source_ambiguity", "flagged"),
    655: item("Someone earning two million has to pay rent, children, and all the necessities of life; you cannot even count everything. Now everything is expensive, so my friend cannot live. That is why people leave by boat—not for no reason.", "200만을 버는 사람은 집세와 아이들, 생활에 필요한 모든 것을 감당해야 해서 다 셀 수도 없어요. 지금은 모든 것이 비싸서 친구가 살 수가 없어요. 그래서 사람들이 배를 타고 떠나는 거예요. 괜히 그러는 게 아니에요.", "C1", 80, "housing", "living_costs_and_irregular_migration", "speech", "opinion", "mixed", "high", "idiom_culture|long_source|source_ambiguity", "flagged"),
    656: item("Do not even put your head into an F3: it starts at four million, and renting it brings additional work and expenses. The figures and final slang are partly unclear, including a reference to fifty million and thirteen.", "F3에는 아예 머리를 들이밀지도 말아요. 400만부터 시작하고, 빌리면 추가 일과 비용이 생겨요. 5천만과 13을 언급하는 수치와 마지막 속어는 일부 불분명해요.", "C1", 86, "housing", "unaffordable_apartment_costs_and_figures", "conversation", "warning", "slang", "high", "long_source|source_ambiguity", "flagged"),
    657: item("I cannot get married in the time we are living in: everything is expensive, not only rent; the whole cost of living in the country is high.", "우리가 사는 지금은 결혼할 수가 없어요. 집세만이 아니라 모든 것이 비싸고, 나라 전체의 생활비가 높아요.", "B1", 42, "housing", "cost_of_living_and_delayed_marriage", "speech", "opinion", "colloquial", "medium", "source_ambiguity", "flagged"),
    658: item("For two and a half or three million, the place may not be good or properly furnished; it may be damaged, and the owner repairs it again before renting it out.", "250만이나 300만을 내도 집이 좋지 않거나 제대로 갖춰져 있지 않을 수 있어요. 집이 망가져 있어서 집주인이 다시 고친 뒤에야 빌려 주기도 해요.", "B2", 62, "housing", "poor_condition_of_low_cost_rentals", "conversation", "description", "colloquial", "high", "source_ambiguity", "flagged"),
    659: item("The rent money is three million, and then the tenant has to repair the place as well. It may cost five million or more to make it livable, and before moving in that month the tenant must pay a year's advance.", "집세는 300만인데 세입자가 집을 다시 고쳐야 하기도 해요. 사람이 살 수 있게 만드는 데 500만 이상이 들 수 있고, 그달에 들어가기 전 1년 치 선불금을 내야 해요.", "C1", 78, "housing", "repair_costs_and_annual_rent_advance", "conversation", "description", "mixed", "high", "long_source|source_ambiguity", "flagged"),
    660: item("So how much will the cow and her daughter cost? That is a lot. The livestock comparison is comic and its exact wording is unclear.", "그러면 소와 그 딸은 얼마가 들까요? 정말 많네요. 가축에 빗댄 말장난이며 정확한 표현은 불분명해요.", "B2", 58, "humor", "comic_comparison_about_cost", "joke", "question", "slang", "high", "idiom_culture|source_ambiguity", "flagged"),
    661: item("For an F3, I searched for an F4 and found one for seven million. Look, I found an F4 rental for eight million per month.", "F3와 관련해 F4를 찾아봤는데 700만짜리를 발견했어요. 보세요. 한 달 800만인 F4 임대를 찾았어요.", "B1", 44, "housing", "comparison_of_f3_and_f4_rents", "conversation", "information", "colloquial", "medium", "source_ambiguity", "flagged"),
    662: item("I say that he should live with his parents. Would you accept it if he made you live with his parents?", "나는 그가 부모님과 살아야 한다고 말해요. 그가 당신을 부모님과 함께 살게 한다면 받아들일 수 있겠어요?", "B1", 42, "family_relationships", "living_with_parents_after_marriage", "conversation", "question", "colloquial", "medium", "source_ambiguity", "flagged"),
    663: item("Yes, I would live with his parents myself. Most people end up in informal housing or rent in Sidi Bachir or Chtaïbo; the details about low payments and an F2 at two million five hundred are partly unclear.", "네, 나도 그의 부모님과 살 거예요. 대부분은 무허가 주거지로 가거나 시디 바시르와 슈타이보에서 세를 살아요. 적은 지불액과 250만짜리 F2에 대한 세부 내용은 일부 불분명해요.", "C1", 76, "housing", "housing_choices_with_in_laws", "conversation", "answer", "colloquial", "high", "idiom_culture|long_source|source_ambiguity", "flagged"),
    664: item("What salary would you need to rent like this and live with children? Even a salary of six million is not enough: where would you go, what would you eat, and what would you pay? It is impossible. We ask the state to provide a good solution.", "이렇게 집을 빌리고 아이들과 살려면 급여가 얼마여야 할까요? 600만을 받아도 충분하지 않아요. 어디로 가고 무엇을 먹고 무엇을 내겠어요? 불가능해요. 우리는 국가가 좋은 해결책을 마련해 달라고 요구해요.", "C1", 72, "housing", "salary_and_state_solution_for_housing", "speech", "request", "mixed", "high", "long_source|source_ambiguity", "flagged"),
    665: item("I am not against marriage, but it is not suitable unless you have a good job and a home that can support you. People today should not think about marriage before building a future, arranging housing, and finding a stable place to live.", "나는 결혼에 반대하는 게 아니지만, 자신을 부양할 좋은 직장과 집이 없으면 적절하지 않아요. 요즘 사람들은 결혼을 생각하기 전에 미래를 만들고 집을 마련하며 안정적인 거처를 찾아야 해요.", "C1", 78, "housing", "stable_work_and_home_before_marriage", "speech", "opinion", "mixed", "high", "long_source|source_ambiguity", "flagged"),
    666: item("To rent, marry, establish a home, and take on responsibility, you need an income.", "집을 빌리고 결혼하고 가정을 꾸려 책임을 지려면 수입이 있어야 해요.", "A2", 24, "housing", "income_required_for_family_responsibility", "speech", "information", "neutral", "low", "", "draft"),
    667: item("As for me, I am approaching marriage, but I cannot move forward: I would have to rent a home, support my wife, and pay for food, drink, water, electricity, and many other things.", "나는 결혼을 앞두고 있지만 도저히 진행할 수가 없어요. 집을 빌리고 아내를 부양하며 음식과 음료, 물과 전기 등 많은 것을 부담해야 해요.", "B2", 64, "housing", "marriage_responsibility_and_household_costs", "conversation", "opinion", "colloquial", "high", "long_source|source_ambiguity", "flagged"),
    668: item("Welcome to another episode of ‘Very Frank.’ Today we are asking Algerian young people what has kept them from marrying until now, and we will hear their answers.", "‘아주 솔직하게’의 새 회차에 오신 것을 환영해요. 오늘은 알제리 청년들이 지금까지 결혼하지 못한 이유를 묻고 그들의 답을 들어 볼 거예요.", "B1", 38, "social_media", "interview_about_youth_and_marriage", "interview", "greeting", "neutral", "low", "", "draft"),
    669: item("Are you married, brother? No. Why have you not married yet? Because there are things that stop you: you need a proper job, and your life is still incomplete while you study. After 24 or 25 you intend to work, but finding a job in our country is difficult.", "결혼했어요, 형제여? 아니요. 왜 아직 결혼하지 않았어요? 결혼을 막는 일들이 있기 때문이에요. 제대로 된 직장이 필요하고 공부하는 동안 삶이 아직 완성되지 않았어요. 24~25살 이후에 일하려고 하지만 우리나라에서 직장을 구하기가 어려워요.", "B2", 70, "work", "youth_employment_and_delayed_marriage", "interview", "answer", "colloquial", "high", "long_source|source_ambiguity", "flagged"),
    670: item("Nothing much—start a project, if it succeeds. The first issue is that young people generally do not have jobs, and we lack work that can guarantee the future.", "별다른 건 없어요. 프로젝트를 시작해서 잘되면 돼요. 가장 큰 문제는 청년 대부분에게 일이 없고 미래를 보장할 수 있는 직장이 없다는 거예요.", "B1", 46, "work", "youth_unemployment_and_future_security", "interview", "opinion", "colloquial", "medium", "source_ambiguity", "flagged"),
    671: item("Maybe I have not found a girl who suits me, or perhaps God has not written it yet. I searched and did not find one; I may be engaged to a girl from my neighborhood, but the exact wording is unclear.", "나에게 맞는 여자를 아직 못 찾았거나 하느님이 아직 정해 주지 않으셨을지도 몰라요. 찾아봤지만 못 찾았어요. 동네 여자와 약혼했을 수도 있다는 말처럼 들리지만 정확한 표현은 불분명해요.", "B2", 62, "family_relationships", "uncertainty_about_finding_a_partner", "interview", "opinion", "colloquial", "high", "idiom_culture|source_ambiguity", "flagged"),
    672: item("If you find a job with a small salary, around eighteen, you might marry with one million five hundred and build a home, but you cannot buy land. Earning one million eight hundred in a month does not support you.", "약 18 정도의 적은 급여를 받는 직장을 구하면 150만으로 결혼하고 집을 마련할 수도 있지만 땅을 살 수는 없어요. 한 달 180만을 버는 것으로는 생활할 수 없어요.", "C1", 76, "housing", "low_salary_cannot_fund_home_purchase", "interview", "opinion", "mixed", "high", "long_source|source_ambiguity", "flagged"),
    673: item("Marriage often comes to my mind. On the other hand, a person may be thinking about building his life, but if they have not gone to ask for her hand, they cannot say anything yet.", "결혼이 자주 생각나요. 반대로 어떤 사람은 자기 삶을 꾸리려고 생각하고 있을 수 있지만, 아직 청혼하러 가지 않았다면 아무것도 말할 수 없어요.", "B2", 58, "family_relationships", "thinking_about_marriage_without_proposal", "interview", "opinion", "colloquial", "high", "source_ambiguity", "flagged"),
    674: item("What keeps me from marrying is the lack of a job, a home, and a car. In this country many things are missing and life is expensive. It is not like Europe, although life can look fine; whether you have your rights here is left partly unclear.", "내가 결혼하지 못하는 이유는 직장과 집과 차가 없기 때문이에요. 이 나라에는 부족한 것이 많고 생활비가 비싸요. 유럽처럼 앞서 있지는 않지만 삶이 괜찮아 보일 때도 있어요. 여기서 권리를 갖는다는 말의 일부는 불분명해요.", "C1", 80, "housing", "missing_resources_and_expensive_life", "interview", "opinion", "mixed", "high", "long_source|source_ambiguity", "flagged"),
    675: item("Housing? Not yet. My siblings have to marry before me; they are about thirty and twenty-eight, so my turn comes later. Yes, may God reward you. Everyone has their own circumstances.", "집이요? 아직 없어요. 내 형제들이 나보다 먼저 결혼해야 해요. 한 명은 서른쯤이고 다른 한 명은 스물여덟쯤이라 내 차례는 나중이에요. 네, 하느님이 보답하시길 바라요. 사람마다 사정이 있어요.", "B1", 48, "family_relationships", "siblings_and_order_of_marriage", "conversation", "answer", "colloquial", "high", "source_ambiguity", "flagged"),
    676: item("‘Abdelq?’ ‘What?’ The following is a rapid, comic exchange about trousers and a sister; the names, clothing wording, and exact action are unclear.", "‘압드크?’ ‘뭐요?’ 이어지는 말은 바지와 누이에 관한 빠르고 코믹한 대화인데, 이름과 옷차림 표현, 정확한 행동은 불분명해요.", "C1", 74, "humor", "unclear_comic_exchange_about_clothes", "joke", "question", "slang", "high", "idiom_culture|source_ambiguity", "flagged"),
    677: item("She is with Chachra. The speaker jokes about trousers and someone’s thighs, then shifts to a sardine refrain and a new table or bargain; most of the slang is unclear.", "그녀는 샤슈라와 함께 있어요. 화자는 바지와 누군가의 허벅지를 농담하고, 이어 정어리 후렴과 새 상이나 거래로 넘어가요. 속어 대부분은 불분명해요.", "C1", 84, "humor", "unclear_sardine_and_body_slang", "joke", "narration", "vulgar", "high", "idiom_culture|long_source|source_ambiguity", "flagged"),
    678: item("The sardine seller has ‘Boulbou’; do you hear me saying sardines? ‘Boulbou’ is not something I work with, and the phrase about something that drains people and those who left the country is unclear. It ends with an insult.", "정어리 장수에게 ‘불부’가 있어요. 내가 정어리라고 말하는 게 들려요? ‘불부’는 내가 다루는 것이 아니고, 사람을 빨아들이는 것과 나라를 떠난 사람들에 대한 표현은 불분명해요. 끝에는 욕설이 나와요.", "C1", 88, "humor", "unclear_sardine_seller_wordplay", "joke", "description", "vulgar", "high", "idiom_culture|long_source|source_ambiguity", "flagged"),
    679: item("I did not ask you to tell me your life; I asked whether Boulbou exists. People from France wanted me to take them Boulbou with chermoula, not sardines. I gave you the sardines yesterday, made them into a prepared dish, and they are still in my fridge.", "나는 네 인생을 말해 달라고 한 게 아니에요. 불부가 있는지 물었어요. 프랑스에서 온 사람들이 불부를 셰르물라와 함께 가져다 달라고 했지 정어리를 달라고 한 게 아니에요. 어제 네게 정어리를 주고 요리해 두었는데 아직 냉장고에 있어요.", "C1", 82, "food", "sardine_and_chermoula_misunderstanding", "conversation", "disagreement", "vulgar", "high", "code_switching|long_source|source_ambiguity", "flagged"),
    680: item("You have a Boulbou face—go inside. I will twist you up; what, do you think you are a rocket and want to blow me up? Mustafa? Come here, brother. This sardine seller thinks he is Arnold. The threats are comic and not resolved literally.", "너는 불부 같은 얼굴이야. 안으로 들어가. 너를 비틀어 버릴 거야. 네가 로켓이라도 돼서 나를 폭파하려는 줄 알아? 무스타파? 이리 와, 형제여. 이 정어리 장수는 자신이 아널드인 줄 알아요. 위협은 코믹한 말싸움이며 문자 그대로 확정하지 않아요.", "C1", 90, "humor", "comic_threats_in_sardine_argument", "joke", "warning", "vulgar", "high", "idiom_culture|long_source|source_ambiguity", "flagged"),
    681: item("Run away and take your hand off the chain. I got angry—go to him and hit him. Mustafa is celebrated with blows from top to bottom; the action and several names are comic but unclear.", "도망가고 쇠사슬에서 손을 떼요. 내가 화가 났어요. 그에게 가서 때려요. 무스타파를 위아래로 때리는 식으로 말하며, 행동과 몇몇 이름은 코믹하지만 불분명해요.", "C1", 88, "humor", "comic_fighting_and_slapstick", "joke", "command", "vulgar", "high", "idiom_culture|long_source|source_ambiguity", "flagged"),
    682: item("My friend, are you not ashamed to insult a woman? Hey, Hambouk, pretend that I defeat you—may God have mercy on your parents. Listen: the sardine head eats it today. The insults and blessing are partly unclear.", "친구야, 여자를 욕하면서 부끄럽지도 않아요? 이봐, 함부크, 내가 너를 이기는 척해. 하느님이 네 부모님께 자비를 베푸시길 바라요. 들어 봐요. 오늘은 정어리 머리가 그것을 먹어요. 욕설과 축원의 의미는 일부 불분명해요.", "C1", 86, "humor", "insulting_banter_and_sardine_joke", "joke", "warning", "vulgar", "high", "idiom_culture|long_source|source_ambiguity", "flagged"),
    683: item("The woman is being insulted while the speaker says not to embarrass him in front of her. The speaker threatens to show what Mustafa is, to shake him, roll him, and hit him; this is aggressive comic banter with unclear boundaries.", "여자 앞에서 자신을 창피하게 하지 말라고 하면서 그 여자를 모욕하는 말이 이어져요. 화자는 무스타파가 어떤 사람인지 보여 주겠다며 흔들고 굴리고 때리겠다고 해요. 경계가 불분명한 공격적 코미디 말싸움이에요.", "C1", 92, "humor", "aggressive_comic_banter_and_threats", "joke", "warning", "vulgar", "high", "idiom_culture|long_source|source_ambiguity", "flagged"),
    684: item("Give it to her or I will come. You have been telling her to give it since morning and are eating yourself up; you are like a rabbit, tightening yourself. The challenge about frightening or confusing someone is unclear.", "그녀에게 줘요. 아니면 내가 갈 거예요. 아침부터 주라고 하면서 스스로를 괴롭히고 있어요. 토끼처럼 몸을 잔뜩 긴장하고 있어요. 겁을 주거나 혼란스럽게 한다는 도전의 의미는 불분명해요.", "C1", 88, "humor", "unclear_command_and_teasing", "joke", "command", "vulgar", "high", "idiom_culture|long_source|source_ambiguity", "flagged"),
    685: item("I am telling you to give it to him. My shirt is tearing, my eyes are turning blue—God. Give it to him; it will not be finished today. The physical details and target are unclear.", "그에게 주라고 말하고 있어요. 셔츠가 찢어지고 눈이 파래져요. 하느님. 그에게 줘요. 오늘은 끝나지 않을 거예요. 신체 묘사와 대상은 불분명해요.", "C1", 86, "humor", "unclear_physical_slapstick", "joke", "command", "vulgar", "high", "idiom_culture|source_ambiguity", "flagged"),
    686: item("Mustafa, I did not tell you to be a wall or hit the window. Go to him, strike him with your head, kick his stomach, and hit him in the eye. The violent imagery is framed as comic banter, and the exact action is unclear.", "무스타파, 내가 너에게 벽이 되거나 창문을 치라고 한 게 아니에요. 그에게 가서 머리로 치고 배를 차고 눈을 때려요. 폭력적인 이미지는 코믹한 말싸움으로 보이지만 정확한 행동은 불분명해요.", "C1", 94, "humor", "comic_violent_imagery", "joke", "command", "vulgar", "high", "idiom_culture|long_source|source_ambiguity", "flagged"),
    687: item("I do not want one, two, or three to go. Mother is calling, and your parents are calling me; then Oran, go safely, go in peace. The ending and the speaker changes are unclear.", "한 명, 두 명, 세 명이 가는 것을 원하지 않아요. 어머니가 부르고 부모님이 나를 부르는 듯해요. 그러고는 오랑에게 안전하게, 평안히 가라고 말해요. 끝부분과 화자 전환은 불분명해요.", "C1", 82, "humor", "unclear_farewell_after_comic_fight", "joke", "wish", "vulgar", "high", "idiom_culture|long_source|source_ambiguity", "flagged"),
    688: item("You mocked Mustafa and looked down on him; today I will settle things with you. You hit him and then tell the other person to go away because you have no words with them. The comic fight and speaker boundaries are unclear.", "무스타파를 놀리고 업신여겼으니 오늘 너와 결판을 내겠다고 해요. 그를 때린 뒤 다른 사람에게는 자신이 할 말이 없으니 가라고 해요. 코믹한 싸움과 화자 경계는 불분명해요.", "C1", 90, "humor", "comic_fight_and_speaker_shift", "joke", "warning", "vulgar", "high", "idiom_culture|long_source|source_ambiguity", "flagged"),
    689: item("No one gets away: give him a blow in the eye. Repeat it, repeat it, hit him again; he deserves it. There is no escape and no one can save him. The aggressive line is presented as banter, not a verified instruction.", "아무도 빠져나가지 못해요. 그의 눈을 때려요. 다시, 다시 말하고 또 때려요. 그는 그럴 만해요. 도망도 구해 줄 사람도 없어요. 공격적인 말이지만 실제 지시라고 확인되지는 않는 말싸움이에요.", "C1", 92, "humor", "aggressive_banter_about_fighting", "joke", "warning", "vulgar", "high", "idiom_culture|source_ambiguity", "flagged"),
    690: item("No rescue, nothing—what is this, a piece of meat? A half-pot has put you in a state. The food and container images are comic, but the exact punchline is unclear.", "구해 줄 사람도 없고 아무것도 없어요. 이게 뭐예요, 고기 한 조각인가요? 반쪽 냄비가 당신을 이런 상태로 만들었어요. 음식과 그릇 이미지는 코믹하지만 정확한 말장난은 불분명해요.", "C1", 84, "humor", "food_and_container_punchline", "joke", "exclamation", "vulgar", "high", "idiom_culture|source_ambiguity", "flagged"),
    691: item("I am telling you: tease him. Tell me how I can take your head—your head is far from me—and grab you by the thigh; the remaining threat is unclear.", "그를 놀리라고 말해요. 네 머리를 어떻게 잡을지 말해 봐요. 네 머리는 나에게서 멀리 있고, 허벅지를 잡겠다는 식의 나머지 위협은 불분명해요.", "C1", 90, "humor", "unclear_physical_threat_banter", "joke", "warning", "vulgar", "high", "idiom_culture|source_ambiguity", "flagged"),
    692: item("Oh, you knocked me down with the head of a sardine; I am sitting here. The line is a comic reaction, but the exact action is unclear.", "아, 네가 정어리 머리로 나를 넘어뜨렸어요. 나는 여기 앉아 있어요. 코믹한 반응이지만 정확한 행동은 불분명해요.", "B2", 70, "humor", "sardine_head_slapstick", "joke", "exclamation", "vulgar", "high", "source_ambiguity", "flagged"),
    693: item("Here is the sardine; there is no more time. The sardine seller and the Boulbou seller are mentioned: bring Boulbou or it is not over.", "여기 정어리가 있어요. 더는 시간이 없어요. 정어리 장수와 불부 장수가 언급돼요. 불부를 가져오지 않으면 끝나지 않아요.", "B2", 76, "food", "sardine_and_boulbou_vendor_banter", "joke", "command", "vulgar", "high", "idiom_culture|source_ambiguity", "flagged"),
    694: item("Until ten in the morning I did not see a woman without makeup or styling. I came to look at what she was doing, but there was nothing; even the man we were talking about was not there. The scene is partly unclear.", "아침 10시까지 화장이나 스타일링을 하지 않은 여자를 한 명도 보지 못했어요. 그녀가 무엇을 하는지 보러 왔지만 아무것도 없었고, 우리가 말하던 남자도 없었어요. 장면은 일부 불분명해요.", "C1", 78, "daily_life", "commentary_on_makeup_and_neighbors", "conversation", "description", "slang", "high", "long_source|source_ambiguity", "flagged"),
    695: item("She started making a fuss—what luck. Why are you going out with this attitude to confront him when you did not meet him? You want to eat everyone; where are you going with that attitude? The exchange is partly unclear.", "그녀가 소란을 피우기 시작했어요. 참 운이 좋네요. 그를 만나지도 못했는데 왜 그런 태도로 나가서 따지려 해요? 모두를 잡아먹을 듯하네요. 그런 태도로 어디로 가는 거예요? 대화는 일부 불분명해요.", "C1", 82, "family_relationships", "argument_about_confronting_someone", "conversation", "complaint", "slang", "high", "idiom_culture|source_ambiguity", "flagged"),
    696: item("Come, let me tell you: in our house I live and behave as I want, and it is none of your business, sister. Remember that I am in my in-laws' house, not yours. When the housing is in your name, then you can tell me what to do.", "이리 와, 말해 줄게요. 우리 집에서는 내가 원하는 대로 살고 행동하니 네가 상관할 일이 아니야, 언니. 나는 네 집이 아니라 시댁에 있다는 걸 기억해. 집이 네 이름으로 되어 있을 때나 나에게 이래라저래라 해.", "C1", 78, "family_relationships", "in_laws_home_and_housing_authority", "conversation", "disagreement", "slang", "high", "idiom_culture|long_source|source_ambiguity", "flagged"),
    697: item("Come, let me tell you: put this in your head—you are at my place, so swallow it. The following insult or response about learning to speak is unclear.", "이리 와, 말해 줄게. 네가 내 집에 있다는 걸 머릿속에 넣고 받아들여. 이어지는 ‘말하는 법을 배웠네’라는 식의 모욕이나 응답은 불분명해.", "B2", 68, "family_relationships", "argument_about_control_of_home", "conversation", "command", "slang", "high", "idiom_culture|source_ambiguity", "flagged"),
    698: item("You have started speaking in our meanings. I do not deal with these matters; I keep them in my head. You are taking things too far, and I have nothing more to say to you. The wording is partly unclear.", "너는 이제 우리 식의 의미로 말하기 시작했어. 나는 이런 일을 상대하지 않고 머릿속에 담아 둬. 네가 너무 심하게 나가서 더는 할 말이 없어. 표현은 일부 불분명해.", "B2", 70, "family_relationships", "argument_about_shared_meanings", "conversation", "disagreement", "slang", "high", "idiom_culture|source_ambiguity", "flagged"),
    699: item("Look at you, a scorpion—you have made your tongue sharp. You were not like this on the first day. When you came in, I was talking to you, but now you insult me in my house; when your father-in-law comes, I will settle it with him.", "너를 봐, 전갈 같아. 혀를 날카롭게 만들었네. 첫날에는 이렇지 않았잖아. 네가 들어왔을 때는 내가 너와 이야기했지만 이제 내 집에서 나를 모욕하니, 네 장인이 오면 그와 해결하겠어.", "C1", 86, "family_relationships", "family_argument_and_father_in_law", "conversation", "warning", "slang", "high", "idiom_culture|long_source|source_ambiguity", "flagged"),
    700: item("Good morning. Are you not ashamed of the noisy work? I came from outside hearing the noise; you humiliated me with the neighbors and exposed me. What do you have? What else is going on?", "좋은 아침이에요. 시끄러운 일을 하면서 부끄럽지도 않아요? 밖에서 소리를 들으며 왔고, 당신들이 이웃들 앞에서 나를 창피하게 하고 드러냈어요. 무슨 일이에요? 또 무슨 일이 있나요?", "B2", 68, "family_relationships", "noise_and_embarrassment_with_neighbors", "conversation", "complaint", "slang", "high", "source_ambiguity", "flagged"),
    701: item("Man, fear God. I am talking to her and telling her to get up, take care of it, or do something. When I went out, I saw what happened, but the rest of the exchange is unclear.", "이봐요, 하느님을 두려워하세요. 나는 그녀에게 일어나서 처리하거나 무언가 하라고 말하고 있어요. 밖에 나가 보니 무슨 일이 있었지만 나머지 대화는 불분명해요.", "B2", 70, "family_relationships", "admonition_about_household_problem", "conversation", "command", "slang", "high", "source_ambiguity", "flagged"),
    702: item("I saw a woman leaving while I was coming in. Explain the problem between you and her; tell me directly what happened.", "내가 들어오는데 한 여자가 나가는 것을 봤어요. 당신과 그 여자 사이의 문제를 설명하고 무슨 일이 있었는지 솔직히 말해 주세요.", "B1", 42, "family_relationships", "asking_about_a_dispute", "conversation", "question", "colloquial", "medium", "source_ambiguity", "flagged"),
    703: item("I still do not know what the problem is. Does your brother work? There is cramped housing, and your brother does not understand himself. Explain it to me; tell me what happened, brother.", "아직도 문제가 무엇인지 모르겠어요. 네 오빠는 일해요? 집이 좁고 네 오빠는 자기 상황도 이해하지 못해요. 나에게 설명해 줘요. 무슨 일이 있었는지 말해 줘, 형제여.", "B2", 66, "family_relationships", "clarifying_work_and_housing_problem", "conversation", "question", "colloquial", "high", "long_source|source_ambiguity", "flagged"),
    704: item("Listen. I met a man when I arrived; he was doing well, was safe and well, and had a place to live.", "들어 봐요. 내가 왔을 때 한 남자를 만났는데, 그는 잘 지내고 건강했으며 살 곳도 있었어요.", "A2", 28, "housing", "meeting_someone_with_housing", "conversation", "narration", "colloquial", "medium", "source_ambiguity", "flagged"),
}

engine.BATCH_ID = BATCH_ID
engine.BASE_COMMIT = BASE_COMMIT
engine.PROMPT_VERSION = PROMPT_VERSION
engine.TARGET_START = TARGET_START
engine.TARGET_END = TARGET_END
engine.BATCH_OUT = BATCH_OUT
engine.MANIFEST_OUT = MANIFEST_OUT
engine.QA_OUT = QA_OUT
engine.RAW = RAW


if __name__ == "__main__":
    if hasattr(engine.sys.stdout, "reconfigure"):
        engine.sys.stdout.reconfigure(encoding="utf-8")
    print(engine.json.dumps(engine.build(), ensure_ascii=False, indent=2))
