"""Build source-only MADOran enrichment Batch 15 for Sentno 897..960."""
from __future__ import annotations

import json
import sys
from pathlib import Path

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts import build_madoran_enrichment_batch10 as engine
from scripts.build_madoran_enrichment_scaffold import ROOT

BATCH_ID = "MADORAN-ENRICH-015"
BASE_COMMIT = "8e0dad7"
PROMPT_VERSION = "madoran-source-enrichment-v15"
TARGET_START = 897
TARGET_END = 960
BATCH_OUT = ROOT / "data/master/enrichment/batches/batch15_sentno_0897_0960.tsv"
MANIFEST_OUT = ROOT / "data/master/enrichment/batches/batch15_manifest.json"
QA_OUT = ROOT / "data/master/qa/madoran_enrichment_batch15_generation_qa.json"
BATCH_FIELDS = engine.BATCH_FIELDS
item = engine.item


def r(english, korean, domain, topic, genre="conversation", speech="description", register="colloquial", context="high", flags="source_ambiguity", state="flagged", cefr="B2", score=60):
    return item(english, korean, cefr, score, domain, topic, genre, speech, register, context, flags, state)


RAW = {
    897: r("The speaker says they do not know about the matter and that the listener knows how Zino is. They say they are not upset with Zino, their younger brother, invite the listener to have coffee, and say they are tired. They ask the listener to come, while saying they will go upstairs, shower, and return to talk with their brother.", "화자는 그 일에 대해서는 모르고 지노가 어떤지 상대도 안다고 해요. 지노는 자신의 어린 남동생이며 그에게 화난 것이 아니라며 커피를 마시라고 해요. 자신은 피곤하다고 하면서 상대에게 오라고 하고, 위층에 올라가 샤워한 뒤 동생과 이야기하고 돌아오겠다고 해요.", "daily_life", "coffee_invitation_and_return_after_shower", "conversation", "request", "colloquial", "high", "", "draft", "A2", 30),
    898: r("The speaker tells the other person to rest and let them go, saying they are tired and will go upstairs to rest. They offer to pay for the coffee later, ask what the other person is carrying, and ask what they want to do with the opaque item described as an imprint or printout.", "화자는 상대에게 쉬라고 하며 자신을 보내 달라고 해요. 피곤해서 위층에 올라가 쉬겠다고 하고, 나중에 커피값을 내겠다고 해요. 상대가 무엇을 들고 있는지 묻고, 불투명한 ‘임프림몽’ 또는 출력물 같은 물건으로 무엇을 하려는지 물어요.", "daily_life", "coffee_debt_and_printed_item", "conversation", "question", "colloquial", "high", "code_switching|source_ambiguity"),
    899: r("The speaker says the printout or machine is faulty. They found it at a bargain price, and Zino understands two relevant matters and will redo it so they can sell it again. The other person tells them to put it there and offers to buy it from them.", "화자는 그 출력물이나 기계가 고장 났다고 해요. 그것을 할인 물건으로 찾았고, 지노가 관련된 두 가지 일을 이해하니 다시 손봐서 재판매하겠다고 해요. 상대는 그것을 여기에 놓으라며 자신이 사겠다고 해요.", "shopping", "repairing_and_reselling_a_faulty_item", "conversation", "suggestion", "mixed", "high", "source_ambiguity"),
    900: r("The speaker says they do not know whether it can be redone. They ask to be allowed to redo it and bring it back, then ask whether the other person wants to sell it.", "화자는 그것을 다시 손볼 수 있을지 모르겠다고 해요. 자신이 다시 손봐서 가져올 때까지 기다려 달라고 하고, 상대가 그것을 팔고 싶은지 물어요.", "shopping", "uncertain_repair_and_resale", "conversation", "question", "colloquial", "medium", "source_ambiguity"),
    901: r("The speaker jokingly asks whether the other person wants to drive them crazy. They say they had asked to be allowed to redo it, and promise that once it is redone they will bring it and give it away for free in good condition. The exchange ends with greetings.", "화자는 상대가 자신을 미치게 하려는 것이냐고 장난스럽게 말해요. 다시 손보게 해 달라고 했고, 손본 뒤에는 좋은 상태로 가져와 공짜로 주겠다고 해요. 이어 서로 인사를 나눠요.", "shopping", "repair_offer_and_free_gift", "conversation", "suggestion", "colloquial", "medium", "source_ambiguity"),
    902: r("The speaker points to the machine the other person is carrying and worries that someone might enter or do something expressed by the opaque phrase ‘fo biye’ while they are asleep. They ask why, suggesting that Marzouq and Zino are decent people and not involved in that opaque matter.", "화자는 상대가 들고 있는 기계를 가리키며, 자신들이 자는 동안 누군가 불투명한 ‘fo biye’ 일을 할까 봐 걱정해요. 왜 그러겠느냐고 하면서 마르주크와 지노는 괜찮은 사람이고 그 일과 관련이 없다고 말해요.", "housing", "suspicion_about_a_machine_and_opaque_activity", "conversation", "warning", "mixed", "high", "code_switching|source_ambiguity"),
    903: r("The speaker asks how the situation can be dismissed when the people involved have lived there for more than a year, paid their rent, eaten and drunk there, and have a car. They say that tomorrow they will send Hussein after them to bring back a dossier, including hidden or covered material.", "화자는 관련된 사람들이 1년 넘게 그곳에 살면서 임대료를 내고 먹고 마셨으며 차도 있는데 어떻게 이 일을 무시할 수 있느냐고 해요. 내일 후세인을 그들 뒤에 보내 숨겨지거나 덮인 자료가 들어 있는 서류를 가져오게 하겠다고 해요.", "crime_safety", "investigating_long_term_occupants", "conversation", "warning", "mixed", "high", "long_source|source_ambiguity"),
    904: r("The speaker says not to put it off until tomorrow but to do it now. They greet Uncle Ali and say that when the people rest, the listener should search their room that night and then sleep peacefully.", "화자는 내일까지 미루지 말고 지금 하라고 해요. 알리 아저씨에게 인사한 뒤, 그들이 쉬면 그날 밤 방을 뒤져 보라고 하며 안심하고 자라고 해요.", "crime_safety", "searching_a_room_at_night", "conversation", "command", "mixed", "high", "source_ambiguity"),
    905: r("The speakers greet Aunt Halima and ask how she is and whether her health is good. She says she is fine, and the other speaker blesses her and calls her mother.", "화자들은 할리마 이모에게 인사하며 잘 지내는지, 건강은 괜찮은지 물어요. 이모가 괜찮다고 하자 상대는 이모를 축복하며 어머니처럼 부드럽게 불러요.", "daily_life", "greeting_aunt_halima", "conversation", "greeting", "colloquial", "low", "source_ambiguity"),
    906: r("The speakers greet Aunt Zoulikha and ask how she is. They exchange blessings, ask how Marzouq is and how Dalila is, and ask where she has been because she has not been seen for a week.", "화자들은 줄리카 이모에게 인사하고 잘 지내는지 물어요. 서로 축복의 말을 주고받고, 마르주크와 달릴라는 어떤지, 일주일 동안 보이지 않았는데 어디 있었는지 물어요.", "daily_life", "greeting_and_asking_about_absence", "conversation", "greeting", "colloquial", "medium", "source_ambiguity"),
    907: r("The person says they were not there because they were working in Algeria and asks what kind of job it was. They answer that they were working, and the other person wishes them strength.", "상대는 그곳에 없었고 알제리에서 일하고 있었다고 해요. 어떤 일이었는지 묻자 그냥 일하고 있었다고 답하고, 다른 사람은 힘내라고 말해요.", "work", "absence_for_work_in_algeria", "conversation", "information", "colloquial", "medium", "source_ambiguity"),
    908: r("The speaker asks whether they should make sandwiches. The other person asks for something to eat, and the speaker says they will make whatever is wanted because they know the person's preference. They then call Zino.", "화자는 샌드위치를 만들어 줄지 묻고, 상대는 먹을 것을 아무거나 만들어 달라고 해요. 화자는 상대가 무엇을 좋아하는지 안다며 원하는 대로 해 주겠다고 하고 지노를 불러요.", "food", "making_a_sandwich_for_a_guest", "conversation", "suggestion", "colloquial", "medium", "source_ambiguity"),
    909: r("The speaker says Ali is no good for coffee or anything else and only knows what is in the opaque place or phrase ‘lmaba’. They call him a free or foolish person who is turning strange, then say to leave him alone.", "화자는 알리가 커피도 아무것도 제대로 못하고 불투명한 장소나 표현 ‘lmaba’에 무엇이 있는지만 안다고 해요. 그를 공짜로 구는 어리석은 사람, 이상해지는 사람처럼 말한 뒤 그를 내버려 두자고 해요.", "daily_life", "insulting_ali_and_leaving_him_alone", "conversation", "complaint", "offensive", "high", "source_ambiguity"),
    910: r("The speaker repeatedly tells the listener to come and see their brother and acknowledge him. They say that if they had been allowed to negotiate with the foolish man, they would have dealt with him harshly; the final bodily expression is preserved as an idiom or threat.", "화자는 상대에게 와서 자신의 형제나 동생을 보고 인정하라고 반복해 말해요. 그 어리석은 사람과 협상하게 두었다면 심하게 처리했을 것이라고 하며, 마지막 신체 표현은 관용적 표현이나 위협으로 보존해요.", "daily_life", "demand_to_acknowledge_a_brother", "conversation", "warning", "offensive", "high", "source_ambiguity"),
    911: r("The speaker says there is no such thing as legs or anything else and tells the listener to look at the money. They ask what the listener's brother will bring, swear that the listener is not paying attention, and tell them to acknowledge it first.", "화자는 다리도 아무것도 없다고 하며 돈을 보라고 해요. 상대의 형제나 동생이 무엇을 가져올지 묻고, 상대가 제대로 보고 있지 않다고 맹세하며 먼저 인정하라고 해요.", "finance", "dispute_about_money_and_acknowledgment", "conversation", "disagreement", "offensive", "high", "source_ambiguity"),
    912: r("The speaker says they have brought it and will store it in the refrigerator. They invite the other person to smell how good the money is, imagine a poor man inside his villa, and ask whether the other person will accept marrying them that night.", "화자는 그것을 가져왔으니 냉장고에 보관하겠다고 해요. 상대에게 돈 냄새가 얼마나 좋은지 맡아 보라고 하고, 가엾은 남자가 자기 별장 안에 있는 모습을 상상해요. 그날 밤 상대가 자신과 결혼해 줄지 묻는 말로 이어져요.", "finance", "money_joke_and_marriage_proposal", "conversation", "suggestion", "mixed", "high", "source_ambiguity"),
    913: r("The speaker tells the other person to put down the money and asks who does not like money. They say they want a life of enjoyment and fun.", "화자는 상대에게 돈을 놓으라고 하며 돈을 싫어하는 사람이 누가 있느냐고 해요. 자신은 삶과 즐거움, 재미를 원한다고 말해요.", "finance", "money_and_desire_for_enjoyment", "conversation", "opinion", "colloquial", "medium", "source_ambiguity"),
    914: r("The speaker welcomes Mr. Jamal, tells him to sit and calm himself, and asks where a document is. They say the loss they will suffer if they do not travel today is serious, ask why the matter has taken so long, and say that the case has lasted so long that even the lawyer can do nothing.", "화자는 جمال 씨를 맞이해 앉아서 진정하라고 해요. 오늘 떠나지 않으면 입을 손실이 크다고 하며 문서가 어디 있는지 묻고, 왜 이렇게 오래 걸리느냐고 해요. 사건이 너무 오래 끌어 변호사조차 아무것도 할 수 없다고 말해요.", "politics_public_affairs", "delayed_case_and_travel_loss", "conversation", "complaint", "mixed", "high", "long_source|source_ambiguity"),
    915: r("They return to the factory case. The speaker says the factory matter has a final decision that they have accepted, while the others are bringing a case against them; they will contest it in court and see what the court decides.", "화자들은 공장 사건으로 돌아가요. 화자는 공장 문제에 최종 결정이 내려져 자신이 받아들였지만, 상대방이 자신을 상대로 소송을 제기했으니 법정에서 다투고 법원이 어떻게 판단하는지 보겠다고 해요.", "politics_public_affairs", "factory_case_and_court_contest", "conversation", "information", "mixed", "high", "source_ambiguity"),
    916: r("The other person says a decision was issued against Mr. Jamal yesterday and that the case is not simple: an unfair dismissal affected five hundred male and female workers at once, leaving them unemployed.", "상대는 어제 جمال 씨에게 불리한 결정이 나왔고 사건이 간단하지 않다고 해요. 부당해고로 남녀 노동자 500명이 한꺼번에 일자리를 잃고 실업자가 되었다고 말해요.", "politics_public_affairs", "mass_unfair_dismissal", "conversation", "information", "mixed", "high", "long_source|source_ambiguity"),
    917: r("The factory owner says there is nothing they can do: the factory was shut down, and restarting the operation will take at least a year. The adviser says that, if they take the advice, they should restore all the workers' rights and negotiate so they can return to work.", "공장 주인은 자신이 할 수 있는 일이 없다며 공장이 문을 닫았고 다시 시작하려면 적어도 1년이 걸린다고 해요. 조언자는 자신의 말을 따른다면 노동자들의 권리를 모두 회복하고 협상해서 다시 일하게 해야 한다고 말해요.", "politics_public_affairs", "factory_closure_and_worker_rights", "conversation", "suggestion", "mixed", "high", "long_source|source_ambiguity"),
    918: r("The speaker says the press has turned the whole world against Mr. Jamal. They plan to bring machines that work by themselves and say they will not need workers, sarcastically asking what the workers they have will do, polish their shoes.", "화자는 언론이 جمال 씨에게 등을 돌리게 만들었다고 해요. 혼자 작동하는 기계를 가져와 노동자가 필요 없게 하겠다고 하며, 지금 있는 노동자들은 무슨 일을 하겠느냐, 자신의 구두를 닦겠느냐고 비꼬아요.", "politics_public_affairs", "automation_and_worker_displacement", "conversation", "complaint", "mixed", "high", "source_ambiguity"),
    919: r("The speaker apologizes to Mr. Jamal and says they are close to him in this case but cannot help. They say the law in this situation is with the workers and advise him to restore all their rights, negotiate with them, and continue with the union.", "화자는 جمال 씨에게 미안하다며 이 사건에서는 그와 가깝지만 아무것도 도울 수 없다고 해요. 이 상황에서는 법이 노동자 편이라며 그들의 권리를 모두 회복하고 협상하며 노조와 계속 논의하라고 조언해요.", "politics_public_affairs", "advice_to_negotiate_with_workers_and_union", "conversation", "suggestion", "mixed", "high", "long_source|source_ambiguity"),
    920: r("Mr. Jamal says he will give them nothing and that he is leaving.", "جمال 씨는 그들에게 아무것도 주지 않겠다며 떠나겠다고 해요.", "politics_public_affairs", "refusal_to_compensate_workers", "conversation", "refusal", "mixed", "medium", "source_ambiguity"),
    921: r("The speaker says this is the time of Hosni, may God have mercy on him, and that Jamal Awad's story is now in the trash so that he may learn not to take poor people's rights. They say he brought it on himself.", "화자는 이제 고인이 된 호스니의 때를 떠올리며, جمال عواد의 이야기는 가난한 사람들의 권리를 빼앗지 말라는 교훈으로 쓰레기통에 들어갔다고 말해요. 그가 자초한 일이라고 해요.", "politics_public_affairs", "public_moralizing_about_a_factory_owner", "conversation", "complaint", "offensive", "high", "source_ambiguity"),
    922: r("The speaker describes a millionaire who takes poor people's rights. They say that someone who pays two million gets what is due and deserves to be taught a lesson. They point to a card belonging to Mr. Cherif and another button or item in the trash; these references remain partly opaque.", "화자는 가난한 사람들의 권리를 빼앗는 백만장자를 말해요. 200만을 내는 사람은 자기 몫을 받으며 그런 사람은 교훈을 얻어야 한다고 해요. 셰리프 씨의 카드와 쓰레기통에 있는 또 다른 단추나 물건을 가리키는데, 일부 지칭은 불투명해요.", "politics_public_affairs", "criticism_of_millionaire_and_opaque_cards", "conversation", "complaint", "offensive", "high", "code_switching|source_ambiguity"),
    923: r("The speaker asks why the cards or items should be burned and says that if they need them they could use them in a fire. They then clarify that each punched card is used for one fire and burned, adding that they still have learned nothing.", "화자는 왜 그것들을 태우느냐고 하며, 필요하면 불에 사용할 수 있다고 말해요. 이어 구멍 난 카드는 각각 한 번의 불에 쓰고 태운다고 설명하면서도 아직 아무것도 배우지 못했다고 해요.", "politics_public_affairs", "burning_punched_cards_and_learning_nothing", "conversation", "question", "mixed", "high", "source_ambiguity"),
    924: r("The speaker agrees that the other person is right and says they know everything. They say there is nothing to eat and that they are dying of hunger.", "화자는 상대가 맞고 모든 것을 안다고 해요. 먹을 것이 아무것도 없으며 배가 고파 죽겠다고 말해요.", "food", "hunger_after_argument", "conversation", "complaint", "colloquial", "medium", "source_ambiguity"),
    925: r("They say Dalila has been asked to bring sandwiches. They wonder why they are still eating Dalila's sandwiches with all their money and why they do not store the money there.", "달릴라에게 샌드위치를 가져와 달라고 부탁했다고 해요. 가진 돈이 모두 있는데도 계속 달릴라의 샌드위치를 먹고 있다며, 왜 돈을 이곳에 보관하지 않는지 물어요.", "food", "sandwiches_and_storing_money", "conversation", "question", "colloquial", "high", "source_ambiguity"),
    926: r("The speaker says the place is known to Ghay or Malik, perhaps because he has cameras everywhere or is ill; the exact reference is unclear.", "화자는 그 장소를 가야나 말리크가 알고 있고, 아마 그가 곳곳에 카메라를 설치했거나 아픈 사람일 수도 있다고 해요. 정확한 지칭은 불분명해요.", "housing", "suspicion_about_a_known_place_and_cameras", "conversation", "warning", "mixed", "high", "source_ambiguity"),
    927: r("The speaker does not want him to know where the money is or how much they pay.", "화자는 그가 돈이 어디 있는지, 자신들이 얼마를 내는지 알기를 원하지 않아요.", "finance", "hiding_money_and_payment_amount", "conversation", "refusal", "colloquial", "medium", "source_ambiguity"),
    928: r("The speaker tells Hosni that it is a serious matter and invokes a generous Lord, but the final threat-like wording is unclear. They say they will not bring up the sandwiches, then another voice tells them to take them upstairs quickly, not forget the money, and says they do not work for free. A mother reassures her child, and hot garantika is served.", "화자는 호스니에게 큰일이라며 자비로운 신을 언급하지만 마지막 위협처럼 들리는 표현은 불분명해요. 샌드위치를 올리지 않겠다고 하자 다른 목소리가 빨리 가져가고 돈을 잊지 말라고 하며 자신은 공짜로 일하지 않는다고 해요. 엄마는 아이에게 걱정하지 말라고 하고 뜨거운 가란티카를 내요.", "food", "sandwich_payment_and_hot_garantika", "conversation", "command", "mixed", "high", "code_switching|long_source|source_ambiguity"),
    929: r("A sister asks how much a bottle of perfume costs, and the answer is two hundred thousand or a similarly uncertain amount. The other person apologizes and says it is forbidden to try or smell it.", "한 자매가 향수 한 병이 얼마인지 묻고, 상대는 20만 또는 그와 비슷한 불확실한 금액이라고 답해요. 이어 미안하지만 그것을 시험해 보거나 맡아 보는 것은 금지되어 있다고 해요.", "shopping", "perfume_price_and_no_testing", "conversation", "question", "colloquial", "medium", "source_ambiguity"),
    930: r("The speaker says they cannot know whether the perfume smells good. The other tells them to look at how the bottle is made, and the speaker decides to take it. They exchange thanks and wishes of help.", "화자는 향이 좋은지 어떻게 알겠느냐고 해요. 상대는 병 모양을 보라고 하고, 화자는 그것을 가져가겠다고 해요. 서로 고맙다는 말과 잘되라는 인사를 나눠요.", "shopping", "choosing_a_perfume_by_its_bottle", "conversation", "information", "colloquial", "medium", "source_ambiguity"),
    931: r("The speaker says this money belongs to Malik and that they will give it to him later. They ask whether it is all his and whether they did not give it to him before.", "화자는 이 돈이 말리크의 것이며 나중에 그에게 주겠다고 해요. 이 돈이 전부 그의 몫인지, 전에 이미 준 것이 아니냐고 물어요.", "finance", "holding_money_for_malik", "conversation", "question", "colloquial", "medium", "source_ambiguity"),
    932: r("They agreed with him on a price, but the speaker says they cannot change their mind a minute later. He made two tarts or cakes and a property certificate, while another part is unclear; the speaker says giving him all this money is too much.", "화자들은 그와 가격을 합의했지만 1분 뒤에 마음을 바꿀 수는 없다고 해요. 그가 타르트나 케이크 두 개와 소유권 증서를 만들었다고 하지만 일부는 불분명하고, 이 돈을 전부 주는 것은 너무 많다고 말해요.", "finance", "price_agreement_and_disputed_payment", "conversation", "disagreement", "mixed", "high", "source_ambiguity"),
    933: r("The speaker launches into a stream of obscene insults against Khairika, attacking his masculinity and mother, calling him a pimp or worthless man, and telling him to keep talking so the speaker can show who they are. The abusive register is part of the source content.", "화자는 카이리카에게 심한 욕설을 쏟아내며 남성성, 어머니, 성적 평판을 공격하고 무가치한 사람처럼 부른 뒤, 계속 말해 보라며 자신이 누구인지 보여 주겠다고 해요. 모욕적인 말투 자체를 원문 내용으로 보존해요.", "daily_life", "obscene_insult_during_argument", "conversation", "complaint", "offensive", "high", "long_source|source_ambiguity"),
    934: r("The speaker uses a highly abusive and partly opaque command, telling the other person to get up in the morning, not leave anyone in peace, leave the speaker alone, and not circle around them; it ends with a vulgar mother-related insult.", "화자는 매우 모욕적이고 일부 불투명한 명령을 하며 아침에 일어나 아무도 편히 두지 말고 자신을 내버려 두며 주변을 맴돌지 말라고 해요. 끝에는 어머니를 겨냥한 심한 욕설이 나와요.", "daily_life", "abusive_command_to_leave_alone", "conversation", "complaint", "offensive", "high", "source_ambiguity"),
    935: r("The speaker insults Zaki, says he knows nothing, tells him to put the machine down and go away, calls him worthless, and orders him to take his foolish things with him. The abusive wording is preserved without normalizing it.", "화자는 자키가 아무것도 모른다고 욕하며 기계를 내려놓고 꺼지라고 해요. 그를 형편없는 사람이라고 부르고 어리석은 물건들을 가지고 가라고 명령해요. 모욕적인 표현은 순화하지 않고 보존해요.", "daily_life", "insulting_zaki_over_a_machine", "conversation", "complaint", "offensive", "high", "source_ambiguity"),
    936: r("The speaker tells Bisha not to make them perform tricks and asks what kind of tricks are meant. They say they are coming to ask for a marriage proposal, while another voice calls the situation a strange proposal and asks how it is supposed to be.", "화자는 비샤에게 자신에게 재주를 부리게 하지 말라고 하며 무슨 재주냐고 물어요. 청혼하러 가는 중이라고 말하지만, 다른 목소리는 이런 청혼이 대체 어떻게 된 것이냐고 해요.", "family_relationships", "confused_marriage_proposal", "conversation", "question", "colloquial", "high", "source_ambiguity"),
    937: r("The speaker insults people who eat with a fork and says they act arrogantly and are unwanted, arriving like excrement and finding nothing satisfactory. They use mother-related profanity and say they want to live normally rather than like Khairika.", "화자는 포크로 먹는 사람들이 거만하게 굴고 아무도 그들을 원하지 않는다며, 아무것도 마음에 들어 하지 않고 아주 모욕적인 모습으로 온다고 욕해요. 어머니를 겨냥한 욕설도 하며 카이리카처럼이 아니라 평범하게 살고 싶다고 말해요.", "daily_life", "obscene_complaint_about_people_and_normal_life", "conversation", "complaint", "offensive", "high", "long_source|source_ambiguity"),
    938: r("A story says that an Algerian man went to France and opened a medical clinic.", "한 알제리 남성이 프랑스로 가서 진료소를 열었다는 이야기예요.", "culture_tradition", "algerian_doctor_in_france", "narrative", "information", "neutral", "low", "source_ambiguity"),
    939: r("The doctor charged one hundred euros for a medical examination or visit.", "의사는 진찰이나 방문 비용으로 100유로를 받았다고 해요.", "culture_tradition", "doctor_charges_for_examination", "narrative", "information", "neutral", "low", "source_ambiguity"),
    940: r("For someone who was not cured, he gave two hundred euros.", "낫지 않은 사람에게는 200유로를 주었다고 해요.", "culture_tradition", "refund_for_no_cure", "narrative", "information", "neutral", "low", "source_ambiguity"),
    941: r("People began flocking to him.", "사람들이 그에게 몰려들기 시작했어요.", "culture_tradition", "crowd_attracted_by_refund", "narrative", "information", "neutral", "low", "source_ambiguity"),
    942: r("One day a Frenchman came to him wanting to trick him.", "어느 날 한 프랑스인이 그를 속이려는 마음으로 찾아왔어요.", "culture_tradition", "frenchman_attempts_to_trick_doctor", "narrative", "information", "neutral", "low", "source_ambiguity"),
    943: r("The Frenchman said that he had lost his sense of taste.", "프랑스인은 미각을 잃었다고 말했어요.", "culture_tradition", "claim_of_lost_taste", "narrative", "information", "neutral", "low", "source_ambiguity"),
    944: r("The doctor told the secretary to bring him bottle number 22.", "의사는 비서에게 22번 병을 가져오라고 했어요.", "culture_tradition", "doctor_requests_bottle_number_22", "narrative", "command", "neutral", "low", "source_ambiguity"),
    945: r("He put a little of it on cotton, and the Frenchman tasted it.", "의사는 그것을 솜에 조금 묻혔고 프랑스인은 맛을 보았어요.", "culture_tradition", "testing_taste_with_bottle", "narrative", "information", "neutral", "low", "source_ambiguity"),
    946: r("The Frenchman asked whether this was the opaque substance or item ‘ziqo’.", "프랑스인은 이것이 불투명한 물질이나 물건 ‘지코’냐고 물었어요.", "culture_tradition", "opaque_ziqo_substance", "narrative", "question", "neutral", "medium", "source_ambiguity"),
    947: r("The doctor congratulated him and said that he now had his sense of taste again.", "의사는 그에게 축하한다고 하며 이제 미각이 돌아왔다고 말했어요.", "culture_tradition", "taste_returned_by_trick", "narrative", "information", "neutral", "low", "source_ambiguity"),
    948: r("The Frenchman was upset and wanted his money back.", "프랑스인은 화가 나서 돈을 돌려받고 싶어 했어요.", "culture_tradition", "customer_demands_money_back", "narrative", "complaint", "neutral", "low", "source_ambiguity"),
    949: r("He tried again or came back and told the doctor that he had lost his memory.", "그는 다시 시도하거나 돌아와서 기억을 잃었다고 의사에게 말했어요.", "culture_tradition", "second_fake_symptom", "narrative", "information", "neutral", "medium", "source_ambiguity"),
    950: r("The doctor again told the secretary to bring bottle number 22.", "의사는 다시 비서에게 22번 병을 가져오라고 했어요.", "culture_tradition", "repeat_bottle_number_22_treatment", "narrative", "command", "neutral", "low", "source_ambiguity"),
    951: r("The doctor said that this bottle was the one for the opaque item ‘ziqo’.", "의사는 그 병이 불투명한 ‘지코’에 쓰는 것이라고 말했어요.", "culture_tradition", "opaque_ziqo_bottle", "narrative", "information", "neutral", "medium", "source_ambiguity"),
    952: r("The Frenchman said that it was good and that his memory had returned.", "프랑스인은 좋다며 기억이 돌아왔다고 말했어요.", "culture_tradition", "memory_returned_by_trick", "narrative", "information", "neutral", "low", "source_ambiguity"),
    953: r("The narrator calls it the height of cunning and spite.", "화자는 이것을 교활함과 악의가 극에 달한 일이라고 말해요.", "culture_tradition", "cunning_and_spite_in_a_joke", "narrative", "opinion", "mixed", "medium", "source_ambiguity"),
    954: r("A parenthetical source note identifies this as ‘337’, an Algerian Oran comedy film.", "괄호 안의 출처 메모는 이것을 ‘337’이라는 알제리 오랑 코미디 영화로 식별해요.", "culture_tradition", "oran_comedy_film_source_note", "expository", "information", "neutral", "low", "", "draft", "A2", 18),
    955: r("The speaker tells the other person to stop their nonsense and says there are two options or people involved. They describe marrying here and being given four children to raise, then mention Benami Lakrish or an unclear proposal involving their father, and tell the other person to follow them.", "화자는 상대에게 허튼소리를 그만하라고 해요. 여기서 결혼하면 네 명의 아이를 받아 함께 키우는 상황을 말하고, بنعمي لاكريش 또는 아버지와 관련된 불투명한 청혼 이야기를 꺼낸 뒤 따라오라고 해요.", "family_relationships", "comic_marriage_and_children_proposal", "conversation", "suggestion", "mixed", "high", "code_switching|long_source|source_ambiguity"),
    956: r("The other person asks where they should follow the speaker, calling them father. The speaker repeats that they should follow.", "상대는 아버지라고 부르며 어디로 따라가야 하느냐고 물어요. 화자는 따라오라고 다시 말해요.", "family_relationships", "following_a_parent_or_elder", "conversation", "request", "colloquial", "medium", "source_ambiguity"),
    957: r("The hosts welcome them and tell them not to worry. The speaker says they are going to inform the tribal sheikh and will return.", "주인은 일행을 환영하며 걱정하지 말라고 해요. 화자는 부족 셰이크에게 알리고 돌아오겠다고 말해요.", "daily_life", "welcoming_visitors_and_informing_a_sheikh", "conversation", "information", "mixed", "medium", "source_ambiguity"),
    958: r("The speaker asks what is wrong with the father and why he is eating himself, an idiomatic or figurative expression of distress.", "화자는 아버지에게 무슨 일이 있기에 자신을 먹는 것처럼 괴로워하느냐고 물어요. 이는 고통이나 초조함을 나타내는 관용적·비유적 표현일 수 있어요.", "daily_life", "father_in_distress", "conversation", "question", "mixed", "high", "idiom_culture|source_ambiguity"),
    959: r("The speaker tells the listener to be quiet because they are in the other group's tribe. The listener agrees but says they have come to do good and want to take the group's daughter.", "화자는 상대 부족의 마을에 있으니 조용히 하라고 해요. 상대는 그곳에 있다는 것을 알지만 좋은 일을 하러 왔고 그들의 딸을 데려가고 싶다고 말해요.", "family_relationships", "marriage_negotiation_in_a_tribal_setting", "conversation", "suggestion", "mixed", "high", "source_ambiguity"),
    960: r("The speaker confirms that they are matchmakers and asks who will take their daughter if the speaker does not take her.", "화자는 자신들이 중매를 하러 왔다고 확인하며, 자신이 데려가지 않으면 그들의 딸을 누가 데려가겠느냐고 물어요.", "family_relationships", "matchmaking_for_a_daughter", "conversation", "suggestion", "mixed", "high", "", "draft", "A2", 26),
}


def build():
    engine.BATCH_ID = BATCH_ID
    engine.BASE_COMMIT = BASE_COMMIT
    engine.PROMPT_VERSION = PROMPT_VERSION
    engine.TARGET_START = TARGET_START
    engine.TARGET_END = TARGET_END
    engine.BATCH_OUT = BATCH_OUT
    engine.MANIFEST_OUT = MANIFEST_OUT
    engine.QA_OUT = QA_OUT
    engine.RAW = RAW
    return engine.build()


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    print(json.dumps(build(), ensure_ascii=False, indent=2))
