"""Build source-only MADOran enrichment Batch 19 for Sentno 1153..1216."""
from __future__ import annotations

import json
import sys
from pathlib import Path

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts import build_madoran_enrichment_batch10 as engine
from scripts.build_madoran_enrichment_scaffold import ROOT

BATCH_ID = "MADORAN-ENRICH-019"
BASE_COMMIT = "7f62fb3"
PROMPT_VERSION = "madoran-source-enrichment-v19"
TARGET_START = 1153
TARGET_END = 1216
BATCH_OUT = ROOT / "data/master/enrichment/batches/batch19_sentno_1153_1216.tsv"
MANIFEST_OUT = ROOT / "data/master/enrichment/batches/batch19_manifest.json"
QA_OUT = ROOT / "data/master/qa/madoran_enrichment_batch19_generation_qa.json"


def r(english, korean, domain, topic, genre="conversation", speech="description",
      register="colloquial", context="high", flags="source_ambiguity",
      state="flagged", cefr="B2", score=60):
    return engine.item(english, korean, cefr, score, domain, topic, genre, speech, register, context, flags, state)


RAW = {
    1153: r("Abdelkader says there is nothing new and asks what the other person has.", "압델카데르가 새로운 일은 없다고 하며 상대에게 무엇이 있는지 물어요.", "daily_life", "brief_check_in_about_news", speech="question", context="low", flags="", state="draft", cefr="A1", score=8),
    1154: r("Hawari says it is the same as before and that there is nothing.", "하와리가 전과 같고 아무것도 없다고 답해요.", "daily_life", "brief_negative_reply", speech="answer", context="low", flags="", state="draft", cefr="A1", score=8),
    1155: r("Abdelkader begins asking what the other person is doing, but the recorded line is incomplete.", "압델카데르가 상대가 무엇을 하는지 묻기 시작하지만 녹음된 문장이 완결되지 않았어요.", "daily_life", "incomplete_question_about_activity", speech="question", context="high", flags="source_ambiguity|source_corruption", cefr="A2", score=24),
    1156: r("Hawari says, ‘Nothing.’", "하와리가 ‘아무것도 아니야’라고 답해요.", "daily_life", "minimal_negative_reply", speech="answer", context="low", flags="", state="draft", cefr="A1", score=4),
    1157: r("The speaker asks whether the listener wants to play a match with them now.", "화자가 지금 자신과 시합을 하고 싶은지 상대에게 물어요.", "sports", "inviting_someone_to_play_a_match", speech="question", context="low", flags="", state="draft", cefr="A1", score=14),
    1158: r("Hawari agrees to play.", "하와리가 시합을 하겠다고 동의해요.", "sports", "accepting_an_invitation_to_play", speech="agreement", context="low", flags="", state="draft", cefr="A1", score=8),
    1159: r("Abdelkader tells Hawari to get ready and says he is going to beat or overtake him; the final verb is retained without forcing one reading.", "압델카데르가 하와리에게 준비하라고 하며 자신이 그를 이기거나 앞설 것이라고 말해요. 마지막 동사는 한 가지로 확정하지 않고 보존해요.", "sports", "playful_challenge_before_a_match", speech="warning", context="medium", flags="source_ambiguity", cefr="A2", score=28),
    1160: r("Hawari gives a brief colloquial acknowledgment, roughly ‘okay’ or ‘thanks’; the isolated expression is context-dependent.", "하와리가 대략 ‘알겠어’ 또는 ‘고마워’에 해당하는 짧은 구어체 응답을 해요. 고립된 표현이라 문맥 의존성이 있어요.", "daily_life", "colloquial_acknowledgment", speech="answer", context="high", flags="source_ambiguity", cefr="A1", score=18),
    1161: r("Abdelkader says he is coming and asks whether he should bring the listener anything.", "압델카데르가 가고 있다고 하며 상대에게 무엇인가 가져다줄지 물어요.", "daily_life", "offering_to_bring_something", speech="question", context="medium", flags="source_ambiguity", cefr="A2", score=24),
    1162: r("Hawari thanks Abdelkader and says he is going to compete with or challenge him; the colloquial verb remains source-close.", "하와리가 압델카데르에게 고맙다고 하며 그와 겨루거나 도전하겠다고 말해요. 구어체 동사는 원문에 가깝게 남겨요.", "sports", "replying_to_a_playful_challenge", speech="agreement", context="medium", flags="source_ambiguity", cefr="A2", score=26),
    1163: r("A corrupted title-like line appears to refer to the Oran dialect and part one, but several characters are not recoverable.", "손상된 제목 형태의 줄로, 오랑 방언과 1부를 가리키는 듯하지만 여러 문자를 복원할 수 없어요.", "culture_tradition", "corrupted_title_about_oran_dialect", genre="expository", speech="information", register="mixed", context="high", flags="source_ambiguity|source_corruption", cefr="C1", score=78),
    1164: r("The speaker introduces a promised explanation of Wahrani speech, says the subject could take years, and explains that contact with many people, dialects, and languages has changed the older Oran variety. They give clothing and threat examples while preserving the long source and its dialect-specific wording.", "화자는 약속했던 와흐라니 말씨 설명을 시작하며 이 주제는 몇 년이 걸릴 수도 있다고 해요. 많은 사람과 방언·언어가 유입되면서 예전 오랑 방언이 바뀌었다고 설명하고, 옷차림과 위협의 예를 들며 긴 원문과 방언 특유의 표현을 보존해요.", "culture_tradition", "introduction_to_wahrani_dialect_change", genre="expository", speech="narration", register="mixed", context="high", flags="code_switching|idiom_culture|long_source|source_ambiguity", cefr="C1", score=88),
    1165: r("The speaker explains that Oran's older speech contained many Spanish elements and connects this to the city's history under Ottoman Algeria and Spanish colonial rule; several historical and loanword details remain source-close.", "화자는 예전 오랑 말에 스페인어 요소가 많았다고 설명하며 오스만 시대의 알제리와 스페인 식민 통치라는 도시의 역사와 연결해요. 역사와 차용어의 세부 내용은 원문에 가깝게 남겨요.", "history", "spanish_influence_on_oran_speech", genre="expository", speech="information", register="mixed", context="high", flags="code_switching|idiom_culture|long_source|source_ambiguity", cefr="C1", score=82),
    1166: r("The speaker describes the Spanish presence in Oran as a substantial population and links it to a European urban setting; the place-description wording is partly opaque.", "화자는 오랑에 있었던 스페인인의 존재를 상당한 인구로 설명하고 유럽 도시 환경과 연결해요. 장소를 설명하는 표현 일부는 불투명해요.", "history", "spanish_population_in_oran", genre="expository", speech="description", register="mixed", context="high", flags="code_switching|source_ambiguity", cefr="B2", score=66),
    1167: r("The speaker recounts Spanish departure, a period of Turkish rule, Bey Mohamed el Kebir, French entry in 1831, an 1834 population count of about 5,000, and local people leaving for Mascara to join Emir Abdelkader's forces; some historical references are uncertain.", "화자는 스페인인의 철수와 튀르크 통치 시기, 바이 무함마드 엘 케비르, 1831년 프랑스의 진입, 1834년 약 5천 명의 인구 조사, 주민들이 마스카라로 떠나 에미르 압델카데르의 군대에 합류한 일을 설명해요. 일부 역사적 지칭은 불확실해요.", "history", "colonial_history_and_population_of_oran", genre="expository", speech="narration", register="mixed", context="high", flags="code_switching|idiom_culture|long_source|source_ambiguity", cefr="C1", score=90),
    1168: r("The speaker gives a breakdown of Oran's population in 1834, including about 5,000 inhabitants, Europeans, Arabs, Kabyle people, Jews, French, and Italians; the census wording and categories are preserved without normalizing them.", "화자는 1834년 오랑 인구를 약 5천 명으로 제시하며 유럽인, 아랍인, 카빌인, 유대인, 프랑스인과 이탈리아인 등의 범주를 나열해요. 인구 조사 표현과 범주는 임의로 정규화하지 않고 보존해요.", "history", "1834_oran_population_breakdown", genre="expository", speech="information", register="mixed", context="high", flags="code_switching|long_source|source_ambiguity", cefr="C1", score=86),
    1169: r("The speaker continues the population list with Spanish, English, German, and Portuguese groups, then says that this mixture helped Oran become a special city with a locally spoken dialect.", "화자는 스페인인·영국인·독일인·포르투갈인 집단을 계속 나열하고, 이런 혼합으로 오랑이 특별한 도시가 되었으며 현지에서 쓰는 방언이 생겼다고 말해요.", "history", "multilingual_population_and_local_dialect", genre="expository", speech="information", register="mixed", context="high", flags="code_switching|idiom_culture|long_source|source_ambiguity", cefr="C1", score=78),
    1170: r("The speaker says each group had its own way of speaking and that Spanish, especially the named varieties, dominated more than 60 percent of Wahrani speech; the percentage and labels are retained as source claims.", "화자는 각 집단이 자기들만의 말을 사용했으며 스페인어, 특히 원문에 이름으로 나온 변종이 와흐라니 말의 60% 이상에 영향을 주었다고 해요. 백분율과 명칭은 원문상의 주장으로 보존해요.", "history", "spanish_dominance_in_wahrani_speech", genre="expository", speech="information", register="mixed", context="high", flags="code_switching|idiom_culture|long_source|source_ambiguity", cefr="C1", score=82),
    1171: r("The speaker adds that they will talk about how Oran people used to speak and about the Wahrani dialect.", "화자는 오랑 사람들이 예전에 어떻게 말했는지와 와흐라니 방언에 대해 더 이야기하겠다고 해요.", "culture_tradition", "announcing_discussion_of_wahrani_speech", genre="expository", speech="narration", register="colloquial", context="medium", flags="idiom_culture|source_ambiguity", cefr="B1", score=42),
    1172: r("The speaker lists Spanish, French, English, German, and Portuguese as languages or language influences found in Oran.", "화자는 오랑에서 스페인어·프랑스어·영어·독일어·포르투갈어를 찾아볼 수 있다고 나열해요.", "culture_tradition", "listing_languages_in_oran", genre="expository", speech="description", register="mixed", context="medium", flags="code_switching|source_ambiguity", cefr="B1", score=44),
    1173: r("The speaker wants to discuss English terms found in Wahrani speech and says that discussing Spanish terms would take too long.", "화자는 와흐라니 말에 있는 영어 용어를 이야기하고 싶다며 스페인어 용어까지 말하면 너무 오래 걸릴 것이라고 해요.", "culture_tradition", "introducing_english_loanwords_in_wahrani", genre="expository", speech="narration", register="mixed", context="medium", flags="code_switching|idiom_culture|source_ambiguity", cefr="B2", score=58),
    1174: r("The speaker says explaining the French terms would never end, but many young people do not know the English terms in Wahrani speech, so they will give a few examples to keep the explanation short.", "화자는 프랑스어 용어를 설명하면 끝이 없지만 많은 젊은이는 와흐라니 말의 영어 용어를 모른다고 하며, 설명을 짧게 하려고 몇 가지 예를 들겠다고 해요.", "culture_tradition", "selecting_english_loanword_examples", genre="expository", speech="narration", register="mixed", context="high", flags="code_switching|idiom_culture|long_source|source_ambiguity", cefr="C1", score=76),
    1175: r("The speaker announces that they will give examples of English expressions used in Oran.", "화자는 오랑에서 사용되는 영어 표현의 예를 들겠다고 해요.", "culture_tradition", "announcing_loanword_examples", genre="expository", speech="narration", register="mixed", context="medium", flags="code_switching|source_ambiguity", cefr="B1", score=38),
    1176: r("The speaker introduces a second historical factor, saying that the Turks entered Algeria in the Middle Ages and the French came afterward; the historical phrasing is retained as a source claim.", "화자는 두 번째 역사적 요인을 소개하며 중세에 튀르크인이 알제리에 들어왔고 그 뒤에 프랑스인이 왔다고 말해요. 역사적 표현은 원문상의 주장으로 보존해요.", "history", "historical_layers_in_algeria", genre="expository", speech="information", register="mixed", context="high", flags="code_switching|idiom_culture|source_ambiguity", cefr="B2", score=64),
    1177: r("The speaker contrasts Oran with the rest of Algeria, mentions Spanish rule for about forty years, French rule across Algeria, and the American landing in Oran on 10 November 1942, with many American deaths.", "화자는 오랑이 알제리의 다른 지역과 다르다고 하며 약 40년의 스페인 통치, 알제리 전역의 프랑스 통치, 1942년 11월 10일 오랑에 들어온 미국인을 언급하고 많은 미국인이 사망했다고 말해요.", "history", "spanish_french_and_american_history_of_oran", genre="expository", speech="information", register="mixed", context="high", flags="code_switching|idiom_culture|long_source|source_ambiguity", cefr="C1", score=84),
    1178: r("The speaker explains that Oran has an American cemetery, describes it as resembling one seen in films, and says many bodies or graves remain there; the exact count is unclear.", "화자는 오랑에 미국인 묘지가 있으며 영화에서 본 것 같은 모습이라고 설명하고, 그곳에 많은 시신이나 무덤이 남아 있다고 말해요. 정확한 수는 불분명해요.", "history", "american_cemetery_in_oran", genre="expository", speech="description", register="mixed", context="high", flags="code_switching|idiom_culture|source_ambiguity", cefr="B2", score=62),
    1179: r("The speaker locates the cemetery behind a train station near Petit Lac and calls it an important story about the Americans' entry into Oran, promising to tell it another day.", "화자는 그 묘지가 프티 라크 근처 기차역 뒤에 있다고 하며 미국인의 오랑 진입에 관한 큰 이야기라고 말하고 다음에 들려주겠다고 해요.", "history", "locating_an_american_war_memorial", genre="expository", speech="information", register="mixed", context="high", flags="code_switching|idiom_culture|source_ambiguity", cefr="B2", score=64),
    1180: r("The speaker says that in 1808 there were 69 English people in Oran and that their words entered the local Oran variety.", "화자는 1808년에 오랑에 영국인이 69명 있었고 그들의 말이 오랑 지역 말에 들어왔다고 해요.", "history", "english_influence_on_oran_dialect", genre="expository", speech="information", register="mixed", context="high", flags="code_switching|idiom_culture|source_ambiguity", cefr="B2", score=58),
    1181: r("The line refers briefly to the Oran dialect that used to be spoken; it is a fragment dependent on the surrounding explanation.", "이 줄은 예전에 사용되던 오랑 방언을 짧게 언급하는 단편이며 앞뒤 설명에 의존해요.", "culture_tradition", "fragment_about_spoken_oran_dialect", genre="expository", speech="description", register="mixed", context="high", flags="idiom_culture|source_ambiguity", cefr="A2", score=28),
    1182: r("The speaker says that when the Americans entered Oran in 1942 they were welcomed or admired by the Algerian population, while adding that the Americans disliked the French; the causal wording is uncertain.", "화자는 미국인이 1942년 오랑에 들어왔을 때 알제리 주민에게 환영받거나 호감을 얻었고 미국인은 프랑스인을 싫어했다고 말해요. 인과관계의 표현은 불확실해요.", "history", "american_entry_and_local_attitudes", genre="expository", speech="information", register="mixed", context="high", flags="code_switching|idiom_culture|source_ambiguity", cefr="B2", score=68),
    1183: r("In a long historical explanation, the speaker discusses the American entry into Oran and Algiers, French groups associated with De Gaulle and Vichy, collaborators under Marshal Pétain, and the resulting major battle; names and political relationships are preserved without resolving every reference.", "긴 역사 설명에서 화자는 미국인의 오랑과 알제 진입, 드골과 연결된 프랑스 세력, 비시 세력과 페탱 원수 아래의 협력자들, 그 결과 발생한 큰 전투를 이야기해요. 이름과 정치적 관계는 모든 지칭을 확정하지 않고 보존해요.", "history", "american_landing_and_vichy_resistance_conflict", genre="expository", speech="narration", register="mixed", context="high", flags="code_switching|idiom_culture|long_source|source_ambiguity", cefr="C1", score=94),
    1184: r("The speaker mentions an American president, identifies Eisenhower, and says that his son entered Oran in a way that is not fully clear; the historical reference remains source-close.", "화자는 미국 대통령을 언급하고 아이젠하워를 지목하며 그의 아들이 불분명한 방식으로 오랑에 들어왔다고 말해요. 역사적 지칭은 원문에 가깝게 남겨요.", "history", "eisenhower_reference_in_oran_history", genre="expository", speech="information", register="mixed", context="high", flags="code_switching|source_ambiguity", cefr="B2", score=64),
    1185: r("The speaker says they will give examples of English words found in Oran and will focus only on English.", "화자는 오랑에서 발견되는 영어 단어의 예를 들고 영어만 다루겠다고 해요.", "culture_tradition", "announcing_english_word_examples", genre="expository", speech="narration", register="mixed", context="medium", flags="code_switching|source_ambiguity", cefr="B1", score=38),
    1186: r("The speaker compares regional words for boys or children: one term is used in eastern Algeria, another around central Algiers, and another in the western region around Mascara and Oran.", "화자는 소년이나 아이를 가리키는 지역별 말을 비교해요. 알제리 동부, 알제 중앙 지역, 마스카라와 오랑을 포함한 서부에서 서로 다른 표현을 쓴다고 해요.", "culture_tradition", "regional_terms_for_boys", genre="expository", speech="information", register="mixed", context="high", flags="idiom_culture|source_ambiguity", cefr="B2", score=62),
    1187: r("The speaker explains that people in Oran use a local term for boys, connecting it to the English plural ‘boys’ and describing a shortened singular form used for small children.", "화자는 오랑 사람들이 소년을 부르는 지역 표현을 사용한다고 설명하며 그 표현을 영어 복수형 ‘boys’와 연결하고 어린아이에게 쓰는 축약 단수형도 설명해요.", "culture_tradition", "english_loanword_for_boys_in_oran", genre="expository", speech="information", register="mixed", context="high", flags="code_switching|idiom_culture|source_ambiguity", cefr="B2", score=68),
    1188: r("As an example, the speaker gives an opaque local term for the object used to close a door and contrasts it with the widespread Algerian word for a lock or bolt.", "예로 화자는 문을 닫는 데 쓰는 물건의 불투명한 지역 표현을 들고, 알제리 전역에서 쓰이는 자물쇠나 빗장 표현과 비교해요.", "culture_tradition", "regional_word_for_a_door_lock", genre="expository", speech="description", register="mixed", context="high", flags="idiom_culture|source_ambiguity", cefr="B2", score=62),
    1189: r("The speaker says people in Oran do not use the common word for a lock but use another local form, explaining it as an adaptation of the English phrase ‘close room’; the folk etymology is preserved as a source claim.", "화자는 오랑에서는 자물쇠의 일반적인 말을 쓰지 않고 다른 지역형을 쓴다고 하며, 그것을 영어 구절 ‘close room’을 변형한 것으로 설명해요. 이 민간어원은 원문상의 주장으로 보존해요.", "culture_tradition", "folk_etymology_of_an_oran_lock_word", genre="expository", speech="information", register="mixed", context="high", flags="code_switching|idiom_culture|long_source|source_ambiguity", cefr="C1", score=78),
    1190: r("The speaker introduces another example, a local word pronounced like ‘Akli’, and asks where it came from; the following explanation is needed to interpret it.", "화자는 ‘아클리’처럼 들리는 또 다른 지역 표현을 예로 들고 그것이 어디에서 왔는지 물어요. 해석하려면 뒤의 설명이 필요해요.", "culture_tradition", "introducing_an_akli_loanword_example", genre="expository", speech="question", register="mixed", context="high", flags="code_switching|idiom_culture|source_ambiguity", cefr="B2", score=54),
    1191: r("The speaker briefly says that people in the western region use another or more frequent form; the referent is omitted in this fragment.", "화자는 서부 지역 사람들이 다른 표현이나 더 많은 형태를 쓴다고 짧게 말하지만, 이 단편에서는 대상이 생략되어 있어요.", "culture_tradition", "fragment_about_regional_word_usage", genre="expository", speech="description", register="mixed", context="high", flags="idiom_culture|source_ambiguity", cefr="A2", score=30),
    1192: r("The speaker explains that the local form ‘Akli’ comes from an English word meaning ugly, used when someone is not handsome, and says the borrowed form eventually became used as a personal name; the word history is retained as a source claim.", "화자는 지역형 ‘아클리’가 못생겼다는 뜻의 영어 단어에서 왔으며 잘생기지 않은 사람을 가리킬 때 쓰였다고 설명하고, 그 차용형이 결국 사람 이름으로도 쓰이게 되었다고 말해요. 단어의 역사는 원문상의 주장으로 보존해요.", "culture_tradition", "folk_etymology_and_name_use_of_akli", genre="expository", speech="information", register="mixed", context="high", flags="code_switching|idiom_culture|long_source|source_ambiguity", cefr="C1", score=78),
    1193: r("The speaker says these are things educated or well-read people know and teases the listener for thinking the subject is easy because they are local.", "화자는 이런 것은 공부한 사람이라면 아는 일이라고 하며, 현지인이라고 해서 쉽다고 생각하느냐고 상대를 놀려요.", "culture_tradition", "teasing_about_local_language_knowledge", speech="opinion", register="colloquial", context="medium", flags="idiom_culture|source_ambiguity", cefr="B1", score=42),
    1194: r("The speaker announces another interesting English term used frequently in the western region.", "화자는 서부 지역에서 자주 쓰이는 또 다른 흥미로운 영어 용어를 소개하겠다고 해요.", "culture_tradition", "introducing_a_western_loanword", genre="expository", speech="narration", register="mixed", context="medium", flags="code_switching|source_ambiguity", cefr="B1", score=38),
    1195: r("The speaker describes a person with a cart pulled by a donkey telling the donkey to move, using a local expression derived from an English command such as ‘hurry, man.’", "화자는 당나귀가 끄는 수레 주인이 당나귀에게 움직이라고 말하며 ‘어서, 이봐’와 같은 영어 명령에서 유래한 지역 표현을 쓴다고 설명해요.", "transport", "english_derived_command_to_a_donkey", genre="expository", speech="description", register="mixed", context="high", flags="code_switching|idiom_culture|source_ambiguity", cefr="B2", score=66),
    1196: r("The speaker recalls the 1940s, when Americans in Oran went out from a neighborhood or parking area where their equipment was stored rather than staying there.", "화자는 1940년대 오랑의 미국인들이 장비를 보관하던 주차장이나 지역에서만 머물지 않고 밖으로 나갔던 일을 회상해요.", "history", "american_vehicles_and_storage_area_in_oran", genre="expository", speech="narration", register="mixed", context="high", flags="code_switching|idiom_culture|long_source|source_ambiguity", cefr="C1", score=76),
    1197: r("The speaker says the Americans drove jeeps and large vehicles through Arab neighborhoods such as Hamri, Medina Jdida, Derb, and Sidi Houari, whose streets were narrow.", "화자는 미국인들이 지프와 큰 차량을 타고 함리·메디나 즈디다·데르브·시디 후아리 같은 아랍인 거주 지역을 다녔다고 하며, 그곳의 길이 좁았다고 말해요.", "history", "american_vehicles_in_oran_neighborhoods", genre="expository", speech="narration", register="mixed", context="high", flags="code_switching|idiom_culture|long_source|source_ambiguity", cefr="C1", score=78),
    1198: r("The speaker says that poor Arab residents generally had only carts.", "화자는 가난한 아랍인 주민들에게는 대체로 수레밖에 없었다고 말해요.", "transport", "carts_in_poor_oran_neighborhoods", speech="description", register="mixed", context="medium", flags="source_ambiguity", cefr="B1", score=44),
    1199: r("In a long anecdote, the speaker describes donkey carts carrying vegetables, narrow streets blocked by carts, and Americans arriving in jeeps and trucks. The Americans were afraid in the Arab quarters and shouted an English command meaning ‘hurry up’; local speakers shortened and reshaped it into expressions used to make carts clear the road, with a final teasing comment.", "긴 일화에서 화자는 채소를 싣는 당나귀 수레와 수레로 막힌 좁은 길, 지프와 트럭을 타고 온 미국인을 설명해요. 미국인들은 아랍인 구역에서 두려워하며 ‘어서 서둘러’라는 뜻의 영어 명령을 외쳤고, 현지인들은 이를 줄이고 변형해 수레에게 길을 비키라고 하는 표현으로 만들었다고 해요. 마지막에는 장난스러운 논평이 이어져요.", "culture_tradition", "folk_adaptation_of_an_english_traffic_command", genre="expository", speech="narration", register="mixed", context="high", flags="code_switching|idiom_culture|long_source|source_ambiguity", cefr="C1", score=92),
    1200: r("The speaker says they will add a little-known detail and asks the listener to wait to understand why it is little known.", "화자는 잘 알려지지 않은 이야기를 하나 더 하겠다며 왜 잘 알려지지 않았는지 곧 알게 될 것이라고 해요.", "history", "introducing_a_little_known_history", genre="expository", speech="narration", register="colloquial", context="medium", flags="source_ambiguity", cefr="B1", score=42),
    1201: r("The speaker says a person who lived in Oran in the 1930s and 1940s was known as Harandou.", "화자는 1930년대와 1940년대에 오랑에 살았던 사람이 하란두라는 이름으로 알려졌다고 말해요.", "history", "introducing_harandou_of_oran", genre="expository", speech="information", register="mixed", context="medium", flags="source_ambiguity", cefr="B1", score=44),
    1202: r("The speaker remembers Harandou, offers a prayer for him, identifies him as an Oranian, and says he had a friend named Ben Yamina.", "화자는 하란두를 회상하며 그를 위한 기도를 하고, 그가 오랑 사람이며 벤 야미나라는 친구가 있었다고 말해요.", "history", "remembering_harandou_and_his_friend", genre="expository", speech="narration", register="mixed", context="medium", flags="idiom_culture|source_ambiguity", cefr="B1", score=52),
    1203: r("The speaker says Harandou played a guembri and moved around the markets in torn clothing; the final local expression is retained without fixing its exact social meaning.", "화자는 하란두가 금브리를 연주하며 찢어진 옷을 입고 시장을 돌아다녔다고 해요. 마지막 지역 표현은 정확한 사회적 의미를 확정하지 않고 보존해요.", "entertainment_music", "harandou_as_a_market_musician", genre="expository", speech="narration", register="mixed", context="high", flags="idiom_culture|source_ambiguity", cefr="B2", score=64),
    1204: r("The speaker says Harandou used to beg in Medina Jdida and sing about two small fish bought at the market, lightly washed and fried in oil, then says local people know the song and that a full explanation would take a long time.", "화자는 하란두가 메디나 즈디다에서 구걸하고 시장에서 사 온 작은 물고기 두 마리를 조금 씻어 기름에 튀긴 이야기를 노래했다고 해요. 지역 사람들이 그 노래를 알고 있으며 자세히 설명하면 오래 걸린다고 말해요.", "entertainment_music", "harandou_song_about_fried_fish", genre="song_lyric", speech="narration", register="mixed", context="high", flags="idiom_culture|long_source|source_ambiguity", cefr="C1", score=78),
    1205: r("The speaker says the problem is understanding why the person was called Harandou or where the word came from, and notes that many people ask what Harandou means.", "화자는 그 사람이 왜 하란두라고 불렸는지 또는 그 말이 어디에서 왔는지가 문제라고 하며 많은 사람이 하란두의 뜻을 묻는다고 말해요.", "culture_tradition", "asking_about_the_origin_of_harandou", genre="expository", speech="question", register="mixed", context="medium", flags="idiom_culture|source_ambiguity", cefr="B1", score=46),
    1206: r("The speaker says they will explain this to their brother.", "화자는 이 이야기를 형제에게 설명하겠다고 말해요.", "daily_life", "announcing_an_explanation_to_a_brother", speech="narration", register="colloquial", context="medium", flags="source_ambiguity", cefr="A2", score=24),
    1207: r("The speaker says Harandou can be divided into several words and begins the explanation with the period of the First World War, 1914–1918.", "화자는 하란두가 여러 단어로 나뉠 수 있다고 하며 1차 세계대전 시기인 1914~1918년부터 설명을 시작해요.", "history", "beginning_the_etymology_of_harandou", genre="expository", speech="narration", register="mixed", context="high", flags="idiom_culture|long_source|source_ambiguity", cefr="C1", score=72),
    1208: r("The speaker moves to the Second World War period, 1939–1945, and describes French forces humiliating and recruiting local people, including poor men, to fight in European wars; the historical account remains source-close.", "화자는 1939~1945년 2차 세계대전 시기로 넘어가 프랑스 세력이 현지인을 모욕하고 가난한 남성들을 포함한 주민을 모집해 유럽 전쟁에 참전시켰다고 설명해요. 역사적 서술은 원문에 가깝게 남겨요.", "history", "colonial_recruitment_during_world_wars", genre="expository", speech="narration", register="mixed", context="high", flags="code_switching|idiom_culture|long_source|source_ambiguity", cefr="C1", score=88),
    1209: r("The speaker explains that some Arab families hid or failed to register their sons, so many people born in that period appear with a 1940 birth entry in family records; the reasons involving remote places and French registration authorities remain partly uncertain.", "화자는 일부 아랍인 가족이 아들을 숨기거나 등록하지 않아 그 시기에 태어난 많은 사람이 가족 기록에 1940년생으로 적혔다고 설명해요. 외딴 지역과 프랑스 행정기관에 관한 이유는 일부 불확실하게 남겨요.", "administration", "birth_registration_and_family_records", genre="expository", speech="information", register="mixed", context="high", flags="code_switching|idiom_culture|long_source|source_ambiguity", cefr="C1", score=82),
    1210: r("The speaker says parents did not register their sons so the boys would remain unknown to the French authorities and would not be taken away.", "화자는 부모가 아들을 등록하지 않아 그 아이들이 프랑스 당국에 알려지지 않고 끌려가지 않도록 했다고 말해요.", "administration", "avoiding_registration_and_recruitment", genre="expository", speech="information", register="mixed", context="high", flags="code_switching|idiom_culture|source_ambiguity", cefr="B2", score=68),
    1211: r("The speaker says the French took these young men for wars in Europe and put them into military service, where periods of weeks, months, or six months taught them military matters such as marching; the final training term is unclear.", "화자는 프랑스인이 이 젊은이들을 유럽 전쟁에 데려가 군대에 넣었고, 몇 주·몇 달·6개월 동안 행군 같은 군사 훈련을 가르쳤다고 말해요. 마지막 훈련 용어는 불분명해요.", "history", "military_recruitment_and_training", genre="expository", speech="narration", register="mixed", context="high", flags="code_switching|idiom_culture|long_source|source_ambiguity", cefr="C1", score=84),
    1212: r("The speaker describes poor people brought from the countryside, living in a small village or forest, knowing little, and owning only a few sheep.", "화자는 시골에서 데려온 가난한 사람들이 작은 마을이나 숲에 살며 아무것도 잘 모르고 양 몇 마리만 가지고 있었다고 설명해요.", "history", "rural_recruits_before_military_service", genre="expository", speech="description", register="mixed", context="high", flags="idiom_culture|source_ambiguity", cefr="B2", score=62),
    1213: r("In a long and derogatory historical anecdote, the speaker describes French forces taking an uneducated rural man as a soldier, using an intermediary to communicate with him, humiliating and drilling him, and treating him like a donkey. The shouted counting command ‘one, two, har’ is presented as the source of Harandou, which later became a mocking label for an unsophisticated person; offensive wording and uncertain etymology are retained as source claims.", "긴 역사적 일화에서 화자는 프랑스군이 교육받지 못한 시골 사람을 병사로 데려가고, 중개인을 통해 소통하며, 그를 모욕하고 훈련시키고 당나귀처럼 대했다고 설명해요. ‘하나, 둘, 하르’라는 구령이 하란두의 유래로 제시되고, 이후 세련되지 못한 사람을 놀리는 말이 되었다고 해요. 모욕적 표현과 불확실한 어원은 원문상의 주장으로 보존해요.", "history", "derogatory_origin_story_of_harandou", genre="expository", speech="narration", register="offensive", context="high", flags="code_switching|idiom_culture|long_source|source_ambiguity", cefr="C1", score=96),
    1214: r("The speaker says the history of the Americans is important and explains that the concern is not only the disappearance of the Wahrani dialect but also the amount of false history told about Oran. They criticize books and television accounts and ask people to describe Oran in a more respectful, vivid way.", "화자는 미국인의 역사가 중요하다고 말하며, 문제는 와흐라니 방언이 사라지는 것만이 아니라 오랑의 역사에 관한 거짓 이야기가 너무 많다는 점이라고 설명해요. 책과 텔레비전의 서술을 비판하고 오랑을 더 존중하고 생생한 방식으로 설명하자고 해요.", "history", "criticizing_false_histories_of_oran", genre="expository", speech="opinion", register="mixed", context="high", flags="idiom_culture|long_source|source_ambiguity", cefr="C1", score=88),
    1215: r("The speaker says that if they talk about Oran, they want to describe it beautifully and calls Oran the third-best city or balcony in the world; the superlative phrase is partly opaque.", "화자는 오랑을 이야기한다면 아름다운 방식으로 설명하고 싶다고 하며 오랑을 세계에서 세 번째로 좋은 도시나 발코니처럼 표현해요. 최상급 표현은 일부 불투명해요.", "culture_tradition", "prideful_closing_description_of_oran", genre="expository", speech="opinion", register="mixed", context="high", flags="idiom_culture|source_ambiguity", cefr="B2", score=60),
    1216: r("A single opaque word or name is recorded; no stable sentence-level meaning can be recovered from the isolated source.", "불투명한 단어 또는 이름 하나만 기록되어 있어 고립된 원문에서 안정적인 문장 수준의 의미를 복원할 수 없어요.", "other", "isolated_opaque_word", genre="other", speech="other", register="mixed", context="high", flags="source_ambiguity", cefr="A1", score=20),
}


def build():
    engine.BATCH_ID = BATCH_ID
    engine.BASE_COMMIT = BASE_COMMIT
    engine.PROMPT_VERSION = PROMPT_VERSION
    engine.TARGET_START = TARGET_START
    engine.TARGET_END = TARGET_END
    engine.BATCH_OUT = BATCH_OUT
    engine.MANIFEST_OUT = MANIFEST_OUT
    engine.QA_OUT = QA_OUT
    engine.RAW = RAW
    return engine.build()


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    print(json.dumps(build(), ensure_ascii=False, indent=2))
