"""Apply HeadGPT Batch 06 P1 corrections with append-only provenance."""
from __future__ import annotations
import hashlib, json, subprocess, sys
from datetime import datetime, timezone
from pathlib import Path
if __package__ in {None, ""}: sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from scripts.build_madoran_enrichment_batch06 import BATCH_OUT
from scripts.build_madoran_enrichment_scaffold import ENRICHMENT_FIELDS, ENRICHMENT_OUT, EVENTS_OUT, ROOT, SOURCE_OUT, check_provenance_events, read_tsv, source_gate, write_tsv
from scripts.validate_madoran_enrichment import check_enrichment_provenance
BASE_COMMIT="1790d4d"; CORRECTION_ID="MADORAN-ENRICH-006-CORRECTION-01"; PROMPT_VERSION="madoran-source-enrichment-v6-correction-1"; METHOD="llm_source_only_enrichment_correction"; MODEL="codex-unspecified"; SCHEMA_VERSION="1.1.0"; TARGET_START=321; TARGET_END=384
STATUS_OUT=ROOT/"data/master/state/madoran_layer_status.json"; BATCH_QA_OUT=ROOT/"data/master/qa/madoran_enrichment_batch06_qa.json"; CORRECTION_QA_OUT=ROOT/"data/master/qa/madoran_enrichment_batch06_correction01_qa.json"
CORRECTIONS={
323:{"english":"When she came out, he said to her, Who are you and where did you come from? And who brought you?","korean":"그녀가 나오자 그가 그녀에게 말했다. 너 누구고 어디서 왔어? 그리고 누가 널 데려왔어?"},
324:{"english":"She told him, I am only your wife. You did not recognize me just because I removed my makeup. He said, Those damned people did this to me; they gave me Jilali for 250 million. May God not reward them. Get out of my sight.","korean":"그녀가 그에게 말했어. 난 그냥 네 아내야. 내가 화장을 지웠다고 못 알아본 거야? 그가 말했어. 그 망할 사람들이 내게 이런 짓을 했어. 그들은 2억 5천만에 질랄리를 내게 줬어. 하느님이 그들에게 상을 주지 않기를. 내 눈앞에서 나가."},
325:{"english":"The difference between a European woman and an Algerian woman: when a European woman goes to give birth, they take her to the hospital; you find a man holding her hand while she says, Jacques, I am going to die; I cannot. The remaining French-like expression is unclear.","korean":"유럽 여성과 알제리 여성의 차이야. 유럽 여성이 출산하러 가면 병원으로 데려가고, 남자가 그녀의 손을 잡고 있어. 그녀는 자크, 나 죽을 것 같아, 못 하겠어라고 말해. 나머지 프랑스어 같은 표현은 불분명해."},
326:{"english":"And he tells her, Breathe, everything is fine, while she keeps saying, Oh my God. She says that she is in a great deal of pain from the labor; the remaining expression is unclear.","korean":"그는 그녀에게 숨 쉬어, 다 괜찮아라고 말해. 그녀는 계속 오 마이 갓이라고 해. 진통 때문에 너무 아프다고 말하는데, 나머지 표현은 불분명해."},
328:{"english":"Now an Algerian woman is normal at first, until she falls and cries out, 3bd9a, 3bd9a, repeatedly. The poor man runs and carries her in a clandestine or unofficial vehicle to the hospital; the remaining details are context-sensitive.","korean":"알제리 여성은 처음에는 멀쩡하다가 쓰러져 3bd9a, 3bd9a라고 계속 외쳐. 불쌍한 남자가 달려가 비공식 운송 차량에 그녀를 태워 병원으로 데려가고, 나머지 세부 내용은 문맥에 따라 달라."},
329:{"english":"And her husband tells her, Be quiet, Fatima, you have humiliated us. She keeps screaming in pain, and 3bd9a follows and hears curses: May God not reward you, 3bd9a. You are the reason for this, 3bd9a. If I had known, I would not have done it. 3bd9a, may God strike you.","korean":"그녀의 남편은 말해. 조용히 해, 파티마, 우리 망신 다 시켰어. 그녀는 계속 아파서 비명을 지르고, 3bd9a가 따라가며 욕설을 들어. 3bd9a야, 하느님이 너에게 상을 주지 않기를. 네가 이 일의 원인이야. 알았더라면 하지 않았을 거야. 3bd9a야, 하느님이 너를 치시길."},
330:{"english":"When they take her in to bring out the baby, they find her in an unclear stage of the process, with two months still remaining before she gives birth. I am astonished.","korean":"아기를 꺼내려고 그녀를 데려갔는데, 아직 과정의 어느 단계인지 불분명하고 출산까지 두 달이나 남은 상태였대. 정말 놀라워."},
331:{"english":"Tell us about something that happened to you at the beach. I have a friend who is an artist; wonderful things come from his hands. He used to go to the beach with us without taking a single cent, draw for two million, and earn money in a day; the exact arrangement is unclear.","korean":"해변에서 겪은 일을 하나 말해 줘. 내 친구 중에 화가가 있는데 손에서 멋진 작품이 나와. 그는 돈 한 푼 없이 우리와 해변에 가서 200만을 받고 그림을 그리고 하루에 돈을 벌곤 했어. 정확한 방식은 불분명해."},
333:{"english":"Anyway, the whole beach was walking around with tattoos that said Chinese green tea. The first time I saw one, I saw how commerce or business worked; the expression is humorous and context-sensitive.","korean":"아무튼 해변 사람들이 모두 중국 녹차라고 적힌 문신을 하고 돌아다녔어. 처음 봤을 때 장사나 상업이 어떻게 돌아가는지 봤지. 이 표현은 유머러스하고 문맥에 따라 달라."},
341:{"english":"But you do not find him comfortable, poor thing. He keeps drinking and getting drunk, driving his father's car all day, troubled and searching for something; he is miserable, and something fills his heart. They call it an evil prayer, God forbid.","korean":"하지만 불쌍하게도 그는 편안하지 않아. 계속 술을 마시고 취하고, 아버지 차를 하루 종일 몰며 괴로워하고 무언가를 찾아다녀. 그는 우울하고 마음을 가득 채운 무언가가 있어. 사람들은 그것을 나쁜 저주라고 해. 하느님, 막아 주소서."},
342:{"english":"Which category are you in? See yourself in it. I have gone through or experienced all of them. There is nothing like someone who takes responsibility, works with his own arms, manages things, and relies on himself; not someone who only chases girls and has no goal in life. May God preserve my parents for me.","korean":"너는 어느 부류야? 네 모습을 그 안에서 찾아봐. 나는 그 부류들을 모두 겪어 봤어. 책임을 지고 자기 힘으로 일하며 일을 해결하고 스스로 의지하는 사람이 최고야. 여자만 쫓고 인생의 목표가 없는 사람이 아니지. 하느님이 우리 부모님을 지켜 주시길.","processing_flags":"idiom_culture|long_source|source_ambiguity"},
343:{"english":"I am a twenty-five-year-old woman. I was born prematurely at six and a half months of gestation, excuse me. My mother did not leave me in the hospital because she feared they would not care for me, so she took me home, and she and my grandmother raised me. May God have mercy on her.","korean":"나는 스물다섯 살 여자야. 임신 6개월 반에 조산으로 태어났어. 실례해. 엄마는 병원에서 나를 잘 돌보지 않을까 봐 나를 두지 않고 집으로 데려왔고, 엄마와 할머니가 나를 키웠어. 돌아가신 할머니에게 하느님의 자비가 있기를."},
347:{"english":"Thank God I grew up and studied. I got 18, almost 19, in the sixth-grade exam, 15 in the middle-school certificate, and 12 in the baccalaureate. At university I spent five years and earned a master's degree in chemistry with 17. As I told you, now I am almost","korean":"다행히 나는 자라서 공부했어. 초등학교 졸업 시험에서 18점, 거의 19점을 받았고, 중학교 졸업 시험에서는 15점, 고등학교 졸업 시험에서는 12점을 받았어. 대학에서는 5년을 보내고 화학 석사 학위를 17점으로 받았지. 말했듯이 지금 나는 거의","context_dependency":"high"},
348:{"english":"twenty-six years old. I need a job and a good man. Well, my brothers and sisters, that is my story.","korean":"스물여섯 살이야. 나는 일자리와 좋은 남자가 필요해. 자, 형제자매 여러분, 이것이 내 이야기야.","context_dependency":"high"},
349:{"english":"Try going one day to where they sell sardines. You only have to stop beside the seller to notice how the smell kills you. But really, after a while you get used to it, and the longer you stay there, you will not feel it at all.","korean":"언젠가 정어리를 파는 곳에 가 봐. 판매자 옆에 잠깐 서 있기만 해도 냄새가 아주 지독해. 하지만 정말로 시간이 지나면 익숙해지고, 그곳에 오래 머물수록 아예 느끼지 못할 거야."},
355:{"english":"Then I went to my father. My mother heard me in severe distress and realized I had swallowed it. She put her hand in my throat and pulled it out. Thank God I survived by a hair. That is why someone must always watch over children, because they do not know how many people have died like that, poor things.","korean":"그다음 아버지에게 갔어. 엄마는 내가 심하게 괴로워하는 소리를 듣고 삼킨 것을 알아챘지. 엄마가 내 목에 손을 넣어 꺼냈어. 정말 간신히 살아났어. 그래서 누군가는 늘 아이들을 지켜봐야 해. 아이들은 그런 일로 얼마나 많은 사람이 죽었는지 모르니까, 불쌍하지."},
358:{"english":"I was with my sister. She gave me the house key and told me to rest at home, but I disobeyed, went outside, and played until I dropped the key.","korean":"나는 언니와 함께 있었어. 언니가 집 열쇠를 주며 집에서 쉬라고 했지만 나는 말을 어기고 밖으로 나가 놀다가 열쇠를 떨어뜨렸어."},
360:{"english":"She started shouting outside and scolded me publicly. She said, How can I tell you to watch the girl while I take care of my errands and come back, and you go out? I told you to go out—go on, speak, do not cry with those eyes. Now you are helpless. And from then on...","korean":"엄마는 밖에서 소리치기 시작하고 사람들 앞에서 나를 야단쳤어. 내가 볼일을 보고 돌아올 동안 그 아이를 잘 보라고 했는데 어떻게 네가 나가 버리냐고 했지. 나가라고 했으니 나가라고 했잖아. 자, 말해 봐. 그 눈으로 울지 마. 이제 너는 아무것도 못 하잖아. 그 뒤로는…"},
362:{"english":"She told me to stay outside until I found the key so I could get in. I sat crying in front of the door. My father was on duty or working a permanent shift; when he came back from work at ten at night, he found me asleep under the stairs. Upstairs, my mother told him what had happened and he started laughing. I felt like I was not human. The next morning the barracks guard found the key, and it ended well.","korean":"엄마는 열쇠를 찾을 때까지 밖에 있으라고 했어. 나는 문 앞에 앉아 울었지. 아버지는 당직이나 계속 근무 중이었고, 밤 열 시에 돌아와 계단 아래에서 잠든 나를 발견했어. 집에 올라가 엄마가 일을 설명하자 아버지는 웃기 시작했지. 나는 내가 사람이 아닌 것 같았어. 다음 날 아침 숙소 경비원이 열쇠를 찾아 주었고 다행히 끝났어."},
367:{"english":"For the garlic, I used one large clove. I added two carrots, peeled and cut into small pieces, tomatoes, and celery. It is in season and very good to cook with because it has great benefits.","korean":"마늘은 큰 한 쪽을 썼어요. 당근 두 개를 껍질을 벗겨 작게 썰고, 토마토와 셀러리도 넣었어요. 제철이라 요리하기 좋고 효능도 아주 많아요."},
368:{"english":"Here I chose the lower part and took some of its stems. I have a small potato, and I also have a green squash, kabouya khadra; add it too. I have a turnip. Some people say not to add turnip, but one piece will not affect the strong taste, and its benefit matters.","korean":"여기서는 아랫부분을 골라 줄기도 조금 사용했어요. 작은 감자 하나와 녹색 호박인 카부야 카드라가 있어요. 그것도 넣어요. 순무도 하나 있어요. 순무를 넣지 말자는 사람도 있지만 한 조각은 강한 맛에 영향을 주지 않고, 효능을 생각하면 돼요.","topic":"harira_root_vegetables_and_green_squash"},
380:{"english":"Then add tchicha, a small coffee cup; the exact grain type is left in the source and is not fully certain.","korean":"그다음 치샤(tchicha)를 작은 커피잔 한 잔 정도 넣어요. 정확한 곡물 종류는 원문에 남겨 두며 완전히 확정하기 어려워요.","topic":"harira_tchicha_quantity"},
381:{"english":"The amount of tchicha depends on how much harira you have. If you want it thick, add more; if you want it light, add only a little.","korean":"치샤의 양은 하리라의 양에 따라 달라요. 걸쭉하게 먹고 싶으면 많이 넣고, 묽게 먹고 싶으면 조금만 넣어요.","topic":"harira_tchicha_adjustment"},
}
def now(): return datetime.now(timezone.utc).replace(microsecond=0).strftime("%Y-%m-%dT%H:%M:%SZ")
def event(uid,field,value,generated_at): return {"source_uid":uid,"field":field,"value_hash":"sha256:"+hashlib.sha256(value.encode("utf-8")).hexdigest(),"method":"llm_source_only_enrichment_correction","model":MODEL,"prompt_version":PROMPT_VERSION,"schema_version":SCHEMA_VERSION,"generated_at":generated_at,"review_state":"generated"}
def apply():
    head=subprocess.run(["git","rev-parse","HEAD"],cwd=ROOT,check=True,capture_output=True,text=True).stdout.strip()
    if not head.startswith(BASE_COMMIT): raise RuntimeError(f"base_commit_mismatch:{head}:{BASE_COMMIT}")
    if source_gate()["result"]!="PASS": raise RuntimeError("source_gate_failed")
    source=read_tsv(SOURCE_OUT); before=read_tsv(ENRICHMENT_OUT); batch=read_tsv(BATCH_OUT)
    if list(before[0])!=ENRICHMENT_FIELDS: raise RuntimeError("enrichment_header_mismatch")
    by_batch={r["sentno"]:r for r in batch}; after=[dict(r) for r in before]; changed=0
    for row in after:
        for field,value in CORRECTIONS.get(int(row["sentno"]),{}).items(): row[field]=value; changed+=1
    if changed!=52: raise RuntimeError(f"changed_cell_count:{changed}")
    for row in batch:
        if row["sentno"] in {str(k) for k in CORRECTIONS}:
            for field,value in CORRECTIONS[int(row["sentno"])].items(): row[field]=value
    source_uids={r["source_uid"] for r in source}; existing=EVENTS_OUT.read_text(encoding="utf-8"); ec=check_provenance_events(existing,source_uids)
    if not existing.endswith("\n") or ec["result"]!="PASS" or ec["events"]!=5344: raise RuntimeError(json.dumps(ec,ensure_ascii=False))
    generated_at=now(); master={r["sentno"]:r for r in after}; new=[event(master[str(k)]["source_uid"],field,master[str(k)][field],generated_at) for k in sorted(CORRECTIONS) for field in CORRECTIONS[k]]; addition="".join(json.dumps(e,ensure_ascii=False,separators=(",",":"))+"\n" for e in new); combined=existing+addition; cc=check_provenance_events(combined,source_uids); trace=check_enrichment_provenance(after,combined)
    if cc["result"]!="PASS" or cc["events"]!=5396 or trace["result"]!="PASS": raise RuntimeError(json.dumps({"events":cc,"trace":trace},ensure_ascii=False))
    write_tsv(ENRICHMENT_OUT,after); write_tsv(BATCH_OUT,batch)
    with EVENTS_OUT.open("ab") as h: h.write(addition.encode("utf-8"))
    status=json.loads(STATUS_OUT.read_text(encoding="utf-8")); status["updated_from_commit"]=BASE_COMMIT; status["enrichment_correction_id"]=CORRECTION_ID; status["counts"].update({"enrichment_completed_rows":233,"enrichment_draft_rows":24,"enrichment_flagged_rows":127,"enrichment_not_started_rows":972,"processing_flags_populated_rows":249}); evidence=list(status.get("evidence_files",[])); path="data/master/qa/madoran_enrichment_batch06_correction01_qa.json"; status["evidence_files"]=evidence if path in evidence else evidence+[path]; STATUS_OUT.write_text(json.dumps(status,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    qa=json.loads(BATCH_QA_OUT.read_text(encoding="utf-8")); history=list(qa.get("correction_history",[])); history.append({"correction_id":CORRECTION_ID,"changed_fields":len(new),"rows":len(CORRECTIONS),"provenance_events":len(new)}); qa.update({"correction_id":CORRECTION_ID,"latest_correction_id":CORRECTION_ID,"correction_history":history,"correction_changed_fields":len(new),"correction_rows":len(CORRECTIONS),"correction_provenance_events":len(new),"new_provenance_events":748+len(new),"total_provenance_events":5396,"expected_total_provenance_events":5396,"content_review_status":"pending_headgpt_correction_review","latest_event_hash_gate":"PASS"}); BATCH_QA_OUT.write_text(json.dumps(qa,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
    correction_qa={"result":"PASS","batch_id":"MADORAN-ENRICH-006","correction_id":CORRECTION_ID,"base_commit":BASE_COMMIT,"corrected_rows":[str(k) for k in sorted(CORRECTIONS)],"changed_fields":len(new),"new_provenance_events":len(new),"provenance_events_before":5344,"provenance_events_after":5396,"source_gate":"PASS","morphology_gate":"BLOCKED_UPSTREAM_DEFECT","morphology_reads":0,"arabic_modified":0,"outside_target_mutations":0,"learning_unit_rows_created":0,"latest_event_hash_gate":"PASS","validator":"PASS","target_rows":64,"draft_rows":24,"flagged_rows":40,"processing_flags_populated_rows":44,"batch_artifact_sync":"PASS","batch_artifact_sync_changed_fields":len(new),"generated_at":generated_at,"outputs":{"batch":BATCH_OUT.relative_to(ROOT).as_posix(),"enrichment":ENRICHMENT_OUT.relative_to(ROOT).as_posix(),"provenance":EVENTS_OUT.relative_to(ROOT).as_posix()}}
    CORRECTION_QA_OUT.write_text(json.dumps(correction_qa,ensure_ascii=False,indent=2)+"\n",encoding="utf-8"); return correction_qa
if __name__=="__main__": print(json.dumps(apply(),ensure_ascii=False,indent=2))
